### ISSUE TITLE
Package content files are missing from VS solution explorer until project is reloaded

### ISSUE THREAD

**Issue by livarcocc** [dotnet/project-system#1934] opened 2017-04-06 03:52 UTC
_From @jainaashish on April 3, 2017 19:59_

1. Create a .net core library and add a content file (a simple txt file with CopyToOutputDirectory set to PreserveNewest)
2. Pack this library and create a NuGet package out of it.
3. Install this nupkg on a .net core console app.

Expected:
Txt file is added into project and shown in Solution Explorer.

Actual:
Txt file isn't available in solution explorer until you reload the project.

_Copied from original issue: dotnet/sdk#1068_

**Comment by davkean** [comment] 2017-04-06 04:31
Thanks @jainaashish, this is a dupe of https://github.com/dotnet/project-system/issues/268.

**Closed by davkean** 2017-04-06 04:31 UTC
