### ISSUE TITLE
Renaming class file doesn't rename class.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#4959] opened 2019-06-24 18:36 UTC
VSF_TYPE_MARKDOWNWhen i rename class files. Sometimes it renames the class, and sometimes it doesn't. I don't see the point of the inconsistency.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/617910/renaming-class-file-doesnt-rename-class.html
VSTS ticketId: 936149_
_These are the original issue comments:_

Visual Studio Feedback System on 6/24/2019, 02:18 AM (9 hours ago): <markdown><p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>
</markdown>
_These are the original issue solutions:_
(no solutions)

**Comment by jmarolf** [comment] 2019-06-24 18:37
closing as duplicate of https://github.com/dotnet/project-system/issues/4537

**Closed by jmarolf** 2019-06-24 18:37 UTC

**Comment by RickRockhold** [comment] 2019-07-01 14:23
This was closed as a duplicate of 4537, which is also closed, referencing this ticket. The problem isn't fixed, and all tickets are closed, referencing other tickets as duplicates. Can we re-open one of them so this gets fixed?

**Comment by jmarolf** [comment] 2019-07-01 15:28
sorry about the redirect ot nowhere :( I am using this bug to track rename: https://github.com/dotnet/project-system/issues/2852

I plan to have this done for 16.3

**Comment by RickRockhold** [comment] 2019-07-01 20:58
Awesome, thanks! I've always relied on this feature, and wanted to make sure it didn't get lost in the shuffle :).

**Comment by rodrigoreis** [comment] 2019-07-13 02:07
> sorry about the redirect to nowhere :( I am using this bug to track rename: #2852
> 
> I plan to have this done for 16.3

Only @ 16.3?! (-_-)
