### ISSUE TITLE
UWP Projects show individual references instead the UWP MetaPackage

### ISSUE THREAD

**Issue by nkolev92** [dotnet/project-system#3491] opened 2018-04-26 16:54 UTC
Zenhub was not cooperating so doing this manually. 

Original issue: https://github.com/NuGet/Home/issues/6868

//cc @rido-min
Affected Branch: 15.7
Affected Build:  27625.0
Affected Product Language: 

Steps to reproduce:

1. Create UWP
2. Change TPMinV=16299

Expected. Project is retargeted without errors.
Observed. The references are expanded with individual DLLs 

![image](https://user-images.githubusercontent.com/14916339/39317106-a536e748-492f-11e8-865a-7bbfb9a82361.png)

internal bug: [606826](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/606826)

nkolev92 commented 27 minutes ago
Project-system is the one handling the reference nodes there.

The only thing from NuGet side is whether the correct package is specified in the assets file.
Since I was not able to repro on 27620 (I know yours is 27625 it's just the version I have installed) it'd be helpful if you can upload the assets file to help them investigate.

 @rido-min
 Member
rido-min commented 23 minutes ago
Adding the assets file
project.assets.zip

 @nkolev92
 Member
nkolev92 commented 10 minutes ago
Thanks @rido-min
From NuGet side it all looks normal. I will copy the issue to the project system as I don't have rights to move it directly to their repository.

//cc @rido-min @karann-msft @rrelyea @Pilchie

**Comment by Pilchie** [comment] 2018-04-26 18:17
@tmeschter can you take a look?

**Comment by tmeschter** [comment] 2018-04-30 20:12
Dupe of https://github.com/dotnet/standard/issues/708, and fixed with https://github.com/dotnet/standard/pull/710. Please see those for more details.

**Closed by tmeschter** 2018-04-30 20:12 UTC
Labels: Area-Legacy-Project-System, Bug
