### ISSUE TITLE
AvailableItemName provided by a NuGet package isn't available as Build Action

### ISSUE THREAD

**Issue by kzu** [dotnet/project-system#2371] opened 2017-06-02 13:48 UTC
In the legacy project system, AvailableItemName provided by a nuget package targets are 
shown in the properties window (at least if the project is opened when the package has already 
been restored): 

![image](https://cloud.githubusercontent.com/assets/169707/26728406/83e0659e-4780-11e7-9ae5-721e7680ad2f.png)

The new project system, however, appears to always show a fixed list that does not include those:

![image](https://cloud.githubusercontent.com/assets/169707/26728442/a12b2bde-4780-11e7-98d6-b269d246eb9a.png)

It would be ideal if the new project system not only preserved the original behavior, but additionally 
refreshed the list of available build actions/item names whenever packages are installed/restored 
to make for a nicer extensibility experience via nugets + targets.

(screenshots taken with a .NETStandard 2.0 class library with 15.3 Preview - 26530.1.d15rel) and a regular .NET46 class library.

Since this is a regression from the legacy project system, I think at least the basic behavior should be fixed (even if the auto-refresh isn't).

**Comment by sharwell** [comment] 2017-06-02 13:51
Duplicate of #113, #1715.

**Closed** 2017-06-02 13:53 UTC
Labels: Resolution-Duplicate

**Comment by davkean** [comment] 2017-06-02 14:09
Yep, duplicate - we'll bring this up as part of legacy project system replacement.

**Comment by kzu** [comment] 2017-06-02 16:15
Hm, I was pretty sure I searched for AvailableItemName before filing. 

Anyway, glad to know it will eventually be fixed :)

**Comment by Neutrino-Sunset** [comment] 2017-06-22 15:50
This functionality is necessary to make it possible to do things like copy files to the output directory, which laughably, are impossible in Visual Studio without resorting to batch files (or a post build event which is a batch file by another name).

E.g. You have a project subdirectory 'Libs' containing binary dependencies, you want that output to your output directory. If you just select build type 'Content' and 'Copy to output directory' it will end up in $(OutDir)/Libs where your binary dependencies will not be resolved.

The 'fix' was to add this to your project file:

   <ItemGroup>
      <AvailableItemName Include="RootContent">
         <Visible>false</Visible>
      </AvailableItemName>
   </ItemGroup>
   <Target Name="AfterBuild">
      <Copy DestinationFolder="$(OutputPath)" SourceFiles="@(RootContent)" SkipUnchangedFiles="true" />
   </Target> 

...which enabled you to mark the files as 'RootContent' whereupon they would get copied to the output directory.

Now even this hack of a workaround is broken with no mention of an alternative. How do I copy files to my output directory now?
