### ISSUE TITLE
build or run a new .net core project leading to VS crash.

### ISSUE THREAD

**Issue by MiaomiaoHuangfu** [dotnet/project-system#2423] opened 2017-06-12 08:13 UTC
Create a .net core console app project (VB or C#);
Auto restore completed with no error or warning;
Build the project or run project;
Actual result: build or run project leading to VS crash. 
![buildleadingvscrashed](https://user-images.githubusercontent.com/22901391/27023147-e21abbf4-4f83-11e7-99c1-b6cc6e8c0f4f.png)
After VS restart, reopen the .sln, build the project succeeded.

Expected result: build the project succeeded, run passed, and VS still works well.

OS: Windows 10 X64;
Build: d15prerel.26611.01

**Comment by davkean** [comment] 2017-06-13 02:25
Dupe of https://devdiv.visualstudio.com/DevDiv/_workitems?id=448980&_a=edit&triage=true.

**Closed by davkean** 2017-06-13 02:25 UTC
