### ISSUE TITLE
[Dependencies] Unloading netcoreapp20 project and reloading can show all dpendencies nodes yellow even though they all resolved

### ISSUE THREAD

**Issue by abpiskunov** [dotnet/project-system#2685] opened 2017-08-02 20:32 UTC
VS d15rel 26730.0

Repro steps are literally same as in this https://github.com/dotnet/project-system/issues/2684 (thats how i ended up with here). It is a regression, this did not happen before.

1. Do all steps frm this issue https://github.com/dotnet/project-system/issues/2684
2. Unload Unit testss project and reload it.

Actual result:

![image](https://user-images.githubusercontent.com/1592091/28893628-09a0573a-7787-11e7-9978-20145dc13680.png)

**Comment by abpiskunov** [comment] 2017-08-02 20:39
This is how UnitTests project's Dependencies should have been looking, notice SDK and Analyzers groups presnt there, when On upper image they are not there.... happens pretty consistent.. 

![image](https://user-images.githubusercontent.com/1592091/28893877-e202f952-7787-11e7-9171-e7f7828e8bde.png)

**Comment by Pilchie** [comment] 2017-12-22 18:23
I'm also unable to reproduce this with 15.6 Preview 1.

**Comment by natidea** [comment] 2018-01-24 22:54
Likely fixed by https://github.com/dotnet/project-system/pull/3167 . Please reopen if it recurs

**Closed by natidea** 2018-01-24 22:54 UTC
Labels: Area-New-Project-System, Bug, Feature - Dependency Node
