### ISSUE TITLE
Sometimes, building and launching dotnet/project-system through IDE does not successfully install latest .vsix

### ISSUE THREAD

**Issue by adamint** [dotnet/project-system#8912] opened 2023-03-09 21:28 UTC
The result of this is that you think that you ran the latest code, but actually have an old version.

I am not aware of any way to tell that this has occurred other than by setting a breakpoint and attaching a debugger to see if sources were actually loaded.

I am also not aware of any fixes that work all of the time, though rebuilding _typically_ works.

Maybe happens ~5-30% of the time. depending?

**Comment by MiYanni** [comment] 2023-03-09 22:42
I've had a similar scenario where I did a full-build and compilation failed. This caused the experimental hive to be broken. Only resolution was clearing the experimental hive.

**Comment by MiYanni** [comment] 2023-03-09 22:45
This change may end up resolving this situation potentially: https://github.com/dotnet/project-system/issues/8432

**Comment by drewnoakes** [comment] 2023-03-10 03:54
I suspect this problem is local to our repo. I don't believe I've seen this in any other solution. I'll check whether CPS sees this.

**Comment by drewnoakes** [comment] 2023-03-10 04:20
When the build works, the build output resembles:

```
7>FastUpToDate: Build acceleration is disabled for this project via the 'AccelerateBuildsInVisualStudio' MSBuild property. See https://aka.ms/vs-build-acceleration. (ProjectSystemSetup)
7>FastUpToDate: Comparing timestamps of inputs and outputs: (ProjectSystemSetup)
7>FastUpToDate:     Adding UpToDateCheckBuilt outputs: (ProjectSystemSetup)
7>FastUpToDate:         D:\repos\project-system\artifacts\Debug\bin\Dlls\ProjectSystem.dll (ProjectSystemSetup)
7>FastUpToDate:         D:\repos\project-system\artifacts\Debug\obj\ProjectSystemSetup\ProjectSystem.dll (ProjectSystemSetup)
7>FastUpToDate:         D:\repos\project-system\artifacts\Debug\bin\Dlls\ProjectSystem.xml (ProjectSystemSetup)
7>FastUpToDate:         D:\repos\project-system\artifacts\Debug\obj\ProjectSystemSetup\ProjectSystem.xml (ProjectSystemSetup)
7>FastUpToDate:         D:\repos\project-system\artifacts\Debug\obj\ProjectSystemSetup\ProjectSystem.pdb (ProjectSystemSetup)
7>FastUpToDate:         D:\repos\project-system\artifacts\Debug\bin\Dlls\ProjectSystem.pdb (ProjectSystemSetup)
7>FastUpToDate:     Adding project file inputs: (ProjectSystemSetup)
7>FastUpToDate:         D:\repos\project-system\setup\ProjectSystemSetup\ProjectSystemSetup.csproj (ProjectSystemSetup)
7>FastUpToDate: Input 'D:\repos\project-system\setup\ProjectSystemSetup\ProjectSystemSetup.csproj' (2023-03-08 20:38:12.178) has been modified since the last successful build started (2023-03-03 15:02:20.550), not up-to-date. (ProjectSystemSetup)
7>FastUpToDate: Up-to-date check completed in 1.9 ms (ProjectSystemSetup)
7>------ Build started: Project: ProjectSystemSetup, Configuration: Debug Any CPU ------
7>ProjectSystemSetup -> D:\repos\project-system\artifacts\Debug\bin\Dlls\ProjectSystem.dll
7>ProjectSystemSetup -> D:\repos\project-system\artifacts\Debug\VSSetup\Insertion\ProjectSystem.vsix
```

The important line is the last one, indicating the VSIX was produced.

---

When this fails, the output resembles:

```
7>FastUpToDate: Build acceleration is disabled for this project via the 'AccelerateBuildsInVisualStudio' MSBuild property. See https://aka.ms/vs-build-acceleration. (ProjectSystemSetup)
7>FastUpToDate: Comparing timestamps of inputs and outputs: (ProjectSystemSetup)
7>FastUpToDate:     Adding UpToDateCheckBuilt outputs: (ProjectSystemSetup)
7>FastUpToDate:         D:\repos\project-system\artifacts\Debug\bin\Dlls\ProjectSystem.dll (ProjectSystemSetup)
7>FastUpToDate:         D:\repos\project-system\artifacts\Debug\obj\ProjectSystemSetup\ProjectSystem.dll (ProjectSystemSetup)
7>FastUpToDate:         D:\repos\project-system\artifacts\Debug\bin\Dlls\ProjectSystem.xml (ProjectSystemSetup)
7>FastUpToDate:         D:\repos\project-system\artifacts\Debug\obj\ProjectSystemSetup\ProjectSystem.xml (ProjectSystemSetup)
7>FastUpToDate:         D:\repos\project-system\artifacts\Debug\obj\ProjectSystemSetup\ProjectSystem.pdb (ProjectSystemSetup)
7>FastUpToDate:         D:\repos\project-system\artifacts\Debug\bin\Dlls\ProjectSystem.pdb (ProjectSystemSetup)
7>FastUpToDate:     Adding project file inputs: (ProjectSystemSetup)
7>FastUpToDate:         D:\repos\project-system\setup\ProjectSystemSetup\ProjectSystemSetup.csproj (ProjectSystemSetup)
7>FastUpToDate:     Adding newest import input: (ProjectSystemSetup)
7>FastUpToDate:         D:\repos\project-system\eng\imports\Packages.targets (ProjectSystemSetup)
7>FastUpToDate:     Adding EditorConfigFiles inputs: (ProjectSystemSetup)
7>FastUpToDate:         D:\repos\project-system\.editorconfig (ProjectSystemSetup)
7>FastUpToDate:     Adding Compile inputs: (ProjectSystemSetup)
7>FastUpToDate:         D:\repos\project-system\setup\ProjectSystemSetup\AssemblyRedirects.cs (ProjectSystemSetup)
7>FastUpToDate:         D:\repos\project-system\setup\Common\ProvideCodeBaseBindingRedirection.cs (ProjectSystemSetup)
7>FastUpToDate:     Adding AdditionalFiles inputs: (ProjectSystemSetup)
7>FastUpToDate:         D:\repos\project-system\src\Common\BannedSymbols.txt (ProjectSystemSetup)
7>FastUpToDate:     Adding UpToDateCheckInput inputs: (ProjectSystemSetup)
7>FastUpToDate:         D:\repos\project-system\artifacts\Debug\obj\ProjectSystemSetup\ProjectSystemSetup.csproj.BuildWithSkipAnalyzers (ProjectSystemSetup)
7>FastUpToDate:     No inputs are newer than earliest output 'D:\repos\project-system\artifacts\Debug\bin\Dlls\ProjectSystem.xml' (2023-03-10 15:13:22.984). Newest input is 'D:\repos\project-system\eng\imports\Packages.targets' (2023-03-09 20:34:18.990). (ProjectSystemSetup)
7>FastUpToDate: Checking built output (UpToDateCheckBuilt with Original property) file: (ProjectSystemSetup)
7>FastUpToDate:     Source      2023-03-09 20:39:12.665: 'D:\repos\project-system\artifacts\Debug\obj\ProjectSystemSetup\ProjectSystem.dll.config' (ProjectSystemSetup)
7>FastUpToDate:     Destination 2023-03-09 20:39:12.665: 'D:\repos\project-system\artifacts\Debug\bin\Dlls\ProjectSystem.dll.config' (ProjectSystemSetup)
7>FastUpToDate: Checking items to copy to the output directory: (ProjectSystemSetup)
7>FastUpToDate:     Checking copy items from project 'D:\repos\project-system\setup\ProjectSystemSetup\ProjectSystemSetup.csproj': (ProjectSystemSetup)
7>FastUpToDate:         Checking PreserveNewest item (ProjectSystemSetup)
7>FastUpToDate:             Source      2022-09-28 10:32:34.222: 'D:\repos\project-system\setup\ProjectSystemSetup\ProjectSelectors.pkgdef' (ProjectSystemSetup)
7>FastUpToDate:             Destination 2022-09-28 10:32:34.222: 'D:\repos\project-system\artifacts\Debug\bin\Dlls\ProjectSelectors.pkgdef' (ProjectSystemSetup)
7>FastUpToDate: Project is up-to-date. (ProjectSystemSetup)
7>FastUpToDate: Up-to-date check completed in 2.9 ms (ProjectSystemSetup)
```

In the above example, source was changed in `Microsoft.VisualStudio.ProjectSystem.Managed`. Our VSIX project is not seeing any change from that assembly that requires it to build. The gap is likely earlier in the output log. @MiYanni let me know if you'd like to look at this together next week.

**Comment by drewnoakes** [comment] 2023-03-10 21:01
> I'll check whether CPS sees this.

@adrianvmsft pointed at an issue he filed which may be the same one we are hitting. We should validate it has the same symptoms. https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1528227

**Comment by MiYanni** [comment] 2023-03-11 02:13
@drewnoakes I don't know the specifics on how this property operates, but the cause it likely that `ReferenceOutputAssembly` is set to `false`:
![image](https://user-images.githubusercontent.com/17788297/224459615-00f8d845-7af8-4122-9261-63da74caba30.png)

This is done to avoid the setup project directly referencing the assemblies, but they aren't necessary for that project's binary. This is something that was there prior to my infrastructure changes last year, so I kept them set that way. Try setting them to `true` and see if the situation still happens. These are set in the `ProjectSystemSetup.csproj` file.

**Comment by MiYanni** [comment] 2023-03-14 00:58
I tested changing the `false` to `true`. Seems to have fixed it.
![image](https://user-images.githubusercontent.com/17788297/224865019-97a8eef1-76e7-4d28-bf49-1c8e6f8fcbe3.png)

This was building `ProjectSystemSetup` after making a change to a random file in `Microsoft.VisualStudio.ProjectSystem.Managed`.

With them set to `false`, you'll see it doesn't work.
![image](https://user-images.githubusercontent.com/17788297/224864543-1ff9b2c1-29c9-4ac4-9c9c-c3ba9cd36d7a.png)

I don't notice any other negative effects of doing this (looked through the artifacts to confirm nothing suspicious). I'll make a PR for it.

**Comment by drewnoakes** [comment] 2023-03-30 05:23
Reopening this as it doesn't appear to be fixed.

Here's an example, with excerpts from a single build where I make a private change in `Microsoft.VisualStudio.ProjectSystem.Managed`:

```
1>FastUpToDate:         D:\repos\project-system\src\Microsoft.VisualStudio.ProjectSystem.Managed\ProjectSystem\Tree\Dependencies\Subscriptions\MSBuildDependencySubscriber.cs (Microsoft.VisualStudio.ProjectSystem.Managed)
1>FastUpToDate: Input Compile item 'D:\repos\project-system\src\Microsoft.VisualStudio.ProjectSystem.Managed\ProjectSystem\Tree\Dependencies\Subscriptions\MSBuildDependencySubscriber.cs' is newer (2023-03-30 16:11:47.914) than earliest output 'D:\repos\project-system\artifacts\Debug\bin\Dlls\Microsoft.VisualStudio.ProjectSystem.Managed.xml' (2023-03-30 15:55:28.743), not up-to-date. (Microsoft.VisualStudio.ProjectSystem.Managed)
1>FastUpToDate: Up-to-date check completed in 29.7 ms (Microsoft.VisualStudio.ProjectSystem.Managed)
1>------ Build started: Project: Microsoft.VisualStudio.ProjectSystem.Managed, Configuration: Debug Any CPU ------
1>Skipping analyzers to speed up the build. You can execute 'Build' or 'Rebuild' command to run analyzers.
1>Microsoft.VisualStudio.ProjectSystem.Managed -> D:\repos\project-system\artifacts\Debug\bin\Dlls\Microsoft.VisualStudio.ProjectSystem.Managed.dll
1>Inputs:
1>projectDirectory: D:\repos\project-system\src\Microsoft.VisualStudio.ProjectSystem.Managed
1>Done building project "Microsoft.VisualStudio.ProjectSystem.Managed.csproj".
```

Then later, for the VSIX projects:

```
5>FastUpToDate: Ignoring up-to-date check items with Kind="ImplicitBuild" (Microsoft.VisualStudio.ProjectSystem.Managed.CommonFiles)
5>FastUpToDate: Comparing timestamps of inputs and outputs: (Microsoft.VisualStudio.ProjectSystem.Managed.CommonFiles)
5>FastUpToDate:     Adding UpToDateCheckBuilt outputs: (Microsoft.VisualStudio.ProjectSystem.Managed.CommonFiles)
5>FastUpToDate:         D:\repos\project-system\artifacts\Debug\bin\Dlls\Microsoft.VisualStudio.ProjectSystem.Managed.CommonFiles.dll (Microsoft.VisualStudio.ProjectSystem.Managed.CommonFiles)
5>FastUpToDate:         D:\repos\project-system\artifacts\Debug\obj\Microsoft.VisualStudio.ProjectSystem.Managed.CommonFiles\Microsoft.VisualStudio.ProjectSystem.Managed.CommonFiles.dll (Microsoft.VisualStudio.ProjectSystem.Managed.CommonFiles)
5>FastUpToDate:         D:\repos\project-system\artifacts\Debug\bin\Dlls\Microsoft.VisualStudio.ProjectSystem.Managed.CommonFiles.xml (Microsoft.VisualStudio.ProjectSystem.Managed.CommonFiles)
5>FastUpToDate:         D:\repos\project-system\artifacts\Debug\obj\Microsoft.VisualStudio.ProjectSystem.Managed.CommonFiles\Microsoft.VisualStudio.ProjectSystem.Managed.CommonFiles.xml (Microsoft.VisualStudio.ProjectSystem.Managed.CommonFiles)
5>FastUpToDate:         D:\repos\project-system\artifacts\Debug\obj\Microsoft.VisualStudio.ProjectSystem.Managed.CommonFiles\Microsoft.VisualStudio.ProjectSystem.Managed.CommonFiles.pdb (Microsoft.VisualStudio.ProjectSystem.Managed.CommonFiles)
5>FastUpToDate:         D:\repos\project-system\artifacts\Debug\bin\Dlls\Microsoft.VisualStudio.ProjectSystem.Managed.CommonFiles.pdb (Microsoft.VisualStudio.ProjectSystem.Managed.CommonFiles)
5>FastUpToDate:     Adding project file inputs: (Microsoft.VisualStudio.ProjectSystem.Managed.CommonFiles)
5>FastUpToDate:         D:\repos\project-system\setup\Microsoft.VisualStudio.ProjectSystem.Managed.CommonFiles\Microsoft.VisualStudio.ProjectSystem.Managed.CommonFiles.csproj (Microsoft.VisualStudio.ProjectSystem.Managed.CommonFiles)
5>FastUpToDate:     Adding newest import input: (Microsoft.VisualStudio.ProjectSystem.Managed.CommonFiles)
5>FastUpToDate:         C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Microsoft\DesktopBridge\Microsoft.DesktopBridge.Common.targets (Microsoft.VisualStudio.ProjectSystem.Managed.CommonFiles)
5>FastUpToDate:     Adding AdditionalFiles inputs: (Microsoft.VisualStudio.ProjectSystem.Managed.CommonFiles)
5>FastUpToDate:         D:\repos\project-system\src\Common\BannedSymbols.txt (Microsoft.VisualStudio.ProjectSystem.Managed.CommonFiles)
5>FastUpToDate:     Adding ResolvedCompilationReference inputs: (Microsoft.VisualStudio.ProjectSystem.Managed.CommonFiles)
5>FastUpToDate:         D:\repos\project-system\artifacts\Debug\obj\Microsoft.VisualStudio.ProjectSystem.Managed\ref\Microsoft.VisualStudio.ProjectSystem.Managed.dll (Microsoft.VisualStudio.ProjectSystem.Managed.CommonFiles)
5>FastUpToDate:     Adding UpToDateCheckInput inputs: (Microsoft.VisualStudio.ProjectSystem.Managed.CommonFiles)
5>FastUpToDate:         Skipping 'D:\repos\project-system\artifacts\Debug\obj\Microsoft.VisualStudio.ProjectSystem.Managed.CommonFiles\Microsoft.VisualStudio.ProjectSystem.Managed.CommonFiles.csproj.BuildWithSkipAnalyzers' with ignored Kind="ImplicitBuild" (Microsoft.VisualStudio.ProjectSystem.Managed.CommonFiles)
5>FastUpToDate:     No inputs are newer than earliest output 'D:\repos\project-system\artifacts\Debug\bin\Dlls\Microsoft.VisualStudio.ProjectSystem.Managed.CommonFiles.xml' (2023-03-30 15:55:34.959). Newest input is 'D:\repos\project-system\artifacts\Debug\obj\Microsoft.VisualStudio.ProjectSystem.Managed\ref\Microsoft.VisualStudio.ProjectSystem.Managed.dll' (2023-03-30 15:55:29.816). (Microsoft.VisualStudio.ProjectSystem.Managed.CommonFiles)
5>FastUpToDate: Checking built output (UpToDateCheckBuilt with Original property) file: (Microsoft.VisualStudio.ProjectSystem.Managed.CommonFiles)
5>FastUpToDate:     Source      2023-03-30 12:10:44.946: 'D:\repos\project-system\artifacts\Debug\obj\Microsoft.VisualStudio.ProjectSystem.Managed.CommonFiles\Microsoft.VisualStudio.ProjectSystem.Managed.CommonFiles.dll.config' (Microsoft.VisualStudio.ProjectSystem.Managed.CommonFiles)
5>FastUpToDate:     Destination 2023-03-30 12:10:44.946: 'D:\repos\project-system\artifacts\Debug\bin\Dlls\Microsoft.VisualStudio.ProjectSystem.Managed.CommonFiles.dll.config' (Microsoft.VisualStudio.ProjectSystem.Managed.CommonFiles)
5>FastUpToDate: Project is up-to-date. (Microsoft.VisualStudio.ProjectSystem.Managed.CommonFiles)
5>FastUpToDate: Up-to-date check completed in 2.6 ms (Microsoft.VisualStudio.ProjectSystem.Managed.CommonFiles)
```

...and...

```
7>FastUpToDate: Ignoring up-to-date check items with Kind="ImplicitBuild" (ProjectSystemSetup)
7>FastUpToDate: Build acceleration is disabled for this project via the 'AccelerateBuildsInVisualStudio' MSBuild property. See https://aka.ms/vs-build-acceleration. (ProjectSystemSetup)
7>FastUpToDate: Comparing timestamps of inputs and outputs: (ProjectSystemSetup)
7>FastUpToDate:     Adding UpToDateCheckBuilt outputs: (ProjectSystemSetup)
7>FastUpToDate:         D:\repos\project-system\artifacts\Debug\bin\Dlls\ProjectSystem.dll (ProjectSystemSetup)
7>FastUpToDate:         D:\repos\project-system\artifacts\Debug\obj\ProjectSystemSetup\ProjectSystem.dll (ProjectSystemSetup)
7>FastUpToDate:         D:\repos\project-system\artifacts\Debug\bin\Dlls\ProjectSystem.xml (ProjectSystemSetup)
7>FastUpToDate:         D:\repos\project-system\artifacts\Debug\obj\ProjectSystemSetup\ProjectSystem.xml (ProjectSystemSetup)
7>FastUpToDate:         D:\repos\project-system\artifacts\Debug\obj\ProjectSystemSetup\ProjectSystem.pdb (ProjectSystemSetup)
7>FastUpToDate:         D:\repos\project-system\artifacts\Debug\bin\Dlls\ProjectSystem.pdb (ProjectSystemSetup)
7>FastUpToDate:     Adding project file inputs: (ProjectSystemSetup)
7>FastUpToDate:         D:\repos\project-system\setup\ProjectSystemSetup\ProjectSystemSetup.csproj (ProjectSystemSetup)
7>FastUpToDate:     Adding newest import input: (ProjectSystemSetup)
7>FastUpToDate:         D:\repos\project-system\setup\ProjectSystemSetup\ProjectSystemSetup.csproj (ProjectSystemSetup)
7>FastUpToDate:     Adding EditorConfigFiles inputs: (ProjectSystemSetup)
7>FastUpToDate:         D:\repos\project-system\.editorconfig (ProjectSystemSetup)
7>FastUpToDate:     Adding Compile inputs: (ProjectSystemSetup)
7>FastUpToDate:         D:\repos\project-system\setup\ProjectSystemSetup\AssemblyRedirects.cs (ProjectSystemSetup)
7>FastUpToDate:         D:\repos\project-system\setup\Common\ProvideCodeBaseBindingRedirection.cs (ProjectSystemSetup)
7>FastUpToDate:     Adding AdditionalFiles inputs: (ProjectSystemSetup)
7>FastUpToDate:         D:\repos\project-system\src\Common\BannedSymbols.txt (ProjectSystemSetup)
7>FastUpToDate:     Adding ResolvedCompilationReference inputs: (ProjectSystemSetup)
7>FastUpToDate:         D:\repos\project-system\artifacts\Debug\obj\VisualStudioEditorsSetup\ref\VisualStudioEditorsSetup.dll (ProjectSystemSetup)
7>FastUpToDate:         D:\repos\project-system\artifacts\Debug\obj\Microsoft.VisualStudio.Editors\ref\Microsoft.VisualStudio.Editors.dll (ProjectSystemSetup)
7>FastUpToDate:         D:\repos\project-system\artifacts\Debug\obj\Microsoft.VisualStudio.AppDesigner\ref\Microsoft.VisualStudio.AppDesigner.dll (ProjectSystemSetup)
7>FastUpToDate:         D:\repos\project-system\artifacts\Debug\obj\Microsoft.VisualStudio.ProjectSystem.Managed.CommonFiles\ref\Microsoft.VisualStudio.ProjectSystem.Managed.CommonFiles.dll (ProjectSystemSetup)
7>FastUpToDate:         D:\repos\project-system\artifacts\Debug\obj\Microsoft.VisualStudio.ProjectSystem.Managed.VS\ref\Microsoft.VisualStudio.ProjectSystem.Managed.VS.dll (ProjectSystemSetup)
7>FastUpToDate:         D:\repos\project-system\artifacts\Debug\obj\Microsoft.VisualStudio.ProjectSystem.Managed\ref\Microsoft.VisualStudio.ProjectSystem.Managed.dll (ProjectSystemSetup)
7>FastUpToDate:     Adding UpToDateCheckInput inputs: (ProjectSystemSetup)
7>FastUpToDate:         Skipping 'D:\repos\project-system\artifacts\Debug\obj\ProjectSystemSetup\ProjectSystemSetup.csproj.BuildWithSkipAnalyzers' with ignored Kind="ImplicitBuild" (ProjectSystemSetup)
7>FastUpToDate:     No inputs are newer than earliest output 'D:\repos\project-system\artifacts\Debug\bin\Dlls\ProjectSystem.xml' (2023-03-30 15:56:01.242). Newest input is 'D:\repos\project-system\artifacts\Debug\obj\Microsoft.VisualStudio.ProjectSystem.Managed\ref\Microsoft.VisualStudio.ProjectSystem.Managed.dll' (2023-03-30 15:55:29.816). (ProjectSystemSetup)
7>FastUpToDate: Checking built output (UpToDateCheckBuilt with Original property) file: (ProjectSystemSetup)
7>FastUpToDate:     Source      2023-03-30 14:46:43.969: 'D:\repos\project-system\artifacts\Debug\obj\ProjectSystemSetup\ProjectSystem.dll.config' (ProjectSystemSetup)
7>FastUpToDate:     Destination 2023-03-30 14:46:43.969: 'D:\repos\project-system\artifacts\Debug\bin\Dlls\ProjectSystem.dll.config' (ProjectSystemSetup)
7>FastUpToDate: Comparing timestamps of copy marker inputs and outputs: (ProjectSystemSetup)
7>FastUpToDate:     Output marker 'D:\repos\project-system\artifacts\Debug\obj\ProjectSystemSetup\ProjectSystemSetup.csproj.CopyComplete' does not exist, skipping marker check. (ProjectSystemSetup)
7>FastUpToDate: Checking items to copy to the output directory: (ProjectSystemSetup)
7>FastUpToDate:     Checking copy items from project 'D:\repos\project-system\setup\ProjectSystemSetup\ProjectSystemSetup.csproj': (ProjectSystemSetup)
7>FastUpToDate:         Checking PreserveNewest item (ProjectSystemSetup)
7>FastUpToDate:             Source      2022-09-28 10:32:34.222: 'D:\repos\project-system\setup\ProjectSystemSetup\ProjectSelectors.pkgdef' (ProjectSystemSetup)
7>FastUpToDate:             Destination 2022-09-28 10:32:34.222: 'D:\repos\project-system\artifacts\Debug\bin\Dlls\ProjectSelectors.pkgdef' (ProjectSystemSetup)
7>FastUpToDate: Project is up-to-date. (ProjectSystemSetup)
7>FastUpToDate: Up-to-date check completed in 3.4 ms (ProjectSystemSetup)
```

It seems like the VSIX projects are only looking at the `ref` assembly, not the implementation assembly/CopyComplete markers.

**Closed** 2023-04-17 19:47 UTC
Labels: Bug, Resolution-Fixed, Area-Infrastructure, Triage-Investigate
