### ISSUE TITLE
updated app.config not output - SDK-style project file in Visual Studio

### ISSUE THREAD

**Issue by fowl2** [dotnet/project-system#8015] opened 2022-03-29 04:58 UTC
## Visual Studio Version
Visual Studio 2022 17.1.2

## Summary
In an SDK-style project when the app.config file is updated in Visual Studio, the changes aren't reflected in the output .exe.config.

Seems to match https://github.com/dotnet/project-system/issues/4569 but I think even rebuild doesn't help.

## Steps to Reproduce

1. Have a .NETFramework SDK-style project, eg.:
``` xml
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net472</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
		<Reference Include="System.Configuration" />
	</ItemGroup>
</Project>
```

2. Run/debug the app.
3. Update the App.config
4. Run/debug the app again (without restarting). 

NB: Adding [`<AppConfig>App.config</AppConfig>`](https://stackoverflow.com/a/50373936) didn't seem to help.

## Expected Behavior
When the app runs, the config file in the bin directory (eg. appname.exe.config) has the changes.

## Actual Behavior
The config file in the bin directory is unchanged.

## Workaround

1. Restart visual studio each time the config should be updated
OR
2. Set the "Copy to Output Directory" property to "Always"

``` xml
	  <None Update="App.config">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
```

## User Impact
Lots of wasted time debugging until you release, and then again each time your forget ;)

**Comment by kvenkatrajan** [comment] 2022-04-07 23:54
This occurs on initial configuration and adding of application configuration file. The app.config updates do not reflect post build.

**Comment by drewnoakes** [comment] 2022-04-08 04:14
The issue here is that the `App.config` file is not modelled as a project input, so VS doesn't monitor it for changes. If it's the only file that's changed, we don't schedule a build (you'll see the project is reported as up-to-date).

We will investigate a fix for this. In the meantime, you can work around the issue by adding it as an explicit input in your project file with:

```xml
<ItemGroup>
  <UpToDateCheckInput Include="App.config" />
</ItemGroup>
```

**Comment by drewnoakes** [comment] 2022-04-08 15:39
This is a dupe of #5918. A fix was attempted in #5994, but that fix likely never worked. It also needs the change in #8051 to have any effect.

**Closed** 2022-04-11 21:01 UTC
Labels: Bug, Feature-Up-to-date, Triage-Investigate

**Comment by igitur** [comment] 2022-08-20 14:20
Hi gurus.

I'll gladly open a new issue if it's required, but since this is a recurring problem, I thought I'd continue on this issue.

I'm still experiencing this problem: When I make changes to `App.config` and no other changes and rebuild the project or solution, the output `MyExe.exe.config` doesn't reflect the changes. Note that this is a `net472` project. Maybe that's relevant.

My setup:
Visual Studio 2022 64b Version 17.3.1 (which according to #8051 should have fixed this?)
MSBuild version 17.3.0+f67e3d35e for .NET Framework

Here is my `.csproj` file, with all the workarounds I've read about included:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>8.0</LangVersion>
    <AppConfig>App.config</AppConfig> <!-- apparently not required, but tried it just in case -->
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <Import Project="$(SolutionDir)\version.props" />

  <ItemGroup>
    <UpToDateCheckInput Include="App.config" /> <!-- https://github.com/dotnet/project-system/issues/8015#issuecomment-1092424254 -->
    <UpToDateCheckBuilt Include="$(OutDir)\$(TargetFileName).config" Original="App.config" /> <!-- bottom of https://github.com/dotnet/project-system/issues/5918#issue-571070747 -->
  </ItemGroup>

  <ItemGroup>
    <Reference Include="log4net">
      <HintPath>..\libs\log4net.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.CSharp" />
  </ItemGroup>

  <ItemGroup>
    <!-- project references -->
    <ProjectReference Include="..\ServerUtils\ServerUtils.csproj" />
  </ItemGroup>

  <ItemGroup>
     <!-- Package references -->
    <PackageReference Include="Enums.NET" Version="4.0.0" />
    <PackageReference Include="Scriban" Version="5.0.0" />
    <PackageReference Include="Topshelf" Version="4.3.0" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\.editorconfig" Link=".editorconfig" />
  </ItemGroup>

</Project>
```

Please let me know how I can help to debug the root cause here. This is a blocker for us to upgrade our project to the SDK format. Thanks for your time.

**Comment by drewnoakes** [comment] 2022-09-07 20:10
@igitur please open a new issue so your comment won't get lost. The behaviour you describe does sound like a bug, and we would want to sign it to someone for investigation.

**Comment by igitur** [comment] 2022-09-14 08:03
Thanks @drewnoakes. I'm trying to produce it using a simpler solution. Will log a new issue when I'm able to do that. Currently, with a simple solution with 1 or 2 projects I can't reproduce the problem.

**Comment by fowl2** [comment] 2022-11-18 06:45
Hmmm I'm still having this problem in  17.3.6 but can't seem to produce a reduced test case. Hopefully I'll have some time next week to do some further investigation in 17.4.1
