### ISSUE TITLE
Nullable dropdown disabled with no explanation

### ISSUE THREAD

**Issue by JohnNilsson** [dotnet/project-system#6956] opened 2021-02-11 11:30 UTC
**Visual Studio Version**:
16.8.5

**Summary**:
In a new project the Nullable dropdown is disabled and there is no explanation of why.
![image](https://user-images.githubusercontent.com/97594/107630887-788d7d00-6c64-11eb-96f9-e3b34720fb38.png)

**Steps to Reproduce**:

1. Create project with `dotnet new console`

2. Open project in visual studio

3. Checkout the build properties tab of the project

**Expected Behavior**:

Either the dropdown is enabled, or some explanation of why it isn't is provided

**Actual Behavior**:

Just a disabled dropdown, no hints

**User Impact**:

Confusion about how to work with this feature. Is there some conflicting setting? Missing dependency?

**Comment by drewnoakes** [comment] 2021-02-11 11:34
What is the project's target framework? This option is greyed out if you target .NET Framework, as that implies a version of C# which does not support nullable.

**Comment by JohnNilsson** [comment] 2021-02-11 11:42
This is the full project file
```csproj
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

</Project>
```

**Comment by JohnNilsson** [comment] 2021-02-11 11:52
Not sure if its related. But when opening the project properties the windows is all black until I switch back and forth between that and something else. Interestingly trying to take a screen shot makes it visible.

**Comment by drewnoakes** [comment] 2021-02-11 12:29
I cannot reproduce the situation you're seeing:

![image](https://user-images.githubusercontent.com/350947/107636469-cafc8700-6cc0-11eb-9672-83a5a3252d47.png)

What version of the .NET SDK are you using? (i.e. the output of `dotnet --info`).

The black screen issue is unrelated. Does it occur on all pages in that UI?

**Comment by JohnNilsson** [comment] 2021-02-11 12:48
```
$ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.103
 Commit:    72dec52dbd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.103\

Host (useful for support):
  Version: 5.0.3
  Commit:  c636bbdc8a

.NET SDKs installed:
  3.1.300 [C:\Program Files\dotnet\sdk]
  3.1.406 [C:\Program Files\dotnet\sdk]
  5.0.102 [C:\Program Files\dotnet\sdk]
  5.0.103 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

The black screen thing hides everything in the window, even the left side menu.

**Comment by JohnNilsson** [comment] 2021-02-11 12:57
Tried moving the project folder out of the repo (to not have .editorconfig or Directory.build.props and such interfere), and deleted .vs,bin,obj and such folders. Same result.

**Comment by drewnoakes** [comment] 2021-02-11 22:22
Your repro steps don't seem to match your experience (i.e. you have extra files around). To help narrow down the issue, could you see if the same behaviour exists with a new .NET Core Console Application with minimal project file and only a `Program.cs` in the project folder?

**Comment by JohnNilsson** [comment] 2021-02-12 10:10
The project had no files besides what `dotnet new console` created. Just did that in a folder hierarchy that happened to be inside a git repo, why I moved it.
```
$ ls -a
./  ../  Program.cs  Test.csproj

$ cat Program.cs Test.csproj
﻿using System;

namespace Test
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
        }
    }
}
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

</Project>
```
![image](https://user-images.githubusercontent.com/97594/107755244-d7b1c700-6d22-11eb-8739-f253d4953717.png)

**Comment by JohnNilsson** [comment] 2021-02-12 10:17
For what it's worth. Same result when switching to `netcoreapp3.1`

**Comment by drewnoakes** [comment] 2021-02-15 01:45
I've followed these exact steps and the combo box is not disabled for me.

Are you sure there's no `Directory.Build.props`/`.targets` file anywhere above the folder you're running `dotnet new` in? If you enable "Show All Files" in Solution Explorer and search for "Directory" do any files appear under the _Imports_ node?

![image](https://user-images.githubusercontent.com/350947/107896507-8ad02980-6f8a-11eb-8560-981a4306f26c.png)

Looking at the code for the debug property page, I see that property is defined using `HiddenIfMissingPropertyControlData`, meaning it is disabled if the value is `MissingProperty`. Looking in `PropertyControlData.InitPropertyValue`, I see the initial value is set to `MissingProperty` if an exception occurs during the initialisation of that property. Such an error will be visible in telemetry. Therefore, if you use the Report a Problem feature in VS to (important) record the opening of the project property pages, we should be able to see an event for such a failure (dev notes: prefix is `vs/ml/proppages/appdesigner`). That tool will record a feedback ticket, which you can then paste here so we can find it.

**Comment by JohnNilsson** [comment] 2021-02-15 10:29
No unexpected files
![image](https://user-images.githubusercontent.com/97594/107931010-0bd3f480-6f7c-11eb-8069-1ad072dcde93.png)
Also tried disabling all extensions. No change.

Feedback ticket at: https://developercommunity2.visualstudio.com/t/Nullable-dropdown-disabled/1339281

**Comment by drewnoakes** [comment] 2021-02-15 19:54
Thanks, I'll take a look at that ticket. Did you search in Solution Explorer using the search text box, or just expand nodes to look for it manually? `Directory.Build.*` may be deeper down than your screenshot shows.

**Comment by JohnNilsson** [comment] 2021-02-15 21:14
Checked again. No such file.

**Comment by drewnoakes** [comment] 2021-02-16 10:31
An update on this. I spent some time looking through the diagnostics in the ticket and nothing jumps out at me to explain why this would be happening on your machine. One question I have is whether adding `<Nullable>enable</Nullable>` to the project causes the combo box to become enabled again.

There were some exceptions in the trace, but they look unrelated. I also didn't see any of the telemetry events I mentioned earlier that might suggest the most obvious failure mode.

Right now I'm working on replacing these property pages, so will make sure this scenario works correctly in their replacement.

**Comment by JohnNilsson** [comment] 2021-02-16 10:36
Well, dropdown still disabled. But it does pickup the property.
![image](https://user-images.githubusercontent.com/97594/108051281-ff6a9d00-704a-11eb-939d-2cbfe8c0e35b.png)

Might be worth to know that we do use the nullability analysis successfully, so this is only a UI thing. The problem is the same on a colleagues machine though, so not unique to me.

**Comment by drewnoakes** [comment] 2021-02-17 05:50
Thanks for the update and additional info.

**Comment by Fulgan** [comment] 2021-04-09 15:29
For what it's worth, I have exactly the same issue on my machine. I created a brand new solution (Blazor client app hosted in ASP.net core server using .net 50) and the problem is immediately present without me touching anything to the solution.

If it's relevant, I have Resharper and CodeRush installed as well (perhaps a weird interaction)

**Comment by drewnoakes** [comment] 2021-04-09 21:20
@JohnNilsson are you using either of these extensions?

**Comment by Fulgan** [comment] 2021-04-12 06:20
Disabling these two extensions does not restore the expected functionality

**Comment by JohnNilsson** [comment] 2021-04-12 11:03
Yes I have Resharper installed. (disabling extensions did not help me either)

**Comment by drewnoakes** [comment] 2022-02-25 01:43
Closing this issue as in 17.0 we replaced the old project property pages with a new UI that does not exhibit this issue.

**Closed by drewnoakes** 2022-02-25 01:43 UTC
Labels: Triage-Investigate
