### ISSUE TITLE
"Target framework" dropdown doesn't list full framework options

### ISSUE THREAD

**Issue by rainersigwald** [dotnet/project-system#4057] opened 2018-09-25 22:58 UTC
SDK-style projects support targeting .NET Framework TargetFrameworks like `net46` and `net472`, but that's not obvious from the dropdown in project properties:

![image](https://user-images.githubusercontent.com/3347530/46047520-05aef600-c0eb-11e8-9a3a-41fa4057ac26.png)

This caused at least one user to rewrite all of their projects after being told that they needed to target full framework rather than .NET Core, when all that was required was

```diff
-  <TargetFramework>netstandard2.0</TargetFramework>
+  <TargetFramework>net46</TargetFramework>
```

**Comment by Pilchie** [comment] 2018-09-26 01:05
Duplicate of https://github.com/dotnet/project-system/issues/3024

**Closed by Pilchie** 2018-09-26 01:05 UTC
Labels: Resolution-Duplicate
