### ISSUE TITLE
IntelliSense output shows "Could not find a file.." after file was deleted and then added back from windows explorer

### ISSUE THREAD

**Issue by abpiskunov** [dotnet/project-system#3472] opened 2018-04-17 17:36 UTC
Repro (VS : d15.7 27613.0)

1. Create a new Core Web App (netcoreapp2.0)
2. Wait for restore and Build
3. Delete Program.cs (copy paste it's content before deleting)
4. Wait when it is gone from Solution explorer (this is also slow - on my fast machine i see a delay before file is gone) 
5. Go to the project root in Windows Explorer and copy Startup.cs to get Startup - copy.cs
6. Rename it to Program.cs
7. Go back to VS and copy paste old content to the new Program.cs

While doing that i see error like on the picture below:

![image](https://user-images.githubusercontent.com/1592091/38886378-9f193624-422a-11e8-9d39-b7ecd1b564f4.png)

**Comment by davkean** [comment] 2018-04-18 04:53
Dupe of https://github.com/dotnet/roslyn/issues/12202.

**Closed by davkean** 2018-04-18 04:53 UTC
