### ISSUE TITLE
Property pages do not refresh when the underlying project file is updated

### ISSUE THREAD

**Issue by jmarolf** [dotnet/project-system#2434] opened 2017-06-13 18:00 UTC
Today if you modify a project file, you need to close and re-open the property pages to see the changes.  We should automatically refresh this information when we detect a change

**Comment by davkean** [comment] 2017-06-14 01:10
This is blocking on the connectpoint container implementation - thought we had a bug on this somewhere.

**Comment by davkean** [comment] 2017-06-15 02:10
Weird, we don't actually have a bug on this anywhere. This is the one.

**Comment by Pilchie** [comment] 2017-12-20 18:08
Dupe of #1259

**Closed by Pilchie** 2017-12-20 18:08 UTC
Labels: Area-External-CPS
