### ISSUE TITLE
Dependencies node shows with a warning icon until restore is complete

### ISSUE THREAD

**Issue by balachir** [dotnet/project-system#2079] opened 2017-04-27 03:01 UTC
With Dev15.3 Preview1 builds (from d15prerel), dependencies node shows with a warning icon until restore is complete.

The warning icon eventually goes away, but it looks ugly especially for ASP.NET Core applications because it takes a long time for the warning icon to go away making me wonder that there are issues with the project that I just created. It shows up during project open as well.
 
![image](https://cloud.githubusercontent.com/assets/8246794/25466052/f175fa3e-2aba-11e7-8f12-609190b83e35.png)

![image](https://cloud.githubusercontent.com/assets/8246794/25466065/f9f1d3fe-2aba-11e7-9729-d6ed5c1c939d.png)

**Comment by jmarolf** [comment] 2017-04-27 03:28
@balachir this is an explicit decision to indicate to the user that the restore has not yet completed for this project.

> making me wonder that there are issues with the project

There is an issue, restore has not yet completed.  Would you prefer to not have any UI to indicate that a restore needs to happen? Would you prefer a different icon?

**Comment by abpiskunov** [comment] 2017-04-27 15:00
Agree, the sign tells you that project is not ready and reasons could be: a. restore did not happen yet. Even if we make icon grey at project open, when user open it all dependencies will be yellow below it since they were not restored yet. So that would kind of meaningless. The real problem here is that restore should not happen everytime you open a project (as it does now) and slow design time builds (which need to be faster).

**Comment by SolderedMushroom** [comment] 2017-05-02 17:03
>There is an issue, restore has not yet completed. 

I don't want to see a yellow warning triangle for an "issue" that will resolve itself without my help. If I see that icon in the solution explorer, I'm going to expand it to try and see what the problem is so I can fix it, and then be annoyed because it's just a package restore that's already in progress.

If it needs an icon, it should be an icon that indicates "something is in progress" or "not everything is here yet," not the universal warning symbol.

**Comment by jmarolf** [comment] 2017-05-02 17:09
@SolderedMushroom I like the idea of showing progress. I think we need some icon to indicate that the project is not ready, but agree that the yellow warning icon is too scary.

**Comment by davkean** [comment] 2017-05-02 22:35
In agree, I don't like the yellow warning icon for "unrestored case".

**Comment by tmeschter** [comment] 2017-05-10 16:20
@srivatsn @natidea What controls which icon is shown here? I would ask @abpiskunov but he's OOF for a couple of months.

**Comment by abpiskunov** [comment] 2017-05-10 23:48
Node models control nodes properties including icons. See corresponding IDependencyModel implementations.

Thanks,
Anton

On May 10, 2017, at 9:20 AM, Tom Meschter <notifications@github.com<mailto:notifications@github.com>> wrote:


@srivatsn<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsrivatsn&data=02%7C01%7Canton.piskunov%40microsoft.com%7Cec190fd892ab40d4d1fb08d497c06b58%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636300300064915008&sdata=d4Vf70WAJLEl8O128co%2F5DCPWI%2FfMnSZ9jbMGax%2BkCo%3D&reserved=0> @natidea<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnatidea&data=02%7C01%7Canton.piskunov%40microsoft.com%7Cec190fd892ab40d4d1fb08d497c06b58%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636300300064915008&sdata=hB%2BzBlhIHGTi%2F4prbPmRqKrVCTG95ncp6GGsD10VOpQ%3D&reserved=0> What controls which icon is shown here? I would ask @abpiskunov<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fabpiskunov&data=02%7C01%7Canton.piskunov%40microsoft.com%7Cec190fd892ab40d4d1fb08d497c06b58%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636300300064915008&sdata=jfBytwcIupVNFM9iNx5rXqThxpCmGuaEtVFVLMNueJE%3D&reserved=0> but he's OOF for a couple of months.

**Comment by abpiskunov** [comment] 2017-05-11 00:03
Then look at dependencies tree view provider that actually applies icons logic to the tree. Btw how you would see that restore is not complete yet? Was this decided already?

Thanks,
Anton

On May 10, 2017, at 9:20 AM, Tom Meschter <notifications@github.com<mailto:notifications@github.com>> wrote:


@srivatsn<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsrivatsn&data=02%7C01%7Canton.piskunov%40microsoft.com%7Cec190fd892ab40d4d1fb08d497c06b58%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636300300064915008&sdata=d4Vf70WAJLEl8O128co%2F5DCPWI%2FfMnSZ9jbMGax%2BkCo%3D&reserved=0> @natidea<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnatidea&data=02%7C01%7Canton.piskunov%40microsoft.com%7Cec190fd892ab40d4d1fb08d497c06b58%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636300300064915008&sdata=hB%2BzBlhIHGTi%2F4prbPmRqKrVCTG95ncp6GGsD10VOpQ%3D&reserved=0> What controls which icon is shown here? I would ask @abpiskunov<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fabpiskunov&data=02%7C01%7Canton.piskunov%40microsoft.com%7Cec190fd892ab40d4d1fb08d497c06b58%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636300300064915008&sdata=jfBytwcIupVNFM9iNx5rXqThxpCmGuaEtVFVLMNueJE%3D&reserved=0> but he's OOF for a couple of months.

**Comment by tmeschter** [comment] 2017-07-06 20:33
So the open question is how do we know that restore is ongoing, or complete.

**Comment by tmeschter** [comment] 2017-09-27 18:14
Doesn't meet the bar for 15.5. Moving out to 15.6.

**Comment by cartermp** [comment] 2019-02-12 18:15
We should close this in favor of #3430 and #4362 - the first is a more specific issue tracking this problem specifically, and the latter groups that into a more general proposal for the Dependencies node with .NET Core 3.0 in mind.

**Comment by drewnoakes** [comment] 2019-02-12 19:15
@cartermp that seems sensible to me.

**Comment by drewnoakes** [comment] 2019-07-12 01:15
This specific request is being tracked by #5044.

**Closed by drewnoakes** 2019-07-12 01:15 UTC
Labels: Bug, Feature-Dependency-Node, Project-System-CPS, Triaged
