### ISSUE TITLE
Dependencies tree should show package's <frameworkAssemblies>

### ISSUE THREAD

**Issue by bording** [dotnet/project-system#2705] opened 2017-08-11 03:16 UTC
When referencing a package that includes framework assembly references, it's currently impossible to tell that the framework assembly references are being added to the project. They don't show up in the Assemblies node for the project, and they aren't listed under the package's node either.

The only way I've found to be able to see these references right now is by looking at the project.assets.json file

I'd really like to see these displayed in the Dependencies node, ideally as an item under the package's node.

**Comment by abpiskunov** [comment] 2017-08-11 15:14
They should appear under package that brings them. It could be regression either in Dependencies node or in sdk target that processes json file and sends data to dependencies node.

Thanks,
Anton

On Aug 10, 2017, at 8:16 PM, Brandon Ording <notifications@github.com<mailto:notifications@github.com>> wrote:


When referencing a package that includes framework assembly references, it's currently impossible to tell that the framework assembly references are being added to the project. They don't show up in the Assemblies node for the project, and they aren't listed under the package's node either.

The only way I've found to be able to see these references right now is by looking at the project.assets.json file

I'd really like to see these displayed in the Dependencies node, ideally as an item under the package's node.

**Comment by bording** [comment] 2017-08-11 16:18
@abpiskunov I have never observed this to be true, and I've used every public version of VS 2017 that's been released, and all of the 15.3 preview releases + public .NET Core preview SDKs.

I've just tested again with 15.2 + 1.0.4 SDK, and I don't see them anywhere. I've also looked at 15.3 preview 7 + a daily preview3 SDK, and they are missing there also.

**Comment by abpiskunov** [comment] 2017-08-11 17:08
Well i tested when it was first added and it was there, but it does not matter. It is broken and need to be fixed ...

**Comment by bording** [comment] 2018-11-14 20:17
Any more word on this? Any chance this will be improved in VS 2019?

**Comment by bording** [comment] 2018-11-14 20:18
![image](https://user-images.githubusercontent.com/753669/48509965-79829a80-e820-11e8-99d8-5b185553a2bd.png)

Not sure how me commenting on this would have made that happen!?!

**Comment by etbyrd** [comment] 2018-11-14 22:05
He isn't a part of the Microsoft org anymore, so maybe commenting triggered some sort of check and automatically unassigned him?

**Comment by drewnoakes** [comment] 2020-03-21 00:08
I filed #5946 which was a dupe of this.

> A package can specify framework assembly references in its `<frameworkAssemblies>`.
>
> https://docs.microsoft.com/en-us/nuget/reference/nuspec#framework-assembly-references
> 
> Expanding a package dependency in the tree would show these assembly references.
> 
> PR #5945 removed some unused code that was related to this feature, but was incomplete.

**Closed** 2020-05-06 12:03 UTC
Labels: Feature Request, Feature-Dependency-Node, Triage-Approved
