### ISSUE TITLE
Up-to-date check broken with Link/CopyToOutputDirectory

### ISSUE THREAD

**Issue by iskiselev** [dotnet/project-system#2894] opened 2017-10-16 21:52 UTC
If link and source file have different name, up-to-date check incorrectly verify file with original name.

Example:
1. Create ConsoleApp:
2. Add linked file with CopyToOutputDirectory
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net20</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <None Update="TextFile1.txt" Link="NewName.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
```
3. Compile multiple time.

Output:
```
FastUpToDate: Checking PreserveNewest file 'C:\projects\RebuildTest\ConsoleApp2\TextFile1.txt': (ConsoleApp2)
FastUpToDate:     Write 8/14/2017 6:13:29 PM: 'C:\projects\RebuildTest\ConsoleApp2\TextFile1.txt'. (ConsoleApp2)
FastUpToDate:     Output file 'C:\projects\RebuildTest\ConsoleApp2\bin\Debug\net20\TextFile1.txt' does not exist. (ConsoleApp2)
FastUpToDate: Project is not up to date. (ConsoleApp2)
```

So, it checked TextFile1.txt in output folder instead of NewName.txt

**Comment by Pilchie** [comment] 2017-10-17 17:46
Duplicate of https://github.com/dotnet/project-system/issues/2413

**Closed by Pilchie** 2017-10-17 17:46 UTC
