### ISSUE TITLE
Undo of rename operation pops up dialog in CPS

### ISSUE THREAD

**Issue by ryzngard** [dotnet/project-system#5580] opened 2019-10-15 00:28 UTC
While enabling more [code refactoring in CPS](https://github.com/dotnet/roslyn/pull/39225) I came across this behavior.

![cfbce04d-3bcf-41e8-a504-084f6f04949d](https://user-images.githubusercontent.com/475144/66791109-a1063b00-eea7-11e9-974e-7b27cbb06561.gif)

Action in the gif is to apply the file rename code action then undo with ctrl+z. 

cc @jmarolf  @davkean

**Comment by davkean** [comment] 2019-10-15 00:30
Dupe of: https://github.com/dotnet/project-system/issues/5139.

**Closed** 2019-10-15 00:30 UTC

**Comment by jmarolf** [comment] 2019-10-15 00:32
@davkean 	this is an issue that _will_ happen if [this PR](https://github.com/dotnet/roslyn/pull/39225) is merged but as far as I am aware does not happen today
