### ISSUE TITLE
Props file in nuget package can't resolve builtin implicit build properties

### ISSUE THREAD

**Issue by dracan** [dotnet/project-system#5853] opened 2020-01-31 17:08 UTC
**Visual Studio Version**: 16.4.0

**Summary**:

A `.props` file in a nuget package gets processed _before_ builtin implicit build properties are set (eg. `Configuration`, `OutputPath`, etc). This means that prop files in nuget packages can't use these built-in built types.

Note that this is when the consuming project is using the new SDK-style csproj format.

**Steps to Reproduce**:

1. Unzip the attached zip file ([MsBuildPropsVariableIssue.zip](https://github.com/dotnet/project-system/files/4140540/MsBuildPropsVariableIssue.zip))
2. Run `go.ps1`

_(if any changes are made after the first run of go.ps1, you'll need to bump the version number of the generated nuget package to avoid it using the cached version. Grep for `0.0.18` to see the two places where the version number will need bumping before running `go.ps1` again)_

**Actual Behavior**:

![jYacTCZv](https://user-images.githubusercontent.com/567988/73558527-44755e80-444b-11ea-826d-b3cfcb225126.png)

**Expected Behavior**:

The value in the above screenshot to be populated.

**User Impact**:

Props files in nuget packages can't use built-in built types.

---

If you need more information, or for me to explain my repro testcase more indepth, then let me know.

**Comment by sharwell** [comment] 2020-01-31 17:15
The .props file is included before the built-in props file in order to allow it to make changes to properties that are used in the default files. The NuGet package can also provide a .targets file, which is included toward the end and can make use of properties set both in the common build files and in the project file itself.

**Comment by dracan** [comment] 2020-01-31 17:23
> The .props file is included before the built-in props file in order to allow it to make changes to properties that are used in the default files (e.g. set a value for a property that is conditionally-initialized in the default build files).

I see. I'm happy for you to resolve this issue then if it's intentional. Just wasn't sure if it was a known issue or not, as it stops prop files from being able to use built-in variables.

> The NuGet package can also provide a .targets file, which is included toward the end and can make use of properties set both in the common build files and in the project file itself.

This is what I had to do - ie. move the properties out of the props file, and into the target file with the tasks.

**Comment by sharwell** [comment] 2020-01-31 17:32
> This is what I had to do - ie. move the properties out of the props file, and into the target file with the tasks.

Yes, this is what I would do as well. Example:

https://github.com/dotnet/winforms/blob/655d03de464f23a6dd9dc2cc363a2df9c5878a75/Directory.Build.props#L29
https://github.com/dotnet/winforms/blob/655d03de464f23a6dd9dc2cc363a2df9c5878a75/Directory.Build.targets#L14-L17

**Comment by davidwengier** [comment] 2020-01-31 18:40
I'm going to close this out, as it is by design, but thank you for logging it; if nothing else this can be a resource for anyone else with the same question who finds this issue. Ultimately the "props" and "targets" are just a convention for where the respective files are imported and with the multitude of imports and properties that make up a modern C# project it is sometimes necessary to break the convention and put things in a place you wouldn't expect.

With the new Imports node in Visual Studio and by using `msbuild /pp` or `dotnet build /pp` hopefully its at least getting easier to diagnose these issues when they come up, and reason about where things need to go and why.

**Closed by davidwengier** 2020-01-31 18:40 UTC
