### ISSUE TITLE
Changing target framework, does not trigger auto-restore and when restre manually uses old target

### ISSUE THREAD

**Issue by abpiskunov** [dotnet/project-system#1940] opened 2017-04-06 23:20 UTC
Had this in my project ClassLibrary1 :

  <PropertyGroup>
    <TargetFrameworks>netcoreapp1.1;netstandard1.4</TargetFrameworks>
  </PropertyGroup>

changed netstandard1.4 to netstandard **1.6** and:

1. no auto restore happened
2. when restored manually (from right click on solution node) did not have restore happening for ClassLibrary1 project at all only second project WebApplication2 referencing ClassLibrary1 was restored and output showed that nuget thought ClassLibrary1 still had old target:

Restoring NuGet packages...
Project ClassLibrary1 is not compatible with net46 (.NETFramework,Version=v4.6). Project ClassLibrary1 supports:
  - netcoreapp1.1 (.NETCoreApp,Version=v1.1)
  - **netstandard1.4 (.**NETStandard,Version=v1.4)
One or more projects are incompatible with .NETFramework,Version=v4.6.
Project ClassLibrary1 is not compatible with net46 (.NETFramework,Version=v4.6) / win7-x86. Project ClassLibrary1 supports:
  - netcoreapp1.1 (.NETCoreApp,Version=v1.1)
  - netstandard1.4 (.NETStandard,Version=v1.4)
One or more projects are incompatible with .NETFramework,Version=v4.6 (win7-x86).
NuGet package restore failed.
Time Elapsed: 00:00:03.7410411
========== Finished ==========

**Comment by srivatsn** [comment] 2017-05-23 17:54
Dupe of https://github.com/dotnet/project-system/issues/1503

**Closed by srivatsn** 2017-05-23 17:54 UTC
Labels: Bug
