### ISSUE TITLE
Cannot manually enter a license file because the control is disabled

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#4634] opened 2019-03-01 23:09 UTC
In places where we let you browse for files, we let you edit/interact with the control:

![image](https://user-images.githubusercontent.com/1103906/53671564-1a636b80-3cd3-11e9-8910-4170e3b3e359.png)

In package page, it's disabled despite me selecting the radio button:

![image](https://user-images.githubusercontent.com/1103906/53671516-d07a8580-3cd2-11e9-9572-c3c0c342aa01.png)

**Comment by etbyrd** [comment] 2019-03-01 23:15
This was by design as discussed with the Nuget team and us. The idea was to keep that to help “soft enforce” being able to only pick txt, md and no extension files. This was noted in the PR, but I think it is worth having the discussion again.

**Comment by jjmew** [comment] 2019-03-05 18:10
I was on the fence here but I inclined  to allow you to edit the text for consistency.

**Comment by etbyrd** [comment] 2019-05-20 21:07
Fixed in #4743

**Closed** 2019-07-06 05:23 UTC
Labels: Triaged
