### ISSUE TITLE
Cannot open *.fsproj or *.fs from explorer

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#3351] opened 2018-03-07 00:20 UTC
*.fsproj and *.fs's aren't associated with any application so you can't open them from Explorer:

![image](https://user-images.githubusercontent.com/1103906/37066425-7c652c06-21f9-11e8-881d-dba9532b4d8d.png)

**Comment by Pilchie** [comment] 2018-03-07 19:01
I wonder if this is related to the setup factoring for F# - are those things in the optional desktop component, but not in the .NET Core component?

@brettfo might also know here.

**Comment by davkean** [comment] 2018-05-14 07:04
Looks like VS icons are also not registered correctly either; we have a FSharpSourcesIconProvider that manually applies icons to CPS projects, but that's does not give the right icons when they are in Misc or other project types. We should remove that move the registration for the icons to install always.

**Comment by blfuentes** [comment] 2018-11-01 07:46
I exported the registry keys  from a machine where I had VS2015 installed and the file extensions were recognized.
**for example .fs:**

HKEY_CLASSES_ROOT_fs
HKEY_CLASSES_ROOT_VisualStudio.fs.12.0
HKEY_CLASSES_ROOT_VisualStudio.fs.14.0
HKEY_CURRENT_USER_Software_Microsoft_Windows_CurrentVersion_Explorer_FileExts_fs

And also copied the folder FSharp from
C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\
and 
C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\
where the defaulticon .dll files are.

After doing this and restarting the computer I managed to make it work.
I created a repository with the exported keys in case it could help

https://github.com/blfuentes/Fsharp_File_extensions

**Comment by davkean** [comment] 2020-02-10 23:17
@cartermp What do you want done with these F# bugs? Can we move them over to the F# project?

**Comment by cartermp** [comment] 2020-02-10 23:32
If this is most appropriate for F# tools setup then it should be moved over. https://github.com/dotnet/fsharp/issues/4017 was closed in favor of this issue since it was specific to SDK-style, but if it's not considered appropriate to handle in the project system then we could close this as a dupe of https://github.com/dotnet/fsharp/issues/4017 and re-open that bug.

**Comment by cartermp** [comment] 2020-02-14 00:19
This can be closed in favor of https://github.com/dotnet/fsharp/issues/4017

**Closed** 2020-02-14 00:40 UTC
Labels: Area-F#
