### ISSUE TITLE
Visual Studio modifies csproj file when adding xaml

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#3639] opened 2018-06-12 03:26 UTC
I am trying to get the new 2017 csproj-Format working with our WPF and WinForms projects. The problem is that Visual Studio modifies the csproj-File after adding a new file. 

Steps-to-reproduce:
- Open the attached project
- Add a new xaml-file

Expected behavior:
- Visual Studio does not touch the csproj-File (as there is already a rule for xaml files)

Actual behavior:
- Visual Studio adds two new ItemGroups:
  &lt;ItemGroup&gt;
    &lt;None Remove=&quot;UserControl1.xaml&quot; /&gt;
  &lt;/ItemGroup&gt;
  &lt;ItemGroup&gt;
    &lt;UpToDateCheckInput Remove=&quot;UserControl1.xaml&quot; /&gt;
  &lt;/ItemGroup&gt;
- Therefore the xaml is not displayed correctly in the Solution Explorer. After restoring the unmodified csproj everything looks good again

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/238439/visual-studio-modifies-csproj-file-when-adding-xam.html

[WpfNewCsProj.zip](https://github.com/dotnet/project-system/files/2092435/WpfNewCsProj.zip)

**Comment by davkean** [comment] 2018-06-12 03:28
This looks like a regression introduced by the update-to-date changes. Did we add a glob for `<UpToDateCheckInput>`?

**Comment by Neme12** [comment] 2018-06-27 12:37
You can add `<None Remove="**\*.xaml" />` to your project file as a workaround.

**Comment by davidwengier** [comment] 2019-08-30 06:12
Closing this. WPF fixed the default targets so this won't happen for Page any more, and its only happening for UpToDateCheckInput in this case because the repro project has an explicit include glob.

**Closed by davidwengier** 2019-08-30 06:12 UTC
Labels: Bug, Feature-Up-to-date

**Comment by davkean** [comment] 2019-08-30 06:43
> UpToDateCheckInput in this case because the repro project has an explicit include glob.

For UpToDateCheckInput?

**Comment by davidwengier** [comment] 2019-08-30 06:44
Yep.

**Comment by davkean** [comment] 2019-08-30 06:45
Ah, that makes sense then - I was really confused by this behavior originally.
