### ISSUE TITLE
MSB4057	The target "ResolveComReferencesDesignTime" does not exist in the project.

### ISSUE THREAD

**Issue by nguerrera** [dotnet/project-system#2076] opened 2017-04-26 15:07 UTC
_From @Mpdreamz on April 26, 2017 12:49_

Getting bit by this mysterious error.

```xml
  <PropertyGroup>
    <TargetFrameworks Condition="'$(DotNetCoreOnly)'==''">net45;net46;netstandard1.3</TargetFrameworks>
    <TargetFramework Condition="'$(DotNetCoreOnly)'=='1'">netstandard1.3</TargetFramework>
  </PropertyGroup
```

If I simplify this to either `<TargetFrameworks>` or `<TargetFramework>` with no condition everything loads fine in visual studio.

By the way the above fully works from the command line and rider.

Changing to 

```xml
  <PropertyGroup>
    <TargetFrameworks Condition="'$(DotNetCoreOnly)'==''">net45;net46;netstandard1.3</TargetFrameworks>
    <TargetFrameworks Condition="'$(DotNetCoreOnly)'=='1'">netstandard1.3</TargetFrameworks>
  </PropertyGroup
```

Works

_Copied from original issue: dotnet/sdk#1152_

**Comment by nguerrera** [comment] 2017-04-26 15:11
@srivatsn Is this because the condition breaks the project system selector?

I moved this here from the SDK since the error only occurs in VS. I have hit this myself and use the following workaround, which is to put an initial value without conditions and the change it with conditions. Something like (adapting the original report's example):

``` xml
<PropertyGroup>
    <TargetFrameworks>net45;net46;netstandard1.3</TargetFrameworks>
    <TargetFrameworks Condition="'$(DotNetCoreOnly)'=='1'">netstandard1.3</TargetFrameworks>
  </PropertyGroup>
```

**Comment by davkean** [comment] 2017-04-27 02:25
This is a dupe of https://github.com/dotnet/project-system/issues/1479, which is caused by https://github.com/Microsoft/msbuild/issues/1726.

**Closed by davkean** 2017-04-27 02:25 UTC
