### ISSUE TITLE
Need a better experience for failed SDK resolution

### ISSUE THREAD

**Issue by nguerrera** [dotnet/project-system#3621] opened 2018-06-06 00:30 UTC
On project load, if you fail to import an SDK that ultimately would have been what provided common targets, you get a popup like this:

```
---------------------------
Microsoft Visual Studio
---------------------------
Project file is incomplete. Expected imports are missing.
---------------------------
OK   
---------------------------
```

This doesn't give me any sense of what the problem is or how to fix it. The SDK resolver would have logged errors to MSBuild with more details, but they are not shown to the user.

@davkean noted offline:
> In flavors, we use to determine up front that the SDK was missing and then do IVsRetargetProject prompting you to install the SDK or point to a page that told you how to get it.
>
> This is a better experience and works great when you have 100 projects that fail to load.

**Comment by Pilchie** [comment] 2018-06-06 18:13
Dupe of https://github.com/dotnet/project-system/issues/2467?

**Comment by Nirmal4G** [comment] 2018-06-06 18:14
Also It should search for the SDK in the NuGet repository and ask the user to create or append to a `global.json` file for that solution.

**Comment by Pilchie** [comment] 2018-06-08 20:20
@nguerrera Does this sound like dupe to you?

**Comment by Pilchie** [comment] 2018-06-11 14:47
Closing for now.

**Closed by Pilchie** 2018-06-11 14:47 UTC

**Comment by davkean** [comment] 2018-06-11 22:46
I'll change the description of that other bug, as it's not asking for the same thing.
