### ISSUE TITLE
Dynamic enum property options that rely on another property are not updated when that property changes

### ISSUE THREAD

**Issue by japarson** [dotnet/project-system#7653] opened 2021-10-01 08:16 UTC
## Visual Studio Version
Version 17.0.0 Preview 5.0 [31730.229.main]

## Summary
I have a DynamicEnumProperty (B) that needs to display certain options depending on the value of another DynamicEnumProperty (A). However, I'm seeing that when property A is updated using the UI, the enum values displayed for property B do not change.
![image](https://user-images.githubusercontent.com/59936622/135587531-c1c9f802-e114-49dd-a068-8c3be6c68bb9.png)

This is extra strange to me because the GetListedValuesAsync() function for property B is generating the correct properties, but the UI is not updating to reflect that (verified using debugger).

The only thing that "refreshes" the UI for property B is to hide the property and then show it again using a visibility condition on some property C.
![repro](https://user-images.githubusercontent.com/59936622/135587983-150ee98f-ce81-4208-832d-1ad1779fe364.gif)

## Steps to Reproduce
1. Create a new project property page rule file.
2. Add 2 DynamicEnumProperty s A & B.
3. Create an enum provider/generator for A with multiple different values.
4. Create an enum provider/generator for property B and import ConfiguredProject.
  - In the generator, get the property value for A using: `_configuredProject.Services.ProjectPropertiesProvider?.GetCommonProperties();`
  - Return distinct enum options depending on the value for property A.
5. Open the page in Visual Studio and select different options for property A.

## Expected Behavior
The options displayed by the property B combo box change depending on the value selected in the property A combobox.

## Actual Behavior
The options displayed by the property B combo box will not change depending on the value selected in the property A combobox.

## User Impact
Users will not see the correct enum options under these specific circumstances.

**Comment by japarson** [comment] 2022-04-07 01:07
@drewnoakes When can we expect this issue to be investigated? Is it something that @adamint can take a look at?

**Comment by drewnoakes** [comment] 2022-04-07 07:30
This is scheduled for 17.3 at this point.

**Comment by drewnoakes** [comment] 2022-05-19 13:52
A workaround for this is to create different properties for each of the ones you wish to show and flip visibilities using conditions.

@tmeschter can you lend a thought to this scenario?

```xml
  <DynamicEnumProperty Name="Dynamic1"
                       EnumProvider="Dynamic1EnumProvider"
                       Visible="True" />

  <DynamicEnumProperty Name="Dynamic2"
                       EnumProvider="Dynamic2EnumProvider"
                       Visible="True" />
```

```c#
[ExportDynamicEnumValuesProvider("Dynamic1EnumProvider")]
[AppliesTo(ProjectCapability.DotNet)]
internal class Dynamic1EnumProvider : IDynamicEnumValuesProvider, IDynamicEnumValuesGenerator
{
    public bool AllowCustomValues => false;

    public Task<EnumCollection> GetListedValuesAsync() => Task.FromResult<EnumCollection>(new[]
        {
            new PageEnumValue(new EnumValue() { Name = "A" }),
            new PageEnumValue(new EnumValue() { Name = "B" })
        });

    public Task<IDynamicEnumValuesGenerator> GetProviderAsync(IList<NameValuePair>? options) => Task.FromResult<IDynamicEnumValuesGenerator>(this);

    public Task<IEnumValue?> TryCreateEnumValueAsync(string userSuppliedValue) => TaskResult.Null<IEnumValue>();
}

[ExportDynamicEnumValuesProvider("Dynamic2EnumProvider")]
[AppliesTo(ProjectCapability.DotNet)]
internal class Dynamic2EnumProvider : IDynamicEnumValuesProvider, IDynamicEnumValuesGenerator
{
    private readonly ConfiguredProject _configuredProject;

    public bool AllowCustomValues => false;

    [ImportingConstructor]
    public Dynamic2EnumProvider(ConfiguredProject configuredProject)
    {
        _configuredProject = configuredProject;
    }

    public async Task<EnumCollection> GetListedValuesAsync()
    {
        IProjectProperties? props = _configuredProject.Services.ProjectPropertiesProvider?.GetCommonProperties();

        if (props is null)
        {
            return Array.Empty<IEnumValue>();
        }

        string value = await props.GetEvaluatedPropertyValueAsync("Dynamic1");

        return value switch
        {
            "A" => new[]
            {
                new PageEnumValue(new EnumValue() { Name = "A1" }),
                new PageEnumValue(new EnumValue() { Name = "A2" })
            },
            "B" => new[]
            {
                new PageEnumValue(new EnumValue() { Name = "B1" }),
                new PageEnumValue(new EnumValue() { Name = "B2" })
            },
            _ => Array.Empty<IEnumValue>()
        };
    }

    public Task<IDynamicEnumValuesGenerator> GetProviderAsync(IList<NameValuePair>? options) => Task.FromResult<IDynamicEnumValuesGenerator>(this);

    public Task<IEnumValue?> TryCreateEnumValueAsync(string userSuppliedValue) => TaskResult.Null<IEnumValue>();
}
```

When selecting a value for `Dynamic1`, the enum provider for `Dynamic2` (`Dynamic2EnumProvider.GetListedValuesAsync`) is called a few times, yet those values are not shipped to the UI via its Project Query API subscription as far as I can tell from my testing.

**Comment by drewnoakes** [comment] 2022-05-19 22:16
Discussed in our team meeting today. @tmeschter is going to take a look at why the updated data is not being sent to the client via the query subscription.

**Comment by drewnoakes** [comment] 2022-05-19 22:18
Also being tracked in AB#1415333.

**Comment by tmeschter** [comment] 2022-05-20 20:07
@drewnoakes One thing I see is that an update does (eventually) come through the query subscription that includes the new set of supported values, and we fire a property changed event. Specifically, we're ending up inside `PropertyValueViewModel.Update` and handling the new set of supported values as I would expect. **However**, the values visible in the dropdown in the UI do no update to reflect the new set.

That seems very suspicious to me, but I still need to check what's happening in the back end systems to make sure I understand the end-to-end behavior.

**Comment by tmeschter** [comment] 2022-05-20 21:17
@drewnoakes Turns out I only needed to look a little further. The combo box has its own view model (`PropertyValueComboBoxViewModel`) with its own copy of the supported values pulled from the underlying `PropertyValueViewModel`. The combo box view model sees when the supported values change, but doesn't actually update its copy. I'll prepare a fix in CPS.

**Comment by drewnoakes** [comment] 2022-05-20 23:08
@tmeschter apologies for the confusion. I didn't see updated values coming through to the UI so made an incorrect assumption about the root cause here.

Sounds like you are close to having a fix. Feel free also to reassign this back to me if you prefer.

**Comment by tmeschter** [comment] 2022-05-31 19:00
This was fixed by https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/400367.

**Closed by tmeschter** 2022-05-31 19:00 UTC
Labels: Triage-Investigate, Feature-Project-Properties-Designer
