### ISSUE TITLE
[Legacy] Allow "No Auth" property in Project settings 

### ISSUE THREAD

**Issue by rajkumar42** [dotnet/project-system#3053] opened 2017-12-13 21:17 UTC
.NET Framework/.NET Core apps, do not expose "No Auth" setting under "Debug" tab of the project properties. 

This especially affect the users who deploy and debug applications inside of windows docker containers.

**Comment by AngelosP** [comment] 2017-12-13 21:25
Thank you for logging this issue Rajkumar. Until we expose the necessary property, here is a workaround:

1. Build app.
2. Copy app/binaries to the container. Exactly in the same location, say if the files are produced under c:\solution1\project1\bin\MyApp.exe , copy it to the same drive and directory on the container.
3. Close the solution.
4. VS menu: File -> Open -> Project/Solution -> c:\solution1\project1\bin\MyApp.exe
5. Open solution explorer. Right click, properties.
6. Change the connection to “Remote with No Authentication”. Debugger type to managed.
7. F5 (Edit and Continue would not work since you are directly working on the exe, not the solution)

**Comment by davkean** [comment] 2017-12-13 22:51
Thanks, we had a bug already tracking this but I'll dupe it against this due to additional scenario and workaround.

**Comment by davkean** [comment] 2017-12-13 22:53
Also https://connect.microsoft.com/VisualStudio/feedback/details/1314617/managed-windows-desktop-applications-projects-do-not-support-remote-debugging-without-authentication is a dupe of this.

**Comment by davkean** [comment] 2020-02-01 03:14
This being added for .NET Framework projects here: https://github.com/dotnet/project-system/pull/5831. .NET Core projects are coming later.

@srdjanjovcic Do you have a bug that I can dupe this against?

**Comment by davkean** [comment] 2020-02-01 22:22
This is being tracked internally by https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1024605.

**Comment by davkean** [comment] 2020-02-04 00:08
I filed https://github.com/dotnet/project-system/issues/5860 to track this the CPS version of this change. This now just represents the work to enable this for the legacy project system.

**Comment by davkean** [comment] 2020-02-06 04:50
This was fixed for .NET Framework projects in 16.5, https://github.com/dotnet/project-system/issues/5860 tracks fixing it for .NET Core projects.

**Closed by davkean** 2020-02-06 04:50 UTC
Labels: Feature Request, Feature-Debugging, Legacy, Tracking, Triage-Approved

**Comment by davkean** [comment] 2020-02-07 06:00
We've submitted a PR to add "no authentication" to the new project system for 16.6 here: https://github.com/dotnet/project-system/pull/5877.
