### ISSUE TITLE
Visual Studio doesn't recognize types until you open their file in the editor

### ISSUE THREAD

**Issue by jamesqo** [dotnet/project-system#2446] opened 2017-06-15 01:57 UTC
I'm using [ANTLR v4](https://github.com/tunnelvisionlabs/antlr4cs) to auto-generate C# code for my project based on a grammar file. For some reason, all of the autogenerated types are "do not exist in the current context" until I navigate to their file in the editor, at which point they turn blue.

## Repro

1. Create a new .NET Standard library
2. `Install-Package Antlr4`
3. Create `Foo.g4`:

```g4
grammar Foo;

foo
    : .*
    ;
```

4. Edit the project file so code is generated for the grammar during the build process:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard1.4</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Antlr4 Include="Foo.g4">
      <Generator>MSBuild:Compile</Generator>
      <CustomToolNamespace>AntlrLab</CustomToolNamespace>
    </Antlr4>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Antlr4" Version="4.6.1" />
  </ItemGroup>

</Project>
```

5. Build the project. Several generated files will be in `obj\Debug\netstandard1.4`, e.g. `FooParser.cs` and others.
6. Create a class and paste this in:

```cs
using System;

namespace AntlrLab
{
    public class Class1
    {
        void M()
        {
            var foo = typeof(FooParser);
        }
    }
}

```

A compiler error is raised at `FooParser` because the type isn't recognized. (But if you run `dotnet build` in your project directory, there will be no errors!)

7. Click View All Files in Solution Explorer. Go to `obj\Debug\netstandard1.4\FooParser.cs`. Open the file then close it.

8. `FooParser` is now recognized, and there are no errors.

**Comment by davkean** [comment] 2017-06-15 02:06
This is us not running the code generator, and is a dupe of https://github.com/dotnet/project-system/issues/1521. I've add a pointer to this bug.

**Closed by davkean** 2017-06-15 02:06 UTC
