### ISSUE TITLE
Platform specific property page does not disappear after platform is removed form TargetFrameworks

### ISSUE THREAD

**Issue by stmoor** [dotnet/project-system#8030] opened 2022-03-31 23:05 UTC
## Visual Studio Version
Version 17.2.0 Preview 3.0 [32329.161.main]

## Summary
Platform specific property page does not disappear when removing related target framework from `TargetFrameworks` property without having to close the properties page and re-opening it. For example, the page called iOS contains all the iOS specific properties. All those properties have a condition on the platform iOS being listed in the `TargetFrameworks` property. When you remove iOS from `TargetFrameworks`, the iOS page should disappear. It only disappears if you close the properties page and then re-open it. 

# Steps to Reproduce
The video below demos the issue. When the user unchecks the Target iOS Framework checkbox, net6.0-ios is removed from the `TargetFrameworks` property. 

https://user-images.githubusercontent.com/77985069/161162485-799313c0-1482-45c1-aca2-019ddf10c5dc.mp4

## Expected Behavior
The platform specific property page (E.g., iOS page) should disappear once the project no longer targets that platform. 

## Actual Behavior
The platform specific property page does not disappear unless you close and reopen the properties page. 

## User Impact
It can be confusing to the user to see the platform specific properties page listed if the project is no longer targeting that platform.

**Comment by adamint** [comment] 2022-05-23 22:45
I can reproduce this most of the time. Interestingly, iOS is more likely to actually update than Android page.

**Comment by adamint** [comment] 2022-06-28 22:53
We are practically blocked on this until https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1547035

**Comment by adamint** [comment] 2022-06-29 23:28
Moving to 17.4 because of the blocker.

**Comment by adamint** [comment] 2022-08-15 18:56
Unable to repro in latest vs Version 17.4.0 Preview 2.0 [32809.211.main]
Looks like we accidentally fixed it

**Closed by adamint** 2022-08-15 18:56 UTC
Labels: Bug, Triage-Approved, Feature-Project-Properties-Designer
