### ISSUE TITLE
Configuring analyzer issues

### ISSUE THREAD

**Issue by onovotny** [dotnet/project-system#2333] opened 2017-05-31 01:31 UTC
When trying to configure the analyzer in VS 2017 15.3 preview 1, I’m getting bad behavior from the IDE.

In a CPS project (in this case a net462 class library using the sdk-style project type), I added a reference to `Microsoft.VisualStudio.Threading.Analyzers`. Now under the analyzers node in the solution explorer, when I expand it to set the severity of specific ones, it creates a new ruleset with the project name. 

There are two problems:
1.	The specified severity isn’t reflected in the context menu of the analyzer once set. It’s also not reflected as the “effective severity” in the properties pane
2.	Going to another analyzer and changing the severity creates a new ruleset file next to the first one. Repeat with another rule for another ruleset file, etc.

**Comment by srivatsn** [comment] 2017-06-05 17:00
I suspect this is a dupe of https://github.com/dotnet/project-system/issues/2114 - the change in severity wasn't taking effect because of an unimplemented API on the PS side. That's now fixed in an upcoming preview.

**Closed by srivatsn** 2017-06-05 17:00 UTC
