### ISSUE TITLE
Dependency node doesn't handle Multi-targeting with a multi portable frameworks 

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#2524] opened 2017-06-29 07:46 UTC
1. git clone https://github.com/aarnott/pinvoke
2. cd pinvoke
3. git checkout c5642c29ddd
4. src\pinvoke.sln
5. Expand Kernel32's dependency node project

```   XML
<PropertyGroup>
    <TargetFrameworks>portable-net4+win8+wpa81;portable-net45+win8+wpa81;net40</TargetFrameworks>
</PropertyGroup>
```

Expected: 3 frameworks to show up
Actual:

![image](https://user-images.githubusercontent.com/1103906/27676841-e2758ada-5cf2-11e7-945d-95a1658a080a.png)

**Comment by srivatsn** [comment] 2017-07-24 20:48
I think we should fix this by following this - https://github.com/dotnet/project-system/issues/2618#issuecomment-317523005

**Comment by drewnoakes** [comment] 2020-03-31 00:00
Triage notes: Identify if this is a dupe of #2618

**Comment by drewnoakes** [comment] 2023-05-10 03:11
With the rewrite:

![image](https://github.com/dotnet/project-system/assets/350947/a98fe872-6987-4192-aa72-96bdaf222bf5)

**Closed** 2023-05-16 03:59 UTC
Labels: Bug, Feature-Dependency-Node, Triage-Investigate
