### ISSUE TITLE
Warning icons in Dependencies node of the VS solution explorer with no explanatory text

### ISSUE THREAD

**Issue by danroth27** [dotnet/project-system#4716] opened 2019-04-10 21:06 UTC
From time to time I see warning icons in the Dependencies node of the VS solution explorer, but with no explanatory text for what the warning is about. 
 
The situations for when this has occurred vary, but the most recent case was when I installed the latest .NET Core 3.0 SDK build (3.0.100-preview4-011112) and then created a new ASP.NET Core Razor Components project with the latest VS2019 build from the Preview channel of VS2019 (16.1.0 Preview 1.0 [28805.205.d16.1]).
 
Repro steps:
- Install .NET Core 3.0 Preview 4 build ((3.0.100-preview4-011112 in my case)
- Install VS2019 Preview 
- File -> New Project -> ASP.NET Core Web App -> Razor Components
 
Actual result:
- A warning icon in the Dependencies node with no explanation:

![dependency-node](https://user-images.githubusercontent.com/1874516/55913545-bbc6c280-5b99-11e9-929b-8f5f2b21d371.png)

![error-list](https://user-images.githubusercontent.com/1874516/55913552-be291c80-5b99-11e9-87e8-26c85a492ec6.png)

 ```
1>------ Rebuild All started: Project: WebApplication8, Configuration: Debug Any CPU ------
1>C:\Program Files\dotnet\sdk\3.0.100-preview4-011112\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(151,5): message NETSDK1057: You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview
1>WebApplication8 -> C:\Users\daroth\Source\Repos\WebApplication8\WebApplication8\bin\Debug\netcoreapp3.0\WebApplication8.dll
1>WebApplication8 -> C:\Users\daroth\Source\Repos\WebApplication8\WebApplication8\bin\Debug\netcoreapp3.0\WebApplication8.Views.dll
========== Rebuild All: 1 succeeded, 0 failed, 0 skipped ==========
```

Expected result:
- Some explanation for the warning icon in the error list and on hover

**Comment by danroth27** [comment] 2019-04-10 21:08
I hit another instance of these nondescript warning messages, this time with the analyzer node:

![dependency-node2](https://user-images.githubusercontent.com/1874516/55913689-1102d400-5b9a-11e9-8742-1b6e6e0d9ac8.png)
![error-list2](https://user-images.githubusercontent.com/1874516/55913701-14965b00-5b9a-11e9-9944-5f628cec066b.png)
![buid-output2](https://user-images.githubusercontent.com/1874516/55913705-16601e80-5b9a-11e9-95b3-7f132fda373e.png)

Repro:
- Create a new ASP.NET Core Web App with .NET Core 3.0 Preview 3
- Open the project in VS2019 Preview with .NET Core 3.0 Preview 4 as the active SDK (3.0.100-preview4-011146)

**Comment by drewnoakes** [comment] 2019-04-12 04:13
See also https://dev.azure.com/devdiv/DevDiv/_workitems/edit/820329/

**Comment by drewnoakes** [comment] 2019-04-29 04:50
In-progress CLI changes for `FrameworkReference` are resulting in the SDK node being shown incorrectly. In preview 5 this changed again, producing a different error state (see https://devdiv.visualstudio.com/DevDiv/_workitems/edit/857810).

We've discussed tool tips. The current way to show meaningful errors to the user is via the error list. This particular error is not caused by the user, nor is it something the user can fix. It's not clear what useful message could be given here.

Closing this in favour of tracking issue #4762.

**Closed by drewnoakes** 2019-04-29 04:50 UTC
Labels: Triaged

**Comment by drewnoakes** [comment] 2019-04-29 04:52
> I hit another instance of these nondescript warning messages, this time with the analyzer node

This is a separate issue. I suspect that more information about that error is available in the error list, or maybe as a child node in solution explorer. If you can reproduce it, could you open a new issue with enough information to repro it please?

**Comment by MisinformedDNA** [comment] 2019-06-27 15:11
@danroth27  @drewnoakes Does this analyzer node issue happen with .NET Standard 2.0? I'm not using .NET Core 3.x, but am also seeing a warning on my analyzer nodes. I'm wondering if my problem is related or if it requires creating a new issue.

**Comment by drewnoakes** [comment] 2019-06-28 00:08
@MisinformedDNA feel free to open a new issue with your repro, just in case it's a different bug.

**Comment by ckelley7** [comment] 2019-11-06 16:28
![image](https://user-images.githubusercontent.com/11668417/68317006-3c399d00-006f-11ea-8e2f-0997c34ac381.png)

I'm seeing this after migrating from .Net Core 2.2 to 3.0 for my Angular 7 app.

**Comment by drewnoakes** [comment] 2019-11-14 22:42
@ckelley7 that is being tracked by #5418.
