### ISSUE TITLE
Cannot modify .NET Standard 2.0 project to multi-targeting. 

### ISSUE THREAD

**Issue by NioZero** [dotnet/project-system#3594] opened 2018-05-29 20:14 UTC
I have a problem with a Class Library in .NET Standard when trying to modify to support multi-targeting. 

The .csproj is as follow (just created using the wizard)

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup Label="Globals">
    <SccProjectName>SAK</SccProjectName>
    <SccProvider>SAK</SccProvider>
    <SccAuxPath>SAK</SccAuxPath>
    <SccLocalPath>SAK</SccLocalPath>
  </PropertyGroup>

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

</Project>

```

Then I edit the file and make the following changes

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup Label="Globals">
    <SccProjectName>SAK</SccProjectName>
    <SccProvider>SAK</SccProvider>
    <SccAuxPath>SAK</SccAuxPath>
    <SccLocalPath>SAK</SccLocalPath>
  </PropertyGroup>

  <PropertyGroup>
    <TargetFrameworks Condition=" '$(TargetFrameworks)' == '' ">net45;net461;netstandard1.5;netstandard2.0;netcoreapp1.0</TargetFrameworks>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

</Project>
```

When I Save Visual Studio shows me these windows and the project get corrupted. 

![capture_20180529_155551](https://user-images.githubusercontent.com/1264186/40682089-e9078520-6358-11e8-9242-17de5393fef1.png)

![capture_20180529_155603](https://user-images.githubusercontent.com/1264186/40682098-ecdc249e-6358-11e8-8c5b-88dd1fca4ec6.png)

I use Visual Studio 2017 15.7.2 and I have other projects with these changes and they worked just fine.

**Comment by Pilchie** [comment] 2018-05-29 20:51
Currently having a condition on `TargetFrameworks` will break the detection logic abut about what project-system will be used to open the project. See https://github.com/dotnet/project-system/blob/master/docs/opening-with-new-project-system.md for more details. 

We're planning on fixing this for VS 2017 version 15.8 Preview 3 and later.

**Comment by Pilchie** [comment] 2018-05-29 20:52
(Dupe of https://github.com/dotnet/project-system/issues/3587)

**Closed** 2018-05-29 20:51 UTC
