### ISSUE TITLE
Restore failed with error NU1101 after changing the Target framework from ".NET Core 2.0" to ".NET Core 1.1"

### ISSUE THREAD

**Issue by MiaomiaoHuangfu** [dotnet/project-system#2500] opened 2017-06-26 09:03 UTC
- create a new .net core console app project;
- Auto restore completed with no error or warnings.
- Right click the project and click Properties;
- change the Target framework from ".NET Core 2.0" to ".NET Core 1.1".

- **Except Result:** auto restore completed with no error or warning.

- **Actual Result:** restore failed with error "NU1101: Unable to find package Microsoft.NETCore.App. No packages exist with this id in source(s): C:\Program Files\dotnet\sdk\NuGetFallbackFolder"
![nopackageinnugetfallbackfolder](https://user-images.githubusercontent.com/22901391/27531442-32156d5a-5a8f-11e7-8a5f-8209678379e1.png)

Install products:
- install 15prerel.26624.01;
- install CLI/SDK 2.0.0 preview 3 from https://github.com/dotnet/cli/tree/release/2.0.0;
- Add https://dotnet.myget.org/F/dotnet-core/api/v3/index.json as a package

dotnet --info
```
.NET Command Line Tools (2.0.0-preview3-006554)

Product Information:
 Version:            2.0.0-preview3-006554
 Commit SHA-1 hash:  c7959b942c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0-preview3-006554\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview3-25419-01
  Build    : 2fab74ca0ab629adfe1291e3f1b5eeae2a57c156

```

**Comment by natidea** [comment] 2017-06-26 18:11
Thanks. This is a dupe of https://github.com/dotnet/cli/issues/6989

**Closed by natidea** 2017-06-26 18:11 UTC
Labels: Bug

**Comment by AraHaan** [comment] 2019-04-20 16:40
oh I am trying to make my own project system too for .NET Core and VS2017/VS2019 usage for one of my command line changelog generator projects so I can overhaul some limitations in it (optimize the program). However it seems I got this error with ``VSPropertyPages``.
