### ISSUE TITLE
No warn icon are displayed in dependency node after adding some Package Reference

### ISSUE THREAD

**Issue by vdanche** [dotnet/project-system#6324] opened 2020-07-02 06:19 UTC
**Visual Studio Version**:
Version 16.7.0 Preview 4.0 [30301.213.master]

**Steps to Reproduce**:

1. Create a project from Any C# or VB .NET Core or .NET Standard groups (e.g. Console App, Unit Test Project etc.)
2. Add some Package Reference pairs that trigger a package downgrade warning.
E.g

    
        <ItemGroup>

       <PackageReference Include="NuGet.Commands" Version="4.0.0" />

       <PackageReference Include="NuGet.Packaging" Version="3.5.0" />

         </ItemGroup>

**Expected Behavior**:
This should produce NU1605 

**Actual Behavior**:
Error NU1605  can be displayed, but no warning icon are displayed in dependency node after adding some Package Reference pairs.
![image](https://user-images.githubusercontent.com/65637796/86323179-f1f4d400-bc6e-11ea-8f62-eab34fd7d209.png)

Dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.400-preview-015178
 Commit:    60cb58d3b1

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.400-preview-015178\

Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26

.NET Core SDKs installed:
  3.1.400-preview-015178 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by drewnoakes** [comment] 2020-07-02 07:53
Duplicate of #6275.

**Closed by drewnoakes** 2020-07-02 07:53 UTC
