### ISSUE TITLE
Error Dialog when copying file from one project to another:

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/project-system#2386] opened 2017-06-05 22:36 UTC
![image](https://cloud.githubusercontent.com/assets/4564579/26806221/976a7560-4a04-11e7-90fd-b261390a5761.png)

I got that when trying to copy (using ctrl-c, ctrl-v in solution explorer):

C:\GitHub\roslyn-internal\Open\src\EditorFeatures\Core\Implementation\Classification\IEditorClassificationService.cs  

over to:

C:\GitHub\roslyn-internal\Open\src\Workspaces\Core\Portable\Classification

Note that this was a copy across projects.  

EditorFeatures has 'References' so i think it's an old style project.  'Workspaces' is a new style project.  Maybe that's the issue?

**Comment by davkean** [comment] 2017-06-06 00:16
Yep I've confirmed this behavior, filed https://devdiv.visualstudio.com/DevDiv/Managed%20Project%20System/_workItems?id=446681&fullScreen=false&_a=edit against CPS.

**Comment by davkean** [comment] 2017-06-06 22:20
Turns out this was a regression in the up-to-date changes, CPS is trying to copy the new FullPath property on <Compile/> we need to prevent that:
```
    <StringProperty Name="FullPath" Visible="false">
        <StringProperty.DataSource>
            <DataSource Persistence="Intrinsic" ItemType="Compile" PersistedName="FullPath" SourceOfDefaultValue="AfterContext" />
        </StringProperty.DataSource>
        <StringProperty.Metadata>
            <NameValuePair Name="DoNotCopyAcrossProjects" Value="true" />
        </StringProperty.Metadata>
    </StringProperty>
```

**Comment by davkean** [comment] 2017-06-15 05:28
The more I think about this - this just should be automatic for intrinsic properties - the fact that you can't copy them to the new item is because it's an intrinsic property.

**Comment by davkean** [comment] 2017-06-15 05:41
Oh I spent some time figuring how why we didn't run into this before with the other intrinsic properties; they are all marked read-only. Read-only properties aren't copied.

**Comment by davkean** [comment] 2017-06-15 05:52
Got a fix for this.

**Closed** 2017-06-16 02:08 UTC
Labels: Bug
