### ISSUE TITLE
Drop "Core" from template descriptions

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/project-system#7761] opened 2021-11-11 15:20 UTC
https://github.com/dotnet/project-system/blob/9d276d96fd1fcda8e0db586c4c0c9042f74ab879/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/VSPackage.resx#L120-L149

Should be just ".NET".

**Comment by drewnoakes** [comment] 2021-11-11 21:03
Looking at this, I cannot see where these strings are actually used, and am wondering whether we can remove them.

**Comment by drewnoakes** [comment] 2021-11-11 22:14
@Youssef1313 did you see these strings somewhere in the UI, or did you only see them in this .resx file?

I've tried removing them altogether, then running a host of tests locally, none of which triggered any failure.

**Comment by Youssef1313** [comment] 2021-11-12 00:57
@drewnoakes There was a complain on Twitter about Visual Studio showing "Core" suffix for projects. Searching across GitHub, I found these strings in both this repo and [dotnet/templating](https://github.com/dotnet/templating/issues/4109). Hence, opened an issue in both repos.

https://twitter.com/Abt_Benjamin/status/1458774037753180162

**Comment by drewnoakes** [comment] 2022-09-13 01:12
The original Twitter post shows:

![image](https://user-images.githubusercontent.com/350947/189785435-ab745717-6234-495d-8e98-0110616ed6e9.png)

Currently the UI looks like this:

![image](https://user-images.githubusercontent.com/350947/189785415-910dcb13-2c6f-4369-a02a-cd65eba73bbc.png)

The resource string in this repo still shows the old string:

https://github.com/dotnet/project-system/blob/8eec0781205b50baeef36b69520f5ef6fddb6d18/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/VSPackage.resx#L139

In #7764 I proposed removing those resources altogether. I'll refresh that PR and run some tests on it.

**Comment by drewnoakes** [comment] 2022-09-13 01:22
I've filed #8484 to remove the unused resource strings from this repo.

As the original bug no longer reproduces, I'll close this.

Thanks for filing this @Youssef1313.

**Closed by drewnoakes** 2022-09-13 01:22 UTC
Labels: Triage-Approved
