### ISSUE TITLE
New csproj + same folder + VS2017: project restore/compilation interference

### ISSUE THREAD

**Issue by controlflow** [dotnet/project-system#1834] opened 2017-03-23 17:50 UTC
1. Grab the source code from here: https://github.com/controlflow/resharper-heapview.git
2. Notice I have a few `.csproj` files in the same directory referencing different versions of the same package ID. Open in VS 15.0.0+26228.9 and observe the weird interference of package restore:

![vs2017](https://cloud.githubusercontent.com/assets/194765/24261726/f17df3dc-1008-11e7-81a0-5c1bc9607215.gif)

So the problem here are:
1. Package restore of 'wave06'-suffixed project for some reason produces wrong package version presentation under 'Dependencies' Solution Explorer node for 'wave08'-project.
2. When I load 'wave06'-suffixed project into solution, the 'wave08' projects stops compiling because of missing nuget dependency. If I load 'wave07' project, 'wave08' compiles fine. Turns out this is because 'wave06' project is targeting .NET Framework 4.0 while 'wave07'/'wave08' is targeting .NET Framework 4.5.

I don't think misguided presentation and build failures are expected behavior in any way. Looks like this is the result of some project model interference happening between unrelated projects.

**Comment by davkean** [comment] 2017-03-24 05:15
Thanks for the repro, this is very likely https://github.com/NuGet/Home/issues/4463.

This MSBuild bug will also break up-to-date: https://github.com/Microsoft/msbuild/issues/1645.

**Comment by davkean** [comment] 2017-03-28 02:23
@natidea Can you confirm this is the same as the NuGet above?

**Comment by natidea** [comment] 2017-05-23 19:23
Confirmed that this is a dupe of https://github.com/NuGet/Home/issues/4463 
Only one of the project.assets.json files survive and the project listed in the file is properly resolved, while the other projects are not.

**Closed by natidea** 2017-05-23 19:23 UTC
Labels: Bug
