### ISSUE TITLE
Renaming an open file causes it end up in the MiscProject

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#2102] opened 2017-05-02 04:05 UTC
Dev15 Preview 1:

1. File -> New -> Console App (.NET Core)
2. In Solution Explorer, rename Program.cs -> Program1.cs
3. Notice that it ends up in Misc:

![image](https://cloud.githubusercontent.com/assets/1103906/25603591/65528600-2f40-11e7-87fd-34fc106903f9.png)

**Comment by davkean** [comment] 2017-05-02 04:09
Note, this appears to be have been caused by: https://github.com/dotnet/project-system/pull/1841. It looks like Roslyn expects that the file has been renaming in the running document table by the time we tell them about the file. This isn't case anymore, it looks like publishing the tree used to do that.

**Comment by CyrusNajmabadi** [comment] 2017-05-08 19:17
This is definitely super annoying (and a pretty bad regression).

**Comment by srivatsn** [comment] 2017-05-10 13:59
This issue was moved to dotnet/roslyn#19389

**Comment by srivatsn** [comment] 2017-05-10 14:00
Moving to Roslyn since per an internal thread the right fix here is in roslyn.

**Closed by srivatsn** 2017-05-10 13:59 UTC
Labels: Bug, Feature - Language Service
