### ISSUE TITLE
MSBuild spinning in the background (to the point that VS was unusable).

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/project-system#2593] opened 2017-07-12 00:59 UTC
Trace is here: https://drive.google.com/file/d/0ByISdSEZ09PBNEZUNUlfOVVQVUE/view?usp=sharing

This may be a dupe of some of the other issues i've filed.  But i'm still filing just in case this is something different.

**Comment by CyrusNajmabadi** [comment] 2017-07-12 00:59
@davkean @srivatsn

**Comment by CyrusNajmabadi** [comment] 2017-07-18 00:04
This issue is still happening.  I'm on:

![image](https://user-images.githubusercontent.com/4564579/28294928-fe221cda-6b11-11e7-8a38-4cb59ae9bdce.png)

This causes continual lag and hiccups in VS.

**Comment by davkean** [comment] 2017-07-18 01:09
11% of this Roslyn calling GetFileAttributes:
![image](https://user-images.githubusercontent.com/1103906/28296104-74bc92fc-6ba9-11e7-8033-79ce1749bfe6.png)

**Comment by davkean** [comment] 2017-07-18 01:11
18% of this is Roslyn:

![image](https://user-images.githubusercontent.com/1103906/28296171-dcfd91ea-6ba9-11e7-81e9-9e53c00a17df.png)

**Comment by davkean** [comment] 2017-07-18 01:13
Looking at the stack something is reloading target files - @CyrusNajmabadi was Restore running in the background?

**Comment by davkean** [comment] 2017-07-18 01:17
It looks like a significant portion of the VS CPU is being chewed by Roslyn:

![image](https://user-images.githubusercontent.com/1103906/28296276-a6eac9d2-6baa-11e7-877e-b57745a92aeb.png)

I suspect that with a combination of the targets reloading is likely the issue.

**Comment by davkean** [comment] 2017-07-18 01:26
Yep, there's three main threads doing all the CPU:

- module msenv <<msenv!CSolutionItemsProject::ReloadItem>>
- module microsoft.codeanalysis.features.ni <<microsoft.codeanalysis.features.ni!GlobalOperationAwareIdleProcessor.OnGlobalOperationStopped>>
- Lots of DiagnosticIncrementalAnalyzer

@CyrusNajmabadi Did you do something to trigger above? Such as switching branches? @lifengl This smells like the issue you investigated where we going down a terrible path when Roslyn switched from a branch with the DependenciesTree capability to one without and vice versa.

**Comment by lifengl** [comment] 2017-07-19 20:44
yes, it looks like some project reloading was triggered by capabilities changes.  It didn't trigger the design time build on the UI thread as what happened inside the Roslyn solution, But the solution recalculated build dependencies, which seems to be very slow.  I saw lots of time in GetMkDocument calls.  Closing project itself is also slow now.

**Comment by davkean** [comment] 2017-07-19 22:30
@CyrusNajmabadi Can you confirm if you switched branches before the issue above?

**Comment by CyrusNajmabadi** [comment] 2017-07-19 23:07
My honest belief is that i didn't.  Or i switched so long ago that it really shouldn't have mattered (i.e. 10s of minutes ago).   I generally file these because i'm doing nothing but editing, but then notice that VS perf has tanked.  I capture a trace to try to figure out why and i report.  It *is* my expectation that if i switch branches that things might be a little slow for a bit, but that it should normalize in a reasonable amount of time.  So i don't generally consider perf issues in those scenarios to be worth reporting.

**Comment by davkean** [comment] 2017-07-19 23:09
@CyrusNajmabadi Roslyn has a hacked up build that no reasonable customer solution will have - which causes us to head down a really bad path. That's what I think you are experiencing.

**Comment by davkean** [comment] 2017-07-19 23:10
After switching branches between a branch that turns on and off the Dependences node - it's taking 10s of minutes for us to deal with this situation.

**Comment by davkean** [comment] 2017-08-01 05:32
Side note, I'm looking at Roslyn-specific perf over here: https://github.com/dotnet/roslyn/issues/21225. It looks like globs probably regressed design-time perf by about 30%.

**Comment by Pilchie** [comment] 2017-10-17 17:37
This looks like an exact dupe of #2576?

**Comment by Pilchie** [comment] 2017-11-01 20:42
See also traces in https://github.com/dotnet/project-system/issues/2576

**Comment by onyxmaster** [comment] 2017-11-04 18:41
Occasionally stumbled upon this, the GetFileAttributes problem was fixed by [dotnet/roslyn#22340](https://github.com/dotnet/roslyn/pull/22340). This doesn't mean that its caller shouldn't be optimized though =)

**Comment by Pilchie** [comment] 2017-12-20 23:32
I think we can close this particular issue, based on the GetFileAttributes fix and other evaluation fixes for SDK based projects in 15.5.

**Closed by Pilchie** 2017-12-20 23:32 UTC
Labels: Bug, Performance

**Comment by davkean** [comment] 2018-05-08 06:50
In 15.7, we now cache design-time builds which means we spent less time chewing CPU in MSBuild when stuff hasn't changed.
