### ISSUE TITLE
UI delay on focus of 'Search Visual Studio' box (project system query status)

### ISSUE THREAD

**Issue by gundermanc** [dotnet/project-system#4522] opened 2019-01-31 07:26 UTC
**Visual Studio Version**:
Visual Studio 2019 Int Preview d16.0stg latest

**Summary:**
Focusing the 'Search Visual Studio' control with a C# project open and an editor window focused causes a UI delay of anywhere from a few MS all the way up to several seconds.

**Steps to Reproduce**:

1. Create or open large C# project.
2. Open an editor window
3. Focus the 'Search Visual Studio' control and immediately start typing.

**Expected Behavior**:
Typing is fluid and responsive.

**Actual Behavior**:
There is a 10 to > 1k ms UI delay on focus of search due to a long running command Query Status in the project system.

```
Delay 7 1200ms @ 11:04:52.4 PM 6 distinct stacks of 6 collected
Failure Frames:
3 GENERIC_MODULE!GENERIC_METHOD
3 Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNodeWrapper.IsDocumentInProject2
…
Microsoft.VisualStudio.ProjectSystem.VS.Tree.Dependencies.DependenciesTreeViewProvider+<>c.<FindByPath>b__7_0
?!?
Microsoft.VisualStudio.ProjectSystem.VS.Tree.Dependencies.DependenciesTreeViewProvider.FindByPath
Microsoft.VisualStudio.ProjectSystem.VS.Tree.Dependencies.DependenciesProjectTreeProvider.FindByPath
?!?
?!?
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[Microsoft.VisualStudio.ProjectSystem.VS.IsDocumentInProjectResult].Start
Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode+StandardIsDocumentInProjectHandler.IsDocumentInProjectAsync
Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode+<>c__DisplayClass636_0+<<IsDocumentInProjectInternal>b__0>d.MoveNext
System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start
Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode+<>c__DisplayClass636_0.<IsDocumentInProjectInternal>b__0
```

**User Impact**:
Causes UI freeze and typing glitches in the search box.

This same issue has been filed against CPS as well in case it is a CPS issue: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/782050

**Comment by davkean** [comment] 2019-01-31 10:02
We own this, I can repro with ProjectSystem.sln - only happens the first time, wonder if the progression init. Looking at traces.

**Comment by davkean** [comment] 2019-01-31 11:16
@gundermanc Can you capture a ETW trace of above? While I can repro the delay, DelayView and ETW on my box and repro (ProjectSystem.sln from this repro) say that it's not IsDocumentInProject2 (it's ~0.5% -> 1% of CPU). 

This is what I did:

1. Open ProjectSystem.sln
2. Switch back to perf view, Start Collection
3. Switch back to VS and click into the search box and start typing
4. Stop tracing
5. Inside trace, in events, find the first Microsoft-VisualStudio-Common/vs_ide_hasfocus/Start and make note its time
6. Also in events, find Microsoft-VisualStudio-Common/vs_ide_search_completed event and make note its time
7. Open CPU, change Start to time to Microsoft-VisualStudio-Common/vs_ide_hasfocus/Start and change End to Microsoft-VisualStudio-Common/vs_ide_search_completed 
8. From Calltree tab, find the UI thread (will have VStudioMain on it) and click Include
9. Go back to By Name tab and sort by Inc
10. Walk down these and try and find the heavy hitters
--

If I look at overhead, I do see Microsoft.VisualStudio.Editor.Implementation!CompoundTextViewWindow.QueryStatus as a heavy hitter, but it's querying a bunch of random commands:

![image](https://user-images.githubusercontent.com/1103906/52050533-f235ff00-25a4-11e9-9e31-a000c4464afd.png)

Almost all of which are not visible. I'm assuming this is the search searching all top-level commands? This will introduce the delays during searching - usually QueryStatus is limited to the commands that currently visible. Here I'm guessing you are querying all visible/enabled commands regardless of their relevance to the query? I think you'll want to flip this - only query a command's availability when it is a candidate for the search results. Above I typed random characters, we shouldn't be querying "ReorderParamaters".

**Comment by davkean** [comment] 2019-02-01 06:37
Going to mark this as no-repro without a trace. I think you should reconsider executing a bunch of Query Status on commands that are not applicable to the current search.

**Comment by gundermanc** [comment] 2019-02-01 06:42
Unforunately the QueryStatus is required because many commands in VS are dynamic text. We don't know what to search without running QueryStatus. This same issue has existed since Dev10 quick launch IIRC and there is no reasonable alternative.

I'll see if I can repro again and may reopen the issue with traces.

**Comment by davkean** [comment] 2019-02-01 06:44
I think you should reconsider the design. Executing a bunch of QueryStatus for a giant set of commands, on the UI thread, is going to be slow. Weren't you working on modern command-routing? Can this be used off thread?

**Comment by gundermanc** [comment] 2019-02-01 06:54
We only search the top 120 commands, same as in Dev10 quick launch. QueryStatus is required to determine the commands that are visible, enabled, and to determine their text. Similar to typing performance, the only alternative is to not search commands.

I've implemented some [VS core perf optimizations](https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/157694) and QueryStatus caching.

I'll see if I can repro again and may reopen the issue with traces.

**Comment by davkean** [comment] 2019-02-25 00:51
Going to close this out - there's no trace that points to IsDocumentInProject as the cause of this trace.

**Closed by davkean** 2019-02-25 00:51 UTC
Labels: Resolution-No-Repro, Triaged

**Comment by gundermanc** [comment] 2019-06-14 04:53
I'm seeing consistent instances of this again, though its a very brief delay on the order of 200-1000ms, so it's not picked up by PerfWatson.

Is there a set of commands that are known to call IsDocumentInproject2 that can be blacklisted to avoid this delay? The callstack is lost in the traces.

**Comment by davkean** [comment] 2019-06-15 00:04
Set a breakpoint on the method and use Debugging trace feature to writeline the callstack and you'll quickly find the callers. There's no list of commands that do this.

Sent from Outlook
________________________________
