### ISSUE TITLE
Allow users to configure which implicit usings are in their project

### ISSUE THREAD

**Issue by jmarolf** [dotnet/project-system#7586] opened 2021-09-13 23:00 UTC
The new implicit usings feature that the SDK implemented bears passing similarity to the "implicit imports" feature that Visual Basic has had for year. In Visual Basic it was possible to see (and modify) the set of implicit imports that were used:
![MicrosoftTeams-image](https://user-images.githubusercontent.com/9797472/133167507-27969d06-8d7c-420e-aaa8-a8c51bd117be.png)

There have been requests (https://github.com/dotnet/roslyn/issues/56283) to allow the user to both be able to see which usings are being implicitly brought in and be able to adjust these.

**Comment by drewnoakes** [comment] 2021-09-13 23:02
@jmarolf looks like this is a dupe of #7488.

**Closed** 2021-09-14 04:28 UTC
