### ISSUE TITLE
Fast up to date check is using incorrect/state data

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#2987] opened 2017-11-27 18:50 UTC
Visual Studio 15.5.0 Preview 4.

I have noticed that some projects are building when no changes have been made. This appears to be a failure of the &quot;fast up-to-date check&quot;. For example, one particular projects is displaying:

1&gt;Project 'X' is not up to date. Missing input file 'C:\Users\&lt;USER&gt;\Source\Repos\Packages\System.Collections.Immutable.1.4.0\lib\netstandard2.0\System.Collections.Immutable.dll'.

In this particular scenario, a nuget package was updated and then rolled back. The project does not  reference the new package anywhere so somethig is being permanently cached (even in between restarts).

On another occassion, it was using the timestamp of the version in the msbuild folder:

&quot;C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\MSBuild\15.0\Bin\System.Collections.Immutable.dll&quot;

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/153857/fast-up-to-date-check-is-using-incorrectstate-data.html
VSTS ticketId: 527711_
_These are the original issue comments:_

David Ward on 11/22/2017, 08:24 AM (5 days ago): <p>This issue is not present in 15.4.4</p>

_These are the original issue solutions:_
(no solutions)

**Comment by davkean** [comment] 2017-11-28 00:04
tag @panopticoncentral

**Comment by Pilchie** [comment] 2017-11-28 02:20
Based on the `Packages` in the path, I wasn't sure whether this was an old style project or an sdk project...

**Comment by davkean** [comment] 2017-11-28 23:33
Yes, looking at data, it is a solution with old style projects and C++.

**Comment by davekoenig** [comment] 2017-12-20 18:49
Is there a work around for this?  I'm getting this on my solution as well and it's causing a significant drop in productivity.  Doesn't seem to effect every developer on the team the same though.

**Comment by Pilchie** [comment] 2017-12-20 18:55
We're trying to investigate, but so far we haven't been able to reproduce the failures :(

**Comment by davkean** [comment] 2017-12-20 23:55
@Pilchie If the reference is added via evaluation or a target - this could be that the props/targets file isn't being reloaded. We should figure out if this is a `<PackageReference/>` which would hit this.

**Comment by davkean** [comment] 2017-12-20 23:56
Hmm, but it's persisted between restarts? Do we cache up-to-date info in the suo in legacy project system?

**Comment by Pilchie** [comment] 2017-12-21 01:33
We cache the timestamps and stuff AFAICT - the fast up to date check *can* skip builds on the first build.

**Comment by Pilchie** [comment] 2017-12-21 01:37
However, I'd be curious to know if this repros on 15.5.2.  There were some issues with "Allow parallel project initialization" that could cause issues here (though not with the symptoms above that I have seen).

Anyone who is seeing this, please make sure you have 15.5.2, and that you have deleted your .vs directory at least once since installing 15.5.2 so that the cache doesn't contain the incorrect data.

**Comment by Pilchie** [comment] 2018-01-08 19:08
Closing as not repro, but will look if I get more data here or on the devlloper community link.

**Closed** 2018-01-08 19:08 UTC
Labels: Area-Legacy-Project-System, Blocked, Bug, Feature - Up-to-date, Resolution-No Repro

**Comment by Novagenda** [comment] 2018-04-16 12:47
@Pilchie We have just updated our Visual Studio from 15.4.x to 16.6.x and are now starting to have this issue.

We have a solution with 100 projects (old style) and when we build it, it only detects that approx. 30 projects are up to date although nothing has changed. 
If we edit a not up to date projects .csproj file in vs and just add a space in the end of the file this project is up to date second time we build it. So it begins to work but if I use this project in another solution it will still not believe it is up to date.

When I have extended build information I can see it can't find our analyzer file, I understand that as the path is wrong. But it is not the path which I have defined.

**Comment by Novagenda** [comment] 2018-04-17 06:24
@Pilchie Rebuild and clean/build do not fix the problem. (already tried several times :-))

From the log: Project 'XXX' is not up to date. Missing input file 'c:\git\YYY\build\packages\microsoft.netframework.analyzers.2.6.0-beta2\analyzers\dotnet\cs\microsoft.netframework.csharp.analyzers.dll'.

This is understandable as the path isn't correct, but I also wonder why the path is different from what I have defined.

Uncheck "Allow parallel project initialization" seems to fix the problem. But I assume that cause increased load time which I will try now.

I found this related topic: https://developercommunity.visualstudio.com/content/problem/172089/vs2017-1552-unresolved-references-when-allow-paral.html

But that should be fixed.

**Comment by Novagenda** [comment] 2018-04-17 06:50
Maybe this is more relevant: https://developercommunity.visualstudio.com/content/problem/161997/full-build-every-time-with-155.html
But I can see you @Pilchie already commented there and it should be fixed in 15.5.4 so maybe someone forgot to merge the fix to the 15.6 branch :-)

**Comment by gfrhd** [comment] 2023-04-12 09:06
>     1. Uncheck "Tools\Options\Projects and Solutions\Allow parallel project initialization"
This one solved the issues in my case. Nothing else (delete all of .vs bin obj folders) have helped. I'm using 2019 (16.11.25)
