### ISSUE TITLE
Visual Studio auto completion misses <Nullable> tag

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/project-system#6345] opened 2020-07-03 15:04 UTC
**Version Used**: 

Visual Studio 2019 16.16.3

**Steps to Reproduce**:

1. Open a csproj file
2. Try writing <Nu...

**Expected Behavior**:

Auto completion shows Nullable

**Actual Behavior**:

Auto completion doesn't show Nullable

![image](https://user-images.githubusercontent.com/31348972/86480893-335cb080-bd4f-11ea-8fc4-552785be3ad8.png)

**Comment by rainersigwald** [comment] 2020-07-07 20:36
Duplicate of microsoft/msbuild#4840

**Comment by rainersigwald** [comment] 2020-07-07 20:36
This is fixed in 16.4+ by microsoft/msbuild#4840.

**Comment by Youssef1313** [comment] 2020-07-07 21:08
@rainersigwald I'm using 16.6.3

**Comment by davkean** [comment] 2020-07-07 23:49
This doesn't show in latest builds:

![Uploading image.png…]()

**Comment by rainersigwald** [comment] 2020-07-09 22:25
Thanks. Closing this in favor of the MSBuild bug, for which an (internal, VS repo) PR is in flight.

**Closed by rainersigwald** 2020-07-09 22:25 UTC

**Comment by drewnoakes** [comment] 2020-08-03 23:38
https://github.com/dotnet/msbuild/pull/5611 adds completion for the possible values (enable, disable, warnings, annotations).
