### ISSUE TITLE
Out of sync nodes in VS2017

### ISSUE THREAD

**Issue by Mpdreamz** [dotnet/project-system#2086] opened 2017-04-28 12:13 UTC
![image](https://cloud.githubusercontent.com/assets/245275/25528161/a077d28e-2c1c-11e7-984f-e585c055c0af.png)

Editing a project with both rider and vs and somehow got into this state.

Those files are definitely there and everything compiles just fine. Not sure if this the right repositiory/place for posting this.

**Comment by srivatsn** [comment] 2017-05-02 19:55
Can you please post what the csproj looks like in this state?

**Comment by davkean** [comment] 2017-08-31 06:05
This looks like a dupe of https://developercommunity.visualstudio.com/content/problem/80855/solution-shows-missing-file-icon.html which will be fixed in Preview 2 of VS 15.4. I'll close it as we don't have a repro - but if you could provide some repro steps or projects, I can confirm this.

**Closed by davkean** 2017-08-31 06:05 UTC
