### ISSUE TITLE
Consider making Launch Profiles a "Properties" editor tab instead of a modal dialog

### ISSUE THREAD

**Issue by MiYanni** [dotnet/project-system#7406] opened 2021-07-20 17:38 UTC
I had a suggestion for the Launch Profiles to function similarly to Project Properties in terms of access and look/feel. So, Launch Profiles would be treated like a .csproj. If you opened (double click) the `launchSettings.json` in VS, it would show the text editor (json editor) for the file. However, just like Project Properties, if you right clicked on `launchSettings.json` and selected `Properties`, it would open this dialog as an editor tab, just like Project Properties. Seems better than a modal dialog.

One thing to keep in mind is that `launchSettings.json` has no unique file extension. There may need to be a process that actually checks to see if a `.json` is a Launch Profile. Not sure if something like that already exists or not.
**Edit:** It sounds like `launchSettings.json` is a unique filename in a specific location. So, it can be assumed to be the launch profile file based on that criteria.

**Comment by drewnoakes** [comment] 2021-07-20 21:29
Duplicate of #7390.

**Comment by MiYanni** [comment] 2021-07-20 22:21
@drewnoakes But it's not a duplicate. The suggestion here is to make Launch Profiles an editor tab. The suggestion in the issue you linked suggests, "I would prefer if this window could just be a tab as in the previous versions of VS." The 'tab' they are referring to is a tab in Project Properties, like this:
![image](https://user-images.githubusercontent.com/17788297/126402530-17506104-061c-4637-9f01-52c4fd17d5da.png)

I'm suggesting it should be an editor 'tab', like the entire Project Properties page. VS opens editors as tabs in the editor pane, so I understand the confusion. So, you'd click `Properties`, and it opens as an editor tab that would say something like `launchSettings` (no extension) or `Launch Profiles` under the appropriate project's tab group.
![image](https://user-images.githubusercontent.com/17788297/126402728-702a6ae8-cd02-4674-ad8c-f5db6315e74e.png)

**Comment by drewnoakes** [comment] 2021-07-20 22:46
This is a dupe. Rikki and I discussed #7390 ahead of it being filed, and the intent is to make the UI a non-modal editor that may be docked in the IDE just as any other document.

**Closed by drewnoakes** 2021-07-20 22:46 UTC
Labels: Feature Request, Feature-Project-Properties-Designer, Triage-Investigate
