### ISSUE TITLE
Package is not shown as resolved in the UI

### ISSUE THREAD

**Issue by nkolev92** [dotnet/project-system#2597] opened 2017-07-12 22:12 UTC
Repro version:
15.3 Preview 3,4

- Create a new .NET Core console app
- Add a dependency
```
<ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore" Version="2.0.0-*" />
  </ItemGroup>
```
- It should restore at resolve 2.0.0-preview2-final.
- Now change the dependency to 2.0.0-preview2-final explicitly
```
<PackageReference Include="Microsoft.AspNetCore" Version="2.0.0-preview2-final" />
```
- The package fails to be resolved in Microsoft.AspNetCore 2.0.0-*

![pic](https://user-images.githubusercontent.com/2878341/28096624-163ef05c-665f-11e7-9519-a207e632a99b.png)
Note:
Closing and opening the solution fixes it. 
Restore actually runs here, so this seems to be only a UI only issue. 
Little bit of a redundant test since it's not really compatible, but this issue does not repro on 15.2. 

Dup of https://github.com/NuGet/Home/issues/5588

//cc
@rrelyea @srivatsn

**Comment by srivatsn** [comment] 2017-07-13 19:09
Dupe of https://github.com/dotnet/project-system/issues/2510 - since the resolved version is the same after the edit, the node doesn't update from unresolved to resolved state.

**Closed by srivatsn** 2017-07-13 19:09 UTC
