### ISSUE TITLE
UI for "PackageVersion" in C# Project Properties does not update the PackageVersion tag in the .csproj file

### ISSUE THREAD

**Issue by Brondahl** [dotnet/project-system#5678] opened 2019-11-28 14:16 UTC
Originally uncovered in report of a Nuget Issue: https://github.com/NuGet/Home/issues/7542
Considered to be a VS UI bug, rather than a Nuget Pack bug.

**Visual Studio Version**:
I have personally reproduced it on:
2017 Professional.
2017 Community.
2019 Professional.

**Summary**:
Setting the "PackageVersion" in the VS UI, modifies the `<Version>` tag, but not the `<PackageVersion>` tag, in the `.csproj` file.

Packing appears to use either tag, but take PackageVersion for preference.
Thus the UI doesn't reliably update the output package version.
**Steps to Reproduce**:

1. Create a new .NET Core ClassLibrary Project
2. Open the .csproj file and observe <PackageVersion> and <Version> are absent
3. In VS. Project > Properties > Package.
4. Enable "Package on Build"
5. Build, and observer a 1.0.0 package created.
6. In VS UI edit PackageVersion to 2.0.0. Save and Rebuild.
7. Observe that the `.csproj` file now has `<Version>2.0.0</Version>` and the `.nupkg` is 2.0.0
8. Edit the `.csproj` file to add `<PackageVersion>3.0.0</PackageVersion>`. Save and Rebuild.
9. Observe that UI still say 2, but the pkg is now 3.
10. Edit the UI to set "PackageVersion" to 4.0.0 . Save and Rebuild.
11. Observe that the `.csproj` file now has `<Version>4.0.0</Version>` but still has `<PackageVersion>3.0.0</PackageVersion>`, and the `.nupkg` is still 3.0.0

**Expected Behavior**:
UI should update the <PackageVersion> tag.
(Either as well as, or instead of, the <Version> tag.

**Actual Behavior**:
UI only updates <Version> tag.

**User Impact**:
Confusing UI that can end up mis-representing the Version that will be built.

**Comment by drewnoakes** [comment] 2019-11-28 21:46
Notes about this bug:

A project and its outputs may have several versions:

- Assembly version (`<AssemblyVersion>`)
- Assembly file version (`<FileVersion>`)
- Package version (`<PackageVersion>`)

Usually you want the same value across all these versions. The `<Version>` property makes that straightforward by giving a single property that populates all of the above.

In the UI, the "Package" property page's "Version" field currently maps to the `<Version>` project property alone. This means that if a `<PackageVersion>` is present in the project, it will not be updated by the UI's "Package version" field, leading to incorrect output.

The "Package" property page has UI for `<AssemblyVersion>` and `<FileVersion>` properties, both of which behave correctly.

![image](https://user-images.githubusercontent.com/350947/69832887-c054fe00-1284-11ea-82f7-d7d06a015940.png)

**Comment by davkean** [comment] 2019-12-20 00:30
Duplicate of https://github.com/dotnet/project-system/issues/3004.

**Closed by davkean** 2019-12-20 00:30 UTC
Labels: Bug, Feature-AppDesigner
