### ISSUE TITLE
Weird behavior in "Imported namespaces" selector

### ISSUE THREAD

**Issue by rchande** [dotnet/project-system#2406] opened 2017-06-08 15:38 UTC
Create a new VB console app, go to project properties -> references. Attempt to deselect some of the automatically imported namespaces.  A number of strange things can happen:
1. it takes multiple clicks on a checkbox to deselect it
2. if you repeatedly click on one checkbox, other checkboxes in the control will start deselecting (!)

This is on 26602.0.d15rel

**Comment by rchande** [comment] 2017-06-08 15:38
cc @tannergooding

**Comment by tannergooding** [comment] 2017-06-08 17:05
Confirmed that this does repro on 15.2

**Comment by srivatsn** [comment] 2017-06-08 17:07
Dupe of https://github.com/dotnet/project-system/issues/1326

**Closed by srivatsn** 2017-06-08 17:07 UTC
