### ISSUE TITLE
Fast Up To Date Check fails for files linked from a neighbor project

### ISSUE THREAD

**Issue by gleblebedev** [dotnet/project-system#9124] opened 2023-06-26 20:30 UTC
## Visual Studio Version
17.6.3

## Summary
Build system ignores changes in files when they referenced from multiple projects. Setting DisableFastUpToDateCheck to true mitigates  the issue.

## Steps to Reproduce

1.  Download attached sample project.
2. Run both projects. Observe output value.
3. Change text file in the first project. Run both projects.

## Expected Behavior
The output should change too

## Actual Behavior
The output prints original text file content

## User Impact
Users have to clean or rebuild the project every time a content file changed.

https://cdn.discordapp.com/attachments/732310858776182866/1122298127647506432/bug.mp4
[MSBuildBufRepro.zip](https://github.com/dotnet/project-system/files/11873888/MSBuildBufRepro.zip)

**Comment by drewnoakes** [comment] 2023-06-27 04:25
Thanks for the bug report.

VS has a special-case handling when launching a debugger (e.g. via <kbd>F5</kbd>), which is triggering a bug in the FUTDC. I will get this fixed.

A workaround for now is to build before launching (you don't have to _re_build, just a regular build will do the trick). The issue only occurs when the build happens as part of launching the debugger.

**Comment by drewnoakes** [comment] 2023-06-27 11:37
I believe this is a duplicate of the feedback ticket https://developercommunity.visualstudio.com/t/Copy-if-newer---Issue-when-only-non-sour/10308822. We'll keep this GitHub issue open too to track the fix.

**Closed** 2023-06-28 12:56 UTC
Labels: Bug, Regression, Feature-Up-to-date

**Comment by drewnoakes** [comment] 2023-06-28 12:57
Fixed in https://github.com/dotnet/project-system/pull/9130 which should make the next 17.7 preview.
