### ISSUE TITLE
.NET Standard Class Diagram Generic Interfaces Error

### ISSUE THREAD

**Issue by PanosKousidis** [dotnet/project-system#3705] opened 2018-07-11 18:32 UTC
1. Create new Class Library (.NET Standard)
2. Add new interface` ITest<T>`
3. Add a class diagram and drag and drop the generic interface (works fine here)
4. Close and re-open the class diagram
5. Get the errors
![image](https://user-images.githubusercontent.com/30468998/42592133-90a47f6e-8540-11e8-9334-7d1a432f8574.png)
![image](https://user-images.githubusercontent.com/30468998/42592170-aaca2cf4-8540-11e8-97b1-2d9418b96225.png)

ClassDiagram1.cd contents:
![image](https://user-images.githubusercontent.com/30468998/42592356-285f949c-8541-11e8-9f37-f5a222528fb0.png)

**Comment by davkean** [comment] 2018-07-12 01:03
Thanks for the great repro, I can repro this in 15.7.5, but does not repro in 15.8. This is a dupe of https://github.com/dotnet/project-system/issues/2999.

**Closed** 2018-07-12 01:03 UTC
Labels: Bug, Resolution-Duplicate
