### ISSUE TITLE
Integration Test: Build and up-to-date

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#1335] opened 2017-01-25 06:14 UTC
We should have a integration test that checks that we can build and subsequent builds are up-to-date.

**Comment by davkean** [comment] 2017-01-25 06:15
To avoid: https://github.com/dotnet/roslyn-project-system/pull/1334

**Comment by srivatsn** [comment] 2017-06-20 22:43
Dupe of #2452

**Closed by srivatsn** 2017-06-20 22:43 UTC
Labels: Bug, Test
