### ISSUE TITLE
Visual Studio ran into unexpected problem, and may impact some project system functions.

### ISSUE THREAD

**Issue by kartheekp-ms** [dotnet/project-system#6679] opened 2020-10-14 18:41 UTC
**Visual Studio Version**: Version 16.9.0 Preview 1.0 [30609.169.main]

**Summary**:

**Steps to Reproduce**:

1.  Cloned [`NuGet.Client` ](https://github.com/NuGet/NuGet.Client) from GitHib

2. Build following [instructions](https://github.com/NuGet/NuGet.Client/blob/dev/CONTRIBUTING.md#build)

3. Opened `NuGet.sln` in VS.

**Expected Behavior**:
No unexpected problems

**Actual Behavior**:
Visual Studio ran into unexpected problem, and may impact some project system functions.

```
=====================
10/14/2020 11:32:47 AM
Recoverable
System.Collections.Generic.KeyNotFoundException: The given key '18075' was not present in the dictionary.
   at System.Collections.Immutable.ImmutableDictionary`2.get_Item(TKey key)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.TreeService.TreeData.NodeFromIdentity(IntPtr identity)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.TreeService.TreeData.FireProjectItemsEventsItemAddedOrRemovedImpl(IVsExtensibility2 vsExtensibility2, SimpleItemNode simpleItemNode, IProjectTree projectTree, Builder pendingList, Boolean isAdded)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.TreeService.TreeData.FireProjectItemsEventsItemAddedOrRemoved(SimpleItemNode simpleItemNode, IProjectTree projectTree, Builder pendingList, Boolean isAdded)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.TreeService.TreeData.OnAfterApplyTree(TreeData previouslyAppliedOutput, ImmutableDictionary`2 renames, TreeUIState treeUIState)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.TreeService.ApplyAsync(TreeData value)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Rethrow(Exception ex)
   at Microsoft.VisualStudio.ProjectSystem.ProjectErrorReporting.<>c__DisplayClass6_0.<SubmitErrorReport>b__0()
   at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>c__DisplayClass2_0.<Guard>g__action|0()
   at GuardMethodClass.GuardMethod(Func`1 , Func`2 , Func`2 )
```

**User Impact**:

**Comment by drewnoakes** [comment] 2020-10-14 21:14
cc: @lifengl

**Comment by drewnoakes** [comment] 2020-10-14 21:51
Duplicate of #6669. 

@vritant24 closed that issue with comment:

> Does not repro in the latest main anymore

@kartheekp-ms that build is five days old. Can you update your main install and verify whether the problem persists?

**Comment by davkean** [comment] 2020-10-14 22:03
This was fixed by the CPS team.

**Closed by davkean** 2020-10-14 22:03 UTC
