### ISSUE TITLE
Changes made through Project Query API are not automatically saved to disk

### ISSUE THREAD

**Issue by tmeschter** [dotnet/project-system#6688] opened 2020-10-16 20:08 UTC
As @drewnoakes noted in https://github.com/dotnet/project-system/pull/6681#issuecomment-709197242 changes made to the project file are not automatically persisted to disk, though they are picked up and processed by the project system.

We need to decide if this is desirable behavior, and if not how to deal with it.

**Comment by drewnoakes** [comment] 2020-11-06 04:33
If we have unsaved changes in the text buffer, does the Project Query API return data that includes unsaved changes? Do we evaluate unsaved changes? //cc @davkean @lifengl

**Comment by drewnoakes** [comment] 2020-11-06 04:34
We need to also consider the legacy case.

**Comment by davkean** [comment] 2020-11-06 04:36
To make sure we're talking about the same concept what do you mean by "text buffer"? There are two effective "buffers" or "docdata" for CPS projects so want to make sure we're talking about the same thing.

**Comment by davkean** [comment] 2020-11-06 04:36
Not sure why we'd expect changes make through project API to automatically save the project?

**Comment by drewnoakes** [comment] 2020-11-06 04:44
The legacy pages apply changes made in the UI to the project file on disk immediately. The question here is whether we should reproduce that behaviour, or keep changes unsaved in memory somewhere (text buffer, something else &mdash; I'm not familiar there yet). The latter is the current behaviour, but I don't know if queries made of the API include these unsaved changes in their results.

If CPS and legacy work correctly with unsaved project changes, then we may consider changing the behaviour in the UI.

There's also the question of whether the legacy behaviour provides a better user experience. What happens if the project file in memory is invalid due to user edits?

> There are two effective "buffers" or "docdata" for CPS projects

I didn't know this. Guessing: one for the project model, one for actual user text edits. Is that the case? Where are the unsaved changes made by the query API held?

**Comment by davkean** [comment] 2020-11-06 04:46
> The legacy pages apply changes made in the UI to the project file on disk immediately

They do not, they immediately apply to the in-memory project. Are you referring to "saving" the project/designer when you mean this?

**Comment by davkean** [comment] 2020-11-06 04:50
Thing about it like this;

Solution Explorer and AppDesigner are both "designers" of the project. Any changes made via them, immediately apply to the unsaved project. Explicitly saving either of them, pushes the changes to disk.

**Comment by drewnoakes** [comment] 2020-11-06 05:01
The current property pages do save to disk. Try changing the output type.

**Comment by davkean** [comment] 2020-11-06 05:09
We must be talking about different things. What do you mean by "apply"? Do you mean "save"?

**Comment by drewnoakes** [comment] 2020-11-06 05:31
Change the output type drop down in the property pages UI, the file is updated on disk immediately.

**Comment by davkean** [comment] 2020-11-06 05:34
Can you show me?

**Comment by davkean** [comment] 2020-11-06 05:35
Are you sure you not getting confused by pending changes?

**Comment by davkean** [comment] 2020-11-06 05:47
We must be talking about different things or steps. The property pages have always applied only to in-memory project unless you save them since they were released in Whidbey.

**Comment by drewnoakes** [comment] 2020-11-06 06:36
I'm using Sublime Text to monitor the file on disk. It is updated as soon as you change the Output Type combo box, for example. This is a .NET Core Console App.

**Comment by drewnoakes** [comment] 2020-11-06 07:37
Further testing shows this only happens in my 16.7 GA install, which has a bunch of extensions installed. One of them appears to be auto-saving the project properties. Possibly R#. The dirty indicator `*` appears briefly in the document tab then disappears.

Once we've verified that the Project Query API includes unsaved changes in its results (so we can refresh the UI) we can close this. It seems likely it already does.

**Closed** 2021-02-02 10:29 UTC
Labels: Feature-Project-Properties-Designer, Triage-Approved
