### ISSUE TITLE
ResXFileCodeGenerator  error on every resx file added

### ISSUE THREAD

**Issue by orobert91** [dotnet/project-system#2912] opened 2017-10-20 02:47 UTC
Using Visual Studio 2017 15.4.1 and .NET Core 2.0.0, when creating resx files, the "Error List" window gets filled with "Custom tool ResXFileCodeGenerator failed to produce an output for input file '<file_name.resx>' but did not log a specific error." This is an old error that is talked about on multiple (closed) threads around here, but I'm reopening the issue because it does not seem fixed at all and is incredibly annoying. 

Steps:
1. Create .NET Core project
2. Create resx file and add a few strings.
3. Right-click on the resx file -> Run Custom Tool

Please note that even without clicking "Run Custom Tool", the errors eventually come up. If I put 30 resx files in the project, my "Error List" window will eventually be filled with 30 errors like this. The resx files do work, but needless to say this is very annoying noise.

![image](https://user-images.githubusercontent.com/6403705/31802833-5bb22380-b51e-11e7-9a33-7fab510fe141.png)

**Comment by Pilchie** [comment] 2017-10-23 23:08
Duplicate of https://github.com/dotnet/project-system/issues/1553.

@davkean is there a workaround that people can use?

**Closed by Pilchie** 2017-10-23 23:08 UTC
