### ISSUE TITLE
The Debug Launch profiles dialog is a mess.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#9030] opened 2023-05-18 12:59 UTC
_This issue has a corresponding [ticket on Developer Community](https://developercommunity.visualstudio.com/t/The-Debug-Launch-profiles-dialog-is-a-me/1618226). Please vote and comment there to make sure your voice is heard._

---
[severity:It's more difficult to complete my work]
The dialog is a mess. It doesn’t dock like other panels in VS. It’s modal, so it must be closed to do anything else – BUT the only way to close it is to click the “x” in the corner ---- which for EVERY other dialog within Windows means “Cancel - Don’t save”, but here, it saves the data, which is counter-intuitive AND leaves no way to exit without saving. You would think that a product from Microsoft would follow Microsoft’s Windows Design Guidelines (particularly when the product target market is people who are expected to write applications that follow the Design Guidelines)

>The Close button on the title bar should have the same effect as the Cancel or Close button within the dialog box. Never give it the same effect as OK.
>https://docs.microsoft.com/en-us/windows/win32/uxguide/win-dialog-box

When I saw this dialog in the previews, I assumed it was just a placeholder which you planned to replace before the release. I was quite surprised to still find it VS2022 Current version. How did no one on the project team see what a disaster that dialog is?

---
#### Feedback Bot on 12/20/2021, 10:41 PM: 

(private comment, text removed)
#### Sara Liu [MSFT] on 12/23/2021, 00:04 AM: 

(private comment, text removed)
#### Feedback Bot on 4/2/2022, 00:58 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by drewnoakes** [comment] 2023-05-22 04:39
Duplicate of #7390.

**Closed** 2023-05-25 23:03 UTC
