### ISSUE TITLE
We need a setting to define the what double clicking project does 

### ISSUE THREAD

**Issue by sharwell** [dotnet/project-system#4493] opened 2019-01-24 04:09 UTC
Version: 16.0 Preview 2

### Steps to reproduce:

1. Open a solution with a CPS-based C# project
2. Double click to expand the project in Solution Explorer.

### Expected results:

The project expands in Solution Explorer.

### Actual results:

The project does not expand in Solution Explorer, and instead the project opens.

📝 I was aware of the behavior change but avoided filing this issue until I actually hit it by accident. It happened within 5 minutes of installing Preview 2.

**Comment by davidwengier** [comment] 2019-01-24 05:04
Thanks for the feedback! Part of our rationale for shipping this feature, and the rest of project file editing improvements, in a preview release was to gauge the response from our users before the final release. Please keep us updated if your opinion changes at all as you use the preview more and potentially get used to the new experience.

Out of curiosity do you have the "Allow new files to be opened in the preview tab" turned on, and if so do you find that experience with the project file a positive or negative one?

**Comment by sharwell** [comment] 2019-01-24 14:47
I believe the **Regression** label is accurate. This behavior works in Visual Studio 2005, 2008, 2010, 2012, 2013, 2015, 2017, and 2019 Preview 1.1. It broke in Visual Studio 2019 Preview 2, which is a clear behavior regression relative to the preceding 8 versions.

**Comment by cartermp** [comment] 2019-01-25 05:40
Not sure if we have a label for this, but I think the classification would be "Intentional behavior change", since regression indicates something is unexpected. We mention it in two places:

* [.NET Blog post](https://blogs.msdn.microsoft.com/dotnet/2019/01/24/net-core-tooling-update-for-visual-studio-2019-preview-2/) - where we'll plan to post again at RTW
* [Release notes](https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-preview#netcore-tools-p2)

Our aim here is to collect feedback wherever possible - GitHub, Blog comments, Twitter, DevCom - and make a call based on that feedback.

**Comment by davkean** [comment] 2019-01-25 05:45
@333fred You had similar feedback, can you +1 above?

**Comment by 333fred** [comment] 2019-01-25 15:44
Done. I still get frustrated with this several times per week.

**Comment by srivatsn** [comment] 2019-01-29 06:33
I find that this disrupts my flow as well. It'll be good to make sure there's an option to change the behavior at least.

**Comment by davkean** [comment] 2019-01-29 10:15
@srivatsn Do you mind following up in a week and see if you feel the same way? I found it disrupted too first few times too. Sounds like it still disrupts Fred's usage though.

**Comment by sharwell** [comment] 2019-01-29 12:18
I'm still hitting this.

**Comment by jjmew** [comment] 2019-01-30 01:02
This issue will track the work for adding a setting to change the behavior of double clicking.

**Comment by jjmew** [comment] 2019-01-30 01:02
Updated the title to reflect what we are tracking

**Comment by srivatsn** [comment] 2019-02-05 17:57
> @srivatsn Do you mind following up in a week and see if you feel the same way?

A week later - still end up double-clicking expecting to open the node.

**Comment by sharwell** [comment] 2019-02-05 17:58
Same here

**Comment by davkean** [comment] 2019-02-05 21:53
We're looking at exposing an option that will revert to the previous behavior.

**Comment by ergometh** [comment] 2019-02-06 08:53
Same for me, annoying change.

**Comment by davidwengier** [comment] 2019-02-06 21:28
A quick status update: Preliminary work has been completed to add an option to disable the double-click behaviour, we are waiting on the UX review process to confirm exactly where the option should go, and as a consequence how it should work.

**Comment by davidwengier** [comment] 2019-02-07 01:12
Internal PR for the functionality: https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/161623
Internal PR for the option UI (pending review): https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/163306

**Comment by Tamer-Gamal** [comment] 2019-02-28 15:23
Is there any update on this request ?
we need the option to disable this feature.

**Comment by eismue** [comment] 2019-03-19 07:56
Please remove this 'feature', it is absolutely annoying as it interrupts the workflow.
For at least 15 years we have been working in such a way that a double click on the project expands it in the Solution Explorer. Now the project file opens for editing.
Question: what is probably done more often: extending a project to navigate to the particular files, or manually editing the project file? I clearly think the first one.
Please make this at least configurable. The behavior is absolutely horrible at the moment...

**Comment by kovachev** [comment] 2019-03-23 21:09
How often do you edit project files manually? Most probably do it once, yes once, in 6 months. But how often do you expand/collapse projects? Hundreds of times a day?

Here's another "great" idea for the next update - why don't you make double clicking on a folder to open it in explorer, some weird mind might find that behavior useful.

**Comment by davkean** [comment] 2019-03-23 22:32
This option is on the cards for 16.1.

This is a reminder to be respectful on this forum, we are all humans here. Please keep the comments constructive.

**Comment by eismue** [comment] 2019-03-24 07:10
I'm glad to hear that. Thank you for this information.

**Comment by stefankip** [comment] 2019-04-01 06:54
Like I mentioned in https://github.com/dotnet/project-system/issues/1224#issuecomment-477967677, I run into this 'issue' several times per hour.

**Comment by f135ta** [comment] 2019-04-01 21:12
Thanks for adding this feature... Its hideous and thoroughly annoying ;-)

**Comment by davidwengier** [comment] 2019-04-03 04:32
Internal PRs have been merged, option will appear in 16.1.

**Closed by davidwengier** 2019-04-03 04:32 UTC
Labels: Area-External-CPS, Feature Request, Feature-Project-File-Editing, Triaged

**Comment by effyteva** [comment] 2019-04-03 06:17
Any estimated release date for 16.1 already? :)
This is indeed a very annoying "feature"

**Comment by cartermp** [comment] 2019-04-03 06:25
@effyteva There is no estimated release date for 16.1 at this time.

**Comment by LeroyK** [comment] 2019-04-03 10:15
Any way to disable this workflow killer without having to wait for 16.1? Perhaps using an extension?

**Comment by stijnherreman** [comment] 2019-04-03 14:19
I honestly don't understand why you wait until 16.1 to make this new behaviour optional, it should have been optional from the get-go. What were you hoping to achieve by asking people to try and get used to it, what do you have to gain from it?

The change doesn't even make sense to me. Expanding/collapsing a project node is an action I frequently perform, especially combined with the 'Collapse All' button, while editing a project file is rarely done.

@davkean with all due respect, it's my first day using VS 2019 and I already wanted to smash my mouse on the desk because of this.

**Comment by stefankip** [comment] 2019-04-03 14:26
I’m staying with 2017 because of this...

**Comment by bording** [comment] 2019-04-03 14:27
To be a contrary opinion here, I love the new feature! I never double click on Solution Explorer items to expand/collapse them. I always use the arrows next to the item. Being able to easily get to the project file is wonderful.

**Comment by effyteva** [comment] 2019-04-03 14:35
> I’m staying with 2017 because of this...

After a day of using VS2019, I have to say, it works a bit slower on my ~80 projects solution, and this "feature" is really making me consider switching back. I'm always switching ASAP to newer versions, but Microsoft did an amazing job :)

**Comment by itanex** [comment] 2019-04-04 22:12
What is this setting if it has already been implemented? Tried searching the options for it, but nothing was found. Please advise.

**Comment by aventus13** [comment] 2019-04-05 14:26
I'm against this change as well and would like to know what was the rationale for making this change non-optional. As it's been mentioned above, developers much more often **open** projects rather than **edit** them. It is slowing me down as well because it is harder to hover the cursor over a collapse/expand caret button instead of simply double clicking the project.

**Comment by TravisTroyer** [comment] 2019-04-05 14:31
Unless I'm forgetting some different behavior in an earlier version, I've been double-clicking these things for over 15 years now.  That's a hard behavior to unlearn.

**Comment by sagoo33** [comment] 2019-04-10 04:20
This change has been very frustrating for me. I'm happy for the ability to Edit the project be on by default, but please make it a setting to revert to "legacy behaviour" to allow us to stay in dinosaur land.

**Comment by domints** [comment] 2019-04-11 14:50
> This change has been very frustrating for me. I'm happy for the ability to Edit the project be on by default, but please make it a setting to revert to "legacy behaviour" to allow us to stay in dinosaur land.

I wouldn't say legacy behaviour and dinosaur land. As far as I remember editing csproj required unloading the project and it was annoying. Being able to edit / view csproj contents without unloading it is great, but I'd rather keep that feature under the context menu (right click) than change how double-click works, as it worked that way for ages.

**Comment by Tamer-Gamal** [comment] 2019-04-14 07:48
I downloaded the 16.1 version and i can't locate the option that turn this option off.

**Comment by poke** [comment] 2019-04-14 10:07
@Tamer-Gamal You probably downloaded 16.0.1 which does not have this functionality. 16.1 is not available yet.

**Comment by Tamer-Gamal** [comment] 2019-04-14 20:34
> 
> 
> @Tamer-Gamal You probably downloaded 16.0.1 which does not have this functionality. 16.1 is not available yet.

![Visual Studio Update](https://user-images.githubusercontent.com/4309859/56098850-b8229b00-5f0d-11e9-92d8-c3d6a6f2ce4d.jpg)

it says 16.1.0,check the attached image

**Comment by jjmew** [comment] 2019-04-14 20:37
> > @Tamer-Gamal You probably downloaded 16.0.1 which does not have this functionality. 16.1 is not available yet.
> 
> ![Visual Studio Update](https://user-images.githubusercontent.com/4309859/56098850-b8229b00-5f0d-11e9-92d8-c3d6a6f2ce4d.jpg)
> 
> it says 16.1.0,check the attached image
> 
> [Visual Studio 2019 Preview Release Notes](https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-preview#16.1_Preview1)

It won't be available until a future preview of 16.1

**Comment by myesn** [comment] 2019-04-18 11:25
Visual Studio 2019 version 16.1 Preview 1 has been released, has the option to double-click the custom behavior of the project file?

**Comment by LeroyK** [comment] 2019-04-24 12:27
Visual Studio 2019 16.1 Preview 2 finally allows you to change this behavior:

Tools => Options => Projects and Solutions => General => Uncheck "Open SDK-style project files with double-click or the Enter key"

**Comment by maliming** [comment] 2019-04-24 12:36
Guess what? I have adapted to this. 😅

**Comment by codematrix** [comment] 2019-05-01 17:41
I guess this will be coming soon. It is an odd behavior. I think a **Ctrl + mouse double click** would be great for opening up the project source file and the old default behavor leave as is - i.e. mouse double click.

**Comment by drewnoakes** [comment] 2019-05-03 03:21
The option to control this is:

![image](https://user-images.githubusercontent.com/350947/57118374-44560e80-6da6-11e9-8937-0f10385f0618.png)

To disable the new behaviour, uncheck this box.

**Comment by jrt324** [comment] 2019-05-09 09:49
The "Open SDK-style project files with double-click or the Enter key" option **disappeared** in 16.0.3

**Comment by stefankip** [comment] 2019-05-09 09:54
@jrt324 ..... it never appeared in the 16.0 releases so how could it disappear?!

**Comment by BalintFarkas** [comment] 2019-05-22 08:29
Just installed the release version of VS2019 16.1, can confirm that the option is there and works as advertised. Whew.

**Comment by aaubry** [comment] 2019-05-22 10:09
I've also tested this setting and it indeed expands the project, but still opens the project in the preview pane, which feels weird. I really want to **only** expand the project. How can I disable opening the project in the preview pane ?

**Comment by stijnherreman** [comment] 2019-05-22 10:36
I don't really mind that the project opens in the preview tab, the most important was to re-enable the previous expand/collapse behaviour. Note that Alt+click to avoid the preview works here too, just Alt+double click on the project.

**Comment by aaubry** [comment] 2019-05-22 10:50
Well, I do. Basically one command (double-clicking on the project) results in two actions, expand the project AND open the project for editing. It's not that I can't live with it, but it feels even weirder than only opening the project.
It is rare that I need to edit a project manually. Maybe once in a while to set LangVersion. Other than that I don't see many use cases for it. Why would I want to be constantly opening it ?

**Comment by stefankip** [comment] 2019-05-22 11:02
Just disable the preview window. It's no good at all anyway :-)

**Comment by mchudinov** [comment] 2019-07-22 21:45
Make this "feature" disabled by default please.

**Comment by StingyJack** [comment] 2019-08-16 04:15
@drewnoakes  -  why did inconsistency get chosen as the default?

**Comment by davkean** [comment] 2019-08-16 04:58
Its inconsistent with some things but consistent with all other files and the direction we want to head; project files are user-editable similar to source code. The option is there for folks that want to switch on the old behavior, it roams with your profile so you will never ever need to set it again.

**Comment by StingyJack** [comment] 2019-08-16 13:46
I dont like that direction. Not because its different, but because I dont want to have to think about editing project files in the first place. Proj files been working just fine for the most part, and I've only had to edit them to add odd build configurations or to remove elements added due to bugs in VS or package uninstallation.  There is nothing in these project files anymore really, so nothing to see on that double click except annoyance at this inconsistent behavior. 

Why is it so important to push staring at project files into the way of the general user?  This just adds needless clicks to close the proj file and click the ever shrinking expand icon.

(What I really need is the option to not use this inferred content project file format, its a PITA for several reasons)

**Comment by StingyJack** [comment] 2019-08-17 01:33
Also does this mean that eventually when I double click on other expandable items like folders that i'm going to get a filesystem properties dialog for the folder?

> Part of our rationale for shipping this feature, and the rest of project file editing improvements, in a preview release was to gauge the response from our users before the final release. Please keep us updated if your opinion changes at all as you use the preview more and potentially get used to the new experience.

VS 2017 cured me from ever taking a preview release again (and almost from using VS entirely), and I know I'm not alone in that regard. Take care to measure that preview release feedback for what it is and that is is not necessarily representative of the general audience.

**Comment by cartermp** [comment] 2019-08-17 01:41
@StingyJack Note that this:

> not necessarily representative of the general audience

Is 100% true 🙂. In fact, we've seen a _lot_ of positive reception over making these files easier to edit, especially now that with SDK-style projects, it's possible to edit these files without having to sift through potentially thousands of seemingly unrelated MSBuild XML.

So, which do we trust more: a GitHub issue, or a channel for the product designed to gauge feedback? Hence the option in the settings.

**Comment by cjbush** [comment] 2019-08-17 02:04
I'm not a big fan of this feature either, and I thank the team for adding the checkbox to turn it off, but I honestly don't understand the harsh vitriol some people are expressing over it. It's a checkbox you uncheck once and then your settings are synced to your account forever. I unchecked it weeks ago and moved on with my life.

**Comment by aaubry** [comment] 2019-08-17 10:08
@cjbush I think the reason for the criticism is that the checkbox to disable it was inexistent at first. When people are used to a behavior and it suddenly changes without a way to revert, that's when people get annoyed. Of course they can't add settings to control everything, so it is to be expected that sometimes people get annoyed.

**Comment by StingyJack** [comment] 2019-08-17 12:13
@cjbush - the _criticism_ from me is about the direction(s). Something that was a "just works" or "no think" a few years ago is soon to be no longer available, replaced by something that requires more effort (ex: running a netcore console app vs netfx, anything dealing with devops build tasks, figuring out where the compiled output is going to end up) on my part to get the same result,  something that falls wildly short feature-wise to it's predecessor or has needless restrictions (nuget package reference style) that I've now got to spend time to cover gaps , or that is just not getting carried forward due to a Shiny Things affectation (unshelve to a different branch). 

The last 3-4 years of output from a software tools vendor I've used for 30 years has been riddled with thousands of these little (and sometimes not little) impediments. 

I can't count how many times this specific interruption-by-design broke my flow. I saw it happening countless times to co-workers too. 

We don't need designs that create interruptions, unless that interruption is important. Showing me a proj file, when I already know to right click if I want to edit it is *not* important.

**Comment by drewnoakes** [comment] 2019-08-19 01:38
@StingyJack I interpret part of what you're saying (the more general part, less around this particular issue) as being a frustration with the rapid changes to platform and tooling that have been going on over the last years. I can see why you'd feel that way. .NET Framework was very stable for a long while and during that time the tooling matured, however the platform started to show its signs of age. 

Since .NET Core we've had an incredible amount of progress across the entire stack, which is great for the long term health of .NET (and our careers as .NET developers), however the tooling is playing catch up to get to that previous level of maturity. These changes have forced us developers to learn new concepts and unlearn old behaviours. Patterns we've known and used for a long time (e.g. output paths) have had to change as new concepts (e.g. multi-targeting) have been introduced. This isn't change for change's sake -- it's unavoidable if we want to progress and grow the platform.

As for your particular preference on this issue, I don't think there's much more I can add here.

> I can't count how many times this specific interruption-by-design broke my flow.

Have you not unchecked the option?

**Comment by StingyJack** [comment] 2019-08-19 13:27
> Have you not unchecked the option?

@drewnoakes  - The option wasn't there until recently, and I came across this quite by happy accident. Its now set to just expand or collapse the projects for me (at least until the next bug that loses my settings). 

_Your_ problem though (not mine now), is that you guys made the new and interrupting behavior the default, so there are probably quite a few - lets just say most - VS .net developers at least scratching their head and thinking "why does this do this now" at varying degrees of exasperation while trying to partially unlearn a conditioned behavior. I would think telemetry would be available to support or dispute this, or at least I hope so.
 
Its not like its an easy setting to find. 
![image](https://user-images.githubusercontent.com/15381181/63239902-61aacd80-c21b-11e9-8266-7b25fb7771db.png)

> as being a frustration with the rapid changes to platform and tooling ...

No no, not upset about speed of changes. MSFT has been making things that do not materially improve on prior creations or that improvement holds little value or that serve some FOTM. And then coercing me to use that in one way or another, often times by declaring "no longer supported".  This is usually the point of frustration. This "feature" is a smaller example; assumption riddled and hidden default heavy proj files and nuget package reference are larger examples. 

Some of this frustration could be abated if I understood that it was a transition step to something better but I don't see anyone explaining what that "better" is. I've re-read both your and @davkean's responses again and neither have given a reason for the proj file opening change, so I'm asking again: Why was this important enough to interrupt development workflow?

> new concepts (e.g. multi-targeting) 

This was always do-able in .netfx and fairly easy to do by creating a build configuration for it.

**Comment by davkean** [comment] 2019-08-19 14:14
Going to lock this thread, I don't think its productive to discuss the same thing over and over again. The original request has been resolved, the setting is permanent, once set you should never have to think about it again.
