### ISSUE TITLE
Crash when editing .resx file of Tizen project

### ISSUE THREAD

**Issue by WonyoungChoi** [dotnet/project-system#6264] opened 2020-06-05 00:32 UTC
**Visual Studio Version**: 16.6.0

**Summary**: 
After the change https://github.com/dotnet/project-system/commit/f8795739f428819f559e9613b443fbdc7180477c, Visual Studio crashes when users edit a value of resource file(.resx) of Tizen project using Resource Editor. It seems that the added code of MultiTargetService instead of the deleted code in https://github.com/dotnet/project-system/commit/f8795739f428819f559e9613b443fbdc7180477c is processing only for .NETStandard and .NETCoreApp TFMs. 
The problem is that the mscorlib.dll of Tizen TFM contains only TypeForwardings because the Tizen TFM includes the same reference assemblies of .NETCoreApp.

**Steps to Reproduce**:
1. Open a Tizen .NET project including a .resx file. [Sample](https://github.com/Samsung/Tizen-CSharp-Samples/tree/aa61cb4b2a7337cc16990e26eda488f24c466dfb/Wearable/UsingResxLocalization/UsingResxLocalization)

2. Open .resx file with Resource Editor

3. Edit a value of any string type row

**Expected Behavior**: Set a new value without errors

**Actual Behavior**: Crash
```
System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. 
File name: 'System.Runtime, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMarkHandle stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName, ObjectHandleOnStack type)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark&amp;amp; stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName)
   at System.RuntimeType.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark&amp;amp; stackMark)
   at System.Type.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase)
   at Microsoft.VisualStudio.Editors.ResourceEditor.Resource.GetValueTypeHelper(String ValueTypeName, Boolean ThrowOnError)
   at Microsoft.VisualStudio.Editors.ResourceEditor.Resource.GetValueType()
   at Microsoft.VisualStudio.Editors.ResourceEditor.Resource.SetValueWithoutUndo(Object NewResourceValue)
   at Microsoft.VisualStudio.Editors.ResourceEditor.Resource.SetPropertyValueWithoutUndo(String PropertyName, Object Value)
   at Microsoft.VisualStudio.Editors.ResourceEditor.ResourcePropertyDescriptor.SetValue(Object Component, Object Value)
   at Microsoft.VisualStudio.Editors.ResourceEditor.Resource.SetValue(Object NewResourceValue)
   at Microsoft.VisualStudio.Editors.ResourceEditor.ResourceStringTable.OnCellValuePushed(DataGridViewCellValueEventArgs e)
   at System.Windows.Forms.DataGridView.OnCellValuePushed(Int32 columnIndex, Int32 rowIndex, Object value)
   at System.Windows.Forms.DataGridViewCell.SetValue(Int32 rowIndex, Object value)
   at System.Windows.Forms.DataGridView.PushFormattedValue(DataGridViewCell&amp;amp; dataGridViewCurrentCell, Object formattedValue, Exception&amp;amp; exception)
   at System.Windows.Forms.DataGridView.CommitEdit(DataGridViewCell&amp;amp; dataGridViewCurrentCell, DataGridViewDataErrorContexts context, DataGridViewValidateCellInternal validateCell, Boolean fireCellLeave, Boolean fireCellEnter, Boolean fireRowLeave, Boolean fireRowEnter, Boolean fireLeave)
   at System.Windows.Forms.DataGridView.EndEdit(DataGridViewDataErrorContexts context, DataGridViewValidateCellInternal validateCell, Boolean fireCellLeave, Boolean fireCellEnter, Boolean fireRowLeave, Boolean fireRowEnter, Boolean fireLeave, Boolean keepFocus, Boolean resetCurrentCell, Boolean resetAnchorCell)
   at System.Windows.Forms.DataGridView.SetCurrentCellAddressCore(Int32 columnIndex, Int32 rowIndex, Boolean setAnchorCellAddress, Boolean validateCurrentCell, Boolean throughMouseClick)
   at System.Windows.Forms.DataGridView.set_CurrentCell(DataGridViewCell value)
   at Microsoft.VisualStudio.Editors.DesignerFramework.DesignerDataGridView.OnMouseDown(MouseEventArgs e)
   at Microsoft.VisualStudio.Editors.ResourceEditor.ResourceStringTable.OnMouseDown(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseDown(Message&amp;amp; m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message&amp;amp; m)
   at System.Windows.Forms.DataGridView.WndProc(Message&amp;amp; m)
   at Microsoft.VisualStudio.Editors.DesignerFramework.DesignerDataGridView.WndProc(Message&amp;amp; m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message&amp;amp; m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message&amp;amp; m)
```

**User Impact**:
Tizen .NET application developers can't use the built-in resource editor for editing the .resx files.

**Comment by davidwengier** [comment] 2020-06-09 02:34
Thanks for the report @WonyoungChoi, I believe I know what the issue is and the fix should be straight forward, but I've been unable to reproduce the issue locally, and I'm wondering if you can help?

I have installed the Visual Studio Tools for Tizen extension, and the Tizen SDK, however when I edit a resource file in Visual Studio the resource editor fails at an earlier spot because it can't find mscorlib. Is there some other component I need to have installed?

**Comment by WonyoungChoi** [comment] 2020-06-09 03:04
@davidwengier Thank you for your help. In fact, this is not a problem with other extensions such like VS tools for Tizen and Tizen SDK. It is about the Tizen TFM and the reference assemblies in Tizen.NET nuget package. 
You can probably simply reproduce it using the following .csproj. 
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworkIdentifier>Tizen</TargetFrameworkIdentifier>
    <TargetFramework>tizen40</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Tizen.NET" Version="6.0.0.14995" />
  </ItemGroup>

</Project>
```
After opening this project, create and open a .resx file with the VS built-in Resource Editor by double-click.  And VS will crash when edit any string value of the resource file.

The reason of this crash is that below TypeNameConverter method return "System.Runtime" assembly when "System.String" type is passed. 
 https://github.com/dotnet/project-system/blob/8dda0a9de722c3ab154233da6b2f08d33141a78f/src/Microsoft.VisualStudio.Editors/ResourceEditor/ResourceFile.vb#L845

**Comment by davidwengier** [comment] 2020-06-09 03:23
Thank you, that let me reproduce the issue and verify the fix.

**Comment by davidwengier** [comment] 2020-06-09 03:24
Internal PR https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/252890 has been merged

**Closed by davidwengier** 2020-06-09 03:24 UTC
Labels: Bug, Regression, Triage-Approved
