### ISSUE TITLE
Cannot switch from "Icon and Manifest" to "Resource File"

### ISSUE THREAD

**Issue by nguerrera** [dotnet/project-system#5197] opened 2019-07-29 22:33 UTC
**Visual Studio Version**:

VisualStudio.16.IntPreview/16.3.0-pre.2.0+29128.8.master

**Summary**:

It's difficult to change from "Icon and Manifest" to "Resource File" in .NET Core project because it switches back to "Icon and Manifest" before I can click browse after selecting "Resource File"

Repro is not 100%, and eventually it will settle down and stay on  Resource File. But usually I can hit this following the steps below, as can @wli3

**Steps to Reproduce**:

1. File -> New Project -> .NET Core Console App

2. Solution Explorer -> Right click project -> properties

3. Application tab, under resources -> select "Resource file"

![cantpickresourcefile](https://user-images.githubusercontent.com/75470/62087316-36355400-b216-11e9-97e4-a25e09285d99.gif)

**Expected Behavior**:
It stays on "Resource file" so I can browse or type in the path to resource file.

**Actual Behavior**:
It reverts back to Icon and Manifest

**User Impact**:
Frustrating UI.

**Comment by drewnoakes** [comment] 2019-07-29 22:59
I can repro this in 16.2.0 (GA).

1. New .NET Core project
2. Open properties
3. Click _Resource file_
  - The _Icon and manifest_ item is reselected
  - The `.csproj` file now contains:
    ```xml
    <ApplicationIcon />
    <Win32Resource />
    ```
4. Clicking _Resource file_ a second time (for me at least) causes the selection to stick

**Comment by drewnoakes** [comment] 2019-07-29 23:01
@etbyrd can you take a look at this?

**Comment by etbyrd** [comment] 2019-07-29 23:28
I see why this is happening. I will try to get a PR out for this tomorrow.

**Comment by drewnoakes** [comment] 2019-07-30 06:22
@etbyrd I've added it to this sprint as it's a regression.

**Comment by davkean** [comment] 2019-07-30 07:38
@etbyrd @drewnoakes Do we have an understanding of what regressed here?

**Comment by etbyrd** [comment] 2019-07-30 18:48
Looking at just the blame, I am not sure if this is even a regression.

**Comment by davidwengier** [comment] 2019-11-21 02:01
Closing this as a duplicate of #4519

I've confirmed that if we don't set property values to their current values this doesn't repro. The real fix for this will be done in CPS (see https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1025549)

**Closed by davidwengier** 2019-11-21 02:01 UTC
Labels: Bug, Feature-AppDesigner

**Comment by davidwengier** [comment] 2019-11-27 20:25
In case anyone is watching this issue, the linked duplicate has been fixed.
