### ISSUE TITLE
UI updating causing FastUpToDate build loop?

### ISSUE THREAD

**Issue by TheOrangeDay** [dotnet/project-system#7030] opened 2021-03-16 20:51 UTC
**Visual Studio Version**: 16.4.6

**Summary**:
- Using SDK style projects.

I'm running into the "set of project items was changed more recently" issue where the project gets into a state that's newer than the build output and keeps building over and over when building incrementally. I see that this particular message has been reported in a few other issues.

I'm working on a project that has an msbuild integrated target implementation that generates .cs code into a subdirectory of the project directory based on an input schema that's included as an item into the root of the project. The target implementation also has support to clean the generated cs files from the subdirectory of the project as well. The generation target executes "BeforeBuild" and generates the cs code during compilation.

When I clean the project, the generated code gets deleted and the project is updated in the VS UI to show the generated code doesn't exist anymore. When I build, the generated code cs files are created during the msbuild processing and the UI updates again to show they are back into the project.

I noticed that right at the end of the build is when the UI updates to show the generated code in its folder in the project again. I have a suspicion that the timing of this is what is causing the FastUpToDate tracked modified time to be updated past the timing of generated binaries. By the time the UI updates, we'd have generated the code and compiled the dlls.

Does this sound like something that's possible?

**Comment by TheOrangeDay** [comment] 2021-03-16 22:07
I have set up a solution and project to demonstrate this. What is the best way to share it?
Also I updated VS and reproed with 16.9.1

**Comment by drewnoakes** [comment] 2021-03-18 00:18
The problem is this target:

```xml
<Target
  Name="TEST_ResolveCompileInputs"
  AfterTargets="TEST_GenerateCodeProcess">
  <ItemGroup>
    <Compile Remove="**\*$(TEST_GenSuffix).cs" />
    <Compile Include="**\*$(TEST_GenSuffix).cs" />
  </ItemGroup>
</Target>
```

During each build it is removing generated code, then re-adding it. This causes the projec to update, which causes the situation you're observing. If I remove this, it builds as expected.

What I think you really want to do is mark your `.schema` files as inputs to the up to date check. Then, if they change, a build will occur and your targets will regenerate them.

You can do this with `UpToDateCheckInput` as described in https://github.com/dotnet/project-system/blob/main/docs/up-to-date-check.md#customization.

**Comment by jjmew** [comment] 2021-03-23 17:27
Closing it given @drewnoakes guidance

**Closed by jjmew** 2021-03-23 17:27 UTC
