### ISSUE TITLE
Binding error in property pages, trying to read 'TextWrapping' editor metadata

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#8955] opened 2023-04-03 02:08 UTC
## Visual Studio Version

Version 17.6.0 Preview 3.0 [33529.503.main]

## Steps to Reproduce

1. Run VS in a debugger
1. Create a .NET 7.0 Console Application
1. Open the property pages
1. Look at the "Debug" output

## Actual Behavior

> Cannot get 'Item[]' value (type 'String') from 'EditorMetadata' (type 'ImmutableDictionary`2'). BindingExpression:Path=Parent.EditorMetadata[TextWrapping]; DataItem='PropertyValueViewModel' (HashCode=48159629); target element is 'TextBox' (Name=''); target property is 'TextWrapping' (type 'TextWrapping') TargetInvocationException:'System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Collections.Generic.KeyNotFoundException: The given key 'TextWrapping' was not present in the dictionary.

```
System.Windows.Data Warning: 17 : Cannot get 'Item[]' value (type 'String') from 'EditorMetadata' (type 'ImmutableDictionary`2'). BindingExpression:Path=Parent.EditorMetadata[TextWrapping]; DataItem='PropertyValueViewModel' (HashCode=48159629); target element is 'TextBox' (Name=''); target property is 'TextWrapping' (type 'TextWrapping') TargetInvocationException:'System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Collections.Generic.KeyNotFoundException: The given key 'TextWrapping' was not present in the dictionary.
   at System.Collections.Immutable.ImmutableDictionary`2.get_Item(TKey key)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at MS.Internal.Data.PropertyPathWorker.GetValue(Object item, Int32 level)
   at MS.Internal.Data.PropertyPathWorker.RawValue(Int32 k)'
```

**Comment by adamint** [comment] 2023-06-21 20:59
Dupe of #9082

**Closed by adamint** 2023-06-21 20:59 UTC
Labels: Bug, Triage-Approved, Triage-Investigate, Feature-Project-Properties-Designer
