### ISSUE TITLE
Visual Studio keeps overwriting my manual csproj changes

### ISSUE THREAD

**Issue by wjk** [dotnet/project-system#2052] opened 2017-04-23 01:18 UTC
The title really says it all. Twice now during one coding session, Visual Studio overwrote my manual changes to the .NET Core csproj file with what it had in memory. This is a problem, seeing as easy manual editing of project files is a marquee feature of both the new project system and .NET Core as a whole. Unfortunately, I'm not sure how to create a repro for this. I do think that this is a regression in VS, though, as I just noticed it now, having installed several VS updates since I last worked with a .NET Core project.

I'm using Visual Studio 2017 Community, version 15.1.26403.7.

**Comment by wjk** [comment] 2017-04-23 01:20
I gets weirder. VS right-click > Edit on a loaded project file gives me a reflection of what VS has in memory (as does the solution explorer and the build process). If I unload the project and _then_ edit it, my manual changes show up, having been there all along. Reloading the project does convince VS to accept my changes, and the build updates accordingly.

**Comment by srivatsn** [comment] 2017-05-03 05:39
If you have run into a repro for this it would be great to look into this.

**Comment by wjk** [comment] 2017-05-03 20:11
@srivatsn I'm afraid it's been a while since I have worked on any Core projects. In addition, while I am pretty sure I was working on [SunburstApps/Sunburst.Win32UI](https://github.com/SunburstApps/Sunburst.Win32UI) at the time, I don't remember what I was trying to change when this problem cropped up. If it reoccurs, I'll be sure to let you know.

**Comment by wjk** [comment] 2017-08-16 20:58
@srivatsn Sorry for reopening such an old issue, but this is still happening with the latest VS15.3 bits. Here's what I was doing when I ran into this:

1. Clone [SunburstApps/Sunburst.Win32UI](https://github.com/SunburstApps/Sunburst.Win32UI)
2. Checkout commit `9b254a09b24cc9d4691d5ca593adcac19cc79be`
3. Load the solution in VS, and right-click > Edit the `Win32UI.Build.Tasks` project.
4. Try to change lines 3 and 9 to use `netcoreapp2.0` instead of `netcoreapp1.1`.
5. Save and close the file, then right-click > Edit the project again.

On my PC, the editor displays what VS has in memory (i.e. the changes made in step 4 are "lost"). Notepad displays the changes as they exist on disk, having correctly been written out. A project unload/reload is required for VS to reconcile its notion of what is versus what really is.

**Comment by davkean** [comment] 2017-08-17 05:28
Thanks,@wjk, for Microsofties I've opened https://devdiv.visualstudio.com/DevDiv/Managed%20Project%20System/_workItems?id=480703&fullScreen=false&_a=edit against CPS, I leave this as a tracking bug.

**Comment by thomaslevesque** [comment] 2017-09-07 15:28
I see this all the times, several times a day. I edit a project, add a PackageReference, save the file, and close the editor, and my changes are not taken into account. When I edit the project again, my changes are gone, as if I never made them. Trying again *usually* works.

**Comment by viktorveis** [comment] 2017-11-10 02:18
Related feedback item: https://developercommunity.visualstudio.com/content/problem/95948/editing-csproj-file-as-xml-in-vs2017-153-rtm-pro-w.html

**Comment by davkean** [comment] 2017-11-10 02:22
We're closing this as a dupe of https://developercommunity.visualstudio.com/content/problem/95948/editing-csproj-file-as-xml-in-vs2017-153-rtm-pro-w.html.

**Closed by davkean** 2017-11-10 02:22 UTC
Labels: Bug, Feature - Project File Editing, Tracking

**Comment by josephjaspers** [comment] 2018-01-18 21:35
Visual Studio 2017 Community (newest edition) same issue.

**Comment by Aashishkebab** [comment] 2024-05-11 04:21
I know this is old, but this is an ancient bug that is still present in Visual Studio 2022. I've reported it six times (on Visual Studio bug tracker) and they keep closing it. Several others have reported it as well.

**Comment by mikenakis** [comment] 2024-12-21 10:06
Visual studio keeps modifying csproj files even today.  (Version 17.12.3)  For example, if I reference a file from within a .csproj file, say with `<Content Include="foo" />` and then from within Solution Explorer I rename `foo` to `bar`, Visual Studio goes and modifies my .csproj file and replaces `"foo"` with `"bar"`. Of course, Visual Studio is nowhere near competent enough to always change my .csproj file correctly, so sometimes it seriously garbles it up.

**Comment by drewnoakes** [comment] 2024-12-23 20:37
@mikenakis open a new issue with repro steps and we will take a look. It's not clear what problem you're facing from the description.
