### ISSUE TITLE
GC pressure:  Excessive memory allocation inside DuplicatedDependenciesSnapshotFilter.BeforeAdd

### ISSUE THREAD

**Issue by lifengl** [dotnet/project-system#2917] opened 2017-10-23 22:25 UTC
Trace shows it is account for 6.6% of total allocation in the solution load (when to load this projectsystem.sln).  The code looks like this:

topLevelBuilder.Any(
                    x => ...  x.Caption.Equals(
                             string.Format(CultureInfo.CurrentCulture, "{0} ({1})", dependency.Caption, x.OriginalItemSpec),
                                StringComparison.OrdinalIgnoreCase))

Try to prevent creating the temporary caption string to do this comparison.  At least, it can check the caption.StartsWith(dependency.Caption) first, so it doesn't have to create a temp string inside the loop all the time.

**Comment by davkean** [comment] 2017-10-23 23:11
Dupe of https://github.com/dotnet/project-system/issues/2596

**Closed by davkean** 2017-10-23 23:11 UTC
Labels: Area-New-Project-System, Performance
