### ISSUE TITLE
Resource Designer cannot load .NET Core types

### ISSUE THREAD

**Issue by jmarolf** [dotnet/project-system#5949] opened 2020-03-05 23:25 UTC
*Repro Steps:**

1. Create a .NET Core WinForms app, then double click the Form1.cs file to show the Form designer.
2. Add a PictureBox control from toolbox to Form1.
3. Add a local image resource to it.
4. Open the Form1.resx file
 
**Actual result:** 
There is an error in Error List Windows.

![ShowError](https://user-images.githubusercontent.com/54019172/69129574-9dd71e00-0ae9-11ea-994f-d4b170789de1.png)

**Expected result:** 
In framework app, after step4, the image will show in the Form1.resx window without error.
 
**More info:** 
After step4, build and run the app successfully.

**Comment by davkean** [comment] 2020-03-06 00:10
Dupe of https://github.com/dotnet/project-system/issues/5629. This is a WinForms bug.

**Closed by davkean** 2020-03-06 00:10 UTC
