### ISSUE TITLE
Debugging via Debugger.Launch or possible via launchSettings?

### ISSUE THREAD

**Issue by robertmuehsig** [dotnet/project-system#2942] opened 2017-11-07 22:09 UTC
Hi

I have a "special" debugging question and I'm not sure if this is the correct repository or not.

I have the following scenario (as a maintainer of the [Electron.NET](https://github.com/ElectronNET/Electron.NET/) project)

We embed a ASP.NET Core app inside a Electron app.

I did the tooling around the project with a CLI extension. The steps to "embed" the ASP.NET Core app inside the Electron part are more or less [these lines](https://github.com/ElectronNET/Electron.NET/blob/master/start.cmd).
I implemented this mechanic in our CLI tooling and now we can invoke the "start" like this:

    dotnet electronize start

Now my goal is it to make debugging as easy as pressing F5, but I can't attach the debugger to the correct .exe.

Currently I was able to invoke the electronize start via this launchSetting file:

```

{
...
  "profiles": {
    ...
    "Electron.NET App": {
      "commandName": "Executable",
      "executablePath": "C:\\Program Files\\dotnet\\dotnet.exe",
      "commandLineArgs": "electronize start"
    }
  }
}
```
Now we build the ASP.NET Core app as portable app and invoke electron, just like this:

```
Start Electron Desktop Application...
Microsoft Windows [Version 10.0.15063]
(c) 2017 Microsoft Corporation. All rights reserved.

D:\Code\GitHub\ElectronNET\ElectronNET.WebApp>dotnet publish -r win-x64 --output "D:\Code\GitHub\ElectronNET\ElectronNET.WebApp\obj\Host\bin"
Microsoft (R) Build Engine version 15.4.8.50001 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  ElectronNET.WebApp -> D:\Code\GitHub\ElectronNET\ElectronNET.WebApp\bin\Debug\netcoreapp2.0\win-x64\ElectronNET.WebApp.dll
  ElectronNET.WebApp -> D:\Code\GitHub\ElectronNET\ElectronNET.WebApp\obj\Host\bin\

D:\Code\GitHub\ElectronNET\ElectronNET.WebApp>


Skip npm install, because node_modules directory exists in: D:\Code\GitHub\ElectronNET\ElectronNET.WebApp\obj\Host\node_modules
Invoke electron.cmd - in dir: D:\Code\GitHub\ElectronNET\ElectronNET.WebApp\obj\Host\node_modules\.bin
Microsoft Windows [Version 10.0.15063]
(c) 2017 Microsoft Corporation. All rights reserved.

D:\Code\GitHub\ElectronNET\ElectronNET.WebApp\obj\Host\node_modules\.bin>electron.cmd "..\..\main.js"
```

The problem is now, that the debugger is just attached to the dotnet.exe and not to my actual process, e.g. MyElectronizedWebApp.exe

Then I tried to manually call a Debugger via "Debugger.Launch()", which failes more or less:

![image](https://user-images.githubusercontent.com/756703/32520347-f303f33a-c40f-11e7-90b8-d6c07f1944ac.png)

(be aware that I have the correct VS-solution currently loaded)

When I do a Attach Process and choose the generated .exe it worked as expected:

![image](https://user-images.githubusercontent.com/756703/32520421-3ad6ce76-c410-11e7-829b-4e7c754daf3b.png)

Now my question is: 
Can I somehow automate this "attach to process" with the launchSettings.json or why does Debugger.Launch() not let me debug my code?

**Comment by Pilchie** [comment] 2017-11-08 19:19
@natidea @davkean ?

**Comment by natidea** [comment] 2017-11-29 21:38
@livarcocc or @BillHiebert , is it possible to trigger the debug on the actual executable in this case thru launchSettings.json, without going thru dotnet.exe?

**Comment by Pilchie** [comment] 2018-03-30 20:45
@Ping @livarcocc and @BillHiebert, and also throwing @greggm on here for any thoughts he might have?

**Comment by ViktorHofer** [comment] 2018-09-21 14:38
That should already be possible today, we do the same in corefx and it works: https://github.com/dotnet/buildtools/blob/0c10cac8b187e43fc8782975465a0474fcb0d3c3/src/Microsoft.DotNet.Build.Tasks/PackageFiles/launchSettings.json

**Comment by air-slip** [comment] 2019-02-07 19:53
Is there an automated way of doing this yet?

**Comment by davkean** [comment] 2020-02-10 23:36
This bug is a little old, but @robertmuehsig Can you see if this extension works for you: https://marketplace.visualstudio.com/items?itemName=vsdbgplat.MicrosoftChildProcessDebuggingPowerTool? It will automatically attach to child processes. 

I'll close this out for now, please follow up if its doesn't.

**Closed by davkean** 2020-02-10 23:36 UTC
Labels: Feature-Debugging

**Comment by danatcofo** [comment] 2020-02-18 18:07
@davkean I tried this method to start debugging from VS but the problem is that the process isn't a child process so the Child Process Debugging Power Tool does not work for this scenario.
