### ISSUE TITLE
Changes to linked CSS or JavaScript files are not reflected in original copy, only local copy.

### ISSUE THREAD

**Issue by Dean-NC** [dotnet/project-system#6226] opened 2020-05-22 22:51 UTC
**Visual Studio Version**:
2019 (16.3.3)
I'm not sure if this is a bug in Visual Studio that's been fixed after my 16.3.3 version, or if it's a bug in .Net Core project system, or if it's a limitation of the design of .Net Core web projects.

**Summary**:
For .Net Core web projects, I can add a linked CSS or js file (add existing item, then click the "add as link" button), and I see them in Solution Explorer with the small link icon. After adding the custom build _Target_ to the .csproj file (see below in steps to reproduce), then when building the project, the linked files get copied from the original directory to the project (for example, my linked .js file gets copied to wwwroot\js folder).  But, after building and the files are copied, the link icon is gone, and any change saved to the linked file inside the project is not reflected in the original copy of the file, but instead is made only to the file inside the project.
This works fine in standard ASP.Net framework projects...changes are reflected to the original file, and the link icon is still there after building.

I have noticed that in the .Net Core project, if you do not put the custom build _Target_ in the .csproj file, then any change to the linked file WILL update the original instead of the copy within the project, but of course then you don't have the copying of the file to the project's directory, which I need.

**Steps to Reproduce**:
1. In a new .Net Core web project (empty is fine), add the wwwroot folder if it doesn't exist.

2.  Add the following to the bottom of the .csproj file:
```
  <Target Name="CopyLinkedContentFiles" BeforeTargets="Build">
    <Copy SourceFiles="%(Content.Identity)" DestinationFiles="%(Content.Link)" SkipUnchangedFiles="true" OverwriteReadOnlyFiles="true" Condition="'%(Content.Link)' != ''" />
    <Copy SourceFiles="%(None.Identity)" DestinationFiles="%(None.Link)" SkipUnchangedFiles="true" OverwriteReadOnlyFiles="true" Condition="'%(None.Link)' != ''" />
  </Target>
```

3. Right-click the wwwroot folder and choose "Add existing item", then point to a .js file that's outside the project directory...like "C:\temp\test.js", and choose the "Add as link" from the dialog's "Add" button dropdown menu.

4. Build the project, and verify a copy of the .js file is now on disk at the wwwroot folder.

5. Open that .js file within the project and make a change and save it. 

**Expected Behavior**:
This is supposed to make the change to the original file you linked to, not the copy within the project.

**Actual Behavior**:
It makes the change to the copy within the project, not the original.

![Untitled](https://user-images.githubusercontent.com/12361341/82714462-ae18b300-9c5c-11ea-8bc5-ade7446d8726.png)

**Comment by jjmew** [comment] 2020-06-04 23:24
@Dean-NC Could you describe the reason of why you are linking and then copying the file? That will help us understand your scenario.

**Comment by Dean-NC** [comment] 2020-06-04 23:42
@jjmew It's simple use-case. I want to have a folder of common JavaScript files (and maybe CSS), that is outside of the project folder, that is re-used for numerous applications. If I make a change to one of these files **within** a project, I want the change to actually be made to the real location outside the project, and then when building the project, the changed file is copied back to the project's folder.
These files don't change often, but when they do, if I don't have this feature working, then an important change would only be in that project's version of the file, and not the original copy.
**I've used this method** for standard ASP.Net projects **for 10 years**. I want to keep it if at all possible.

**Comment by davidwengier** [comment] 2020-06-05 02:14
@Dean-NC I'm afraid this is by design behaviour, caused by the fact that the new project system is automatically including files to save users from specifying each one manually in the project file. In your case, this means that once your items are copied the project system sees the files in the wwwroot folder, and they essentially override the linked files that were there before.

You have a couple of options that should get you back the legacy behaviour:

* Go back to legacy include behaviour - By specifying `<EnableDefaultItems>false</EnableDefaultItems>` you will opt out of the automatic inclusion of files and return to the state where each file needs to be individually included in the project. You could also use `<EnableDefaultNoneItems>false</EnableDefaultNoneItems>` and/or `<EnableDefaultContentItems>false</EnableDefaultContentItems>` to not be as broad, so compiled files are still automatically included but other files aren't.
* Manually remove the copied files - After adding the linked files your project file would have something like this in it:
```
  <ItemGroup>
    <Content Include="..\Common\file.js" Link="wwwroot\file.js" />
  </ItemGroup>
```
If you add the following to the project it will stop the project system seeing that specific copied file and revert the `file.js` item in solution explorer to see the linked file instead:
```
  <ItemGroup>
    <Content Remove="wwwroot\file.js" />
  </ItemGroup>
```

**Comment by Dean-NC** [comment] 2020-06-05 15:08
@davidwengier Thanks for the detailed response. So this is a case where new is sometimes not better.  I didn't know about any of the options you mentioned, but I knew I didn't want the EnableDefaultItems or EnableDefaultContentItems, since the ContentItems would mean manually dealing with Razor Pages and/or views, since they're .cshtml and considered "Build action: Content".

I was hoping the _EnableDefaultNoneItems_ would work, since a linked .js file is considered "None".  I don't know if it ever worked in Visual Studio, but in 16.6 it's broken. In the attached .zip tiny/simple demo project, if you add a linked .js file to the wwwroot/js folder, it shows as a linked file, and build action is None. After you build though, the custom _Target_ in the .csproj copies the file, and then Solution Explorer shows it's no longer linked, AND build action is "Content"! Viewing the .csproj file still shows "None" for the file.

Using the extra _ItemGroup_ and _Remove_ (your option #2) does work, which is good, but if you later remove the file from Solution Explorer, it leaves the extra ItemGroup/Remove in the project file!

**It would be great if the team could fix the bug with EnableDefaultNoneItems, and when the custom Target copies the file during build, that Visual Studio leaves the file as "None".**
[zzTempWeb2a.zip](https://github.com/dotnet/project-system/files/4736837/zzTempWeb2a.zip)

**Comment by davidwengier** [comment] 2020-06-07 23:50
Thanks for the sample project, unfortunately it looks like this is the base .NET SDK and ASP.NET SDK both having opinions on what the *.js files should be, so I doubt its something that can be fixed. After the item isn't in the None item type, by virtue of turning off the `EnableDefaultNoneItems` the ASP.NET Core SDK kicks in and includes anything under wwwroot as Content. 

One other thing to do would be turning off `EnableDefaultNoneItems` and `EnableDefaultContentItems`, but then including razor pages and views in the project file, instead of relying on the SDK. You should be able to just copy this patter here, and remove the condition: https://github.com/dotnet/aspnetcore/blob/66dd4919dafcb21c57a923a661cdbb0ff351713d/src/Razor/Microsoft.NET.Sdk.Razor/src/build/netstandard2.0/Sdk.Razor.CurrentVersion.props#L76-L81

**Comment by Dean-NC** [comment] 2020-06-08 13:48
@davidwengier Thanks for taking time to help me with this!  Please see updated attached project. I really appreciate you trying all avenues.
I tried what you mentioned, and at first it seemed to work, meaning after a build, the linked .js file in wwwroot\js\common was still "None", and the change I made was reflected in the original file outside the project, and the updated file was copied to the project because of the custom _Target_. However, after closing/re-opening the solution, Solution Explorer no longer shows the linked .js file at all, even though the .csproj says it's there, and it's there on disk ???
I'm hoping it's a simple mistake on my part.
[zzTempWeb2a.zip](https://github.com/dotnet/project-system/files/4746318/zzTempWeb2a.zip)

**Comment by davidwengier** [comment] 2020-06-09 04:50
Thanks again for the sample project. I can repro the issue you're talking about, and will continue to investigate, but I should warn you that it is likely this behaviour is owned by another team, not on GitHub, and the behaviour is most likely by design. It might be worth posting about the scenario you're trying to solve in the ASP.NET Core repository in case there is some other way to facilitate the same behaviour, or sharing content files.

**Comment by davidwengier** [comment] 2020-06-12 12:15
I've sent an email to the internal team that owns this scenario and will let you know what the response is.

**Comment by davidwengier** [comment] 2020-06-16 02:22
Logged AB#1141929 internally, I will update this issue if/when that issue changes.

**Comment by Dean-NC** [comment] 2020-06-16 13:32
@davidwengier  Thanks.

**Comment by davidwengier** [comment] 2020-06-26 05:02
Sorry, but the internal issue has been marked as "Won't Fix".

**Closed by davidwengier** 2020-06-26 05:02 UTC
Labels: Area-External-CPS, Resolution-External, Tracking, Triage-No-Action

**Comment by Dean-NC** [comment] 2020-06-26 16:38
@davidwengier Thanks for trying. It seems like ASP.Net applications in general are lower priority these days.
