### ISSUE TITLE
Fast up-to-date check does not work with linked items

### ISSUE THREAD

**Issue by sharwell** [dotnet/project-system#4580] opened 2019-02-18 00:18 UTC
**Visual Studio Version**: Visual Studio 2019 Preview 3

**Summary:**

A project containing a linked item with `CopyToOutputDirectory` set to `PreserveNewest` is never considered up-to-date.

This situation is observable in dotnet/roslyn@fec31a956848c23417baf5b02f6a83c4095a3a37 when building Microsoft.CodeAnalysis.UnitTests, and was reproduced in DotNetAnalyzers/StyleCopAnalyzers to verify that this is not an arcade issue.

**Steps to Reproduce**:

1. Add a linked file to a CPS project with the following:

    ```xml
    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    ```

2. Build the project 3 times

**Expected Behavior**:

On the third build, the project is considered up-to-date and does not build.

**Actual Behavior**:

The project builds. Up-to-date check logging reveals a non-existent path was getting checked.

**User Impact**:

Unit test projects are never considered up-to-date, significantly slowing developer iterations.

**Comment by sharwell** [comment] 2019-02-18 00:22
@drewnoakes @davkean I have been unable to find a workaround for this issue. If you can think of one, it would be greatly appreciated.

**Comment by drewnoakes** [comment] 2019-02-18 19:22
@sharwell I'm trying to repro this but haven't managed to do so with your steps.

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <None Include="../LinkMe.txt" Link="Linked.txt" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
```

It doesn't matter how many times I build that project, it does the right thing.

I checked out dotnet/roslyn@fec31a956848c23417baf5b02f6a83c4095a3a37 and build `Microsoft.CodeAnalysis.UnitTests` five times in 28614.69.d16.0 (master) and it results in 7 up-to-date projects after the first build.

Can you help me reproduce the bug?

**Comment by huoyaoyuan** [comment] 2019-02-23 08:05
I have touched this bug too.
This seems new to preview 3.
The linked files are provided by certain nuget packages, for example `xunit.runner.visualstudio` and `cef.redist.x64`.
Build log says that FastUpToDate is finding `.nuget` directory in **solution directory**:
`C:\Users\Me\Source\Repos\ing\tests\SomeTestProject\bin\Debug\netcoreapp2.2\..\..\..\..\..\.nuget\`
Comparing to VS 2017, the path is just `C:\Users\Me\.nuget\`.

**Comment by drewnoakes** [comment] 2019-02-25 14:27
@huoyaoyuan if you create a minimal project like the one in https://github.com/dotnet/project-system/issues/4580#issuecomment-464849700, can you repro the issue? I'd like to understand whether it's something related to your machine/environment, or something specific to the project. I haven't been able to reproduce the problem locally yet, which makes it harder to debug.

**Comment by huoyaoyuan** [comment] 2019-03-03 07:25
@drewnoakes no, I can't reproduce.
My case is somehow associated with nuget, and I've changed the bin and obj folders' position.

**Comment by drewnoakes** [comment] 2019-03-05 16:18
@huoyaoyuan, this should be fixed in VS2019 Preview 4. Would you be able to verify for your project and let me know whether it's resolved for you?

**Comment by huoyaoyuan** [comment] 2019-03-05 16:53
@drewnoakes Yes, this issue is fixed. But there is still another issue that my UWP projects aren't considered up to date. Should I open a new issue?

**Comment by drewnoakes** [comment] 2019-03-05 16:58
@huoyaoyuan thank you for confirming.

Would you mind creating a new issue for the UWP projects? It will be easier to track.

As far as I know, Preview 4 and RC are exactly the same build. The difference (as I understand it) is that the former will roll over to future previews, whereas the latter rolls over to the GA release.

**Closed** 2019-03-05 16:58 UTC
Labels: Bug, Feature-Up-to-date
