### ISSUE TITLE
VS2017RC4 writes csproj file unnecessarily

### ISSUE THREAD

**Issue by JamesNK** [dotnet/project-system#1536] opened 2017-02-11 20:33 UTC
VS2017RC4 is updating the csproj file (and making git think the content is binary https://github.com/dotnet/roslyn-project-system/issues/1534) even though all I'm doing in Visual Studio is compiling my application.

VS should only update and write the csproj file when the user does something that will cause its content to change, e.g. edit the package details.

**Comment by JamesNK** [comment] 2017-02-11 20:40
An example of it happening is right clicking on the project, chosing to edit the csproj, and compiling the project.

**Comment by davkean** [comment] 2017-02-11 21:16
I noticed this too, we shouldn't be saving the project if we're not dirty.

**Comment by 333fred** [comment] 2017-02-12 22:30
This is by design to avoid races between the temp version of the file and the real version of the file, we save the file when opening the project file editor. This is to prevent spurious "The file has changed" popups from occurring. When we finish designing and implementing the in-memory version of the editor, I expect that this step will no longer be necessary.

**Comment by davkean** [comment] 2017-02-13 00:16
@333fred Not sure I understand - I think I'm/James is referring to the situation where the editor saves the file even though the file is not dirty, not referring to saving the file when the editor is being opened.

**Comment by davkean** [comment] 2017-02-13 22:08
This is also causing unneeded evaluations  and design-time builds as well when this occurs.

**Comment by davkean** [comment] 2018-04-17 10:33
@JamesNK This has been fixed in 15.7 - we've moved to editing the project file like a normal file and as part of that, this is fixed.

**Closed by davkean** 2018-04-17 10:33 UTC
Labels: Area-New-Project-System, Bug, Feature-Project-File-Editing
