### ISSUE TITLE
Properties window for NETCore.App displays path as 'c:\some\path'

### ISSUE THREAD

**Issue by jmarolf** [dotnet/project-system#5029] opened 2019-07-10 22:01 UTC
**Visual Studio Version**: 16.3 P1

**Steps to Reproduce**:

Using the build from [this PR](https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/190717?_a=overview), or after its merged:
1. Create a .NET Core project
2. In solution explorer, expand dependencies node to click on Microsoft.NETCore.App

**Expected Behavior**:
The actual path for .NET Core framework

**Actual Behavior**:
The path shown is 'c:\some\path'
![image](https://user-images.githubusercontent.com/9797472/61008072-6b3f3c80-a323-11e9-9221-759d1059723a.png)

**Comment by drewnoakes** [comment] 2019-07-10 22:46
Duplicate of #4762. 

Specifically, the point about removing temporary code.

**Closed by drewnoakes** 2019-07-10 22:46 UTC
