### ISSUE TITLE
VS hang while working in Roslyn.sln

### ISSUE THREAD

**Issue by tmat** [dotnet/project-system#3090] opened 2018-01-02 22:17 UTC
Version: 
![image](https://user-images.githubusercontent.com/41759/34502251-894523cc-efc7-11e7-940e-b479c9a19850.png)

Threads:
![image](https://user-images.githubusercontent.com/41759/34502239-7c1d0a7a-efc7-11e7-8d2a-60d17cde2630.png)

Memory dump:
%internal_share%\public\tomat\Bugs\3090

**Comment by Pilchie** [comment] 2018-01-02 22:40
@davkean any idea what's up here?

**Comment by davkean** [comment] 2018-01-02 23:52
@lifengl was this one of the ones that was introduced in 15.6?

**Comment by Pilchie** [comment] 2018-01-03 18:54
Ping @lifengl?

**Comment by Pilchie** [comment] 2018-01-04 16:16
Ping @lifengl?

**Comment by lifengl** [comment] 2018-01-04 16:42
We need a 32bits heap dump.  It looks like we are seeing more deadlock.

Sent from my phone

On Jan 4, 2018, at 8:16 AM, Kevin Pilch <notifications@github.com<mailto:notifications@github.com>> wrote:


Ping @lifengl<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Flifengl&data=02%7C01%7C%7Cb7eda8f94d8848f4c1ad08d5538e7455%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636506793649984262&sdata=cpHIy12UWn3Iq%2BANT%2BvhCS9BIUDzz8RU0rlCmkF7h54%3D&reserved=0>?

**Comment by lifengl** [comment] 2018-01-05 00:14
This issue is related to some code didn't release an upgradeable read lock, but the current infrastructure didn't catch which code causing the problem.  It could be a task still using it, but was blocked by something else, (but it happens to have 16k tasks on-going).  @tmat : can you reproduce this issue (consistently, or with reasonable chance to hit it)?  We are considering to add some extra logging to make it possible to locate where the lock was acquired.

**Comment by tmat** [comment] 2018-01-05 00:26
@lifengl Unfortunately I can't repo.

**Comment by lifengl** [comment] 2018-01-05 23:07
@tmat can you set environment variable CPS_DiagnosticRuntime on the machine, and capture a memory dump, if you happen to run into it again?  Also do you happen to remember what kind of things you did before VS ran into this problem?  (some project modifications?  GIT branch changes?...)

**Comment by Pilchie** [comment] 2018-01-08 19:31
Going to close this as not repro in the meantime.

**Closed by Pilchie** 2018-01-08 19:31 UTC
