### ISSUE TITLE
Open Containing Folder broken for editing project files

### ISSUE THREAD

**Issue by sharwell** [dotnet/project-system#2661] opened 2017-07-26 02:31 UTC
### Steps to reproduce

1. Open a project
1. Right click the project in Solution Explorer &rarr; Edit *ProjectName*.csproj
1. Right click the document tab at the top of the editor &rarr; Open Containing Folder

### Expected results

The project folder opens in Explorer, similar to if you right clicked on the project name in Solution Explorer and selected Open Folder in File Explorer.

### Actual results

A folder in the temporary directory opens, which contains nothing but a copy of the actual project file.

**Comment by davkean** [comment] 2017-07-26 02:42
Yep, known, dupe of: https://github.com/dotnet/project-system/issues/780

**Closed by davkean** 2017-07-26 02:42 UTC
