### ISSUE TITLE
Class generation in nested namespaces swaps namespace order for generated directories

### ISSUE THREAD

**Issue by poke** [dotnet/project-system#2105] opened 2017-05-02 14:26 UTC
Hey, I’ve noticed the following issue with the class code generation in Visual Studio 2017 (15.1 26403.7) using the new .csproj format:

1.  Create a .NETStandard library project.

2.  Create some class inside the namespace `Service.Internal` (created directories accordingly). It should look like this:

    ![Project with a simple folder structure `Service.Internal.MyService`](https://cloud.githubusercontent.com/assets/132240/25621981/4c247298-2f53-11e7-8f95-1f78c7ebdc4f.png)

3.  Reference a non-existent type in the class, and use the quick fix bulb to generate the type:

    ![Referencing a non-existent type, and generating that type using the quick fix bulb](https://cloud.githubusercontent.com/assets/132240/25622034/7f501794-2f53-11e7-95c8-ef5edb2a0853.png)

4.  Observe the resulting folder structure:

    ![Created `Utility` class is in the folder `Internal.Services` instead of `Service.Internal`](https://cloud.githubusercontent.com/assets/132240/25622117/b4c4af98-2f53-11e7-90d8-a44990d880af.png)

Obviously, the `Utility` class should have been created next to the `MyService` file in the same folder. The rest of the process works correctly, especially the actual namespace for the `Utility` class is correct.

**Comment by davkean** [comment] 2017-05-03 00:39
Thanks for the bug, this is a dupe of https://github.com/dotnet/project-system/issues/1760.

**Closed by davkean** 2017-05-03 00:39 UTC
Labels: Bug
