### ISSUE TITLE
Error list should not show errors until a restore has completed

### ISSUE THREAD

**Issue by jmarolf** [dotnet/project-system#2330] opened 2017-05-30 21:44 UTC
Part of the issue with https://github.com/dotnet/project-system/issues/2281 is that the error list is inaccurate for and indeterminate amount of time while we wait for the project system to actually set things up.  We should at lest tell the user this and ideally not show errors in the errorlist until the restore has completed.

**Comment by davkean** [comment] 2017-05-30 23:12
It's not restore per se, but really need to wait until the first design-time build that contains the restore results.

This is how Roslyn gets the results of the restore:

1. Restore does nothing but write an assets file to the obj directory.
2. We detect that file has changed, and kick off a reevaluation of the project
3. Based on that reevaluation we launch a design-time build
4. That design-time build reads the assets file, and converts it to `<Reference Include="MyNuGet.dll"/>`
5. These end up getting passed to `<Compile/>` and returned to us as command-line arguments.
6. We parse those command-line arguments and pass them onto Roslyn.

Things to note:

- Not all projects have restore results - they may never have a `<PackageReference/>`, it's hard to tell though, because one of their references could result in them getting an assets file
- We may not always been restore if the results are already valid for the project

**Comment by davkean** [comment] 2017-05-30 23:34
We currently set LastDesignTimeBuildSucceeded to `true' during the first design-time build, but we could only set it to `true` on the first design-time build with restore results.

**Comment by srivatsn** [comment] 2017-06-05 17:03
Dupe of https://github.com/dotnet/project-system/issues/928

**Closed by srivatsn** 2017-06-05 17:03 UTC
