### ISSUE TITLE
Can't use Class Diagram with .Net Standard class library

### ISSUE THREAD

**Issue by weshaggard** [dotnet/project-system#2616] opened 2017-07-15 00:17 UTC
@wolf99 commented on [Fri Jul 14 2017](https://github.com/dotnet/standard/issues/426)

I have a solution in VS2017 that contains a .Net Standard 1.4 class library. If I attempt to view a class diagram for the namespace or any class, nothing is displayed but a `classDiagram1.cd` file is added to the project. Attempting to open this file results in an error:

> Class diagrams are not supported by this project type.
> Add the class diagram file to a C#, VB or C++ project and try opening it again.

Viewing the file using notepad I see it contains:

    <?xml version="1.0" encoding="utf-8"?>
    <ClassDiagram /> 

Additionally the Class Diagram file type is not available to add in the Add New item wizard. Seems to work fine with non-standard and non-core projects. Not sure why classes in one type of project can not be diagrammed while classes in another can.

See also https://developercommunity.visualstudio.com/content/problem/31297/in-core-app-11-c-class-library-getting-class-diagr.html

**Comment by srivatsn** [comment] 2017-07-24 18:50
Dupe of https://github.com/dotnet/project-system/issues/256

**Closed by srivatsn** 2017-07-24 18:50 UTC
