### ISSUE TITLE
Hundreds of false errors in .NET SDK solution with multi-targeting projects

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#1696] opened 2017-03-08 09:11 UTC
_From @AArnott on March 7, 2017 23:17_

**Version Used**: 

VS 2017 RTW (dev15rtwsvc 26228.04)

**Steps to Reproduce**:

Disable NuGet package restore in the IDE to workaround https://github.com/NuGet/Home/issues/4764

```
git clone https://github.com/aarnott/pinvoke
cd pinvoke
git checkout c5642c29ddd
.\build -Restore -Build
src\pinvoke.sln
```

Open BCrypt.cs (from the BCrypt project).
Opening Hid.cs and other files also does this.

**Expected Behavior**:

No errors

**Actual Behavior**:

The error list is full of false errors.

![image](https://cloud.githubusercontent.com/assets/3548/23682500/eff84ea8-0348-11e7-863b-bf9983a3b303.png)

_Copied from original issue: dotnet/roslyn#17614_

**Comment by davkean** [comment] 2017-03-08 09:11
I think we'll probably want to take first look at this. I'll move it, and reopen if it's not us.

**Comment by AArnott** [comment] 2017-03-08 14:50
FWIW, I've noticed that *sometimes* no errors show up. But it's usually like this.

**Comment by davkean** [comment] 2017-06-15 00:52
@AArnott With latest bits and all the changes from https://github.com/dotnet/project-system/issues/2297 - I'm not seeing these errors, however, I am seeing lots of design-time build errors around your CodeGeneration AppDomain that you are firing up expecting to find v14 dlls.

**Comment by AArnott** [comment] 2017-06-24 22:25
When I try on the latest d15rel, nuget is badly broken and I can't make any progress building pinvoke itself.

But on the latest public release (15.2, 26430.14) restore fails with https://github.com/NuGet/Home/issues/4753 which I can workaround and build succeeds.
After VS is loaded, I still see hundreds of compile errors after I open a source file. And I also notice that the TFM context switcher on the document incorrectly says `$(DesktopAndPortableFrameworks)`, which is the macro I use in my project file, as if it was reading the unevaluated MSBuild syntax instead of the evaluated, semicolon-delimited list.

![image](https://user-images.githubusercontent.com/3548/27512311-2554c02e-58f1-11e7-8b1f-711686113633.png)

**Comment by davkean** [comment] 2017-06-27 02:47
@AArnott We only added support for evaluated values in `<TargetFrameworks>` in 15.3. Can you try a recent 15.3 build?

**Comment by davkean** [comment] 2017-06-27 02:48
Oh I see you tried that - when you say NuGet is badly broken, what do you mean?

**Comment by AArnott** [comment] 2017-06-27 04:58
Actually, the screenshot above was taken on 15.2 (to avoid all the nuget failures). On 15.3, I see the context switcher works properly. Thanks for the tip.
I'll have to retry on the nuget stuff to report. But generally I file those issues on nuget/home directly.

**Comment by davkean** [comment] 2017-06-27 05:26
I was running into design-time build failures - if they are running in the path that we're running into figure out PackageReferences, then this will block restore.

**Comment by AArnott** [comment] 2017-06-27 05:32
Thanks for the tip. I'll try to find that out by adding Message tasks to my codegen targets and then running restore at the command line. Should that effectively reproduce what VS might be doing?

FWIW, I'm in 15.3 right now (26621.2 d15rel), and I'm seeing 94 errors in the Error List of my open PInvoke.sln solution (master branch). None of which are "real". 
![image](https://user-images.githubusercontent.com/3548/27572194-525d1f56-5abf-11e7-9e60-f555160a9c62.png)

**Comment by Pilchie** [comment] 2017-12-19 22:00
@AArnott - any current status here?

**Comment by AArnott** [comment] 2017-12-19 23:47
@Pilchie My last attempt at opening PInvoke with 15.5 was *awesome*. Everything worked better than it ever has (at least since Dev14). :)

**Comment by Pilchie** [comment] 2017-12-20 00:20
@AArnott - I saw your mail on that, wanted to make sure it was the same project.  Going to close this for now then.  Let us know if (when) you run into future issues!

**Closed by Pilchie** 2017-12-20 00:20 UTC
Labels: Bug, Feature - Language Service, Urgency-Soon
