### ISSUE TITLE
Condition on ItemGroup not being evaluated in VS

### ISSUE THREAD

**Issue by twsouthwick** [dotnet/project-system#1542] opened 2017-02-13 16:35 UTC
I have a project that has a mix of PackageReference and project.json (the plan is to move to PackageReference, but stuck on project.json in one project right now). I also have  global targets file that is imported by all the projects with various shared items. One of them is a PackageReference, which I condition on a variable `IncludeAnalyzers`. This is set to true in the all projects except the project.json where it is set to false.

When I attempt to restore is VS, the project.json project ends up getting the PackageReference and incorrectly restoring as NuGet believes that the project has opted into the PackageReference system. If I restore from the commandline, NuGet restores the project.json correctly and does not see the PackageReference.  It appears that the condition is not being evaluated correctly in VS. This node was within a conditional `ItemGroup`;. After switching it to a `choose/when` block, it works as expected.

**Before:**
```xml
<ItemGroup Condition="'$(IncludeAnalyzers)' == 'true'">
  <PackageReference Include="StyleCop.Analyzers" Version="1.0.0" />
</ItemGroup>
```

**After:**
```xml
<Choose>
  <When Condition="'$(IncludeAnalyzers)' == 'true'">
    <ItemGroup>
      <PackageReference Include="StyleCop.Analyzers" Version="1.0.0" />
    </ItemGroup>
  </When>
</Choose>
```

**Comment by mqudsi** [comment] 2017-08-31 00:18
Is there a reason VS doesn't just relegate all package management tasks to NuGet instead of needing to take care of everything twice, once in the VS package manager and once in NuGet?

**Comment by natidea** [comment] 2017-08-31 00:28
To enable auto-restore, package management has to be synchronized with [design time builds](https://github.com/dotnet/project-system/blob/master/docs/design-time-builds.md). That synchronization happens in Project System while restore activities based on this information happen in NuGet.

**Comment by davkean** [comment] 2017-08-31 00:42
@twsouthwick Is this new project system or legacy project system? I'm assuming its the new project system - I have no idea why this wouldn't work out of the box.

**Comment by twsouthwick** [comment] 2017-08-31 18:22
This is with the new project system

**Comment by kzu** [comment] 2018-01-04 16:19
I can confirm this isn't working in the legacy project system, whereas it works great on the new one. 

![conditionalpackages](https://user-images.githubusercontent.com/169707/34572983-b13b7bf2-f151-11e7-9997-633210b5b59f.gif)

Switching to `<Choose>` is ugly as hell, but it fixes the legacy projects until everything is new "sdk-style" at least...

**Comment by davkean** [comment] 2018-01-04 22:14
I tried this and it does work well in the new project system. Also after [this change for 15.6](https://github.com/dotnet/project-system/pull/3093), we also support the following construct that will cause us to restore when you change active configurations:

``` XML

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <IncludeAnalyzers Condition="'$(Configuration)' == 'Release'">true</IncludeAnalyzers>
  </PropertyGroup>

<ItemGroup Condition="'$(IncludeAnalyzers)' == 'true'">
  <PackageReference Include="StyleCop.Analyzers" Version="1.0.0" />
</ItemGroup>

</Project>
```

The legacy project system evaluation support is being tracked by https://github.com/dotnet/project-system/issues/2129 and close this in lieu of that.

**Closed by davkean** 2018-01-04 22:14 UTC
Labels: Area-New-Project-System, Bug, Feature - NuGet

**Comment by davkean** [comment] 2018-01-04 22:22
The other thing to note is that other items, other than `<PackageReference/>` such as `<Compile/>`  are read ignoring conditions. That's always been its behavior since the dawn of time and will likely always be its behavior.
