### ISSUE TITLE
Add items to solution tree dynamicaly

### ISSUE THREAD

**Issue by iskiselev** [dotnet/project-system#2904] opened 2017-10-18 22:42 UTC
I'm looking in possibility to add/update dynamically items based on another itemgroup in such way, that it would be shown in solution explorer.
If I do it outside of target, I'm not able to reference another itemGroup metadata in new item metadata with `%(OtherItem.Metadata)` syntax. If I move modification inside target, even that is called with DesignBuild (I tried before CompileDesignTime, ResolveAssemblyReferencesDesignTime), newly added items are not visible in Solution explorer.

**Comment by Pilchie** [comment] 2017-10-23 22:59
@davkean any ideas here?

**Comment by davkean** [comment] 2017-10-23 23:07
First of all, there's no intentions to populate the tree using the build (targets) - this is currently intentionally evaluation based due to performance constraints.

I'm not sure what you are trying to do, but if you can achieve it via evaluation then we will show in the tree if;

- It's not a duplicate of another item (ie two item types that point to the same file)
- If it's a new item type, then you need to (currently) create a [new rule](https://github.com/Microsoft/VSProjectSystem/blob/master/doc/extensibility/custom_item_types.md) that describes it so that it shows up in the tree.

**Comment by iskiselev** [comment] 2017-10-24 01:01
I've registered custom build action for .proto files with new rule and ProjectSchemaDefinitions.  On pre-build (and CompileDesignTime) I generate c# sources from them, placing output to proto folder in project directory with name .proto.cs. Generated files are noticed by VS as soon as they are created, which is great. What I really want, is to add for each generated file DependentUpon metadata to link them back to proto files. I know how to translate each of my ProtoBuf item group item into generated file, I even can create compile items using transforms (Something like `<Compile Include="@(ProtoBuf-gt;'%(Identity)'.cs" />` - it works only for source location in same folder, but could be rewritten to extend with other locations), but I'm not able to specify metadata from transform out of Target section.

**Comment by Pilchie** [comment] 2017-10-31 19:30
@davkean any further suggestions here?

**Comment by davkean** [comment] 2017-11-02 03:37
There is no way to influence the metadata of an item in evaluation from an item generated during the build. The latter occurs after the former.

However, there might be able to influence nesting via ProjectSchemaDefinitions. @lifengl @jviau?

**Comment by iskiselev** [comment] 2017-11-03 17:27
I was able to solve this with msbuild.
As item created from another item derives all metadata from original one, and it is possible to create metadata for item from it's own metadata, it is possible to prepare all required information in original item. So, here is an example that works for me:
```xml
  <ItemGroup>
    <ProtoBuf Update="@(Protobuf)">
      <OutputFileName>proto\$([System.String]::new('%(Filename)').Replace('-', '')).proto.cs</OutputFileName>
      <OutputLink Condition="'%(Link)' != ''">$([System.String]::new('%(Link)').Replace('-', '')).cs</OutputLink>
      <OutputLink Condition="'%(Link)' == ''">$([System.String]::new('%(Identity)').Replace('-', '')).cs</OutputLink>
      <DependentUponTemplate>%(Identity)</DependentUponTemplate>
    </ProtoBuf>
    <Compile Include="@(ProtoBuf->'%(OutputFileName)')" >
      <DependentUpon>%(DependentUponTemplate)</DependentUpon>
      <Link Condition="'%(OutputLink)' != '%(Identity)'">%(OutputLink)</Link>
    </Compile>
  </ItemGroup>
```

I'm still has question if it is possible to solve better with ProjectSchemaDefinitions, and why msbuild do not allow referernce in format `%(ProtoBuf.Identity)` (with explicit item) outside of target. Probably second should be asked in msbuild repo.

**Comment by iskiselev** [comment] 2017-12-07 01:00
Unfortunately my solution still not work on project opening. Generated items are not placed under their sources.
But, if you edit project/target which defines them, commenting <Compile Include=...> section, save it and uncomment it back - it shows correctly in tree under proto files.

**Comment by lifengl** [comment] 2017-12-07 05:30
Nesting can only happen inside the same folder ( linked files are treated as a virtual item in the virtual path), you can only use file name in the dependUpon data, not a path.

Linked files are currently expected to be outside of the project root folder.  Links to files inside the project cone are not supported/tested and you might run into bugs that we might not know of.

Sent from my phone

On Dec 6, 2017, at 5:00 PM, Igor Kiselev <notifications@github.com<mailto:notifications@github.com>> wrote:


Unfortunately my solution still not work on project opening. Generated items are not placed under their sources.
But, if you edit project/target which defines them, commenting section, save it and uncomment it back - it shows correctly in tree under proto files.

**Comment by davkean** [comment] 2017-12-15 03:28
Just to close this, we don't have any plans to update/show the tree based on targets as was the original question. There's a huge performance hit to run builds, so we're going to stick evaluation. It looks like the other items were resolved.

**Closed by davkean** 2017-12-15 03:28 UTC
Labels: Area-New-Project-System, Feature Request
