### ISSUE TITLE
Project level imports untick themselves when clicking on a different project level import

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#4131] opened 2018-10-17 14:38 UTC
In a VB.NET project, Under My Project, References, the Imported namespaces section has a bug in - when clicking on an import lower down in the list, a higher one is often unticked, often above the visible items.  This has been going on for quite a while - not sure what version of VS.NET it was introduced in.

The UI of that area is really not great either - it is a bit odd the way that imported namespaces are added, edited and removed - a checkbox list is a strange choice - I would have expected add/edit/delete buttons with a dialog to add where you can choose either from the checkboxlist to add new ones or enter one, a dialog for editing an existing one and a messagebox to confirm deletion.  It is not intuitive that if you untick a namespace and close and reopen the tab, it can disappear or drop to a different place in the list.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/359025/project-level-imports-untick-themselves-when-click.html
VSTS ticketId: 706730_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by Pilchie** [comment] 2018-10-17 14:41
Strange - I thought I fixed this as part of https://github.com/dotnet/project-system/pull/3095, but that should be included already...

**Comment by jjmew** [comment] 2019-01-10 19:13
I am not able to reproduce this on Dev16 Preview 2. The original issues was filed on 15.7.  @Pilchie  were you able to repro it when you moved it to GitHub?

**Comment by jjmew** [comment] 2019-01-11 00:31
W

>           I thought I did, but as I noted, I did try to fix this too, so maybe it is fixed, or maybe there is something finicky about the repro now.

Should I close it and wait if someone else to reactivate it if they are able to repro it? I tried in different machines.

**Comment by Pilchie** [comment] 2019-01-11 00:55
That's fine with me.

**Comment by jjmew** [comment] 2019-01-11 01:07
We are not able to reproduce this issue in Dev 16. Closing until we have reports on Dev 16.

**Closed by jjmew** 2019-01-11 01:07 UTC
Labels: Bug, Feature-AppDesigner, Triaged
