### ISSUE TITLE
Ctrl+X does not work in Project Properties UI text boxes (1)

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#6900] opened 2021-02-02 04:09 UTC
(Moved from #6627)

Repro steps:

1. Open the Project Properties UI
2. Select text in a text box (e.g. _Assembly name_)
3. Press <kbd>Ctrl</kbd>+<kbd>X</kbd>
4. Expect text to be cut to the clipboard. Actually, nothing happens.

Unclear why. Probably the VS command bound to this keystroke is hijacking it. This works in the legacy pages though. The code in `PropertyPageElementHost` might be relevant.

**Comment by MiYanni** [comment] 2021-08-17 02:55
This keystroke isn't being hijacked as `Shift+Delete` doesn't work either (same as `Ctrl+X` in Windows). `Shift+Insert` is Paste and `Ctrl+Insert` is Copy. These also work as expected, so it is actually the Cut action that has an issue. Investigating... 👀

**Comment by MiYanni** [comment] 2021-08-17 03:01
The Cut option in the right click context menu works as expected. Still investigating... 👀

![ContextMenuCutWorking](https://user-images.githubusercontent.com/17788297/129656997-4d605903-084a-4427-b285-d4b48b92606f.gif)

**Comment by MiYanni** [comment] 2021-08-17 03:29
It is certainly getting the command as Ctrl+X on text is clearing the clipboard. So, if you Ctrl+C and Ctrl+V, you'll see text. As soon as you hit Ctrl+X, when you hit Ctrl+V, nothing appears anymore. I'm going back and forth between Notepad, and it is definitely getting the command, but is acting like I have selected nothing. Thus, the clipboard has no text in it and nothing is removed from the edit field. More investigating... 👀

**Comment by MiYanni** [comment] 2021-08-17 03:37
Ah ha! Getting somewhere. Used a clipboard viewing app, and it seems that the Cut action via hotkey is getting a `CF_VSREFPROJECTS` object instead of the standard Text object. So, something is definitely awry.

![CutVSRefProjects](https://user-images.githubusercontent.com/17788297/129659687-8ad32a1f-cf9c-401c-838c-0ba612f5e5eb.gif)

**Comment by drewnoakes** [comment] 2021-08-17 12:05
@MiYanni does Ctrl+X work in the text boxes if you unbind that keystroke from the VS command for cut?

**Comment by MiYanni** [comment] 2021-08-17 22:48
@drewnoakes If you remove the binding, it works as expected (meaning, the issue is fixed). I think the binding is doing some logic to create a type of paste object. When I looked for `CF_VSREFPROJECTS`, I found this in CPS:
https://devdiv.visualstudio.com/DevDiv/_git/CPS?path=%2Fsrc%2FMicrosoft.VisualStudio.ProjectSystem.VS.Implementation%2FPackage%2FCopyPaste%2FDragDropHelper.cs&version=GBmain&line=172&lineEnd=173&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents

It seems like it is recognizing it is Cut/Paste, but isn't doing the right work for it. I can determine there is a difference between Copy and Cut. For Copy, it doesn't find a paste processor. However for Cut, it does find a processor. Though, changing this logic to never find one doesn't fix anything. The code I was looking at for this interaction is here:
https://devdiv.visualstudio.com/DevDiv/_git/CPS?path=%2Fsrc%2FMicrosoft.VisualStudio.ProjectSystem.VS.Implementation%2FPackage%2FCopyPaste%2FProjectNode.CopyPaste.cs&version=GBmain&line=768&lineEnd=769&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents

My hunch is that the actual Cut action isn't being recognized properly. This is why the Paste information is incorrect and stuff gets weird. If Cut was working properly, it would remove the text that is already there, which it is not doing. Still investigating... 👀

**Comment by drewnoakes** [comment] 2021-08-19 13:08
@tmeschter uncovered this code in the legacy pages:

https://github.com/dotnet/project-system/blob/0476235d70d1b65b8062492075db6fd86995612a/src/Microsoft.VisualStudio.AppDesigner/PropPageDesigner/PropPageDesignerView.vb#L422-L426

**Comment by MiYanni** [comment] 2021-08-31 19:50
## Summary (of information so far)
From Richard Stanton:

> I believe what you want to do here is handle the `VSStd97CmdID.Cut` (and Copy/Paste probably) commands for the project properties editor. The editor’s `IVsOleCommandTarget` should be called before it is passed to the global handler. If it the command is marked as handled, then the project properties can do the actual “Cut” on the current textbox.
By handling the `VSStd97CmdID.Cut` command, you will then automatically get any user customizations to the command. For example if they change the keyboard binding to Shift+Del, that would also work in the project properties editor.
There is a small section here on adding an `IOleCommandTarget` to an editor, although this documentations seems to be a bit light:
[Walkthrough: Adding Features to a Custom Editor - Visual Studio (Windows) | Microsoft Docs](https://docs.microsoft.com/en-us/visualstudio/extensibility/walkthrough-adding-features-to-a-custom-editor?view=vs-2019)

From the earliest I could tell via debugging, CPS was already getting the wrong command sent to it. It gets sent `SolutionCfg` (Group `5EFC7975-14BC-11CF-9B2B-00AA00573819` with ID `684`) and `SolutionPlatform` (Group `1496A755-94DE-11D0-8C3F-00C04FC2AAE2` with ID `1990`) commands when you activate `Edit.Cut` (by pressing Ctrl+X as the default binding). So, I'm a bit baffled as to where or when I need to create a handler. I'm told that the Property Pages UI would need to handle that itself. So, I'm currently investigating. I'm also speaking with Ryan Molden about the issue.

**Comment by drewnoakes** [comment] 2021-09-03 03:39
Do we know why cut has this problem, but copy and paste do not?

**Comment by MiYanni** [comment] 2021-09-03 17:20
@drewnoakes No idea. When doing `Copy` or `Paste`, those actions don't hit the page at all. Let me update with the details I figured out yesterday.

I had a discussion with Ryan Molden and we looked at the stack trace of the umanaged code. He explained that the info I mentioned above about `SolutionCfg` and `SolutionPlatform` is unrelated to the command. He said, "that isn't command dispatch, it is an idle time update of a combo, which requires an exec because QS doesn't have a way to express the info we need" So, that was a red herring. I looked through what he said and found the frame code in CPS. My branch is: https://devdiv.visualstudio.com/DevDiv/_git/CPS?path=%2F&version=GBdev%2Fmiyanni%2FCutIssueInvestigation&_a=contents

The code (specifically for property pages) needs to go in `ProjectPropertiesEditorFactory.WindowPane.cs`. I'd have to check if there is a similar one for Launch Profiles, but I'm not testing that at this moment (just something to note). This class, if you re-implement `IOleCommandTarget`, it will properly intercept the `Cut` command ID. As mentioned, `Copy` and `Paste` do not get intercepted here, and I don't know why. I tried various means to 'push the command forward' but nothing has worked so far. I'm certain this is the 'right way' to do it, but I don't know what actual code I need to make it work. I think it is a good idea to figure out how `Copy` and `Paste` are being handled, and see if I can re-create that here.

One thing to note is that I said 're-implement' `IOleCommandTarget`. That's because this class derives of `WindowPane`, and that abstract class implements `IOleCommandTarget`.

**Comment by MiYanni** [comment] 2021-09-09 20:19
There is more discussion on this in the PR that I created. Potentially, the fix I made will not work and a better fix is needed. Instead of changing the Cut mechanics, we may need to change how selection of the property page window occurs. It seems that another PR might also break Copy, which would be much worse than Cut. PR here: https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/349555

**Comment by MiYanni** [comment] 2021-09-21 00:11
The changes to resolve the issue have been merged into CPS via: https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/349555

**Closed by MiYanni** 2021-09-21 00:11 UTC
Labels: Bug, Triage-Approved, Must-Have, Feature-Project-Properties-Designer
