### ISSUE TITLE
Working folder when debugging a .NET Core app changing bizarrely

### ISSUE THREAD

**Issue by adamralph** [dotnet/project-system#3609] opened 2018-06-01 22:33 UTC
_Continuing from [Twitter](https://twitter.com/davkean/status/1002675512399970304)._

Note that the breakpoint is _before_ the call to `Directory.SetCurrentDirectory()`!

![working-dir](https://user-images.githubusercontent.com/677704/40866148-6f48d7b0-65fc-11e8-9e9b-498bae7e57c2.gif)

**Comment by adamralph** [comment] 2018-06-01 22:35
@davkean if you want to try it yourself, the repo is https://github.com/adamralph/liteguard

I'm using VS 15.7.1.

**Comment by adamralph** [comment] 2018-06-01 22:40
Also, this is when I create a blank console project in a fresh instance of VS:

![image](https://user-images.githubusercontent.com/677704/40866350-8372ed9c-65fd-11e8-90cd-21376e604851.png)

**Comment by adamralph** [comment] 2018-06-01 22:43
And again, as soon as I add a call to `Directory`, it changes, _before_ the call to `Directory` has happened_.

![image](https://user-images.githubusercontent.com/677704/40866444-f5d3e76a-65fd-11e8-9381-35b4f5a7931a.png)

**Comment by adamralph** [comment] 2018-06-01 22:44
@davkean I suspect that to produce the screenshot in your tweet, you called `Directory.GetCurrentDirectory()`, hence the reason you saw the project output folder.

**Comment by steveharter** [comment] 2018-06-04 16:29
I can confirm this is an issue with 2.0.x. I also have a "random" location in a simple app: `C:\\Program Files\\dotnet\\shared\\Microsoft.NETCore.App\\2.0.7\\System.Private.CoreL` when there aren't any references to a System.IO type (or perhaps others; I didn't try) in the code block.

However with 2.1.0 I couldn't repro the issue because the immediate window won't run a `Directory.GetCurrentDirectory()` without an assembly reference: `error CS0234: The type or namespace name 'Directory' does not exist in the namespace 'System.IO' (are you missing an assembly reference?)`

I suggest moving this issue to coreclr repo since it appears to be related to type initialization.

**Comment by Pilchie** [comment] 2018-06-04 16:58
This issue was moved to dotnet/coreclr#18284

**Closed by Pilchie** 2018-06-04 16:58 UTC
