### ISSUE TITLE
The language version is not displayed

### ISSUE THREAD

**Issue by Varorbc** [dotnet/project-system#7614] opened 2021-09-18 02:35 UTC
## Visual Studio Version

17.0.0 preview 4.0

## Summary

The language version is not displayed

## Steps to Reproduce

```
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
```

## Actual Behavior
![image](https://user-images.githubusercontent.com/5714438/133869515-ea45342d-41a1-4385-813e-fcde3c236385.png)

**Comment by drewnoakes** [comment] 2021-09-20 13:03
@Varorbc can you share more details about your project please? I can't repro this with a new .NET Core Console Application. For example, what SDK are you using, what target framework(s) do you have, etc.

**Comment by drewnoakes** [comment] 2021-09-28 03:36
Found the root cause of this. The UI supports `ShowEvaluatedPreviewOnly` metadata on properties, which is taken to indicate that no editor should be shown and only a read-only version of evaluated value(s) be displayed.

We show a value when no `<LangVersion>` is in the project file. In that case, the unevaluated value is `""` and the evaluated value is `"9.0"` (for example). The important point is that they differ.

When a `<LangVersion>` is specified in the project, the unevaluated and evaluated values match, which means we don't have a `PropertyValue.EvaluatedValues` collection for the UI to bind to, so we show nothing.

The fix will be in how the UI implements `ShowEvaluatedPreviewOnly`.

**Comment by drewnoakes** [comment] 2021-09-28 10:29
Fixed in https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/354332

![image](https://user-images.githubusercontent.com/350947/135070427-6259fd8b-a74c-45da-b5ef-67279a22feeb.png)

**Comment by Varorbc** [comment] 2021-09-28 10:31
Would it be better to display the digital version?

**Comment by drewnoakes** [comment] 2021-09-28 10:52
That'd be nice, yes. In this case the value `latest` is passed to the compiler directly. We don't know what value the compiler thinks that is.

https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/language#langversion

**Comment by drewnoakes** [comment] 2021-09-29 12:50
The CPS PR has been merged.

**Closed by drewnoakes** 2021-09-29 12:50 UTC
Labels: Triage-Investigate, Feature-Project-Properties-Designer
