### ISSUE TITLE
Edit and Continue not working when debugging project with mixed TFMs

### ISSUE THREAD

**Issue by siegfriedpammer** [dotnet/project-system#2926] opened 2017-10-26 17:32 UTC
## Tested with:
* VS 2017 15.4.1
* VS 2017 15.5 preview 2

## Configuration:
* Disabled Light-weight solution load (as noted [here](https://www.visualstudio.com/en-us/news/releasenotes/vs2017-knownissues#a-idkilsl-alightweight-solution-load-issues))
* Debugger Settings:
![grafik](https://user-images.githubusercontent.com/344204/32067083-380a2cb6-ba82-11e7-8df3-8bdc44af3dac.png)

## Steps to reproduce:
* Clone the ILSpy repository master branch: https://github.com/icsharpcode/ILSpy
* Execute `git submodule update --init --recursive` to get all required submodules
* Open ILSpy.sln in VS
* Set a breakpoint in `ILReader.DecodeInstruction` (e.g. line 366 in `ILReader.cs` in `ICSharpCode.Decompiler`)
* Make sure ILSpy is set as start-up project.
* Run with debugger
* Open an assembly and try to decompile a method with a body
* After the breakpoint is hit, try to press enter and add a new line of source code, e.g. `Console.WriteLine()`

## Expected behavior:
* Code can be altered and is recompiled on the fly.

## Actual behavior:
* The file is not editable.

## Notes:
* EnC is working fine in simple projects
* `ICSharpCode.Decompiler` uses `net461` and `netstandard2.0` as TFMs. While running `ILSpy.exe` the `net461` assembly is loaded by the debugger.

**Comment by Pilchie** [comment] 2017-10-26 19:50
Tagging @tmat.  Have you heard about this?  Does it belong on the Roslyn repo?

**Comment by jinujoseph** [comment] 2017-10-26 19:57
dupe of https://github.com/dotnet/roslyn/issues/21170

**Comment by Pilchie** [comment] 2017-10-26 19:59
Thanks @jinujoseph 

Duplicate of dotnet/roslyn#21170

**Closed by Pilchie** 2017-10-26 19:59 UTC
