### ISSUE TITLE
WPF Designer breaks with certain projects

### ISSUE THREAD

**Issue by clairernovotny** [dotnet/project-system#3634] opened 2018-06-08 00:09 UTC
Not sure what combination of things is tripping it up (may be the NuGet SDK resolver, but possibly something else). To be clear, this is with the CPS project system, enhanced with the MSBuild.Sdk.Extras.

To repro:
Clone: https://github.com/NuGetPackageExplorer/NuGetPackageExplorer
Build. Then open, any of the Xaml files in the NuGetPackageExplorer project (this was MainWindow.xaml).

![image](https://user-images.githubusercontent.com/1427284/41132352-b365ef28-6a8e-11e8-8825-afc799744618.png)

**Comment by davkean** [comment] 2020-01-27 23:51
Triage: @davidwengier Please investigate if this still occurs and send back to triage with the cause if it does.

**Comment by davidwengier** [comment] 2020-03-24 00:50
I can repro the above with MainWindow.cs, but it seems to be a problem with the XAML, or the editor, specifically [this line](https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/blob/236ad96855ed0913d6ccf4a51597c63dd8c91650/PackageExplorer/MainWindow.xaml#L139) has an issue around quotes. Changing it as per below unblocks the editor:

From:
```
<TextBlock Text="{Binding SelectedItem.Name, Mode=OneWay, FallbackValue='', StringFormat='Edit \'{0}\'', Converter={StaticResource StringShortenerConverter}, ConverterParameter=35}" />
```
to:
```
<TextBlock Text="{Binding SelectedItem.Name, Mode=OneWay, FallbackValue='', StringFormat='Edit &quot;{0}&quot;', Converter={StaticResource StringShortenerConverter}, ConverterParameter=35}" />
```

I couldn't repro with any other files, so I'm going to close this. If the above line is definitely correct XAML (sorry, I don't have enough experience with XAML to know) then I would suggest filing feedback through Visual Studio itself.

**Closed by davidwengier** 2020-03-24 00:50 UTC
Labels: Bug, Feature-XAML, Parity-Legacy-API, Parity-Legacy-Feature, Triage-Investigate
