### ISSUE TITLE
View in Object Browser doesn't show up for some references

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#1964] opened 2017-04-11 03:31 UTC
I cannot figure out the logic but View in Object Browser doesn't show up for some references:

![image](https://cloud.githubusercontent.com/assets/1103906/24891745/2507f994-1ebb-11e7-9d3d-a6f75968c373.png)

**Comment by abpiskunov** [comment] 2017-04-11 03:51
Dupe of existing issue, i added description there that we need to have our own command handler.

Thanks,
Anton

On Apr 10, 2017, at 8:31 PM, David Kean <notifications@github.com<mailto:notifications@github.com>> wrote:


I cannot figure out the logic but View in Object Browser doesn't show up for some references:

[image]<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcloud.githubusercontent.com%2Fassets%2F1103906%2F24891745%2F2507f994-1ebb-11e7-9d3d-a6f75968c373.png&data=02%7C01%7Canton.piskunov%40microsoft.com%7Ceadbc7bc132640526ecd08d4808b3cac%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636274782880422871&sdata=BCq5997Jm24hTM%2FU43%2Boj0y9F70y%2ByBZDez74eSPEOw%3D&reserved=0>

**Comment by abpiskunov** [comment] 2017-04-11 04:14
this is dupe of https://github.com/dotnet/project-system/issues/403 (root cause is the same - we need our own command handler and can't rely on default on from CPS, since it is tied to their References node)

**Closed by abpiskunov** 2017-04-11 04:14 UTC
