### ISSUE TITLE
Open the projects for the netstandard test apps,  error occurred while restoring NuGet packages. 

### ISSUE THREAD

**Issue by YunWeiaa** [dotnet/project-system#3945] opened 2018-09-05 03:00 UTC
### Steps to reproduce
Open the projects for the netstandard test apps below eg: [\\JOPEREZRZ240\tarekNS\NS16Test461\NS16Test461.csproj](\\JOPEREZRZ240\tarekNS\NS16Test461\NS16Test461.csproj) for the first one in the list below.
### Actual behavior
Error occurred while restoring NuGet packages: The operation failed as details for project NetStandard16Lib could not be loaded.
![net461](https://user-images.githubusercontent.com/33921754/45068028-34dbd400-b0f8-11e8-85c0-a43e61009e25.jpg)
### Expected behavior
Build and run. There should be no errors. 
### Test Environment:
**VS-Val\d15.8\products\28031.9000.licavalc.180831.132124**
dotnet --info:

> .NET Core SDK (reflecting any global.json):
>  Version:   2.1.402
>  Commit:    3599f217f4
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  10.0.17134
>  OS Platform: Windows
>  RID:         win10-x64
>  Base Path:   C:\Program Files\dotnet\sdk\2.1.402\
> 
> Host (useful for support):
>   Version: 2.1.4
>   Commit:  85255dde3e
> 
> .NET Core SDKs installed:
>   1.1.10 [C:\Program Files\dotnet\sdk]
>   2.1.202 [C:\Program Files\dotnet\sdk]
>   2.1.402 [C:\Program Files\dotnet\sdk]
> 
> .NET Core runtimes installed:
>   Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 1.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 1.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
> 
> To install additional .NET Core runtimes or SDKs:
>   https://aka.ms/dotnet-download

**Comment by joperezr** [comment] 2018-09-05 16:42
From looking at the prompt, it seems like the problem is that you may not have access to write to the share where the projects are. Could you try copying the projects locally and trying again?

**Comment by Pilchie** [comment] 2018-09-05 17:01
Please verify that this works if you copy locally.

**Comment by YunWeiaa** [comment] 2018-09-07 10:52
When I copy it locally, After running the msbuild command: `dotnet msbuild C:\Users\vseqa1\Documents\Test\NS16Test461\NS16Test461.csproj /t:restore /v:m /bl /flp:v=diag`, 
![msbuildcommand](https://user-images.githubusercontent.com/33921754/45214776-f861d100-b2cd-11e8-9401-01a41cf529dd.PNG)
Restore succeed, build failed with 15 errors as below:

![errors](https://user-images.githubusercontent.com/33921754/45215012-99e92280-b2ce-11e8-8bcf-a9dc19a4c56f.PNG)

[ErrorsInfo.txt](https://github.com/dotnet/project-system/files/2360699/ErrorsInfo.txt)

**Comment by joperezr** [comment] 2018-09-07 16:33
Could you try building each project individually like:
```
msbuild project.csproj /t:rebuild
```
And see if that succeeds? I saw in the past that Buidling in Visual studio wouldn't pass in a constant that is needed for building to work. In order to build all of the projects with one command, simply run the following on a developer command prompt from the root where you copied all of the projects:


```
for /f %x in ('dir /s /b *csproj') do msbuild %x /t:rebuild
```

**Comment by YunWeiaa** [comment] 2018-09-10 09:44
When I choose those workloads manually, restore and build succeeded with no errors.
![workloads](https://user-images.githubusercontent.com/33921754/45289518-f1ca9800-b51f-11e8-96b6-54376a7f6a71.PNG)
When I press "Ctrl + F5", it shows as below:
![cmd](https://user-images.githubusercontent.com/33921754/45289778-9b118e00-b520-11e8-94cf-527948bd3050.PNG)
```
Invalid paramters
GenNS.exe <NetStandard Assembly Full Path> <NS library CS file to generate> <Exe CS file to generate fot 4.6.1>
          <Exe CS file to generate fot 4.6.2> <Exe CS file to generate fot 4.7> <Exe CS file to generate fot 4.7.1>
          <Exe CS file to generate fot 4.7.2>
```
 I want to know how to run correctly each project. Thanks.

**Comment by joperezr** [comment] 2018-09-10 17:12
GenNS is not one of the projects that you need to test. The easiest way to run the tests once you are done restoring and building each project is to manually call each executable file that was generated without parameters. To find the list of all the executables you have to run, go to the top folder that contains all of these projects and call the following on a command prompt:
`dir /s /b *exe | findstr bin | findstr Test`

That should list about 10 executable files which are the ones you have to call.

**Comment by richaverma1** [comment] 2018-09-14 17:18
Not a product issue. Closing the bug.

**Closed by richaverma1** 2018-09-14 17:18 UTC
