### ISSUE TITLE
Add Assembly Information to set Author Name, Assembly name, or Description

### ISSUE THREAD

**Issue by mckennabarlow** [dotnet/project-system#8029] opened 2022-03-31 20:39 UTC
In the old property pages there was an Assembly Information dialog where you could set the Title, Description, Assembly name etc. This dialog seems to be missing from the new property pages and has popped up in a handful of feedback items.

<img width="760" alt="image" src="https://user-images.githubusercontent.com/28914569/161145385-992150bd-c0f6-4f4a-ae44-76a1efc1a52f.png">

**Comment by MiYanni** [comment] 2022-04-08 19:19
Duplicate of https://github.com/dotnet/project-system/issues/7246

While the dialog doesn't exist in the same form (separate pop-up), all the properties still exist. There was some investigation done on which properties should exist from these dialogs in the linked issue. Maybe some coordination or design is needed to surface these properties appropriately. Sync with me at some point, @mckennabarlow, and we can discuss what the current concerns from customers look like, and ideas on solutions.

Authors:
![image](https://user-images.githubusercontent.com/17788297/162509173-a6c51b48-1770-4206-8bc0-0457172027d5.png)

Assembly Name:
![image](https://user-images.githubusercontent.com/17788297/162509255-bd520569-3696-4360-8822-48e86215f027.png)

Description:
![image](https://user-images.githubusercontent.com/17788297/162509313-7c05e4bf-028c-49c9-ba03-63a8a4f37870.png)

**Closed by MiYanni** 2022-04-08 19:19 UTC
Labels: Feature Request, Triage-Investigate, Feature-Project-Properties-Designer
