### ISSUE TITLE
.dcproj won't accept azure functions project

### ISSUE THREAD

**Issue by sanderobdeijn** [dotnet/project-system#7317] opened 2021-06-13 15:47 UTC
**Visual Studio Version**: 16.10.1

**Summary**:
When adding an azure functions project to a docker-compose .dcproj file.
Vs studio gives an error when building in vs studio
CTC1031 Linux containers are not supported for Func project.

When building the dockercompose file from the commandline it works fine.
Is there some check or flag somewhere that controls this behavior?

**Steps to Reproduce**:

1. Create a .dcproj project
2. Create an azurefunctions docker project.
3. Add azurefunctions project to docker-compose file in dcproj project
4. Run dcproj project

**Expected Behavior**:

Run project without error

**Actual Behavior**:

Error: CTC1031 Linux containers are not supported for Func project.

**User Impact**:
Can't run function projects with .dcproj projects

**Comment by swesonga** [comment] 2021-06-22 17:38
Filed https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1346033

**Comment by drewnoakes** [comment] 2021-06-24 09:54
@sanderobdeijn thank you very much for taking the time to submit this feedback. The issue is not related to this repo. Saint has reported it internally, but unfortunately you cannot track that work item. If it's something you'd like to track, I suggest you file a feedback ticket on Developer Community so that you can be updated on status there. I'll close it here.

**Closed by drewnoakes** 2021-06-24 09:54 UTC
Labels: Area-External

**Comment by swesonga** [comment] 2021-06-24 17:34
cc @NCarlsonMSFT

**Comment by NCarlsonMSFT** [comment] 2021-06-24 17:37
@swesonga thanks for the ping, @sanderobdeijn this is already being tracked with https://github.com/microsoft/DockerTools/issues/124

**Comment by sanderobdeijn** [comment] 2021-06-24 18:21
Ok thank you.
