### ISSUE TITLE
COM references on the project-system repo don't use Name

### ISSUE THREAD

**Issue by arkalyanms** [dotnet/project-system#6573] opened 2020-09-02 21:24 UTC
**Visual Studio Version**: Version 16.8.0 Preview 3.0 [30431.218.main]
**Summary**: Only on the project-system repo the COM references get displayed with Identity instead of the Name.

**Steps to Reproduce**:
1. Right click a project -> Add COM Reference
2. Select a few COM references and Ok
3. Navigate to the COM references and notice the references are using guids.

**Expected Behavior**: Shows the friendly name of the references

**Actual Behavior**: Shows the Identity guid

**User Impact**: Makes removal or actions on the tree not possible. 
![COM](https://user-images.githubusercontent.com/60013978/92038252-f5b4dd80-ed27-11ea-95db-7d32462c1ef5.png)

**Comment by drewnoakes** [comment] 2020-09-03 01:57
Appears to be an issue with how these references are added:

```xml
  <ItemGroup>
    <COMReference Include="{1ea4dbf0-3c3b-11cf-810c-00aa00389b71}">
      <WrapperTool>tlbimp</WrapperTool>
      <VersionMinor>1</VersionMinor>
      <VersionMajor>1</VersionMajor>
      <Guid>1ea4dbf0-3c3b-11cf-810c-00aa00389b71</Guid>
    </COMReference>
    <COMReference Include="{714dd4f6-7676-4bde-925a-c2fec2073f36}">
      <WrapperTool>tlbimp</WrapperTool>
      <VersionMinor>0</VersionMinor>
      <VersionMajor>1</VersionMajor>
      <Guid>714dd4f6-7676-4bde-925a-c2fec2073f36</Guid>
    </COMReference>
    <COMReference Include="{c523f390-9c83-11d3-9094-00104bd0d535}">
      <WrapperTool>tlbimp</WrapperTool>
      <VersionMinor>0</VersionMinor>
      <VersionMajor>3</VersionMajor>
      <Guid>c523f390-9c83-11d3-9094-00104bd0d535</Guid>
    </COMReference>
  </ItemGroup>
```

Adding the same references to a new .NET Core Console app:

```xml

  <ItemGroup>
    <COMReference Include="Accessibility.dll">
      <WrapperTool>tlbimp</WrapperTool>
      <VersionMinor>1</VersionMinor>
      <VersionMajor>1</VersionMajor>
      <Guid>1ea4dbf0-3c3b-11cf-810c-00aa00389b71</Guid>
      <Lcid>0</Lcid>
      <Isolated>false</Isolated>
    </COMReference>
    <COMReference Include="AccessibilityCplAdminLib.dll">
      <WrapperTool>tlbimp</WrapperTool>
      <VersionMinor>0</VersionMinor>
      <VersionMajor>1</VersionMajor>
      <Guid>714dd4f6-7676-4bde-925a-c2fec2073f36</Guid>
      <Lcid>0</Lcid>
      <Isolated>false</Isolated>
    </COMReference>
    <COMReference Include="AcrobatAccessLib.dll">
      <WrapperTool>tlbimp</WrapperTool>
      <VersionMinor>0</VersionMinor>
      <VersionMajor>3</VersionMajor>
      <Guid>c523f390-9c83-11d3-9094-00104bd0d535</Guid>
      <Lcid>0</Lcid>
      <Isolated>false</Isolated>
    </COMReference>
  </ItemGroup>
```

---

In the project system solution, when adding those COM references we see N+1 failed design-time builds:

![image](https://user-images.githubusercontent.com/350947/92062562-60bfec00-eddc-11ea-81d5-7adcb782f616.png)

The failure is emitted by the `ResolveComReference` task:

> {1ea4dbf0-3c3b-11cf-810c-00aa00389b71} error MSB3299: The key file 'C:\Users\drnoakes\.nuget\packages\roslyntools.repotoolset\1.0.0-beta-62705-01\tools\35MSSharedLib1024.snk' does not contain a public/private key pair.

Building also gives the same error:

> {1ea4dbf0-3c3b-11cf-810c-00aa00389b71} : error MSB3299: The key file 'C:\Users\drnoakes\.nuget\packages\roslyntools.repotoolset\1.0.0-beta-62705-01\tools\35MSSharedLib1024.snk' does not contain a public/private key pair.

**Comment by davkean** [comment] 2020-09-03 02:02
Those are signing issues, I'm interested if these refs actually get resolved? Let's pretend that these are valid references, what name would we use for evaluation anyway? There is no better name than the GUID.

**Comment by davkean** [comment] 2020-09-03 02:05
In a standalone project they do get resolved and we use the resolved name:

![image](https://user-images.githubusercontent.com/1103906/92063098-a29d6200-eddd-11ea-8ea6-c4e8194e7745.png)

But at evaluation time we're going to use the GUID, there's no other name to use.

**Comment by davkean** [comment] 2020-09-03 02:23
@arkalyanms

> Makes removal or actions on the tree not possible.

What do you mean by this? VS happily removes this item. What other actions don't work?

I think its:

1) By design that we show the GUID in unresolved state. There is no name available for us to show, what should we show instead?

2) Probably a bug that VS added the GUID. How did you add the GUID?

**Comment by davkean** [comment] 2020-09-03 02:46
@drewnoakes Oh, I missed a comment, are you saying that the GUID repro only occurs in our code base?

**Comment by arkalyanms** [comment] 2020-09-03 17:46
> @drewnoakes Oh, I missed a comment, are you saying that the GUID repro only occurs in our code base?
Yes only on the project-system repo. Basic netcore is fine.

> * By design that we show the GUID in unresolved state. There is no name available for us to show, what should we show instead?
Can't we use the same friendly name already resolved in the reference manager dialog? I get that its all unresolved guids under typelib, but under the versions for each guid are various keys including a numeric that holds the typelib details. I believe the other project systems use this too. Perhaps can be frontloaded into CPS inside the provider context to avoid each context having to do the same(?).

> * Probably a bug that VS added the GUID in the Include. How did you add the reference?
Using the friendly name listed in the reference manager dialog's COM tab.

> What do you mean by this? VS happily removes this item. What other actions don't work?
The removal on context menu actions on that COM is rather difficult because the user has to now somehow map the friendly name based COM selection they made from the reference manager dialog to the guid in the tree.

**Comment by davkean** [comment] 2020-09-03 21:02
We can't provide the name, because we don't know what dll the reference resolves to. 

Add the following reference to legacy, and will see its behavior is identical.

``` XML
    <COMReference Include="{97D25DB0-0363-11CF-ABC4-02608C9E7554}">
      <Guid>{97D25DB0-0363-11CF-ABC4-02608C9E7554}</Guid>
      <VersionMajor>1</VersionMajor>
      <VersionMinor>0</VersionMinor>
      <Lcid>0</Lcid>
      <WrapperTool>tlbimp</WrapperTool>
      <Isolated>False</Isolated>
      <EmbedInteropTypes>True</EmbedInteropTypes>
    </COMReference>
```

The reason the GUID is inserted is because CPS itself failed to resolve the reference on Add. It seems that legacy handles this situation better on inserting of the reference, so if you'd like a better name inserted into Include the bug should be moved to CPS as they own inserting the reference.

**Comment by arkalyanms** [comment] 2020-09-03 21:21
Makes sense, We can consider this issue by designed and open/move this over to CPS then.

**Comment by davkean** [comment] 2020-09-04 05:14
Closing this out, @arkalyanms feel free to open a bug against CPS for the write.

**Closed by davkean** 2020-09-04 05:14 UTC
Labels: Resolution-External, Triage-No-Action
