### ISSUE TITLE
launchsettings.json commandLineArgs environment variable substitution behaviour change

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#9020] opened 2023-05-17 20:46 UTC
_This issue has a corresponding [ticket on Developer Community](https://developercommunity.visualstudio.com/t/launchsettingsjson-commandLineArgs-envi/1460955). Please vote and comment there to make sure your voice is heard._

---

_[severity:It's more difficult to complete my work]_

In non-sdk style projects the debug commandLineArgs could contain string of the form `"$(thing)"` which was passed to the application verbatim - In the sdk style system, inside VS, this string is interpreted as an msbuild-style environment variable expression which is passed to the application as `""`.

I can see the use in such a feature - but this behaviour wasn't present in the old system, and has made debugging certain applications quite convoluted, as there is no way to work around this.

Either reverting to the old behaviour, or providing a way to escape the expansion of msbuild style environment variables in launchsettings.json would be good.

**Comment by drewnoakes** [comment] 2023-05-18 11:02
Duplicate of #8906.

**Comment by MiYanni** [comment] 2023-05-18 23:10
Closing as duplicate.

**Closed by MiYanni** 2023-05-18 23:10 UTC
Labels: Resolution-Duplicate
