### ISSUE TITLE
Can't change 'Copy to Output Directory' in property pages

### ISSUE THREAD

**Issue by nguerrera** [dotnet/project-system#3152] opened 2018-01-16 23:30 UTC
## Version used
```
Microsoft Visual Studio Enterprise 2017 Int Preview (Dogfood)
Version 15.6.0 Preview 3.0 [27315.1.d15.6]
VisualStudio.15.IntPreview/15.6.0-pre.3.0+27315.1.d15.6
```

## Repro steps
* File -> New Project -> Console App (.NET Core)
* Right click project -> add -> new item -> text file
* Right click text file -> properties
* Change 'Copy to output directory' to 'Copy if newer' -> OK

![image](https://user-images.githubusercontent.com/75470/35017441-b7a44e86-fad1-11e7-8329-e5686fdeaf73.png)

## Expected result
Project is modified to set CopyToOutputDirectory=PreserveNewest metadata on TextFile1.txt.

Note that this works fine if you use the properties window (View -> Properties) , but not the property pages that show with above steps.

## Actual result
![image](https://user-images.githubusercontent.com/75470/35017361-60daa23a-fad1-11e7-9ae4-3744a2a2ec69.png)

**Comment by Pilchie** [comment] 2018-01-16 23:45
Dupe of https://github.com/dotnet/project-system/issues/2736 I think.  Use the VS properties Tool Window, instead of the modal properties dialog.

**Closed by Pilchie** 2018-01-16 23:45 UTC
