### ISSUE TITLE
Publish defaults to a Release configuration even under a bin Debug directory

### ISSUE THREAD

**Issue by davidmatson** [dotnet/project-system#5212] opened 2019-07-30 19:01 UTC
**Visual Studio Version**:
2019 (16.2.0)

**Summary**:
When publishing a .NET Core app for a new project, the default mismatches a Debug directory with a Release publish configuration.

**Steps to Reproduce**:

1. File -> New -> Project -> .NET Core exe

2. Right-click on the project in solution explorer and choose Publish. Don't change anything an click Publish. (The default folder is ```bin\Debug\netcoreapp2.2\publish\```.)

3. Examine the settings for the profile created.

**Expected Behavior**:
The directory and the profile's configuration match.

**Actual Behavior**:
The directory is Debug but the profile's configuration is Release.

**User Impact**:
Hard to understand Release publish bits in a Debug parent directory.

**Comment by vijayrkn** [comment] 2019-07-30 23:37
@davidmatson 

Just tried this scenario & I see release in the path. Does this issue reproduce consistently? Is there anything else that I need to do between step (1) & (2) ?

![image](https://user-images.githubusercontent.com/3981619/62172725-238b4f80-b2e8-11e9-942d-3a749eca6fd3.png)

**Comment by davidmatson** [comment] 2019-07-30 23:42
It might be dependent on what solution configuration is currently active in the IDE. I had the default of Debug active when I clicked Publish for the first time. I have seen in repro fairly consistently - at least across multiple projects.

**Comment by vijayrkn** [comment] 2019-07-30 23:57
I tried creating a few projects. I have debug selected. May be it is a timing issue. Let me try with multiple projects to see if I can get a repro. 

![image](https://user-images.githubusercontent.com/3981619/62173466-060bb500-b2eb-11e9-9ca8-636eada56047.png)

**Comment by vijayrkn** [comment] 2019-07-31 00:01
I can reproduce with existing projects. If I open a solution with multiple projects and try it, then it does bring up the path with wrong configuration. I will take a look. Thanks for reporting this. 

![image](https://user-images.githubusercontent.com/3981619/62173668-b5488c00-b2eb-11e9-815a-46d5c4d5ad1c.png)

**Comment by vijayrkn** [comment] 2019-07-31 00:43
@davidmatson - Looks like some kind of a configuration initialization issue. If you switch your solution configuration once and switch it back, then it works reliably every time until you re-open VS.  Also, it seems to occur only on project open and not on project create.

**Comment by vijayrkn** [comment] 2019-08-02 01:33
We were able to identify the issue. This happens when the release configuration is not loaded by the project system. In this case, publish falls back to the available configuration (which is debug in this case) to identify the PublishDir Path. 

We will get this fixed in an upcoming VS release. Thank you for reporting this. 

/cc @davkean

**Comment by davidmatson** [comment] 2019-08-02 17:05
Sounds great. Thanks, Vijay!

**Comment by davkean** [comment] 2020-01-20 23:07
Closing in lieu @vijayrkn's comment above.

**Closed by davkean** 2020-01-20 23:07 UTC
