### ISSUE TITLE
VS 2017 'Generate package on build' ignores 'Package version' field

### ISSUE THREAD

**Issue by menaheme** [dotnet/project-system#4693] opened 2019-04-04 07:48 UTC
**Visual Studio Version**: 15.9.0

**Summary:**
VS 2017 'Generate package on build' ignores 'Package version' field

**Steps to Reproduce**:

1. open project properties -> package -> tick 'Generate Nuget Package on build'

2. set a 3 part version in the Package version field

3. save and build.

example:

![package_prop_page](https://user-images.githubusercontent.com/5694495/55538364-f37bc900-56c6-11e9-92f4-05a8465b6450.png)

and the resulting package:

![build_result](https://user-images.githubusercontent.com/5694495/55538363-f37bc900-56c6-11e9-911d-78282786bc0a.png)

**Expected Behavior**: version of generated package is as specified in package version filed.

**Actual Behavior**: version of generated package is 1.0.0

**User Impact**: cannot use vs package building feature of VS.

**Comment by drewnoakes** [comment] 2019-05-22 06:13
I cannot reproduce this in VS2019 (16.1.0).

Changed via the UI:

![image](https://user-images.githubusercontent.com/350947/58151131-1d577200-7cac-11e9-8f7d-3d7c4e9c0fde.png)

Produces project file:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Version>3.2.1</Version>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

</Project>
```

Building gives:

```text
1>------ Build started: Project: Issue4693GeneratedPackageVersion, Configuration: Debug Any CPU ------
1>Issue4693GeneratedPackageVersion -> ...\Issue4693GeneratedPackageVersion\bin\Debug\netstandard2.0\Issue4693GeneratedPackageVersion.dll
1>Successfully created package '...\Issue4693GeneratedPackageVersion\bin\Debug\Issue4693GeneratedPackageVersion.3.2.1.nupkg'.
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
```

Please retry this in VS2019. If you still see the problem could you include more information about your project structure?

I'll close this for now.

**Closed by drewnoakes** 2019-05-22 06:13 UTC
