### ISSUE TITLE
After adding SharedProject to core project and opening Add Reference dialog again, SharedProject is not checked there

### ISSUE THREAD

**Issue by abpiskunov** [dotnet/project-system#1391] opened 2017-01-31 21:38 UTC
1. Create a core class library
2. add a SharedProject to solution
3. Add reference to SharedProject for class library
4. Wait for restore 
5. Open Add Reference dialog again 
 
Actual Result: SharedProject is not checked 
 
Expected: Shared project to be checked there in dialog

**Comment by abpiskunov** [comment] 2017-01-31 21:38
Per Mohit C. commets:

This mail doesn’t have the full description of the RM + Shared project issue; I am guessing you are describing a problem where an added Shared project reference is not showing up as checked in the dialog.

It’s the project systems that inform the Reference Manager about the items that are already referenced, RM does not read the project file directly.
You can set a BP here and that would tell you why the already referenced Shared projects are not being marked for this type of project.

https://devdiv.visualstudio.com/DevDiv/_git/VS?path=%2Fsrc%2Fvsproject%2FReferenceManager%2FProviders%2FProviderImpls%2FSharedProjectProvider%2FSharedProjectReferenceProvider.cs&version=GBlab%2Fd15prerel&_a=contents&line=260&lineStyle=plain&lineEnd=260&lineStartColumn=22&lineEndColumn=44

**Comment by RaulPerez1** [comment] 2017-01-31 21:45
Is this not related to #954?

**Comment by abpiskunov** [comment] 2017-01-31 21:47
no, #954 just displaying data and it is unrelated to add reference dialog

**Comment by RaulPerez1** [comment] 2017-01-31 21:53
It shouldn't have been, when I opened it everything (including this scenario) was busted. I think it's fine to have a separate bug if we have multiple root causes though, I was curious because the repro you have above is exactly what I was doing when I opened that one.

**Comment by abpiskunov** [comment] 2017-01-31 21:54
yes repros are the same, but code paths are completely different. #954 i am fixing right now and on my machine it is working already :)

**Comment by abpiskunov** [comment] 2017-02-01 01:45
Same happens when you Browse for assembly reference and add it to project , then re-open Add Reference dialog - check box for assembly would not be checked.

**Comment by drewnoakes** [comment] 2019-01-23 19:43
From [VSFeedback](https://developercommunity.visualstudio.com/content/problem/130875/console-net-core-2-app-still-not-showing-reference.html) | [508624](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/508624)

Repro Steps:
- Create a .NET Core Console app and a Shared Project. 
- Reference the shared project from the .NET Core console app.
- Open Add References dialog again.

Expected
Shared project is checked

Actual 
Shared project is unchecked

![image](https://user-images.githubusercontent.com/7732033/31873724-e861756c-b779-11e7-855f-8d629e633f59.png)

**Comment by drewnoakes** [comment] 2019-01-23 19:44
:link: also reported at https://developercommunity.visualstudio.com/content/problem/328798/cannot-remove-a-shared-project-reference-from-net.html

**Comment by etbyrd** [comment] 2019-03-19 17:31
This is a CPS issue - it does not register shared projects correctly. Closing as a duplicate of https://devdiv.visualstudio.com/DevDiv/_workitems/edit/792775

**Closed by etbyrd** 2019-03-19 17:31 UTC
Labels: Bug

**Comment by davkean** [comment] 2020-01-17 03:31
This was fixed in https://github.com/dotnet/project-system/pull/5805.
