### ISSUE TITLE
error  : The project file cannot be opened by the project system, because it is missing some critical imports or the referenced SDK cannot be found.

### ISSUE THREAD

**Issue by smoothdeveloper** [dotnet/project-system#8372] opened 2022-07-13 11:47 UTC
(edit: intended for dotnet/project-system project, my mistake)

When I face this error in Visual Studio (2019 or 2022): 

> error : The project file cannot be opened by the project system, because it is missing some critical imports or the referenced SDK cannot be found.

I have no idea how to troubleshoot it and I'd expect the project to remain useable in VS rather than showing hard stop to end user.

Right now, even removing the global.json from the repository of my solution doesn't solve the issue in VS2022, while the same solution works in VS2019.

Building through Jetbrains Rider works fine.

### Further technical details

```
C:\Windows\System32>dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.302
 Commit:    c857713418

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22598
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.302\

global.json file:
  Not found

Host:
  Version:      6.0.7
  Architecture: x64
  Commit:       0ec02c8c96

.NET SDKs installed:
  3.1.421 [C:\Program Files\dotnet\sdk]
  5.0.401 [C:\Program Files\dotnet\sdk]
  5.0.404 [C:\Program Files\dotnet\sdk]
  5.0.410 [C:\Program Files\dotnet\sdk]
  6.0.100 [C:\Program Files\dotnet\sdk]
  6.0.104 [C:\Program Files\dotnet\sdk]
  6.0.300 [C:\Program Files\dotnet\sdk]
  6.0.302 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.27 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.27 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info
```

- vs 2022 17.2.6
- vs 2019 16.11.17

**Comment by drewnoakes** [comment] 2022-08-01 01:46
@smoothdeveloper can you share the contents of your `.csproj` file? That should help narrow down where this issue is coming from. You can redact any company/product/person names if you prefer. 

Another option would be to use the "Report a problem" feature in VS and record a trace. Be sure to open the project in order to trigger the failure during that recording. Doing that will create a ticket that shares diagnostic information privately with Microsoft, allowing us to diagnose, triage and potentially fix any issue here.

See https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio for more info.

**Comment by kvenkatrajan** [comment] 2022-08-16 21:57
@smoothdeveloper , checking in - have you had a chance to create a feedback ticket item for this request? Please share the contents of the csproj file in there if possible.

**Comment by TalhaBhayat** [comment] 2022-08-18 09:03
I have the same weird error which suddenly started happening.

My csproj file:

`<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <RootNamespace>Volume.WebApi</RootNamespace>
        <AssemblyName>Volume.WebApi</AssemblyName>
        <Nullable>enable</Nullable>
        <IsPackable>true</IsPackable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>efad71c6-743c-4b87-9de8-f26d77146f6d</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Application\Application.csproj" />
        <ProjectReference Include="..\Infrastructure\Infrastructure.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="FluentValidation.AspNetCore" Version="10.3.4" />
        <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="6.0.8" />
        <PackageReference Include="Microsoft.AspNetCore.SpaProxy" Version="6.0.8" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="6.0.8">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" Version="6.0.8" />
        <PackageReference Include="Microsoft.Identity.Web" Version="1.25.1" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="6.3.1" />
    </ItemGroup>

    <PropertyGroup>
        <RunPostBuildEvent>OnBuildSuccess</RunPostBuildEvent>
    </PropertyGroup>
</Project>
`

**Comment by TalhaBhayat** [comment] 2022-08-18 09:09
I had updated some of the references above to use 6.0.8 but my installed version of .net core was 6.0.3. Having upgraded, my project now loads.

**Comment by smoothdeveloper** [comment] 2022-08-18 09:19
@kvenkatrajan sorry for the delay in response and thanks for the prompt; I haven't figured out what is wrong yet (and have to use Rider which doesn't face the issue).

Here is one .csproj file:

```xml
<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Library</OutputType>
    <AssemblyOriginatorKeyFile>..\..\..\..\Tools\Signing\uplan_signing.snk</AssemblyOriginatorKeyFile>
    <OutputPath>..\..\..\..\Bin\$(Configuration)\</OutputPath>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <DocumentationFile>$(OutputPath)\$(AssemblyName).xml</DocumentationFile>
    <NoWarn>1591</NoWarn>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
	  <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="lcg.Common.FrameworkExtensions">
      <HintPath>..\..\..\..\Lib\lcg.Shared\net48\lcg.Common.FrameworkExtensions.dll</HintPath>
    </Reference>
    <Reference Include="microsoft.visualbasic" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\..\..\..\BuildTools\uplancodebuild\AssemblyInfoVersion.cs">
      <Link>Properties/AssemblyInfoVersion.cs</Link>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\declarations\classlibraries\lcg.Uplan.Declarations\lcg.Uplan.Declarations.csproj" />
    <ProjectReference Include="..\..\..\declarations\classlibraries\uplan.declarations\uplan.declarations.fsproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\..\..\..\Tools\Signing\uplan_signing.snk">
      <Link>uplan_signing.snk</Link>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Advanced\AdvancedScreenParameters.cs" />
    <Compile Remove="Transmission\CapacityRatingTemperaturesDbCommandProvider.cs" />
  </ItemGroup>
  <Import Project="..\..\..\..\..\.paket\Paket.Restore.targets" />
</Project>
```

the paket.dependencies (which does similar as nuget package reference) looks like this:

```
Castle.Core 
log4net
 System.Data.DataSetExtensions
```

It doesn't reproduce on another machine with same Visual Studio and dotnet sdk installed, and I tried to uninstall all SDK and reinstall Visual Studio, to no avail.

I think the first measure to help me troubleshoot would be to highlight where the error message is generated, from the SDK msbuild targets file, and how I could surface the actual things being checked to embed some diagnostic info in the message.

The error message seems too generic, if the SDK can improve it with that diagnostic info, I think it would help, there are many people facing this message based on online search.

**Comment by tmeschter** [comment] 2022-08-18 17:00
@smoothdeveloper Does the project build correctly on the command line?

**Comment by kvenkatrajan** [comment] 2022-08-18 17:39
@smoothdeveloper, thanks for sharing your csproj file details. Unfortunately there is not enough information for us to narrow down the issue at this point. Next steps -

1. Please confirm @tmeschter question on whether its working via command line
2. Send diagnostic information via "Report a problem" suggested by @drewnoakes. Refer to instructions at: https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio
3. Provide original content of global.json file
4. Provide details on the nuget reference package versions
5. Repo project would be great (not mandatory) - please attach to the VS feedback ticket created in step 2

Thanks in advance!

**Comment by smoothdeveloper** [comment] 2022-08-22 15:53
@kvenkatrajan, @tmeschter

1. I get the expected output (builds) out of invoking `msbuild` from dev command prompt.
2. I sent the trace https://developercommunity.visualstudio.com/t/error--:-The-project-file-cannot-be-ope/10124635?entry=problem
3. ```json
    {
      "sdk": {
         "version": "6.0.302",
         "rollForward": "feature"
      }
    }
    ```
4. Castle.Core (2.5.2)
    log4net (2.0.10)
    System.Data.DataSetExtensions (4.5)
5. I can only reproduce it in this large solution, but I attached all the items generated with the "Report a problem" tool to the VS Feedback ticket

Could anyone highlight where the message stem from so I can try to hack around it to surface more details?

Thanks

**Comment by kvenkatrajan** [comment] 2022-08-22 23:47
@smoothdeveloper , we have received your ticket and trace information - thank you! @ocalles is currently reviewing and will get back to you as soon as we have next steps.

**Comment by kvenkatrajan** [comment] 2022-08-25 17:31
@smoothdeveloper please have a look at the feedback ticket: https://developercommunity.visualstudio.com/t/error--:-The-project-file-cannot-be-ope/10124635?entry=problem for instructions to upload binlogs for further troubleshooting. Thanks for your continued patience

CC: @ocalles

**Comment by drewnoakes** [comment] 2022-09-12 10:38
Taking another look after my vacation. Thanks for the .csproj file, it looks like there's nothing fancy going on with the SDK import.

@smoothdeveloper did you see the comments from @TalhaBhayat:

> I had updated some of the references above to use 6.0.8 but my installed version of .net core was 6.0.3. Having upgraded, my project now loads.

What versions of the .NET SDK do you have installed on your machine? You can check via `dotnet --list-sdks`.

Your `global.json` file is pinning the SDK version. Does the project load if you delete the `global.json` file altogether?

**Comment by drewnoakes** [comment] 2022-09-12 10:41
Chatted with @smoothdeveloper on Twitter who explained that this no longer reproduces on their system. Will close this out as I don't see any actionable information here. If someone encounters this in future, please comment here and provide as much info as possible so we can investigate it again. Thanks.

**Closed by drewnoakes** 2022-09-12 10:41 UTC
Labels: Triage-Investigate

**Comment by drewnoakes** [comment] 2022-09-12 10:45
Searching for error _The project file cannot be opened by the project system, because it is missing some critical imports or the referenced SDK cannot be found_ online, it seems one cause of this can be putting MSBuild assemblies in the GAC. This is not recommended!
