### ISSUE TITLE
Assertion failed in Dependencies.DependenciesTreeViewProvider.CreateOrUpdateNode

### ISSUE THREAD

**Issue by tmat** [dotnet/project-system#5459] opened 2019-09-10 16:17 UTC
**Visual Studio Version**:
![image](https://user-images.githubusercontent.com/41759/64631334-b91c0380-d3ab-11e9-9d65-93850a450b5e.png)

**Summary**:
```
Recoverable
Microsoft.Assumes+InternalErrorException: An internal error occurred. Please contact Microsoft Support.
   at Microsoft.Assumes.Fail(String message)
   at Microsoft.VisualStudio.ProjectSystem.VS.Tree.Dependencies.DependenciesTreeViewProvider.CreateOrUpdateNode(IProjectTree node, IDependencyViewModel viewModel, IRule browseObjectProperties, Boolean isProjectItem, Nullable`1 additionalFlags, Nullable`1 excludedFlags)
   at Microsoft.VisualStudio.ProjectSystem.VS.Tree.Dependencies.DependenciesTreeViewProvider.<>c__DisplayClass6_0.<<BuildTreeAsync>g__BuildMultiTargetTreeAsync|2>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Tree.Dependencies.DependenciesTreeViewProvider.<BuildTreeAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Tree.Dependencies.DependenciesProjectTreeProvider.<>c__DisplayClass20_0.<<OnDependenciesSnapshotChangedAsync>g__UpdateTreeAsync|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.ProjectTreeProviderBase.TreeUpdateSubmission.<UpdateTree>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.VisualStudio.ProjectSystem.CoreProjectTreeProviderBase.<>c__DisplayClass76_1.<<Initialize>b__2>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.CoreProjectTreeProviderBase.<>c__DisplayClass78_0.<<SubmitTreeUpdateCoreAsync>g__waitOnTask|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Tree.Dependencies.DependenciesProjectTreeProvider.<OnDependenciesSnapshotChangedAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Rethrow(Exception ex)
   at Microsoft.VisualStudio.ProjectSystem.ProjectErrorReporting.<>c__DisplayClass6_0.<SubmitErrorReport>b__0()
   at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>c__DisplayClass2_0.<Guard>g__action|0()
   at GuardMethodClass.GuardMethod(Func`1 , Func`2 , Func`2 )
```

**Steps to Reproduce**:

Open Roslyn.sln

**Expected Behavior**:

**Actual Behavior**:
![image](https://user-images.githubusercontent.com/41759/64631356-c933e300-d3ab-11e9-945f-1010324c23be.png)

**Comment by drewnoakes** [comment] 2019-09-10 23:19
Duplicate of #5454 which is fixed, pending release.

**Closed by drewnoakes** 2019-09-10 23:19 UTC
