### ISSUE TITLE
Manage nuget dependencies does not appear on the nuget node

### ISSUE THREAD

**Issue by jmarolf** [dotnet/project-system#1968] opened 2017-04-11 15:57 UTC
Cannot add nuget package from nuget node
![image](https://cloud.githubusercontent.com/assets/9797472/24918303/cdade22e-1e94-11e7-8922-d4ed4947e553.png)

But can from dependencies node
![image](https://cloud.githubusercontent.com/assets/9797472/24918323/daab9214-1e94-11e7-918a-8315cb749449.png)

**Comment by abpiskunov** [comment] 2017-04-11 18:50
dupe of https://github.com/dotnet/project-system/issues/1945

**Closed by abpiskunov** 2017-04-11 18:50 UTC
