### ISSUE TITLE
Launch Profile UI hangs/timesout when adding new profile to mixed-language solution

### ISSUE THREAD

**Issue by alwu-msft** [dotnet/project-system#7393] opened 2021-07-08 01:25 UTC
**Visual Studio Version**: 
17.0.0 Preview 3.0 [31507.28.main] (Dev17.IntPreview)

**Summary**: 
If a solution contains both a .NET 5/6 project and a C++ project and the user uses the Launch Profile UI to add a new launch profile to the .NET project, VS will hang for several seconds and then display a message box with an exception stack. The same hang also occurs if duplicating or deleting an existing profile.

**Steps to Reproduce**:
Min repro solution: [WpfApp2.zip](https://github.com/dotnet/project-system/files/6780805/WpfApp2.zip)

1. Create an empty solution.
2. Add New Project > WPF Application (.NET 5 or 6)
3. Add New Project > C++ Windows Desktop Application
4. Right-click on the WPF application project in Solution Explorer and select "Properties" from the context menu
5. Go to the "Debug" page and open the Launch Profiles UI
6. Click on "Create a new profile" and choose any of the options

**Expected Behavior**: 
New launch profile is created and VS remains responsive throughout the process

**Actual Behavior**: 
VS hangs for several seconds before displaying a message box with the below text. The profile does ultimately get created, however.

```
---------------------------

---------------------------
System.TimeoutException: The operation has timed out.

   at Microsoft.VisualStudio.Threading.TplExtensions.<WithTimeout>d__5.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Microsoft.VisualStudio.Threading.TplExtensions.<WithTimeout>d__6`1.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.PropertyPages.Designer.LaunchProfileSubscription.<CaptureAddedProfileAsync>d__31.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.PropertyPages.Designer.LaunchProfileSubscription.<AddLaunchProfileAsync>d__23.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.PropertyPages.Designer.LaunchProfilesWindowViewModel.<>c__DisplayClass2_2.<<-ctor>b__5>d.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()

   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.PropertyPages.Designer.LaunchProfilesWindowViewModel.<>c__DisplayClass2_0.<.ctor>b__0(LaunchProfileKind kind)

   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.PropertyPages.Designer.DelegateCommand`1.Execute(Object parameter)
---------------------------
OK   
---------------------------
```

**User Impact**:
Doesn't affect functionality per se (the launch profile is ultimate created/deleted and works as expected), but leads to a bad user experience. This issue also sent me down a rabbit hole to rule out the possibility that it was the extension I was working that was somehow causing the hang. :)

**Comment by drewnoakes** [comment] 2021-07-08 02:35
Thanks very much for the report.

This is a timeout while we wait for the added profile to be made available to the client (in `CaptureAddedProfileAsync`).

The fact that it doesn't appear suggests this is an issue in the back end. @tmeschter does anything jump out at you here?

**Comment by tmeschter** [comment] 2021-07-08 16:19
This sounds very similar to an internal bug where something similar happens when you have .NET Framework project instead of a C++ project.

Wild speculation:
1. The back end is re-executing the query after the change
2. Some part of executing the query involves getting information for the C++ project
3. That information can only be obtained by running code on the UI thread
4. The modal dialog box is (unintentionally) blocking the code from running on the UI thread

**Comment by tmeschter** [comment] 2021-08-05 22:22
@drewnoakes My best guess at this moment is that the issue is caused by the time out itself. Considering this code:

``` csharp
private async Task<LaunchProfileViewModel> CaptureAddedProfileAsync(Func<Task> action)
{
    var tcs = this.whenLaunchProfileAdded = new TaskCompletionSource<LaunchProfileViewModel>(TaskCreationOptions.RunContinuationsAsynchronously);

    await action();

    return await tcs.Task.WithTimeout(CaptureReplyTimeout);
}
```

The `await action();` completes quickly, and then we get stuck on `return await tcs.Task.WithTimeout(CaptureReplyTimeout);`.

Meanwhile, our implementation of `IObserver.OnNext` doesn't get called at all until right after the timeout occurs, which is why the `this.whenLaunchProfileAdded` `TaskCompletionSource` is never completed.

I wonder if maybe the `Task` produced by the `TaskCompletionSource` doesn't play nicely with JTF?

**Comment by tmeschter** [comment] 2021-08-09 21:14
Per our email thread, I think the right thing to do here is to pull the newly added launch profile off the project after the update query has executed, rather than waiting for the subscription to push the updates. This would require changes on both the CPS and dotnet/project-system sides. dotnet/project-system is already adding the new launch profile entity to the project entity, but it isn't including the child entities (i.e. the categories and properties). I'll take care of that.

**Comment by tmeschter** [comment] 2021-08-30 23:05
The last piece of the fix for this went into [CPS 347250](https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/347250).

**Closed** 2021-08-30 23:05 UTC
Labels: Bug, Feature-Debugging, Triage-Approved, Must-Have

**Comment by alwu-msft** [comment] 2021-08-30 23:31
Awesome, thanks!
