### ISSUE TITLE
Perf: Prevent double design time build during loading solution

### ISSUE THREAD

**Issue by lifengl** [dotnet/project-system#2939] opened 2017-11-06 19:22 UTC
Register dataflow earlier and link rule subscriptions to DataflowBlock.NullTarget<T>().  Reduce double build can reduce overall DT build time a lot during the solution loading phase.

**Comment by Pilchie** [comment] 2017-11-06 22:11
Is this a duplicate of #2594

cc @davkean

**Comment by Pilchie** [comment] 2017-12-22 21:10
Closing as a dupe - let me know if it's not.

**Closed by Pilchie** 2017-12-22 21:10 UTC
Labels: Bug, Performance
