### ISSUE TITLE
Building a new enlistment fails

### ISSUE THREAD

**Issue by jcouv** [dotnet/project-system#2331] opened 2017-05-30 23:15 UTC
I cloned the repo, then ran `build.cmd` from a VS2017 command prompt and got the failures below.

![image](https://cloud.githubusercontent.com/assets/12466233/26608927/0fd46d78-4553-11e7-8f76-df61203b2d8c.png)

@srivatsn for assistance.
@OmarTawfik in case you've encountered this.

**Comment by davkean** [comment] 2017-05-30 23:18
@emgarten How would this be possible? What builds would not have the "Restore" target?

**Comment by davkean** [comment] 2017-05-30 23:20
@jcouv Can you run the following from the VS command prompt and attach the results?
```
msbuild /pp src\Microsoft.VisualStudio.ProjectSystem.Managed\Microsoft.VisualStudio.ProjectSystem.Managed.csproj > build.pp
```

**Comment by jcouv** [comment] 2017-05-31 02:07
Attached output from `msbuild /pp`: [pp.txt](https://github.com/dotnet/project-system/files/1040126/pp.txt)

**Comment by davkean** [comment] 2017-05-31 03:40
Here's the relevant portion:

```
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.targets\ImportAfter\*" Condition="'$(ImportByWildcardAfterMicrosoftCommonTargets)' == 'true' and exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.targets\ImportAfter')">

C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\MSBuild\15.0\Microsoft.Common.targets\ImportAfter\Microsoft.NuGet.ImportAfter.targets
============================================================================================================================================
-->
  <!--
***********************************************************************************************
Microsoft.NuGet.ImportAfter.targets

WARNING:  DO NOT MODIFY this file unless you are knowledgeable about MSBuild and have
          created a backup copy.  Incorrect changes to this file will make it
          impossible to load or build your projects from the command-line or the IDE.

Copyright (c) .NET Foundation. All rights reserved. 
***********************************************************************************************
-->
  <PropertyGroup xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <NuGetTargets Condition="'$(NuGetTargets)'==''">$(MSBuildExtensionsPath)\Microsoft\NuGet\$(VisualStudioVersion)\Microsoft.NuGet.targets</NuGetTargets>
  </PropertyGroup>
  <!--<Import Project="$(NuGetTargets)" Condition="Exists('$(NuGetTargets)') and '$(SkipImportNuGetBuildTargets)' != 'true'" />-->
  <!-- Import NuGet.targets for Restore -->
  <PropertyGroup xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <NuGetRestoreTargets Condition="'$(NuGetRestoreTargets)'==''">$(MSBuildExtensionsPath)\..\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets</NuGetRestoreTargets>
  </PropertyGroup>
  <!--<Import Project="$(NuGetRestoreTargets)" Condition="Exists('$(NuGetRestoreTargets)')" />--> <!-- This means that is wasn't imported
  <!--
============================================================================================================================================
  </Import>
```

Basically looks like the location $(MSBuildExtensionsPath)\..\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets cannot be found.

Can you see if NuGet.targets exists any under Visual Studio directory in program files?

**Comment by emgarten** [comment] 2017-05-31 04:52
I would also be interested to know what workloads are installed in VS 2017. I haven't seen any issues around NuGet missing in the past, but it could be possible.

**Comment by srivatsn** [comment] 2017-05-31 05:01
@natidea mentioned running into this today as well. I wonder if this is some recent regression

**Comment by davkean** [comment] 2017-05-31 05:10
@jcouv Can you run the following:

```
msbuild /v:d src\Microsoft.VisualStudio.ProjectSystem.Managed\Microsoft.VisualStudio.ProjectSystem.Managed.csproj > build.log
```

And attach that? Perhaps MSBuildExtensionsPath is resolving to a different path? I do find it strange that NuGet is walking outside of the extensions path to find it's target - so if MSBuild move themselves they are broken.

**Comment by jcouv** [comment] 2017-05-31 07:05
Attached new pp file: [build.txt](https://github.com/dotnet/project-system/files/1040487/build.txt)

Dave and I troubleshooted on Skype. The `NuGet.targets` file was under `C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\Common7\IDE\Extensions\5y0bse3d.tbd` which seemed to be the problem (the sub-folder has a random name and it's under Extensions instead of CommonExtensions).

**Comment by davkean** [comment] 2017-05-31 07:06
This issue was moved to NuGet/Home#5300

**Closed by davkean** 2017-05-31 07:06 UTC
