### ISSUE TITLE
Build events properties aren't roundtripping

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#1879] opened 2017-03-28 23:21 UTC
1. Create a new project
2. Right-click on project and choose Properties
3. Click Build Events
4. In pre-build, enter echo $(ProjectDir)
5. Save 
6. Close properties
7. Open properties

Expected: `echo $(ProjectDir)`
Actual: `echo `

We shouldn't be evaluating these when we read them.

**Comment by davkean** [comment] 2017-03-28 23:22
Similar to: https://github.com/dotnet/roslyn-project-system/issues/1569 but separate, we shouldn't be using the evaluated versions of these properties.

**Comment by dev-nextprogress** [comment] 2017-04-10 00:50
In my case I noticed it's not only evaluating these 'macros' but swallowing a bunch of them. In my post-build script I am trying to pass $(SolutionName) $(SolutionDir) $(ConfigurationName) $(PlatformName) $(ProjectDir) $(ProjectPath) $(ProjectName) $(TargetDir) $(TargetName) and after re-opening the properties it only shows the values of $(SolutionName) $(SolutionDir). The rest of them have disappeared and they also don't seem to be passed to the script I am invoking. The .csproj file sill looks correct though. This is breaking all my components that I intended to migrate to .NET Standard. Showstopper now. Thanks

**Comment by davkean** [comment] 2017-04-10 00:52
@dev-nextprogress Your issue is a mix of this bug and https://github.com/dotnet/project-system/issues/1569.

**Comment by dev-nextprogress** [comment] 2017-04-10 01:02
Yep, noticed that. Wish I could help. Love what you guys do. Many thanks for your work !

**Comment by srivatsn** [comment] 2017-04-25 08:35
Another report here -https://developercommunity.visualstudio.com/content/problem/43837/post-build-displays-old-value.html

**Comment by CD-UNCC** [comment] 2017-06-07 14:52
help

**Comment by jmarolf** [comment] 2017-06-13 03:01
fixed with https://github.com/dotnet/project-system/pull/2367

**Closed** 2017-06-20 19:18 UTC
Labels: Bug, Urgency-Soon

**Comment by StingyJack** [comment] 2019-01-22 15:38
This is happening to me in VS 15.9.5. Every time I save a pre-build event (`call attrib -R "$(ProjectDir)wwwroot\dist\*.*"`) its removing the values I've typed into the window.

**Comment by jmarolf** [comment] 2019-01-22 18:23
@StingyJack 	can you file a new issue with repo steps?

When create a new ASP.NET core project and add this entry to the prebuild events
![image](https://user-images.githubusercontent.com/9797472/51556636-998d9600-1e2f-11e9-8f94-5a0a11b8d34a.png)

they get persisted to the project like so:

```XML
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>
  </PropertyGroup>

  <Target Name="PreBuild" BeforeTargets="PreBuildEvent">
    <Exec Command="call attrib -R &quot;$(ProjectDir)wwwroot\dist\*.*&quot;" />
  </Target>

</Project>
```

**Comment by StingyJack** [comment] 2019-01-24 11:47
@jmarolf - this is an existing netfx SDK style csproj that I've recently inherited. I could add the command to the pre-build event (and use the macro editor to do it) but as soon as I tried to build or save all, the pre-build event text would disappear.  I had to manually add the `<Target>` to make the event work.

**Comment by Pilchie** [comment] 2019-01-24 16:13
@davkean is this related to https://github.com/dotnet/project-system/issues/3641?

**Comment by sebagomez** [comment] 2019-03-19 01:35
I'm facing this issue with a .net standard 2.0 project library with VS 15.9.9

**Comment by jmarolf** [comment] 2019-03-19 10:36
@sebagomez 	can you open a new issue with a repro project? At this point I think a new issue would be the best way to get traction here.

**Comment by StingyJack** [comment] 2019-03-19 10:50
@jmarolf - Another issue is going to be _one more thing to manage_ for you, and there are already a lot (too many, imo) of issues MSFT has on their plate, so I dont quite get it. It also causes a bit of history loss/disconnect and missed identification of a regression.

**Comment by jmarolf** [comment] 2019-03-19 10:59
@StingyJack 	you are welcome to also post a repo here. My assumption is that the problems some people are having is not exactly this bug but I'll need a repro to determine that.

**Comment by TahirAhmadov** [comment] 2020-08-20 19:37
I'm not sure if this is the right place. Pre-build and post-build macros evaluate to empty.

Microsoft Visual Studio Enterprise 2019
Version 16.6.0

**Comment by krypt-lynx** [comment] 2021-09-02 05:43
Microsoft Visual Studio Community 2019
Version 16.11.2
The issue is there for .net standard 2.1 class library project.

**Comment by drewnoakes** [comment] 2021-09-03 03:06
This issue has been addressed in VS2022 as part of the new Project Properties UI.

**Comment by StingyJack** [comment] 2021-09-03 04:06
> new Project Properties UI

![image](https://user-images.githubusercontent.com/15381181/131948882-28863148-8420-46ae-80bf-54fb8441a2cb.png)

=D

**Comment by Tragen** [comment] 2022-05-03 22:14
> This issue has been addressed in VS2022 as part of the new Project Properties UI.

I have the some problem with VS2022 Enterprise 17.1.6 and a VB.NET SDK format project.
Targetdir is stripped out and also in the xml file, the variable is removed.

How it it solved?

**Comment by Tragen** [comment] 2022-05-05 09:28
Btw, we use multi target for .NET 4.6.2 and .NET 5.0 and .NET 6.0.

**Comment by drewnoakes** [comment] 2022-05-05 09:29
@Tragen we are working on VB support right now. Once they are running on the new Project Properties UI, they will round trip correctly. The Application Designer for VB projects has quite a few more features than for C# projects, and we weren't able to migrate all of them in the initial release. We are making good progress on the work though.

**Comment by Tragen** [comment] 2022-05-05 09:30
Is there a timeframe or a quick solution for now?

**Comment by drewnoakes** [comment] 2022-05-05 09:34
The workaround is to edit the `.vbproj` file manually.

You could also try adding this to your project and re-opening the editor, but I'm not sure it'll work so please try carefully and at your own risk!

```xml
<ItemGroup>
  <ProjectCapability Include="ProjectPropertiesEditor" />
</ItemGroup>
```

**Comment by drewnoakes** [comment] 2022-05-05 09:36
We generally don't commit to timeframes for features, but it's being worked on now and we're currently working on 17.3. We really want to make sure the VB experience is as capable in the new version as in the old version before turning it on by default.

**Comment by gxrxrdx** [comment] 2024-06-13 17:56
them problem still there, VS community Version 17.10.1    variables are removed from the Post-build event command line textbox when saving the changes.
How come the ticket is closed?
