### ISSUE TITLE
VS 15.6.0 freezes when trying to load an F# project that worked in 15.5.7

### ISSUE THREAD

**Issue by loop-evgeny** [dotnet/project-system#3349] opened 2018-03-06 19:06 UTC
I just upgraded from 15.5.7 to 15.6.0. When loading a particular solution containing 12 C# and 2 F# projects VS freezes while the following dialog is shown:

> Loading solution projects
> 
> Loading project 3 of 14: FSharpModules

("FSharpModules" is the name of an F# project).

Deleting the .vs directory did not help, but deleting the bin and obj directories for that project allowed the rest of the solution to load. That project still fails to load, however, and an error dialog is shown:

> ---------------------------
> Microsoft Visual Studio
> ---------------------------
> The project system has encountered an error.
> 
> An item with the same key has already been added.
> 
> A diagnostic log has been written to the following location: "C:\Temp\User\VsProjectFault_62cc9d63-f6d6-4407-8a51-0f488d4d7384.failure.txt".
> 
> ---------------------------
> OK   
> ---------------------------

Log file attached: [VsProjectFault_62cc9d63-f6d6-4407-8a51-0f488d4d7384.failure.txt](https://github.com/dotnet/project-system/files/1786328/VsProjectFault_62cc9d63-f6d6-4407-8a51-0f488d4d7384.failure.txt)

The project is unloaded and if I try to load it from the context menu VS freezes again. It also freezes if I restore the deleted bin and obj directories (I took a backup), so this is 100% reproducible on that project. (I am able to load other F# projects.) The problematic project worked immediately before upgrading and in earlier VS versions.

**Comment by loop-evgeny** [comment] 2018-03-06 19:10
How do I downgrade to VS 15.5.7 now? I need to open this project to do my work.

**Comment by Pilchie** [comment] 2018-03-06 19:50
@loop-evgeny based on the stack in the fault, this looks like https://github.com/Microsoft/visualfsharp/issues/4300.  You should be able to work-around by removing a `<None Include` from your F# project for whatever item is already covered by the default globs covering everything in the project directory.

**Comment by Pilchie** [comment] 2018-03-06 20:02
Putting in 15.7, but we're also considering for 15.6 servicing.

**Comment by loop-evgeny** [comment] 2018-03-06 21:08
@Pilchie There is no `<None Include` item in the project. The project file looks like this:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <FSharpCoreImplicitPackageVersion>4.3.*</FSharpCoreImplicitPackageVersion>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="SomeSourceFile.fs" />
	... more .fs source files ...
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CoreCompat.System.Drawing.v2" Version="5.2.0-preview1-r131" />
    <PackageReference Include="FSharp.Collections.ParallelSeq" Version="1.1.0" />
    <PackageReference Include="MathNet.Numerics" Version="4.1.0" />
    <PackageReference Include="MathNet.Numerics.FSharp" Version="4.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CSharpProject\CSharpProject.csproj" />
    <ProjectReference Include="..\AnotherCSharpProject\AnotherCSharpProject.csproj" />
    <ProjectReference Include="..\FSharpProject\FSharpProject.fsproj" />
	... 3 more C# project references ...
  </ItemGroup>

</Project>
```

**Comment by Pilchie** [comment] 2018-03-06 21:12
Any chance you have the same filename listed multiple times in that `Compile` ItemGroup?

**Comment by loop-evgeny** [comment] 2018-03-06 22:05
Yes! Removing the duplicate fixed the problem. Thank you!

**Comment by Pilchie** [comment] 2018-03-06 22:15
Glad to hear it.  I'm going to close this as a dupe of Microsoft/visualfsharp#4300 then.

**Closed by Pilchie** 2018-03-06 22:15 UTC
Labels: Area-F#, Bug, Tenet-Reliability, Urgency-Now

**Comment by davkean** [comment] 2018-03-06 22:32
Or rather a dupe of https://github.com/dotnet/project-system/issues/3218, that other one looks like a tracking bug?
