### ISSUE TITLE
ConfiguredProjectReadyToBuild throws ArgumentNullException if project is unloaded immediately after open

### ISSUE THREAD

**Issue by jviau** [dotnet/project-system#2437] opened 2017-06-13 23:18 UTC
You can repro this by having these two exports:

``` CSharp
    [Export(typeof(IVetoProjectLoad))]
    [AppliesTo(ProjectCapabilities.Cps)]
    internal class AlwaysVeto : IVetoProjectLoad
    {
        public Task<bool> AllowProjectLoadAsync(bool isNewProject, CancellationToken cancellationToken = default(CancellationToken))
        {
            return Task.FromResult(false);
        }
    }

    private class InitializeProjectBuildRule
    {
        [Import]
        private IProjectSubscriptionService SubscriptionService { get; set; }

        [ConfiguredProjectAutoLoad]
        [AppliesTo(ProjectCapabilities.Cps)]
        private void Initialize()
        {
            var actionBlock = new ActionBlock<IProjectVersionedValue<IProjectSubscriptionUpdate>>(@in => { });
            IProjectSubscriptionService subscriptionService = this.SubscriptionService;
            subscriptionService.ProjectBuildRuleSource.SourceBlock.LinkTo(actionBlock, new DataflowLinkOptions { PropagateCompletion = true });
        }
    }
```

You will receive the following exception opening any .netcore project

```
System.AggregateException: Project system data flow 'ProjectBuildSnapshotService Outer 11246' closed because of an exception: System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: projectConfiguration2
   at Microsoft.Requires.NotNull[T](T value, String parameterName)
   at Microsoft.VisualStudio.ProjectSystem.ProjectConfigurationExtensions.EqualIgnoringTargetFramework(ProjectConfiguration projectConfiguration1, ProjectConfiguration projectConfiguration2)
   at Microsoft.VisualStudio.ProjectSystem.LanguageServices.ConfiguredProjectReadyToBuild.GetLatestActivationTask()
   at Microsoft.VisualStudio.ProjectSystem.LanguageServices.ConfiguredProjectReadyToBuild.<WaitReadyToBuildAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.VisualStudio.ProjectSystem.Designers.ProjectBuildSnapshotService.<UpdateSnapshotCoreAsync>d__36.MoveNext() in E:\Repos\CPS\src\Microsoft.VisualStudio.ProjectSystem.Implementation\Designers\ProjectBuildSnapshotService.cs:line 340
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.VisualStudio.ProjectSystem.Designers.CustomizableBlockSubscriberBase`3.<UpdateSnapshotAsync>d__28.MoveNext() in E:\Repos\CPS\src\Microsoft.VisualStudio.ProjectSystem.Implementation\Designers\CustomizableBlockSubscriberBase.cs:line 233
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.VisualStudio.ProjectSystem.Designers.CustomizableBlockSubscriberBase`3.<>c__DisplayClass27_0.<<Initialize>b__1>d.MoveNext() in E:\Repos\CPS\src\Microsoft.VisualStudio.ProjectSystem.Implementation\Designers\CustomizableBlockSubscriberBase.cs:line 169
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.<JoinAsync>d__78.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask`1.<JoinAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.VisualStudio.ProjectSystem.Designers.CustomizableBlockSubscriberBase`3.<<Initialize>b__27_0>d.MoveNext() in E:\Repos\CPS\src\Microsoft.VisualStudio.ProjectSystem.Implementation\Designers\CustomizableBlockSubscriberBase.cs:line 166
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.VisualStudio.ProjectSystem.DataflowExtensions.<>c__DisplayClass24_0`2.<<CreateSelfFilteringTransformBlock>b__0>d.MoveNext() in E:\Repos\CPS\src\Microsoft.VisualStudio.ProjectSystem\Utilities\Extensions\DataflowExtensions.cs:line 709
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
```

`_activeConfiguredProjectProvider.ActiveProjectConfiguration` in `ConfiguredProjectReadyToBuild` can become `null` when the project is closing, so it needs to guard against that.

**Comment by davkean** [comment] 2017-06-14 00:47
👍

**Comment by davkean** [comment] 2017-11-10 06:01
Dupe of https://github.com/dotnet/project-system/issues/2895, have a PR out.

**Comment by davkean** [comment] 2017-11-10 21:15
Fixed in https://github.com/dotnet/project-system/issues/2437.

**Closed by davkean** 2017-11-10 21:15 UTC
Labels: Bug, Up for Grabs
