### ISSUE TITLE
Property page shows empty target framework for .NET Standard Class Library projects

### ISSUE THREAD

**Issue by davidfowl** [dotnet/project-system#782] opened 2016-11-21 05:28 UTC
![image](https://cloud.githubusercontent.com/assets/95136/20471631/47e296ee-af68-11e6-8225-132f1f32aa0d.png)

**Comment by davkean** [comment] 2016-11-21 05:32
Yeah, we're fixing this along with net core app, right @srivatsn @jinujoseph ?

**Comment by davkean** [comment] 2016-11-21 05:53
@davidfowl That screen was taken on a Surface, right? (I see layout issues)

**Comment by davidfowl** [comment] 2016-11-21 06:00
MacOS in a Parallels VM

**Comment by jinujoseph** [comment] 2016-11-21 07:34
yes , tracked along with #589

**Comment by srivatsn** [comment] 2016-11-21 19:57
Dupe of #582

**Comment by robauer** [comment] 2018-10-04 18:59
I'm still seeing this:

![image](https://user-images.githubusercontent.com/7127264/46496394-8ce02600-c7dd-11e8-9a8d-718c0dfc9584.png)

**Comment by etbyrd** [comment] 2018-10-04 19:07
Looking at this.

**Comment by robauer** [comment] 2018-10-09 18:35
So does this mean this will be addressed in v16.0 of Visual Studio? When is that coming out? My customers can't wait that long...

**Comment by etbyrd** [comment] 2018-11-22 00:32
This is not a Project System issue - this is how Xamarin has configured their projects. As far as I can tell, Xamarin iOS projects don't expose a Target Framework, so there is nothing to show in the Application property page for iOS projects. I also noticed that on the the Application property page for Android projects, the Target Framework is replaced with "Compile using Android version: (Target Framework)" that lets you choose the Android SDK, and they expose that with TargetFrameworkVersion.

I am not sure if showing the Target Framework drop down in this case is a blocking issue for you, but if it is, I would recommend using Visual Studio's "Report a Problem" tool to route it to Xamarin.

**Closed by etbyrd** 2018-11-22 00:32 UTC

**Comment by baoshenyi** [comment] 2019-05-10 16:35
![Moq4 10 1](https://user-images.githubusercontent.com/9803653/57542517-2e4cce80-730f-11e9-9c7a-fd2f6aa2fe7c.png)

This happened on https://github.com/moq/moq4/releases/tag/v4.10.1 please download and give it try.

Thanks,

Shenyi

**Comment by davkean** [comment] 2019-05-13 21:26
@baoshenyi This is being tracked by: https://github.com/dotnet/project-system/issues/3024.
