### ISSUE TITLE
code-len features does not work after closing and reopening .sln

### ISSUE THREAD

**Issue by MiaomiaoHuangfu** [dotnet/project-system#2816] opened 2017-09-12 08:18 UTC
- Create a .net core project (console, class lib, mstest, xunit or web), restore succeeded, code-len features work well;
- File --> Close Solution and reopen it;

**Expected Result:** code-len features work well.
**Actual Result:** code-len features do not work.
![code-lensnotwork](https://user-images.githubusercontent.com/22901391/30314847-9d27d470-97d4-11e7-8841-4cd4cbab023c.PNG)

Tested on d15rel.26911.00
dotnet --info
 ```
.NET Command Line Tools (2.0.2-vspre-006949)

Product Information:
 Version:            2.0.2-vspre-006949
 Commit SHA-1 hash:  23fc6ec23d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x86
 Base Path:   C:\Program Files\dotnet\sdk\2.0.2-vspre-006949\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

**Comment by davkean** [comment] 2017-09-12 08:22
@MiaomiaoHuangfu Is this a regression?

**Comment by MiaomiaoHuangfu** [comment] 2017-09-12 08:35
Yeah, it seems a regression issue.

**Comment by davkean** [comment] 2017-09-12 08:37
From which release?

**Comment by MiaomiaoHuangfu** [comment] 2017-09-12 08:44
the bug repro on d15rel.26911.00.
code-len features work well before this build (d15rel.26908.01).

**Comment by davkean** [comment] 2017-09-12 09:01
@basoundr Can you have a quick look here? If you don't have time, tell me and I'll find someone else.

**Comment by basoundr** [comment] 2017-09-12 17:14
Yes, I am able to repro the regression. After the initial Solution close, Code lens is not working for any of the solution(using the new project system) thats opened after.

**Comment by Pilchie** [comment] 2017-09-12 17:19
Does it repro in the old project system? It could be a roslyn regression instead.

Also take a look at what exceptions are thrown, it could be a difference in events between the old/new project systems causing issues in the Roslyn workspace.

**Comment by basoundr** [comment] 2017-09-12 17:40
It does not happen in the old project system. This is only with the new project system. which is why looking at the recent changes might also help since Codelens was working 3 days before

**Comment by basoundr** [comment] 2017-09-12 18:00
Between 26908.01 and 26911.00, only CPS has made a change and no Roslyn change.

**Comment by basoundr** [comment] 2017-09-12 20:32
Confirmed that the bug has been introduced by CPS with the recent change to cache the Project Guid. Looping in @adrianvmsft

**Comment by basoundr** [comment] 2017-09-12 20:38
I am not able to assign the issue over to @adrianvmsft. Maybe because he is not part of dotnet org?

**Comment by adrianvmsft** [comment] 2017-09-12 20:39
I am investigating... that side effect is really unexpected

**Comment by basoundr** [comment] 2017-09-12 22:49
Opened a [bug in VSO](https://devdiv.visualstudio.com/DevDiv/_workitems?id=493875) to track this issue. Hence closing this issue.

**Closed by basoundr** 2017-09-12 22:49 UTC
Labels: Bug
