### ISSUE TITLE
VS Hangs / Takes a long time to close projects

### ISSUE THREAD

**Issue by cdmihai** [dotnet/project-system#1835] opened 2017-03-23 18:00 UTC
Repro steps:

1. Load the MSBuild solution: https://github.com/Microsoft/msbuild/blob/master/src/MSBuild.sln
2. Via an external editor change 3-4 csprojes (add new compile items (also create them on disk), etc)
3. Go back to VS. Hit yes to reload all

=> Vs hangs on unloading projects

Dump: `\\fsu\shares\MsEng\MSBuild\micodoba\vsdumps\unload_hang\devenv.DMP`

**Comment by cdmihai** [comment] 2017-04-14 16:54
Another one: "\\fsu\shares\MsEng\MSBuild\micodoba\vsdumps\unload_hang\devenv2.DMP"

**Comment by tannergooding** [comment] 2017-06-22 17:05
I'm no longer seeing this repro on the latest internal builds.

**Comment by srivatsn** [comment] 2017-06-26 16:13
I'll close this out. @cdmihai - if you still see this with 15.3 builds let us know.

**Closed by srivatsn** 2017-06-26 16:13 UTC
Labels: Bug

**Comment by davkean** [comment] 2017-06-27 00:05
Did we look at the dumps?

**Comment by davkean** [comment] 2017-06-27 01:19
This is the stack for the second dump:
```
>	ntdll.dll!7786231c()	Unknown
 	[Frames below may be incorrect and/or missing, no symbols loaded for ntdll.dll]	
 	WindowsBase.ni.dll!65f0a15c()	Unknown
 	WindowsBase.ni.dll!65f0a15c()	Unknown
 	[Managed to Native Transition]	
 	WindowsBase.dll!MS.Win32.UnsafeNativeMethods.WaitForMultipleObjectsEx(int nCount, System.IntPtr[] pHandles, bool bWaitAll, int dwMilliseconds, bool bAlertable)	Unknown
 	WindowsBase.dll!System.Windows.Threading.DispatcherSynchronizationContext.Wait(System.IntPtr[] waitHandles, bool waitAll, int millisecondsTimeout)	Unknown
 	mscorlib.dll!System.Threading.SynchronizationContext.InvokeWaitMethodHelper(System.Threading.SynchronizationContext syncContext, System.IntPtr[] waitHandles, bool waitAll, int millisecondsTimeout)	Unknown
 	[Native to Managed Transition]	
 	mscorlib.ni.dll!729e80b7()	Unknown
 	[Managed to Native Transition]	
 	mscorlib.dll!System.Threading.Monitor.Wait(object obj, int millisecondsTimeout, bool exitContext)	Unknown
 	mscorlib.dll!System.Threading.SemaphoreSlim.WaitUntilCountOrTimeout(int millisecondsTimeout, uint startTime, System.Threading.CancellationToken cancellationToken)	Unknown
 	mscorlib.dll!System.Threading.SemaphoreSlim.Wait(int millisecondsTimeout, System.Threading.CancellationToken cancellationToken)	Unknown
 	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.Workspace.OnDocumentContextUpdated(Microsoft.CodeAnalysis.DocumentId documentId, Microsoft.CodeAnalysis.Text.SourceTextContainer container)	Unknown
 	Microsoft.VisualStudio.LanguageServices.dll!Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.DocumentProvider.OnHierarchyChanged(uint docCookie, Microsoft.VisualStudio.Shell.Interop.IVsHierarchy pHierOld, uint itemidOld, Microsoft.VisualStudio.Shell.Interop.IVsHierarchy pHierNew, uint itemidNew, bool itemidChanged)	Unknown
 	Microsoft.VisualStudio.LanguageServices.dll!Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.DocumentProvider.OnAfterAttributeChangeEx(uint docCookie, uint grfAttribs, Microsoft.VisualStudio.Shell.Interop.IVsHierarchy pHierOld, uint itemidOld, string pszMkDocumentOld, Microsoft.VisualStudio.Shell.Interop.IVsHierarchy pHierNew, uint itemidNew, string pszMkDocumentNew)	Unknown
 	Microsoft.VisualStudio.LanguageServices.dll!Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.DocumentProvider.RunningDocTableEventsSink.OnAfterAttributeChangeEx(uint docCookie, uint grfAttribs, Microsoft.VisualStudio.Shell.Interop.IVsHierarchy pHierOld, uint itemidOld, string pszMkDocumentOld, Microsoft.VisualStudio.Shell.Interop.IVsHierarchy pHierNew, uint itemidNew, string pszMkDocumentNew)	Unknown
 	[Native to Managed Transition]	
 	msenv.dll!0f7f4caf()	Unknown
 	msenv.dll!0f8179a9()	Unknown
 	msenv.dll!0f817a56()	Unknown
 	msenv.dll!0fa4e81f()	Unknown
 	msenv.dll!0fa4e3cd()	Unknown
 	csproj.dll!1c591f1d()	Unknown
 	[Managed to Native Transition]	
 	Microsoft.VisualStudio.LanguageServices.dll!Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.SetDocumentContext(Microsoft.CodeAnalysis.DocumentId documentId)	Unknown
 	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.Workspace.ClearOpenDocument(Microsoft.CodeAnalysis.DocumentId documentId, bool isSolutionClosing)	Unknown
 	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.Workspace.ClearOpenDocuments(Microsoft.CodeAnalysis.ProjectId projectId)	Unknown
 	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.Workspace.ClearProjectData(Microsoft.CodeAnalysis.ProjectId projectId)	Unknown
 	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.Workspace.OnProjectRemoved(Microsoft.CodeAnalysis.ProjectId projectId)	Unknown
 	Microsoft.VisualStudio.LanguageServices.dll!Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.VisualStudioWorkspaceHost.Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.IVisualStudioWorkspaceHost.OnProjectRemoved(Microsoft.CodeAnalysis.ProjectId projectId)	Unknown
 	Microsoft.VisualStudio.LanguageServices.dll!Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioProjectTracker.RemoveProject(Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.AbstractProject project)	Unknown
 	Microsoft.VisualStudio.LanguageServices.dll!Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.AbstractProject.Disconnect()	Unknown
 	Microsoft.VisualStudio.LanguageServices.CSharp.dll!Microsoft.VisualStudio.LanguageServices.CSharp.ProjectSystemShim.CSharpProjectShimWithServices.Disconnect()	Unknown
```

Which is a duplicate of: https://github.com/dotnet/roslyn/issues/17305.
