### ISSUE TITLE
Project system does not respect conditional compile

### ISSUE THREAD

**Issue by jmarolf** [dotnet/project-system#3234] opened 2018-02-09 20:43 UTC
1. **Use:** https://github.com/SolutionsDesign/Algorithmia
2. Open the main csproj in vs 2017 15.5 (I used 15.5.5) in xml editor. 
3. [This line](https://github.com/SolutionsDesign/Algorithmia/blob/master/SD.Tools.Algorithmia/SD.Tools.Algorithmia.csproj#L21) doesn't do anything

**NOTE:**  intellisense says 'these are your options', but picking 'Exclude' will make the project not loadable, and the valid option 'Remove' isn't in the list. 
![image](https://user-images.githubusercontent.com/9797472/36049119-85e7b8c4-0d96-11e8-8304-eef2d9af82c7.png)

**Comment by jmarolf** [comment] 2018-02-09 22:33
**Additional Note:** need to add conditional compilation `#ifdefs` to that file to exclude the code for netstandard and make it compile on netstandard (as it's for .netfull). So it's easy to test the conditional doesn't work.

**Comment by Pilchie** [comment] 2018-02-13 01:19
@davkean - do you know what the expectation is here?

**Comment by davkean** [comment] 2018-02-13 01:32
@jmarolf Can you expand on what "Project system does not respect conditional compile" means? It's passed the compiler? It shows up in the tree?

I expect it not to be passed to the compiler for netstandard2.0, but for it to show up in the tree under "None".

**Comment by FransBouma** [comment] 2018-02-13 08:05
I was the one reporting this issue, and this morning I look again at the screenshot and I see I made a mistake there, it should be $(TargetFramework)=="net452", not netstandard20. OMG I spent hours on this, and it's such a stupid PEBKAC error. I'll verify this and close it asap if it's indeed the error I think it is!

**Comment by FransBouma** [comment] 2018-02-13 08:11
Ok, I'll try again, as my previous message was an error. (It's early).

@davkean The conditional compilation for netstandard2.0 should make the compiler *not* compile that file (and the other files in the folder, but this is for testing), as those files contain references to .NET full types and it's for .net452, not for netstandard.

However the compiler compiles that piece of code. I had to add #if defs in the file to make it not compile the code in the file for netstandard2.0. You can try it yourself in the repo linked in the startpost, and remove the #if !NETSTANDARD2_0 ifdef in the file: it will compile the file for netstandard2.0 giving a compile error. 

Interestingly I have a (not OSS) library where I do the same thing and there it works OK, I tried to check whether I made a typo somewhere but the xml is the same.

**Comment by davkean** [comment] 2018-02-13 12:27
The path is wrong, it's currently:

``` XML
<Compile Remove="PropertyEditing\PropertyBag.cs"/>
```

but it needs to be:

``` XML
<Compile Remove="GeneralDataStructures\PropertyEditing\PropertyBag.cs"/>
```

**Comment by FransBouma** [comment] 2018-02-13 21:08
@davkean crap, that's a serious blunder on my part. Sorry for wasting your time on this, I'll fix this! 

The intellisense issue is what's left now (the one in the screenshot), the conditional compilation issue is solved.

**Comment by davkean** [comment] 2018-02-13 21:15
I see the following in 15.6 builds:

![image](https://user-images.githubusercontent.com/1103906/36174066-31a1a9ec-115f-11e8-8a8b-64a81ef3f5e9.png)

@rainersigwald Was Remove doc'd between 15.5 -> 15.6?

**Comment by rainersigwald** [comment] 2018-02-13 21:19
It appears to have been there with that string for years: https://github.com/Microsoft/msbuild/blame/e9b4e08f9470b795ddfcc441010da72d747d63f5/src/MSBuild/Microsoft.Build.Core.xsd#L437-L441

**Comment by davkean** [comment] 2018-02-13 21:26
Maybe not on the separate type:

``` XML
     <!-- note this allows Remove or no attribute instead of Include, which is too lax outside of Targets at present, but 
            it's the best we can reasonably do with an XSD -->
```

I have no idea what this would be.

**Comment by FransBouma** [comment] 2018-02-14 08:53
@davkean 
> @FransBouma what locale is your Windows set to?
"United States" says System Info, tho regional settings for numbers etc. is set to "Dutch". Windows itself is en-US, keyboard too. 
MSBuild version is `Microsoft (R) Build Engine version 15.5.180.51428 for .NET Framework` when running msbuild in the vs2017 command prompt. 
Is there more info I need to dig up or change to see whether that affects anything?

The folder name changed fixed the Compile Remove command in csproj, it now works properly. I was wondering though why msbuild doesn't spawn a warning because the folder wasn't found? It would saved me a lot of time. ;)

**Comment by davkean** [comment] 2018-02-14 22:02
>  I was wondering though why msbuild doesn't spawn a warning because the folder wasn't found? 
Due to language design, which ends up being leaky abstraction here. There's no requirement that Remove actually refers to an item that exists, let alone a folder/file.

Let me seeing whether your IntelliSense issue is caused by: https://github.com/Microsoft/msbuild/issues/2723.

**Comment by Pilchie** [comment] 2018-02-20 18:36
@davkean any update here?  Is this still an issue for this repo?

**Comment by davkean** [comment] 2018-02-20 22:24
I was unable to repro the IntelliSense issue. What's interesting is that it skips any attribute that is new for 4.0 - perhaps they are represented differently? I'll close it in lieu of #2723 and add info there.

**Closed by davkean** 2018-02-20 22:24 UTC
Labels: Area-New-Project-System, Bug, Feature - Multi-Targeting
