### ISSUE TITLE
MSBuild properties are not resolved in launchsettings.json anymore

### ISSUE THREAD

**Issue by TFTomSun** [dotnet/project-system#8218] opened 2022-06-02 13:44 UTC
## Visual Studio Version
VS 17.3

## Summary
In the past it was possible to use msbuild properties in the launchsettings.json. For example:

```json
{
  "profiles": {
    "MyApp.Net": {
      "commandName": "Project",
      "launchBrowser": true,
      "launchUrl": "$(MyLaunchUrl)",
      "environmentVariables": {
        "USENONMINIMIZEDJS": "$(UseNotMinimizedJs)",
        "NOCACHE": "$(NoCache)",
        "ASPNETCORE_ENVIRONMENT": "Development"
      },
      "applicationUrl": "https://localhost:5001;http://localhost:5000"
    },
  }
}
```

## Expected Behavior
The msbuild properties MyLaunchUrl, UseNotMinimizedJs and NoCache gets resolved during build and their values are passed correctly to the running app.

## Actual Behavior
The variables don't get resolved anymore. Instead e.g. "$(MyLaunchUrl)" is passed as the final value.

Is there any new way to configure the values of the launchsettings.json through msbuild properties?

**Comment by drewnoakes** [comment] 2022-06-05 23:22
@TFTomSun what build are you seeing this in? I believe it was a point-in-time bug falling out of work to restore the environment variable editing experience in the UI, and that bug has since been fixed.

I cannot reproduce it in the latest (internal) build 17.3.0 Preview 3.0 [32604.83.main]:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <MyProp>Hello, World!</MyProp>
  </PropertyGroup>

</Project>
```

```json
{
  "profiles": {
    "ConsoleApp1": {
      "commandName": "Project",
      "commandLineArgs": "\"$(MyProp)\""
    }
  }
}
```

```c#
Console.WriteLine(string.Join(", ", args));
```

Writes:

```
Hello, World!
```

I'm going to close this as I believe the bug has been fixed.

**Closed by drewnoakes** 2022-06-05 23:22 UTC
Labels: Triage-Approved

**Comment by TFTomSun** [comment] 2022-06-07 06:00
I was able to reproduce the issue with this version:
![image](https://user-images.githubusercontent.com/5387192/172306653-af63c512-6eb6-4fba-b078-f22e3b21e7d3.png)

@drewnoakes  Did you try to configure the LaunchUrl of a AspNet Application as well?
