### ISSUE TITLE
Changing output type results in two properties being persisted into the project file

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#1298] opened 2017-01-23 03:46 UTC
1. File -> New Console App (.NET Core)
2. Properties -> Output type -> Library

Expected:
``` XML
    <OutputType>library</OutputType>
    <TargetFramework>netcoreapp1.0</TargetFramework>
    <OutputTypeEx>library</OutputTypeEx>
```

Actual:
``` XML
    <OutputType>library</OutputType>
    <TargetFramework>netcoreapp1.0</TargetFramework>
```

**Comment by RaulPerez1** [comment] 2017-03-08 22:54
Should be fixed once #1709 is implemented.

**Comment by basoundr** [comment] 2017-03-28 16:56
Fixing #1709 did not fix this issue. Reopening

**Comment by RaulPerez1** [comment] 2017-03-28 19:40
@basoundr This is due to the fact that you still have OutputTypeEx on the rules. You opened another issue to track removing that right? It will be the same root cause.

**Comment by basoundr** [comment] 2017-03-28 19:42
Yes, removal of OutputTypeEx should fix this. There is another bug where the Property was added under Configuration condition, I will look into this along with that. Maybe everything will get fixed if I just remove the property altogether.

**Comment by RaulPerez1** [comment] 2017-03-28 19:45
I just replied to that one as well. I had a fix for it which I cancelled. I linked the commit with those changes to that issue.

**Comment by srivatsn** [comment] 2017-05-19 16:52
Fixed by https://github.com/dotnet/project-system/pull/2221

**Closed by srivatsn** 2017-05-19 16:52 UTC
Labels: Bug
