### ISSUE TITLE
Some project settings show per-target UI when they shouldn't

### ISSUE THREAD

**Issue by BretJohnson** [dotnet/project-system#8043] opened 2022-04-06 06:28 UTC
## Visual Studio Version
Latest Int Preview (32404.430.main)

## Summary
Some project settings show per-target UI, when the values don't actually vary by target.

## Steps to Reproduce

1. Do File / New Project / MAUI, to create a project that uses multitargeting
2. Bring up the project settings UI

## Expected Behavior

Settings should list targets by default, only when the user explicitly chooses to have different settings for different targets

## Actual Behavior

The targets show for some properties, when values are the name. I see this for the 3 properties below, all under Build / Advanced.

![image](https://user-images.githubusercontent.com/245892/161908334-77a6378a-9f8b-4a14-9f30-417afe95085b.png)
![image](https://user-images.githubusercontent.com/245892/161908368-05de6a93-cc49-4c0e-bf59-aa224397fc8d.png)
![image](https://user-images.githubusercontent.com/245892/161908398-38962ce4-417d-430d-be65-7054f599e5d6.png)

And I also see it for some of the iOS properties. But note that the iOS properties really should just show for iOS only (https://github.com/dotnet/project-system/issues/7873).

![image](https://user-images.githubusercontent.com/245892/161908941-2af62239-83ab-40f0-b854-b9ec85a77d13.png)
![image](https://user-images.githubusercontent.com/245892/161908964-18d6d328-8dad-40f9-b867-3dc8b47d899e.png)
![image](https://user-images.githubusercontent.com/245892/161908993-0bb7e3fc-0ea2-4c47-b35e-16cda9a3c7fa.png)

Also, possibly related: https://github.com/dotnet/project-system/issues/8042

## User Impact

Users can be confused, especially because this is the default behavior.

**Comment by adamint** [comment] 2022-05-18 03:45
This is a duplicate of #7886

**Comment by adamint** [comment] 2022-05-23 19:52
PR tracked in https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/400622

**Closed** 2022-06-27 23:37 UTC
Labels: Triage-Approved, Feature-Project-Properties-Designer
