### ISSUE TITLE
"Command line arguments" should be a multi-line text box

### ISSUE THREAD

**Issue by tmeschter** [dotnet/project-system#7332] opened 2021-06-18 18:54 UTC
Previous property pages:

![image](https://user-images.githubusercontent.com/10506730/122605124-de7f7c00-d02b-11eb-8ea9-93aed7be3d42.png)

Current Launch Profiles UI:

![image](https://user-images.githubusercontent.com/10506730/122605150-e808e400-d02b-11eb-9cd3-ded26f367091.png)

Due to the length of command line arguments, we should make this a multi-line text box again.

**Comment by drewnoakes** [comment] 2021-06-20 08:39
I'm not sure about this.

The legacy UI _does_ show space for multiple lines of text, however you cannot actually press enter to enter multiple lines of text. The extra space is used if you enter a long string, which is useful in WinForms which has poor layout, but in our new WPF based-UI, the layout expands automatically to include longer strings.

Here is how some very long text looks in both:

![image](https://user-images.githubusercontent.com/350947/122667504-7f219780-d1f6-11eb-9bc8-13abb139d175.png)

![image](https://user-images.githubusercontent.com/350947/122667508-847ee200-d1f6-11eb-80ad-c7f9461966b2.png)

All our single-line text boxes will expand to show the entered text in this way, which is not true of the legacy UI.

**Comment by drewnoakes** [comment] 2021-06-21 00:03
Closing as by design.

**Closed by drewnoakes** 2021-06-21 00:03 UTC
Labels: Feature-Project-Properties-Designer
