### ISSUE TITLE
VS Code Coverage does not work properly with new project file format

### ISSUE THREAD

**Issue by Tornhoof** [dotnet/project-system#2854] opened 2017-09-26 10:54 UTC
VS Code Coverage does not work if the project file (new format) does not contain propertygroups with release conditions. If I follow the upgrade guide (http://www.natemcmaster.com/blog/2017/03/09/vs2015-to-vs2017-upgrade/) by @natemcmaster I can remove those propertyGroups, It works nicely, just not the code coverage.

Visual Studio version:
VS 2017 Enterprise 15.3.5

If the following snippet is missing:
```xml
 <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <DefineConstants>TRACE</DefineConstants>
  </PropertyGroup>
```
no code coverage is calculated.
![withoutreleasepropertygroup](https://user-images.githubusercontent.com/7989549/30856484-ccb344ce-a2b8-11e7-9ae0-ef7fba1742a9.png)
If I put the snippet back in, coverage is calculated again:
![withreleasepropertygroup](https://user-images.githubusercontent.com/7989549/30856483-ccab6cb8-a2b8-11e7-9064-b88e7e8fcc01.png)

## Steps to reproduce
 1. Open Repro
 2. Use Test -> Analyze Code Coverage
 3. Look at the output of code coverage
Repro:
[Repro.zip](https://github.com/dotnet/project-system/files/1332824/Repro.zip)
See the project file and uncomment the properties to see both behaviours.

I noticed the behaviour during a TFS 2017 run, so it is not only Visual Studio UI but also the vs.test.console.exe (version 15.0.26720.2) on my build machine.

**Comment by davkean** [comment] 2018-05-23 04:33
This is a dupe of https://github.com/Microsoft/vstest/issues/800.

**Closed by davkean** 2018-05-23 04:33 UTC
Labels: Area-New-Project-System, Feature-Configurations, Parity-VSLangProj
