### ISSUE TITLE
When editing the nuget vesion in the package reference inside csproj file, it is not taken into account before second build is launched 

### ISSUE THREAD

**Issue by MathieuPilotInvivoo** [dotnet/project-system#9096] opened 2023-06-16 18:31 UTC
## Visual Studio Version
Visual Studio 2019 Community
Visual Studio 2022 Community

## Summary
I have a single package reference inside an empty project. I edit the csproj manually to increase the package's version.
After first build the dll in the output directory is still the one from the old version.
After second build, the dll is correctly updated and matches the new nuget version.

## Steps to Reproduce

1.  Create an emtpy SDK project.
2. Add a reference to nuget package System.Text.Json version 7.0.2
		<PackageReference Include="System.Text.Json" Version="7.0.2" GeneratePathProperty="True" />
3. Build the project
4. Verify that the System.Text.Json.dll inside the output directory has the expected version 7.0.2
5. Edit the csproj to modify the nuget version and set it to 7.0.3
6. Build the project
7. Verify that the System.Text.Json.dll inside the output directory has NOT the expected version. It is still 7.0.2 instead of 7.0.3
8. Build the project again
9. Verify that the System.Text.Json.dll inside now has the expected version 7.0.3

## Expected Behavior
Updating a nuget package reference and building the project once should copy the correct version of nuget assemblies.

## Actual Behavior
It requires to launch the build twice to make sure all nuget assemblies are correctly updated. Note that using Rebuild has the same behavior as Build and therefore  does not work as expected either.

## User Impact
When updating the package references without using package manager, the developper's sometimes have the wrong version of nuget packages locally and encounter unexpected bugs and then lose time understanding what went wrong.

**Comment by drewnoakes** [comment] 2023-06-16 20:54
I'm wondering if there's a race condition here.

If you bump the package version then save the project and wait for the background restore to complete before requesting the build, does the issue go away?

**Comment by MathieuPilotInvivoo** [comment] 2023-06-17 14:02
> I'm wondering if there's a race condition here.
> 
> If you bump the package version then save the project and wait for the background restore to complete before requesting the build, does the issue go away?

Right. I confirm it works if done slowly like you suggested: save, wait for background restore and build.
Not very practical as you need to remember to do the update in 2 steps but at least it's proving your point: probably some kind of race condition.

**Comment by drewnoakes** [comment] 2023-06-19 02:07
Thank you for confirming. I believe this is a duplicate of https://github.com/dotnet/project-system/issues/8014.

**Comment by melytc** [comment] 2023-06-29 23:31
Closing as duplicate of #8014

**Closed by melytc** 2023-06-29 23:31 UTC
