### ISSUE TITLE
VS2017 project drop down sometimes doesn't work

### ISSUE THREAD

**Issue by JamesNK** [dotnet/project-system#2054] opened 2017-04-23 06:00 UTC
Sometimes the VS2017 project drop down sometimes doesn't work.

Repo:
1. Open Newtonsoft.Json.Roslyn.sln in VS2017
2. Open a cs file
3. Choose a new project in the project dropdown, e.g. file opens as .NET 2, change the project drop down to .NET 4.5
4. The cs file is not updated to reflect .NET 4.5. Clicking on the text editor area causes the project drop down to change from .NET 4.5 back to .NET 2

Note that sometimes this happens, while other times the project is successfully changed.

Project: https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/Newtonsoft.Json.Roslyn.csproj

**Comment by davkean** [comment] 2017-08-31 05:58
Dupe of https://github.com/dotnet/roslyn/issues/21358.

**Closed by davkean** 2017-08-31 05:58 UTC
