### ISSUE TITLE
Blazor components namespaces - code behind

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#8581] opened 2022-10-07 22:24 UTC
_This issue has a corresponding [ticket on Developer Community](https://developercommunity.visualstudio.com/t/Blazor-components-namespaces---code-behi/10080068). Please vote and comment there to make sure your voice is heard._

---
[severity:It bothers me. A fix would be nice]

Steps to reproduce the bug.

1. Create Blazor Server App
1. Create folders
   * `Components`
   * `Components\Sub1`
   * `Components\Sub2`
1. Add new Razor component e.g. `MyComponent1.razor` to folder `Components\Sub1`
1. Add behind the class to 'MyComponent1.razor.cs' to folder `Components\Sub1`:
   

    ```
       using Microsoft.AspNetCore.Components;
    
       namespace BlazorApp1.Components.Sub1
       {
        public partial class MyComponent1:ComponentBase
        {
    
        }
       }
    ```

1. Verify that `<MyComponent1\>` works on some page. Eg. add lines to Index.razor:

    ```
    @using BlazorApp1.Components.Sub1
    
    ```

1. Rename folder `Components\Sub1` to `Components\Sub1Renamed`. 
1. Visual studio does not display any error and project can be compiled/started. Code behind is even displayed 'linked' to razor file:

![image](https://user-images.githubusercontent.com/350947/198413888-bcc7cf24-15e1-417f-b3bd-8ad4b5718e10.png)

This seems as a VS bug to me, because code behind class is totally different namespace and in reality it is not code-behind for the razor component any more.

**Comment by kvenkatrajan** [comment] 2022-10-20 22:27
@vijayrkn - can you weigh in here? Is this something that can be handled by the web tools team during folder rename?

**Comment by vijayrkn** [comment] 2022-10-20 22:38
Those are actually handled at the project-system (CPS) level AFAIK. Not sure if we can do anything more from the web stand-point.

**Comment by adamint** [comment] 2022-10-27 22:19
There are duplicate issues on VSFeedback and Github. We should close one.

**Comment by adamint** [comment] 2022-10-27 23:03
@davidwengier do you have any additional insight on this?

**Comment by davidwengier** [comment] 2022-10-27 23:13
As far as I can tell from the description, this is simply not a supported scenario in file nesting. File nesting is based purely on path and filename, and CPS seems to be working as intended here. The feature doesn't look inside code files to try to understand whether their namespace and/or class names match, or anything else of that nature.

**Comment by adamint** [comment] 2022-11-03 23:00
Closing as intended behavior.

**Closed by adamint** 2022-11-03 23:00 UTC
