### ISSUE TITLE
MSBuild cannot see the files whose extension is changed to .cs

### ISSUE THREAD

**Issue by mayur-ekbote** [dotnet/project-system#7568] opened 2021-09-06 09:00 UTC
1. Suppose you have the following class referred somewhere in your code:

Renaming.cs
```
    public class Renaming
    {
        public string Name { get; set; }
        public string Description { get; set; }

        public string Category { get; set; }
    }
```

2. Copy this code and put it in another file (say RenamingBackup.txt). 
3. Rebuild => this builds fine.
4. Now, comment out the code in Renaming.cs and change the file name of the file RenamingBackup.txt to RenamingBackup.cs
5. Rebuild => build fails. It cannot find the definition of the class Renaming. Ideally, it should have detected the class in RenamingBackup.cs

Tested on .net 5 and VS 2019, 2022. You can also verify that the runtime does not see the class because it does not appear in the object browser either.

**Comment by drewnoakes** [comment] 2021-09-07 02:58
I cannot reproduce this.

@mayur-ekbote can you share the contents of your `.csproj` at step 5? That would help us see what is going on here for you.

**Comment by drewnoakes** [comment] 2021-09-07 02:59
Also, please include a screenshot of the project in Solution Explorer.

**Comment by mayur-ekbote** [comment] 2021-09-07 06:51
PFA recording of all the steps. You can see the contents of csproj file at the end. 

https://user-images.githubusercontent.com/40038634/132297734-13996f3b-67d8-4a1c-a645-43a5b8fb4b1d.mp4

**Comment by drewnoakes** [comment] 2021-09-07 12:04
I see what is happening here.

When you create the new text file, it is added to your project as a `None` item. These are not given to the compiler.

When you rename it from `.txt` to `.cs`, the item type in the project is unchanged. In fact the project system correctly preserves the item type by explicitly removing it from the `Compile` group, as the item has `None` type. This stops the globbing (i.e. **/*.cs) from picking it up. You can see that in this:

![image](https://user-images.githubusercontent.com/350947/132340976-a67c6f51-5bac-4949-9947-a03fc93b3c4e.png)

There are two ways to get out of this state:

1. Click the file in Solution Explorer, go to the Properties panel and change the item type to Compile, or
2. Remove both of the `<ItemGroup>` elements from your project so that the default globbing rules pick it up automatically as a compile item.

Note that there may be valid scenarios for including a .cs file as a non-compilation item in a project. As far as your project is concerned, that is what you have requested.

Another hint of this is the "miscellaneous files" above the editor, which indicates that the source file is not really considered as a regular source file:

![image](https://user-images.githubusercontent.com/350947/132341359-e0178775-bec4-4f29-aef8-9afaf41833f6.png)

Let me know if you have any questions. I believe the system is behaving as expected, so will close this for now. Thanks for taking the time to submit this issue.

**Closed by drewnoakes** 2021-09-07 12:04 UTC

**Comment by mayur-ekbote** [comment] 2021-10-08 07:31
To create a workaround for point 4, I created a .cs file and then renamed it to .razor. 
(https://github.com/dotnet/razor-tooling/issues/4425#issuecomment-938107815)

The .razor file sits in the Remove / Include pair.

```
  <ItemGroup>
    <Content Remove="App\Blocks\Bug.razor" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="App\Blocks\Bug.razor" />
  </ItemGroup>
```
For the code:

```
<div>
</div>

@code{
   protected override bool ShouldRender() => false;
}
```

The build fails with a bunch of fails (I guess VS is still expecting a .cs file):

![Rename-bug](https://user-images.githubusercontent.com/40038634/136516096-7761ff85-8112-4227-88ba-737472080e99.PNG)

@NTaylorMullen
