### ISSUE TITLE
Unable to switch launch profiles

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#3328] opened 2018-03-01 01:24 UTC
1. open project system
2. Open ProjectSystemSetup -> Properties -> Debug
3. Change Profile
4. Close properties
5. Reopen properties, Profile didn't change

**Comment by Pilchie** [comment] 2018-03-01 15:44
What build are you on?  There was a recent bug where picking a different launch profile didn't work.  could it be that instead?

cc @BillHiebert

**Comment by davkean** [comment] 2018-03-01 22:39
I'm on latest build. Yes, the issue appears to be that you can't switch profiles. Do we have a bug on that?

**Comment by BillHiebert** [comment] 2018-03-01 22:48
Changing it on the property page doesn’t change the default. That is done on the debug dropdown.  I opened a bug\suggestion a long time ago to look at changing this

See https://devdiv.visualstudio.com/web/wi.aspx?pcguid=011b8bdf-6d56-4f87-be0d-0092136884d9&id=410821

**Comment by davkean** [comment] 2018-03-01 22:52
Yeah confirmed that was the issue, used to change properties in Debug page to affect my next debugging session.

**Comment by etbyrd** [comment] 2019-07-19 17:14
@davkean Can we close this as not a bug?

**Comment by kvenkatrajan** [comment] 2023-10-12 20:48
Closed - not a bug

**Closed by kvenkatrajan** 2023-10-12 20:48 UTC
Labels: Bug, Feature-Debugging, Triage-Approved
