### ISSUE TITLE
Startup projects tooling issue

### ISSUE THREAD

**Issue by weshaggard** [dotnet/project-system#2587] opened 2017-07-11 16:32 UTC
@vinguan commented on [Sun Jul 02 2017](https://github.com/dotnet/standard/issues/414)

.NET Stardard lib can be used as startup project if you put the Output Type as "Console Application" or  "Windows Application", but if the output type is set as "Class Library" they are also shown as Startup Projects as well. I have several .net stardard libs to serve my Xamarin Apps and Web Apps and and they appear together with no meaning.
![netstandardstartupprojectstoolingissue](https://user-images.githubusercontent.com/6222878/27774921-001c0114-5f72-11e7-9386-86eb0659d288.png)
[NETStandardStartupProjectsToolingIssue.zip](https://github.com/dotnet/standard/files/1118206/NETStandardStartupProjectsToolingIssue.zip)

---

@weshaggard commented on [Mon Jul 10 2017](https://github.com/dotnet/standard/issues/414#issuecomment-314288829)

@srivatsn @livarcocc where is the best place to route?

---

@livarcocc commented on [Mon Jul 10 2017](https://github.com/dotnet/standard/issues/414#issuecomment-314314330)

I may be wrong, but I would start with the project system.

**Comment by srivatsn** [comment] 2017-07-24 19:06
Dupe of https://github.com/dotnet/project-system/issues/1308

**Closed by srivatsn** 2017-07-24 19:06 UTC
