### ISSUE TITLE
Create integration test for fast uptodate check

### ISSUE THREAD

**Issue by srivatsn** [dotnet/project-system#2452] opened 2017-06-15 22:49 UTC

**Comment by MattGertz** [comment] 2017-06-30 17:07
Agreed, but won't block 15.3 at this point and is test-only, so moving to 15.4 to get it off the radar.

**Comment by panopticoncentral** [comment] 2018-11-28 20:07
@drewnoakes Did you do this already? Or do you think that our tests are coverage enough?

**Comment by drewnoakes** [comment] 2020-03-19 22:47
Duplicate of #5438.

**Closed by drewnoakes** 2020-03-19 22:47 UTC
Labels: Area-Testing, Bug, Feature-Up-to-date
