### ISSUE TITLE
[Dependencies] When have netcoreapp1.1 referencing netcoreapp2.0 there is error in error list from NuGet. however Dependencies tree does not mark unsupported project with yellow icon

### ISSUE THREAD

**Issue by abpiskunov** [dotnet/project-system#2654] opened 2017-07-24 23:26 UTC
![image](https://user-images.githubusercontent.com/1592091/28549111-e8ac03c2-708c-11e7-8df1-52ecb449a227.png)

**Comment by abpiskunov** [comment] 2017-07-24 23:29
Repro:

1. Create a core web app targeting 1.1, and then create a core class lib targeting 2.0.
2. Try to add core class lib dependency to web app.

wait for restore is complete (it should fail) and see no yellow icon in the Dependencies tree.

**Comment by natidea** [comment] 2017-07-25 21:03
This is a dupe of https://github.com/dotnet/project-system/issues/2436 which contains the root problem. Fixes are needed in multiple repos

**Closed by natidea** 2017-07-25 21:03 UTC
Labels: Bug, Resolution-Duplicate
