### ISSUE TITLE
Find All Files causes project properties to be opened

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/project-system#1486] opened 2017-02-08 00:01 UTC
I can't figure out exact repro steps for this, but it has happened to me many times with the SDK solution in VS:

- Place the cursor on a word you want to search for in the editor
- Hit CTRL+SHIFT+F to bring up the Find All Files dialog
- Press Enter to start the Find All operation

**EXPECTED:** Find all operation starts, and the focus moves to the Find Results window
**ACTUAL:** Find all operation starts, but a project properties window is opened and the focus moves to the newly opened project properties window

Once this happens for me, it does not appear to happen again if I repeat the same steps immediately.

**Comment by srivatsn** [comment] 2017-02-09 21:13
Do you mean property pages or the properties window? I wonder if it's trying to open the project file..

**Comment by davkean** [comment] 2018-11-15 08:11
I ran into this also, cannot repro it again, or figure out the cause.

**Comment by davkean** [comment] 2018-11-16 02:47
I've figured out the cause, repro is that the AppDesigner needs to be in uninitialized state:

1. Create a new Console App (.NET Core)
2. Right-click on project and choose properties
3. Make Program.cs the active document
4. Close Solution
5. Reopen solution
6. Open Quick Find
7. Enter "Foo"
8. Choose Find All

Expected: AppDesigner to not get focused
Actual: AppDesigner is opened and focused

**Comment by davkean** [comment] 2018-11-16 02:49
Note that this is a regression from legacy because it doesn't actually restore AppDesigner.

**Comment by davidwengier** [comment] 2018-11-20 23:04
Found the culprit:
https://github.com/dotnet/project-system/blob/9185282cdd8c1e80e23dae32d5082221b86a1f57/src/Microsoft.VisualStudio.AppDesigner/ApplicationDesigner/ApplicationDesignerView.vb#L246-L248

**Comment by davidwengier** [comment] 2018-12-11 05:41
We don't want to restore legacy behaviour.

**Comment by drewnoakes** [comment] 2022-11-03 23:49
We no longer use the app designer for these projects, so closing this.

**Closed by drewnoakes** 2022-11-03 23:49 UTC
Labels: Bug, Feature-Project-File-Editing, Triage-Approved
