### ISSUE TITLE
Copy-pasting a content item included by a wildcard causes the copy to be removed in project file

### ISSUE THREAD

**Issue by mellinoe** [dotnet/project-system#2824] opened 2017-09-14 07:21 UTC
Example project file:

```XML
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>
 -- other stuff --
  <ItemGroup>
    <Content Include="TestAssets/**/*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
```

Select a .cs file in VS and copy-paste it to the same folder.

Save the project, and now it contains:

```XML
  <ItemGroup>
    <Content Remove="TestAssets\Class1 - Copy.cs" />
  </ItemGroup>
```

The new file should still be covered by the wildcard -- why is it explicitly removed? Are .cs files treated specially?

**Comment by davkean** [comment] 2017-09-25 22:39
Yes, C# files have a default of `<Compile />`, so the project system is trying to maintain that - by adding the Remove. @lifengl @jviau Thoughts?

**Comment by jviau** [comment] 2017-09-25 23:46
I imagine CPS is copying only the Compile item, and sees the target also has a Content glob and removes it from that. We have not yet decided what the final behavior will be in scenarios like this, so it could always change in the future. In this case though maybe duplicate items are not desired.

@mellinoe do you intend to compile items under `TestAsstes\`? If not, you can add a `<Compile Remove="TestAssets\**"`, and now copy/pastes within that folder will remain as Content. Between folders won't work as well though, as CPS will try to retain the origin type of the item (so a .cs item from another folder copied under TestAssets will remain as "Compile").

**Comment by mellinoe** [comment] 2017-09-25 23:54
In this case, I'd like to compile them, although I can imagine cases where I wouldn't -- in that case I would use `<Compile Remove="TestAssets\**"` as you said.

**Comment by davkean** [comment] 2018-04-17 10:14
Re-reading this, this behavior seems to be exactly how it was designed. The project system is copying the original item type going out of its way to prevent items from being included in two item types (which in most cases is not what you want). In your case it is, and we let you edit the project file manually for those advanced situations. In 15.7 we also update the undo stack in the edited file when we make an automatic change so you can just open the file and press CTRL+Z to undo our changes. 

I'm going to close this as I don't see us making any current changes to this behavior, if you disagree feel free to add additional information and I'll reopen.

**Closed by davkean** 2018-04-17 10:14 UTC
Labels: Area-External-CPS, Area-New-Project-System
