### ISSUE TITLE
F# Visual Studio build fails despite presence of global.json

### ISSUE THREAD

**Issue by jackfoxy** [dotnet/project-system#5666] opened 2019-11-27 22:32 UTC
**Visual Studio Version**: 16.3.10

**Summary**:
F# project builds successfully in batch, but not in Visual Studio, despite a global.json file in the solution root . 

**Steps to Reproduce**:

See instructions in ReadMe of demonstration project
https://github.com/jackfoxy/TestFSharpGlobalJson

**Expected Behavior**:
Expect build in Visual Studio to succeed.

**Actual Behavior**:
Visual Studio build fails, while batch build succeeds.

**User Impact**:
Biggest problem is cannot run tests within VS, because test adapter requires successful VS build.

**Comment by davkean** [comment] 2019-11-28 00:40
Error inside VS is:

```
Severity    Code    Description    Project    File    Line    Suppression State
Error    FS0193    The module/namespace 'Encode' from compilation unit 'Thoth.Json' did not contain the val 'ValLinkagePartialKey(generateEncoder)'    Client    C:\TestFSharpGlobalJson\src\Client\FSC    1    Active```

**Comment by cartermp** [comment] 2019-11-28 01:02
@jackfoxy two questions:

1. When you say "batch", do you mean `dotnet build`? Because that fails, but the `build.cmd` file succeeds. So there is definitely something wrong with the way the project is configured.
2. I noticed that this project doesn't depend on `Thoth.Json.Net`, but that's required to use Thoth.Json on .NET Core. Given this I'm not sure how this project is supposed to build in VS, which simply shells out to `dotnet build`.

**Comment by jackfoxy** [comment] 2019-11-28 15:39
@cartermp  yes, I mean dotnet build.

> project doesn't depend on Thoth.Json.Net

Yeah, I see that's not in paket.lock.
I first reported this in the Thoth.Json project 
https://github.com/thoth-org/Thoth.Json/issues/45#issuecomment-558045431
 
Close here and reopen there?

**Comment by matthid** [comment] 2019-11-28 19:50
@cartermp it should build with `Thoth.Json` this package cannot be used in dotnet runtime but it has everything to make the compiler happy.

By the way. I see the error in VS2019 and in dotnet build. To be honest I'm not even sure what to look for. This looks similar to https://stackoverflow.com/questions/55117499/how-to-fix-f-error-fs0193-fsharp-core-does-not-contain-vallinkagepartialkey-f and https://github.com/dotnet/fsharp/issues/5378

**Comment by matthid** [comment] 2019-11-28 19:53
I can send (in private) MSbuild binlogs of a successful and a failing invocation and maybe work out a minimal repro (again probably private only). I'll try to make a public repro as well but I cannot promise anything.

**Comment by cartermp** [comment] 2019-12-01 20:18
Given the activity here: https://github.com/thoth-org/Thoth.Json/issues/45

And in linked issues, I do not think this is an issue in either the .NET project system or the F# compiler. I recommend closing this out, since the issue is not about VS failing to respect a pinned SDK.

**Comment by matthid** [comment] 2019-12-01 20:48
@cartermp I'd say this is a compiler bug for sure, what should that message even mean? If the failure is really expected (and this has yet to be proven) then at the very least the error message needs a hard rework. The code location is useless as well.

**Comment by cartermp** [comment] 2019-12-01 21:11
@matthid there's generally a bug insofar as an internal error like that shouldn't leak, but that doesn't mean the root issue is in the compiler. Discussion about the environment leads me to believe it's not to do with the compiler in a .NET Core environment.

**Comment by jackfoxy** [comment] 2019-12-02 21:10
@cartermp There is sometimes a difference in VS and dotnet build output messages. Probably having to do with VS shelling out to MSBuild.exe, and dotnet using MSBuild.dll (maybe I have that backwards).
 
I'm guessing the leaking has to do with that, and in this case not only a message leaked, but a severity.

**Comment by cartermp** [comment] 2019-12-02 23:27
@jackfoxy that's not what's going on. Since it's a .NET Core project, it's effectively doing what `dotnet build does` (parallelism strategy is different than from the CLI, but that's not what's affecting this). I do not believe this is an issue related to building with a global.json - I recommend this issue be closed and discussion continue in the Thoth repository, which has more information about how it's likely a Fable issue.

**Comment by davkean** [comment] 2019-12-20 00:57
Triage: Based on @cartermp's comment, I'm closing this as external of this repository.

**Closed by davkean** 2019-12-20 00:57 UTC
