### ISSUE TITLE
Changing Git branches from the command line results in non-fatal Watsons and error reports

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/project-system#5979] opened 2020-03-13 01:50 UTC
I don't have a precise repro at this time, but here's the stack. I feel like I've seen it the last two or three days while dogfooding internal builds, but it's a newerish regression it feels like.

```
Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.DocumentLockedException (0x80070005): Operation canceled because the document 'F:\Projects\Roslyn\src\CodeStyle\Core\Tests\Microsoft.CodeAnalysis.CodeStyle.UnitTestUtilities.csproj' is locked by another component. Try opening the document to unlock.
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.DocumentManager.VerifyDocumentIsClosed(RunningDocumentTable runningDocuments, String itemPath)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.DocumentManager.Close(SimpleHierarchyNode projectItem, __FRAMECLOSE closeFlag)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.DocumentManager.CloseOrDetachDocument(SimpleHierarchyNode projectItem)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.SimpleItemNode.CloseOrDetachDocument()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Rethrow(Exception ex)
   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.RethrowOrAggregate(ICollection`1 exceptions)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.SimpleItemNode.CloseOrDetachDocument()
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.TreeService.TreeData.OnBeforeApplyTree()
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.TreeService.ApplyAsync(TreeData value)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Rethrow(Exception ex)
   at Microsoft.VisualStudio.ProjectSystem.ProjectErrorReporting.<>c__DisplayClass6_0.<SubmitErrorReport>b__0()
   at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>c__DisplayClass2_0.<Guard>g__action|0()
   at GuardMethodClass.GuardMethod(Func`1 , Func`2 , Func`2 )
```

**Comment by tmeschter** [comment] 2020-03-16 23:32
This looks like an issue in CPS.

**Comment by tmeschter** [comment] 2020-03-16 23:45
@jasonmalinowski Did this happen once, or repeatedly? That is, how easy is it to reproduce? Is it possible to get a memory dump?

**Comment by jasonmalinowski** [comment] 2020-03-17 01:53
@tmeschter It's happened multiple times, but I don't know if I have a specific repro. If I see it again should I take a dump when the dialog is up?

**Comment by davkean** [comment] 2020-03-17 02:48
(Sending back to triage - this was assigned a milestone without triage or without an assigned dev)

This is very likely caused by an overlap of us updating the buffer while the project is closing, we don't coordinate this to avoid overlap and we should.

**Comment by davkean** [comment] 2020-03-31 00:31
This is fixed by: https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/238530.

**Comment by davkean** [comment] 2020-03-31 04:57
This is now fixed.

**Comment by chucker** [comment] 2020-04-28 12:04
@davkean is that fix released in 16.6 Preview 4? I just ran into what looks like a similar issue.

**Comment by davkean** [comment] 2020-04-29 00:32
@chucker It is in Preview 4, but it looks ineffective. I'm also seeing hits in Preview 4.

**Comment by davkean** [comment] 2020-04-29 01:44
We've figured out the cause and hoping to get a fix for the final build of 16.6.

**Comment by jjmew** [comment] 2020-06-26 00:19
This was fixed by Lifeng

**Closed by jjmew** 2020-06-26 00:19 UTC
Labels: Bug, Feature-Project-File-Editing, Needs-CPS-work, Triage-Approved

**Comment by davkean** [comment] 2020-06-26 04:49
PR: https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/245482.
