### ISSUE TITLE
$(TargetFramework) inside Include is only evaluated for the first target framework

### ISSUE THREAD

**Issue by jnm2** [dotnet/project-system#6042] opened 2020-03-29 19:02 UTC
**Visual Studio Version**: 16.6-p2

**Summary**:

**Steps to Reproduce**:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netcoreapp3.1;netstandard2.0</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <AdditionalFiles Include="PublicAPI/$(TargetFramework)/PublicAPI.Shipped.txt" />
    <AdditionalFiles Include="PublicAPI/$(TargetFramework)/PublicAPI.Unshipped.txt" />
  </ItemGroup>

</Project>
```

**Expected Behavior**:

All files show up in Solution Explorer and the Properties window as additional files

**Actual Behavior**:

![image](https://user-images.githubusercontent.com/8040367/77857885-4733cc00-71ce-11ea-8ea0-e1b1b11320ee.png)

![image](https://user-images.githubusercontent.com/8040367/77857887-49962600-71ce-11ea-895e-7cc5123d9bc3.png)

**Comment by jnm2** [comment] 2020-03-29 19:03
Additionally with:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netcoreapp3.1;netstandard2.0</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="PublicAPI/**" />
    <AdditionalFiles Include="PublicAPI/$(TargetFramework)/PublicAPI.Shipped.txt" />
    <AdditionalFiles Include="PublicAPI/$(TargetFramework)/PublicAPI.Unshipped.txt" />
  </ItemGroup>

</Project>
```

The files for the second target framework don't even show up in Solution Explorer at all:

![image](https://user-images.githubusercontent.com/8040367/77857932-79452e00-71ce-11ea-90a4-513f3d835fb6.png)

**Comment by drewnoakes** [comment] 2020-03-30 23:33
Possible dupe of #935. @davkean can you verify?

**Comment by davkean** [comment] 2020-03-30 23:36
Yes this is a dupe, we only use the first TFM at the moment to determine the tree.

**Closed by davkean** 2020-03-30 23:36 UTC
Labels: Triage-Investigate

**Comment by jnm2** [comment] 2020-03-31 01:06
Looks like I thumbed up that one already. I don't remember that. The joy of rediscovery! :D
