### ISSUE TITLE
[Test Failure] The .csproj file of .net core project can’t be edited at the second time after installing a package

### ISSUE THREAD

**Issue by kartheekp-ms** [dotnet/project-system#5659] opened 2019-11-25 18:51 UTC
Copied from /NuGet/Home#8854

## Details about Problem

NuGet Version: Implicit NuGet Client Dev\5.5.0.6319
VS Version: VS Master\29522.92
OS Version: Windows-10-Enterprise-19H2

## Installation step:  
[https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3268236&view=results](url)

## Repro steps: 
1. Create a C# Console App (.Net Core) project.
2. Unload the project.
3. Reload the project.
4. Install a 'PackageReference' package into the project.
5. Unload the project again.
6. Edit the .csproj file or reload project.

## Expected:
The .csproj file can be edited and the project can be reloaded successfully.

## Actual:
The .csproj file can’t be edited and the project can’t be reloaded whether you select yes or no with below pop up dialog. 
![1125](https://user-images.githubusercontent.com/20632775/69526200-a1185100-0fa4-11ea-9d76-22a10e5af0f8.png)

## Here is the record video for the repro steps:
![reload](https://user-images.githubusercontent.com/20632775/69526250-bee5b600-0fa4-11ea-8779-1322a12db75a.gif)

## Notes: 
1. The issue not repro on .Net Framework project.
2. The issue repro on VS Master\29522.92 + NuGet Client Dev\5.5.0.6325.

**Comment by davkean** [comment] 2019-11-25 21:37
@davidwengier I've marked this as a regression but haven't actually confirmed that.

**Comment by davidwengier** [comment] 2019-11-26 00:21
Yep, this is a regression, doesn't repro in 16.3 or 16.4.

**Comment by davidwengier** [comment] 2019-11-26 00:59
Turns out its not leaking any buffers, its that when the project is unloaded we don't get the OnFrameDestroyed event for the project file editor (that opened via the provisional tab when the project was reloaded), so we don't unlock the document in the RDT.

**Comment by davidwengier** [comment] 2019-11-26 02:28
Okay, this regression has nothing to do with Nuget, it occurs whenever there are multiple project editor window frames open. Completely my fault and simple fix :)

**Comment by davidwengier** [comment] 2019-11-26 04:48
Internal PR: https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/216089

**Comment by davidwengier** [comment] 2019-11-27 04:18
PR complete

**Closed by davidwengier** 2019-11-27 04:18 UTC
Labels: Bug-Regression, Feature-Project-File-Editing, Needs-CPS-work

**Comment by davidwengier** [comment] 2019-12-11 04:10
Also tracked by AB#1007299
