### ISSUE TITLE
Graphics files in .net standard 2.0 library do have have build action of "Resource"

### ISSUE THREAD

**Issue by dgxhubbard** [dotnet/project-system#3620] opened 2018-06-05 21:19 UTC
We have a few graphics files in .net standard 2.0 libraries, and .net 4.7.1 libraries. We are using     
MSBuildSdkExtras in these libraries. All the libraries have been converted to the new project system. However, when we try to set the build action to "Resource", on an image file like png or gif, it 
is not an available option in .net standard 2.0 libraries.

**Comment by dgxhubbard** [comment] 2018-06-05 22:05
If I switch the project type from .net standard 2.0 to .net 4.7.1 then the Resource option becomes available.

**Comment by dgxhubbard** [comment] 2018-06-05 22:11
Below is an example project. The project folder has a "graphics" folder with an image foo.png.
If the target framework is .net 4.7.1 then the  build action "Resource" is available. If the target framework is .net standard 2.0 then build action "Resource" is not available in drop down.

```xml
<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <LanguageTargets>$(MSBuildExtensionsPath)\$(VisualStudioVersion)\Bin\Microsoft.CSharp.targets</LanguageTargets>
    <TargetFramework>net471</TargetFramework>
    <AssemblyName>ImgResources</AssemblyName>
    <RootNamespace>ImgResources</RootNamespace>
  </PropertyGroup>
  
  <PropertyGroup>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>  
  </PropertyGroup>
  
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <OutputPath>..\..\..\..\bin\Debug\</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <OutputPath>..\..\..\..\bin\Release\</OutputPath>
  </PropertyGroup>
  
  
  <ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="MSBuild.Sdk.Extras" Version="1.5.4" />
  </ItemGroup>
  
  <ItemGroup>
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.Xml.Linq" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Data" />
    <Reference Include="System.Xml" />
  </ItemGroup>
  

  <Import Project="$(MSBuildSDKExtrasTargets)" Condition="Exists('$(MSBuildSDKExtrasTargets)')" />

</Project>
```

**Comment by Nirmal4G** [comment] 2018-06-06 18:10
Duplicate of [@onovotny/MSBuildSdkExtras#81](https://github.com/onovotny/MSBuildSdkExtras/issues/81)

**Comment by davkean** [comment] 2018-10-11 05:28
Here's an example: https://github.com/dotnet/project-system/pull/2664.

**Comment by davidwengier** [comment] 2018-10-11 05:30
Thanks for that. Found the definition in the WPF project system, so should be straightforward

**Comment by davkean** [comment] 2018-10-11 05:31
I suspect that's Shared Project's definition. WPF is a "flavor" of project system and does not use the rule system.

**Comment by davidwengier** [comment] 2018-10-11 05:38
You're presumably correct, I just went on the fact its description is "WPF file" :)

http://index/?query=Resource.xaml&rightProject=Microsoft.Ide.Roslyn.ProjectSystem&file=Rules%5CResource.xaml&rightSymbol=a1n0ougwtam4

**Closed** 2018-10-12 09:18 UTC
Labels: Feature Request, Feature-Rules/Properties, Feature-XAML, Project-System-CPS
