### ISSUE TITLE
Copy paste .cs file from one Visual Studio instance to another 

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#5673] opened 2019-11-28 02:17 UTC
_This issue has a corresponding [ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/803508/copy-paste-cs-file-from-one-visual-studio-instance.html). Please vote and comment there to make sure your voice is heard._

---
I have opened two solutions, each in a separate Visual Studio window instance. I would like to copy a .cs file from Solution Explorer of the first VS instance to Solution Explorer of the second VS instance. 

Now when I paste the .cs file into a folder in Solution Explorer of the second VS instance, a small dialog appears with the message "The source files for this operation cannot be found in this solution".

---
#### Visual Studio Feedback System on 11/3/2019, 11:24 PM: 

Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by davkean** [comment] 2019-11-28 02:20
Dupe of https://github.com/dotnet/project-system/issues/112.

**Closed by davkean** 2019-11-28 02:20 UTC
