### ISSUE TITLE
rename project folders and files

### ISSUE THREAD

**Issue by jmarolf** [dotnet/project-system#3511] opened 2018-05-02 18:06 UTC
Create a way to rename a project folder. This is closely related to http://visualstudio.uservoice.com/forums/121579-visual-studio/suggestions/2517011-enable-project-renaming- and http://visualstudio.uservoice.com/forums/121579-visual-studio/suggestions/3054944-rename-the-project-folder-when-renaming-a-project

I would like a way where I can change a folder name and optionally filenames: Project -> right click -> rename folder and files... -> give a new name, select folder, output filename or both -> 
* Visual Studio updates name of the the solutiondirectory 
* Visual Studio updates the solution to point at the new directory 
* Visual Studio updates references of other projects to this project to the new directory 
* Visual Studio updates the project to reflect the new output file name 
* Visual Studio cleans the old files from the output dir if present

Extra brownie points for optionally integrating this in the rename project functionality (update output file name and directory to NEWNAME? <yes> <no>)

Double extra brownie points for a 'search for references to this directory from other tools': text-based search for all files not in obj or bin dirs in all folders under the solution dir that contain the old filename, and ask if the old directory name should be replaced with the new one, or if you want to open the files and edit them manually.

**Comment by jrouaix** [comment] 2019-04-23 11:44
Hello, I needed it and coded a global tool. It's an early release but should save you minutes of tidious text remplacements on big repositories : https://github.com/jrouaix/dotnet-rename

**Comment by drewnoakes** [comment] 2024-11-13 03:12
Closing this as a duplicate of #111, given it's so closely related.

**Closed by drewnoakes** 2024-11-13 03:12 UTC
Labels: Triage-Approved
