### ISSUE TITLE
It seems that dotnet#1409 is still an issue in 15.4.1.

### ISSUE THREAD

**Issue by bill-call** [dotnet/project-system#2934] opened 2017-11-01 02:17 UTC
Seems that this is a duplicate of dotnet#1553.

Custom tool ResXFileCodeGenerator failed to produce an output for input file 'Resources\Views\Manage\AccessDenied.en-US.resx' but did not log a specific error.

It may be worth noting that I am running VS with admin privileges.

I have, in the past, tried to move this solution to a different directory, but then moved it back to it's original location. I currently have two rezx files, both of which were created after the solution was returned to its original directory.

The directory I was trying to move it to as the empty parent of the actual solution directory.  Moving it did not seem to cause any problems at the time. I moved the solution back to its original directory because I decided that I wanted it that way, not because I had noticed a problem.

See: dotnet#1409.

Microsoft Visual Studio Community 2017 
Version 15.4.1
VisualStudio.15.Release/15.4.1+27004.2005
Microsoft .NET Framework
Version 4.7.02558

Installed Version: Community

Visual Basic 2017   00369-60000-00001-AA555
Microsoft Visual Basic 2017

Visual C# 2017   00369-60000-00001-AA555
Microsoft Visual C# 2017

Visual C++ 2017   00369-60000-00001-AA555
Microsoft Visual C++ 2017

Visual F# 4.1   00369-60000-00001-AA555
Microsoft Visual F# 4.1

Application Insights Tools for Visual Studio Package   8.9.00809.2
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.0.30925.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   1.0
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2012   4.0.20601.0
For additional information, visit https://www.asp.net/

ASP.NET Web Frameworks and Tools 2017   5.2.50921.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.0.30915.0
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.3.0000.1
Microsoft Azure Data Lake Tools for Visual Studio

Azure Data Lake Tools for Visual Studio   2.3.0000.1
Microsoft Azure Data Lake Tools for Visual Studio

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Cookiecutter   3.0.17262.1
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

Dotfuscator Community Edition   5.30.0.5167-c98e2f8
PreEmptive Protection - Dotfuscator CE

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

GitHub.VisualStudio   2.2.0.10
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

Merq   1.1.17-rc (cba4571)
Command Bus, Event Stream and Async Manager for Visual Studio extensions.

Microsoft Azure HDInsight Azure Node   2.3.0000.1
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.3.0000.1
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio   1.8
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service   2.3.0000.1
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.50719.1

Microsoft Continuous Delivery Tools for Visual Studio   0.3
Simplifying the configuration of continuous build integration and continuous build delivery from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   4.7.4-pre (c2d89eb)
Support for debugging Mono processes with Visual Studio.

Node.js Tools   1.4.10918.1
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   4.4.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Python   3.0.17262.1
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Python - Django support   3.0.17262.1
Provides templates and integration for the Django web framework.

Python - IronPython support   3.0.17262.1
Provides templates and integration for IronPython-based projects.

Python - Profiling support   3.0.17262.1
Profiling support for Python projects.

SQL Server Data Tools   15.1.61707.200
Microsoft SQL Server Data Tools

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript   2.3.5.0
TypeScript tools for Visual Studio

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio tools for CMake   1.0
Visual Studio tools for CMake

Visual Studio Tools for Unity   3.4.0.2
Visual Studio Tools for Unity

VisualStudio.IoT   1.0
Package with IoT components for Visual Studio

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

WebJobs Tools v1.0.0   15.0.30923.0
WebJobs Tools v1.0.0

Xamarin   4.7.10.22 (fe36bec)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin.Android SDK   8.0.0.33 (HEAD/7a6a056e8)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   11.2.0.8 (9a9f054)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by bill-call** [comment] 2017-11-01 13:31
Re-starting VS seems to have stopped the errors.  I only got them in the same session in which I created the new .resx files.  Note, however, that I am not the only one reporting this problem in 15.4.1.

**Comment by bill-call** [comment] 2017-11-01 13:40
I attached a second instance of VS to devenv.exe, set the Common Language Runtime Exceptions to only break on System.NullRefrenceException, and ran the custom tool on one of the problem .resx files.  I get the error, but do not get a break in the debugger.

**Comment by bill-call** [comment] 2017-11-01 13:43
Even If I enable *all* CLREs, I don't catch any exceptions when running the custom tool.

**Comment by bill-call** [comment] 2017-11-01 13:56
This  might be a clue. Every time I open my solution, even if VS is not currently running, it tries to save "devenv.sln*"  This only happens if I try to open the solution directly.  If I just open VS, then navigate to my solution via the Start Page, then I get no save dialog for "devenv.sln*".  I do see that there  is a devenv.exe on my Recents list, though. I can remove it, but it just comes back the next time I launch my solution directly.

**Comment by bill-call** [comment] 2017-11-01 15:40
Seems that this is a duplicate of dotnet#1553.

**Comment by Pilchie** [comment] 2017-11-01 18:03
Closing as a duplicate of #1553

**Closed by Pilchie** 2017-11-01 18:03 UTC
