### ISSUE TITLE
Resolved references have different properties to unresolved references

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#1480] opened 2017-02-07 05:01 UTC
Unresolved reference:

![image](https://cloud.githubusercontent.com/assets/1103906/22678436/2f1eddd8-ed4e-11e6-9883-8297ad643b45.png)

Resolved references:

![image](https://cloud.githubusercontent.com/assets/1103906/22678488/947455be-ed4e-11e6-8cdd-3042573cc0c3.png)

These are supposed to contain the same properties.

**Comment by abpiskunov** [comment] 2017-02-07 17:27
dupe of https://github.com/dotnet/roslyn-project-system/issues/59

**Comment by davkean** [comment] 2017-02-07 22:37
This isn't a dupe, that bug is "make them the same as CSProj" - this is; resolved references are different from unresolved references. You can fix this one without the other. Or vice versa.

**Comment by abpiskunov** [comment] 2017-02-08 00:46
hm yeah if you read it directly - you are right :). However for issue i mentioned, i wanted to do a complete review of all properties for all dependency types and that would include issue you reported. Anyway , let's keep it just in case.

**Comment by srivatsn** [comment] 2017-05-23 17:50
Fixed by #2209

**Closed by srivatsn** 2017-05-23 17:50 UTC
Labels: Bug
