### ISSUE TITLE
“app.config” error after creating a .Net Core 3.1 project with an app.config and a Settings.settings file

### ISSUE THREAD

**Issue by ContentsMayVary** [dotnet/project-system#6799] opened 2020-09-10 07:54 UTC
Tested with Visual Studio 2019 version **16.7.3** (and some earlier versions).

If I create a .Net Core 3.1 project which has an "app.config" _and_ a "Settings.settings" file, I see the following warning every time I try to look at the project properties, or load the project:

> An error occurred while reading the app.config file. The file might be corrupted or contain invalid XML.

**Steps to reproduce:**

1. Create a new "Windows Forms App (.Net Core)" .Net Core 3.1 project.
2. In the IDE, right-click the project in Solution Explorer and select Add | New Item...
3. Select "Application Configuration File" and click 'Add'.
4. Go to "Project Properties" and the "Settings" tab.
5. Click "This project does not contain a default settings file. Click here to create one."
6. Add a string user setting called "Setting" with a value of "test".
7. Build application.
8. Close all the project windows.
9. Go to "Project Properties" and the "Settings" tab.

At this point, I see the error I mentioned above.

For reference, I originally asked about this on StackOverflow: https://stackoverflow.com/questions/63813523/how-to-prevent-app-config-error-after-porting-to-net-core-an-app-with-an-app

**Comment by dsplaisted** [comment] 2020-12-17 00:01
@jjmew Can you triage / assign this issue?

Here's a repro, if you go to the project properties you'll get the exception: [WinFormsSettings.zip](https://github.com/dotnet/project-system/files/5706126/WinFormsSettings.zip)

**Comment by swesonga** [comment] 2020-12-17 22:53
The root cause of this error is the same assembly load exception described in #6784

**Comment by drewnoakes** [comment] 2020-12-18 00:16
@melytc please investigate and close this if it's a duplicate of #6784.

**Comment by Tape-Worm** [comment] 2021-02-03 17:01
I just wanted to add that I'm having this issue in C# and .NET 5. Most of what I've seen regarding this problem has been for Visual Basic.NET and this issue is definitely not exclusive to that language.

I'm using visual studio 16.8.4

**Comment by cbass27** [comment] 2021-06-17 07:57
I'm still encountering this issue. Has anyone found a solution to this yet?

VB .NET 5
Visual Studio 16.10.2

**Comment by paul1956** [comment] 2021-06-17 10:11
Try deleting below from App.Config
```
<system.diagnostics>
    <sources>
        <!-- This section defines the logging configuration for My.Application.Log -->
        <source name="DefaultSource" switchName="DefaultSwitch">
            <listeners>
                <add name="FileLog"/>
                <!-- Uncomment the below section to write to the Application Event Log -->
                <!--<add name="EventLog"/>-->
            </listeners>
        </source>
    </sources>
    <switches>
        <add name="DefaultSwitch" value="Information" />
    </switches>
    <sharedListeners>
        <add name="FileLog"
                type="Microsoft.VisualBasic.Logging.FileLogTraceListener, Microsoft.VisualBasic, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL"
                initializeData="FileLogWriter"/>
        <!-- Uncomment the below section and replace APPLICATION_NAME with the name of your application to write to the Application Event Log -->
        <!--<add name="EventLog" type="System.Diagnostics.EventLogTraceListener" initializeData="APPLICATION_NAME"/> -->
    </sharedListeners>
</system.diagnostics>
```

**Comment by jjmew** [comment] 2021-06-22 17:42
This is a duplicate of #6784

**Closed by jjmew** 2021-06-22 17:42 UTC
Labels: Resolution-Duplicate, Triage-Investigate

**Comment by patsperca** [comment] 2021-06-24 16:24
Same here, very annoying that it is not possible to use Appsettings in conjunction with app.config so that enduser is able to change settings of app. Tried several workarounds that work more or less but Visual Studio is not able to update app.config as soon something changes in settings.
