### ISSUE TITLE
app.config not updated in 15.9.5

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#4569] opened 2019-02-14 21:06 UTC
VS 15.9.5 does not copy updated `app.config` into `assemblyname.dll.config` on build after it was changed. REbuild works as a workaround, but it is clearly a regression.

Both `dotnet build` and cli `msbuild` update file correctly, it's only VS build that doesn't.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/428703/appconfig-not-updated-in-1595.html
VSTS ticketId: 768825_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by jmarolf** [comment] 2019-02-14 22:11
@panopticoncentral 	this looks like an up-to-date check issue.  Do you recall if we had regressions here around app.config files for .NET Core?

**Comment by drewnoakes** [comment] 2019-02-19 19:13
Unable to reproduce this in a `netcoreapp2.1` project. `App.config` is copied correctly.

I've reopened the feedback item and asked the customer for more information to try and repro this.

**Comment by uncleyo** [comment] 2019-02-19 19:38
Hi, original reporter here.

I'm experiencing this when targeting `net472` in a .NET Core SDK style project.
Not sure if `App.config` even means anything in `netcoreapp`/`netstandard` targets.

**Comment by drewnoakes** [comment] 2019-02-19 20:28
@uncleyo the log will be useful. See https://github.com/dotnet/project-system/blob/master/docs/repo/up-to-date-check.md#debugging

Can you include the log details, either here (or if they're sensitive in any way, you may attach them privately to the feedback ticket.)

**Comment by uncleyo** [comment] 2019-02-19 21:21
@drewnoakes, now I cannot reproduce this issue anymore running 15.9.7...

I had a theory if maybe 2019 upgrade from Preview 1 (at the time of original report) to Preview 3 I run today may have fixed it somehow? It is also installed on my machine and I noticed that it installs 2.2.200-preview-something SDK versions which take precedence in absence of global.json to pin sdk version.

I'll ask my colleague who originally noticed this behavior to try and test on his machine tomorrow and let you know the results. And I do not know if he ever had 2019 installed.

**Comment by uncleyo** [comment] 2019-02-20 10:20
@drewnoakes, so we tested this a bit today.

He also has VS 15.9.7 today and the issue _did_ reproduce on the real solution. We captured the output and the interesting piece, I believe, is here (redacted):
```
8>FastUpToDate: Checking build output file '...\obj\Debug\net472\MyProjectName.dll.config': (MyProjectName)
8>FastUpToDate:     Source 2/20/2019 11:37:36 AM: '...\obj\Debug\net472\MyProjectName.dll.config'. (MyProjectName)
8>FastUpToDate:     Destination 2/20/2019 11:37:36 AM: '...\bin\Debug\net472\MyProjectName.dll.config'. (MyProjectName)
8>FastUpToDate: Project is up to date. (MyProjectName)
```

I then asked him to test on an isolated project and issue did not reproduce:
```
1>FastUpToDate: Checking build output file 'E:\stale-app-config\stale-app-config\App.config': (stale-app-config)
1>FastUpToDate:     Source 2/20/2019 11:51:33 AM: 'E:\stale-app-config\stale-app-config\App.config'. (stale-app-config)
1>FastUpToDate:     Destination 2/20/2019 11:51:06 AM: 'E:\stale-app-config\stale-app-config\bin\Debug\net472\stale-app-config.dll.config'. (stale-app-config)
1>FastUpToDate: Build output destination is newer than source, not up to date. (stale-app-config)
1>FastUpToDate: Project is not up to date. (stale-app-config)
```

I noticed that in the problematic case it picked up a strange copy of the config from `obj` instead of taking one from project root. We physically deleted `bin` and `obj` and now `obj` doesn't have the file and rebuild triggers just fine on the project that had issues. `Rebuild` action from VS ran many times before did not have that effect as it didn't clean everything in `obj`.

We have no idea how that file in `obj` came to be. Was it VS 15.9.5 that added it or some version of SDK invoked via `dotnet msbuild` or VS cli `msbuild`...

We got used to nuking `bin` and `obj` first thing when something doesn't work with the new SDK, but _back then_ problem would reappear, now it seems it doesn't.

**Comment by drewnoakes** [comment] 2019-02-20 19:25
@uncleyo thank you for the logs, that's really useful.

**Comment by drewnoakes** [comment] 2019-02-21 00:10
@uncleyo are there any other mentions of `MyProjectName.dll.config` or `App.config` in the logs when you see the error?

**Comment by uncleyo** [comment] 2019-03-06 10:18
@drewnoakes, sorry for going dark.

No, there was nothing else in the logs and I don't know how to get `MyProjectName.dll.config` to appear in `obj` anymore using latest tools.

I guess this can be closed for now.

**Comment by drewnoakes** [comment] 2019-03-06 11:01
@uncleyo can you try this in the VS2019 preview?

**Comment by drewnoakes** [comment] 2019-03-06 11:02
Re-reading the comments above it seems we've already identified that this issue doesn't repro in newer builds. I'll close this for now. Thanks.

**Closed by drewnoakes** 2019-03-06 11:02 UTC
Labels: Feature-Up-to-date, Triaged
