### ISSUE TITLE
Missing Package Diagnostic does not appear in Dependencies Node

### ISSUE THREAD

**Issue by natidea** [dotnet/project-system#2515] opened 2017-06-28 20:22 UTC
**Repro**

Create a .NET Core app and add a reference to an invalid package:
E.g. 1: Package does not exist
```xml
  <ItemGroup>
    <PackageReference Include="System.Missing" Version="1.2.3" />
  </ItemGroup>
```

E.g. 2: Version does not exist
```xml
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Server.Kestrel" Version="2.3.0-*" />
  </ItemGroup>
```

**Expected**
NuGet errors NU1101 or NU1102: Unable to find package, in both Error List and Dependencies node

**Actual**
The error appears in the error list, and the dependencies node is unresolved, but there is no attached diagnostic. Additionally, sometimes after changing to an unknown version, the missing package does not appear in the dependencies tree, even as unresolved node (but it usually reappears after closing and reopening solution). This issue is similar to https://github.com/dotnet/sdk/issues/451

This is because even though the diagnostic is forwarded to the dependencies tree, the Parent ID does not match the ID of the unresolved node. 

Possible solutions are:
- Make unresolved and resolved node IDs consistent as proposed by https://github.com/dotnet/sdk/issues/790
- Return a "resolved" entry from the SDK with the diagnostic for missing packages
- Map unresolved nodes to parent IDs some other way

**Comment by drewnoakes** [comment] 2019-07-04 00:56
Closing this in favour of #3780 (for the missing diagnostic).

> Additionally, sometimes after changing to an unknown version, the missing package does not appear in the dependencies tree, even as unresolved node (but it usually reappears after closing and reopening solution).

I cannot reproduce this, however while trying to do so I discovered #4992.

**Closed by drewnoakes** 2019-07-04 00:57 UTC
Labels: Bug, Feature-Dependency-Node, Project-System-CPS
