### ISSUE TITLE
[Data loss] When the project file editor has unsaved changes changes are no longer merged

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#5976] opened 2020-03-12 04:50 UTC
**Visual Studio Version**:
Version 16.6.0 Preview 2.0 [29911.137.master]

**Summary**:
When changes are unsaved in the project file editor, making a change to a project outside of it lost when you save the editor

**Steps to Reproduce**:

1. Create two .NET Core projects; 1 and 2
2. Open 1 in editor and make an whitespace change
3. In Solution Explorer, drag the project not open in the editor and drop it on the other in Solution Explorer

**Expected Behavior**:
The editor to contain the new reference

**Actual Behavior**:
While the reference is added, the editor does not reflect the change and saving the editor, loses the changes

**User Impact**:

**Comment by davkean** [comment] 2020-03-12 04:51
tag @davidwengier

**Comment by davidwengier** [comment] 2020-03-20 02:36
This repros in 15.9. I think this is just another instance of #5430

**Comment by davidwengier** [comment] 2020-03-30 03:41
Closing as a duplicate of #5430

**Closed by davidwengier** 2020-03-30 03:41 UTC
Labels: Feature-Project-File-Editing, Triage-Investigate
