### ISSUE TITLE
VS takes too long to open a right click menu inside a source file

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#6109] opened 2020-04-21 00:11 UTC
_This issue has a corresponding [ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/975950/vs-takes-too-long-to-open-a-right-click-menu-insid.html). Please vote and comment there to make sure your voice is heard._

---
VS takes too long to open a right click menu inside a source file. I would expect this to be instant.

---
#### Visual Studio Feedback System on 4/3/2020, 00:47 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Yuanyuan Dong [MSFT] on 4/10/2020, 04:21 AM: 

<p>Thanks for your feedback, engineer team is investigateing your issue now. We will contact you if need any information.</p>

#### Visual Studio Feedback System on 4/17/2020, 10:56 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by drewnoakes** [comment] 2020-04-21 00:44
Analysis on the original feedback ticket suggests the issue is related to the debugger, not the dependencies node.

We may be able to make some small improvement to the dependencies node here, but it won't be noticeable in the reported scenario.

Closing this and moving the feedback ticket.

**Closed by drewnoakes** 2020-04-21 00:44 UTC
Labels: Feature-Dependency-Node, Triage-Approved
