### ISSUE TITLE
GraphProvider integration test

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#2598] opened 2017-07-13 04:25 UTC
We need an integration test that tests the GraphProvider portion of the depedendency node.

**Comment by tmeschter** [comment] 2017-09-20 19:23
We're in the process of re-evaluating our integration test framework. This will be addressed in 15.6 at the earliest.

**Comment by drewnoakes** [comment] 2019-03-14 16:34
Closing as a duplicate of #1607.

**Closed by drewnoakes** 2019-03-14 16:34 UTC
Labels: Bug, Feature-Dependency-Node, Project-System-CPS, Test, Triaged
