### ISSUE TITLE
Label on AppDesigner isn't respecting theme

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#2289] opened 2017-05-25 07:09 UTC
![image](https://cloud.githubusercontent.com/assets/1103906/26439795/e71d6dec-416c-11e7-82e9-fda847239f2a.png)

**Comment by tannergooding** [comment] 2017-05-25 17:24
Closing as this is actually just caused by #2228

**Closed by tannergooding** 2017-05-25 17:24 UTC
