### ISSUE TITLE
App Designer - Debug page - TAB order starts at "delete" button

### ISSUE THREAD

**Issue by WilliamXieMSFT** [dotnet/project-system#5180] opened 2019-07-25 17:30 UTC
**Visual Studio Version**:
D16.3 Preview 2

**Summary**:
For Asp.NET Core and .NET Core Console applications, opening the project's App Designer Debug page and hitting TAB starts at the "Delete" button rather than the ComboBox for Profile.

**Steps to Reproduce**:

1. Open an Asp.NET Core or .NET Core Console app in Visual Studio

2. Right Click Project > Properties, Navigate to the Debug section & click on the page to set focus.

3. Hit tab and observe the keyboard focus.

**Expected Behavior**:
Focus should be on the Profile Combobox as it's the first item in the page:
![image](https://user-images.githubusercontent.com/29215642/61895216-03fabe00-aec7-11e9-84b3-84e3906ec755.png)

**Actual Behavior**:
Focus is on the "Delete" button:
![image](https://user-images.githubusercontent.com/29215642/61895242-12e17080-aec7-11e9-9c3b-cb6e22995d19.png)

**User Impact**:
This bug was found from an internal UX board review: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/951777

**Comment by etbyrd** [comment] 2019-07-25 17:59
@jmarolf This seems to be a potential regression from this fix: https://github.com/dotnet/project-system/pull/3782 The tab order still has the profile combo box at 0, so I am not sure how this behavior cropped up again.

**Comment by etbyrd** [comment] 2019-07-25 20:30
It seems that at least part of the issue is that the Profile ComboBox is disabled when the page is loaded, and the tab is put onto the first control that is not disabled. https://github.com/dotnet/project-system/blob/7d06fb8c592377af422e83235c9031c0bf57372c/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/DebugPageControl.xaml#L74-L80

OneWay and EnvironmentVariablesValid both are false because they haven't been initialized yet. I will get a PR out for this.

**Comment by WilliamXieMSFT** [comment] 2019-07-25 20:36
Great, thanks @etbyrd !

**Comment by davkean** [comment] 2019-07-25 22:57
@etbyrd I've moved this into 15.3 as it affects accessibility.

**Comment by etbyrd** [comment] 2019-09-04 20:18
Fixed in https://github.com/dotnet/project-system/pull/5191

**Closed by etbyrd** 2019-09-04 20:18 UTC
Labels: Bug, Tenet-User Friendly
