### ISSUE TITLE
Opening a non-sdk-based project with CPS results in an error about missing configurations.

### ISSUE THREAD

**Issue by nkolev92** [dotnet/project-system#2454] opened 2017-06-16 02:15 UTC
Product: d15rel 26614.0.d15rel preview 3.

1. `git clone git clone https://github.com/NuGet/NuGet.Client`
2. `NuGet.sln`

```
=====================
6/15/2017 3:42:05 PM
Recoverable
System.ArgumentException: 'dimensionValuesMap' must contain at least one element.
Parameter name: dimensionValuesMap
   at Microsoft.Requires.NotNullOrEmpty(IEnumerable values, String parameterName)
   at Microsoft.VisualStudio.ProjectSystem.ProjectConfigurationsServiceBase.CreateConfigurations(ImmutableArray`1 orderedDimensionNames, ImmutableDictionary`2 dimensionValuesMap)
   at Microsoft.VisualStudio.ProjectSystem.DeclaredDimensionsProjectConfigurationsService.<CalculateKnownProjectConfigurationsAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.UnconfiguredProjectCache`1.<GetValueAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.ProjectConfigurationsServiceBase.<GetKnownProjectConfigurationsAsync>d__51.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.DefaultingProjectConfigurationsServiceBase.<GetProjectConfigurationAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.VSUnconfiguredProjectIntegrationService.<GetActiveProjectConfigurationAsync>d__68.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.VSUnconfiguredProjectIntegrationService.<RefreshActiveProjectConfigurationAsync>d__62.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.VisualStudio.ProjectSystem.LanguageServices.LanguageServiceHost.<>c__DisplayClass26_0.<<UpdateProjectContextAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.LanguageServices.LanguageServiceHost.<>c__DisplayClass24_0`1.<<ExecuteWithinLockAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.<JoinAsync>d__78.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask`1.<JoinAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.LanguageServices.LanguageServiceHost.<UpdateProjectContextAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.LanguageServices.LanguageServiceHost.<UpdateProjectContextAndSubscriptionsAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.LanguageServices.LanguageServiceHost.<InitializeCoreAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.OnceInitializedOnceDisposedAsync.<<-ctor>b__4_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.AsyncLazy`1.<>c__DisplayClass13_1.<<GetValueAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.OnceInitializedOnceDisposedAsync.<<InitializeAsync>b__27_0>d.MoveNext()
===================
6/15/2017 3:42:18 PM
```

[VsProjectFault_b7d3be62-7a4f-469a-a800-2fab05726618.failure.txt](https://github.com/dotnet/project-system/files/1079557/VsProjectFault_b7d3be62-7a4f-469a-a800-2fab05726618.failure.txt)

Remove the txt part of this file, it does not let me upload an xml.
[ActivityLog.xml.txt](https://github.com/dotnet/project-system/files/1079560/ActivityLog.xml.txt)

//cc @davkean @rrelyea

**Comment by davkean** [comment] 2017-06-16 03:57
The reason this is occurring is because certain projects are opt'ing into the new project system, such as src\NuGet.Clients\NuGet.PackageManagement.VisualStudio\NuGet.PackageManagement.VisualStudio.csproj but they are not defining the following elements anywhere in their targets graph:

``` XML
<Configurations>Debug;Release</Configurations>
<Platforms>AnyCPU</Platforms>
```

This is resulting in a project with zero configurations, and CPS isn't handling that very well. 

These projects are being opt'd in by the project type GUID in the solution:

```
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "NuGet.VisualStudio.Client", "src\NuGet.Clients\NuGet.VisualStudio.Client\NuGet.VisualStudio.Client.csproj", "{3B96F91B-3B58-40ED-B06E-5CD133A79A63}"
EndProject
Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "NuGet.PackageManagement.VisualStudio", "src\NuGet.Clients\NuGet.PackageManagement.VisualStudio\NuGet.PackageManagement.VisualStudio.csproj", "{306CDDFA-FF0B-4299-930C-9EC6C9308160}"
EndProject
```

NuGet.VisualStudio.Client will be opened in the legacy project system ({FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}), whereas, NuGet.PackageManagement.VisualStudio ({9A19103F-16F7-4668-BE54-9A1E7A4F7556}) is being opened in the new project system.

It looks like most your other projects are getting configurations, by being moved to the Microsoft.NET.SDK, this project has not. 

This behavior looks to have been the same since the very early builds of 15.3 (new for 15.3) - so I can't see what changed here in the past couple of builds to make this start occuring for you. Are you sure you were using 15.3 builds?

**Comment by davkean** [comment] 2017-06-16 04:17
Got a PR here: https://mseng.visualstudio.com/VSIDEProj/_git/VSIDEProj.CPS/pullrequest/228088?_a=overview to handle this. Make note, while this avoids this case - CPS eventually runs into https://github.com/dotnet/project-system/issues/2036 because the project and Solution don't agree on the configurations.

**Comment by lifengl** [comment] 2017-06-16 20:56
I think it started to happen after some .props/.targets changes to turn on the ProjectConfigurationsDeclaredDimensions capability in the target file.  Originally, ProjectConfigurationsInferredFromUsage was declared somewhere in the msbuild .props/.targets, which works for traditional project systems.  When ProjectConfigurationsDeclaredDimensions is not declared, I think CPS will fall back to ProjectConfigurationsInferredFromUsage.  @davkean although your change looks good by itself, I wonder the no configuration will only prevent them to hit this failure message.  Either somewhere in the system should open this project in the traditional project system, or somehow we need fall back to use ProjectConfigurationsInferredFromUsage instead.

**Comment by rrelyea** [comment] 2017-06-16 21:00
do we think this should be a 15.3 preview 3 shipstopper or not? (regression from preview 2 for nuget.sln)

**Comment by srivatsn** [comment] 2017-06-16 21:01
No - this is only an issue for projects that have explicitly opted into CPS by setting a guid but are not importing the SDK - that's not a supported scenario.

**Comment by srivatsn** [comment] 2017-06-16 21:06
> Either somewhere in the system should open this project in the traditional project system, or somehow we need fall back to use ProjectConfigurationsInferredFromUsage instead.

@lifengl but what if the project has no conditions with configuration labels either? Then falling back to ProjectConfigurationsInferredFromUsage wouldn't help either. I don't know what the legacy project system does in this case.

**Comment by lifengl** [comment] 2017-06-16 23:37
In that case, I think the ProjectConfigurationsInferredFromUsage should fall back to a single configuration without any condition...  I didn't try.

**Comment by nkolev92** [comment] 2017-06-20 22:32
Since @lifengl seemed to suggest that no configuration change would help us to avoid this error, is there anything we can do on NuGet side to workaround this? 

I  tried changing the guid for the NuGet.PackageManagement.VisualStudio project and I am still hitting the same error.
Am I doing something wrong? If not, then what Lifeng suggested seems to be happening.
```
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "NuGet.PackageManagement.VisualStudio", "src\NuGet.Clients\NuGet.PackageManagement.VisualStudio\NuGet.PackageManagement.VisualStudio.csproj", "{306CDDFA-FF0B-4299-930C-9EC6C9308160}"
EndProject
```

**Comment by davkean** [comment] 2017-06-20 22:36
There's more than one project in this situation, PackageManager.VisualStudio is one of many. I think you got 3 prompts? So there's probably 3 projects.

**Comment by lifengl** [comment] 2017-06-21 00:07
To work around this issue, can you try to remove ProjectConfigurationsInferredFromUsage capability from the project?

Inside your project, add this to the end of your project
 <ItemGroup>
   <ProjectCapability Remove="ProjectConfigurationsInferredFromUsage" />
  </ItemGroup>

**Comment by davkean** [comment] 2017-06-21 00:08
@lifengl The issue is that project is opting into CPS when it's not supposed to. We should stop if from opt'ing in.

**Comment by nkolev92** [comment] 2017-06-21 06:13
@davkean 

Thanks I changed the guids and seems good now, there were 4 projects. 
The experience with the project faul wasn't great though. I never got the 4 pop-ups even before fixing it.

**Comment by davkean** [comment] 2017-06-21 06:16
Projects faults shown as dialogs are the bane of my existence and I hate the experience. I plan on tackling/working with CPS to fix this experience.

This particular project fault (as are other project faults), is a bug and has been fixed in 15.4.

**Comment by tmat** [comment] 2017-06-29 17:58
This is also showing up in a solution that uses shared code projects. 

Repro: clone dotnet/symreader-converter repo, checkout master branch, run ```restore.cmd``` and open ```SymReaderConverter.sln```.

**Comment by jkotas** [comment] 2017-06-29 20:41
We have started hitting it on https://github.com/dotnet/corert/blob/master/src/ILCompiler/ILCompiler.sln too

**Comment by davkean** [comment] 2017-06-30 03:54
@jkotas @tmat There was a breaking change between 15.2 -> 15.3 for projects that were manually "opt'd" into the new project system, but were not created via the templates. While we're fixing the above experience, the real fix is to define configurations using the new syntax, see: https://github.com/dotnet/project-system/blob/master/docs/configurations.md.

**Comment by davkean** [comment] 2017-06-30 03:55
We pulled data on this before we made it, and this was only going to affect a very tiny amount of projects - mostly MS projects.

**Comment by tmat** [comment] 2017-06-30 18:33
@davkean I'm not sure I understand the problem. I do not have any configuration and platform conditions in the projects:
```
<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
```

**Comment by bizcad** [comment] 2017-09-27 15:50
After updating to 15.5.2 I started getting the fault.  I upgraded to 15.5.3 and the fault is still there.

[VsProjectFault_88f01812-bb44-436a-92c5-41bd3d3879dc.failure.txt](https://github.com/dotnet/project-system/files/1337826/VsProjectFault_88f01812-bb44-436a-92c5-41bd3d3879dc.failure.txt)

**Comment by Pilchie** [comment] 2017-12-20 18:16
@davkean are we still planning to do more work here beyond documenting in https://github.com/dotnet/project-system/blob/master/docs/configurations.md ?

**Comment by davkean** [comment] 2018-05-14 05:05
CPS bug is here about doing something better than faulting when the project doesn't have any configurations: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/536278 (internal-only).

**Closed** 2018-05-14 05:06 UTC
Labels: Area-External-CPS, Area-New-Project-System, Bug, Feature-Configurations
