### ISSUE TITLE
Saving project file after editing xml does nothing.

### ISSUE THREAD

**Issue by JohanLarsson** [dotnet/project-system#5249] opened 2019-08-05 12:33 UTC
**Visual Studio Version**:
Latest

**Summary**:

![Save](https://user-images.githubusercontent.com/1640096/62464888-00e8b300-b78e-11e9-9130-4839602663f1.gif)

restarting VS solved it. Have seen it somewhat frequently lately.

**Comment by drewnoakes** [comment] 2019-08-05 14:56
@davidwengier you should take a look at this and see if we need it in this sprint.

**Comment by davidwengier** [comment] 2019-08-05 21:40
@JohanLarsson can you share exactly what version of Visual Studio you are using? I cloned your project and followed the steps in your video but this did not repro for me. This bug did exist in previous versions of of Visual Studio however, and was fixed in 16.2. It would be good to know if this has re-appeared.

If you are already on v16.2 of Visual Studio, could you use the Send Feedback | Report a Problem feature to record your repro, as that will send more diagnostic information that might help narrow down the cause. For information on recording the repro see this page: https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019#record-a-repro

**Comment by JohanLarsson** [comment] 2019-08-05 21:41
```
Microsoft Visual Studio Enterprise 2019
Version 16.1.6
VisualStudio.16.Release/16.1.6+29102.190
Microsoft .NET Framework
Version 4.7.03056

Installed Version: Enterprise

Visual C++ 2019   00435-60000-00000-AA947
Microsoft Visual C++ 2019

Application Insights Tools for Visual Studio Package   9.1.00429.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2019   16.1.429.50124
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   16.1.429.50124
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.1.429.50124
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.1.429.50124
Azure Functions and Web Jobs Tools

C# Tools   3.1.1-beta4-19281-06+58a4b1e79aea28115e66b06f850c83a3f1fcb6d3
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

EZ-GIT   1.9.0


File Nesting   2.6.85
Automatically nest files based on file name and enables developers to nest and unnest any file manually

JetBrains ReSharper Ultimate 2019.1.3   Build 191.0.20190704.212735
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2019 JetBrains, Inc.

Kill the WPF Designer   1.0
Helper for killing the WPF designer. Kills all instances of XDesProc.exe.

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 0x10 - v2.9.20419.2

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   1.0
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

NuGet Package Manager   5.1.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

Snapshot Debugging Extension   1.0
Snapshot Debugging Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.61904.23160
Microsoft SQL Server Data Tools

StylerPackage Extension   1.0
StylerPackage Visual Stuido Extension Detailed Info

Syntax Visualizer   1.0
An extension for visualizing Roslyn SyntaxTrees.

TypeScript Tools   16.0.10506.2004
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.1.1-beta4-19281-06+58a4b1e79aea28115e66b06f850c83a3f1fcb6d3
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.4 for F# 4.6   16.1.0-beta.19253.3+42526fe359672a05fd562dc16a91a43d0fe047a7
Microsoft Visual F# Tools 10.4 for F# 4.6

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Spell Check Everywhere   VSSpellCheckEverywhere
An extension that enables spell checking within any Visual Studio file editor or tool window that uses WPF text boxes.
https://GitHub.com/EWSoftware/VSSpellChecker

Visual Studio Spell Checker   VSSpellChecker
An editor extension that checks the spelling of comments, strings, and plain text as you type or interactively with tool windows.
https://GitHub.com/EWSoftware/VSSpellChecker

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers
```

**Comment by JohanLarsson** [comment] 2019-08-05 21:42
Looks like I should update.

**Comment by davidwengier** [comment] 2019-08-05 22:25
Thanks for the extra info. I'll close this issue, but yes, please feel free to open a new issue, or comment here again, if it reoccurs for you after you update to 16.2.

**Closed by davidwengier** 2019-08-05 22:25 UTC
Labels: Bug-Regression
