### ISSUE TITLE
Uninstalled NuGet packages remain in the Visual Studio solution explorer

### ISSUE THREAD

**Issue by aortiz-msft** [dotnet/project-system#6853] opened 2021-01-21 18:58 UTC
---
**Issue moved from NuGet/Home#10442**
- Please respond to @chgill-MSFT.

---

_From @chgill-MSFT on Friday, January 8, 2021 10:27:13 PM_

## Details about Problem

Product: Visual Studio

NuGet version: 5.9.0.7005

VS version: 16.9.0 preview 3 (30907.6 main)

Worked before? Yes

Works fine in Visual Studio 16.9.0 preview 2 with NuGet 5.9.0.6967.

## Detailed repro steps so we can see the same problem

1. Install a package to a project through any means (PMC or UI)
2. Uninstall a package to a project through any means (PMC or UI)
3. Check dependencies folder for project in the solution explorer and notice that uninstalled packages haven't been removed there even though they have been successfully removed from the project and assets file.

![image](https://user-images.githubusercontent.com/15097183/104070881-e9f58e00-51d5-11eb-83cb-1ad7c762975a.png)

**Comment by aortiz-msft** [comment] 2021-01-21 18:58
---
**Issue moved from NuGet/Home#10442**
- Please respond to @heng-liu.

---

_From @heng-liu on Tuesday, January 12, 2021 12:51:49 AM_

I could repro. But if I reopen the solution, the nodes will be removed as expected.
Is this by design, or we should work with project-system team to fix that?

**Comment by aortiz-msft** [comment] 2021-01-21 18:58
---
**Issue moved from NuGet/Home#10442**
- Please respond to @chgill-MSFT.

---

_From @chgill-MSFT on Tuesday, January 12, 2021 3:26:58 PM_

I can't imagine it's by design as I don't see any potential customer benefit unless maybe it's a result of some perf optimization. I think we should work with project-system to get a fix 😊

**Comment by drewnoakes** [comment] 2021-01-21 21:19
Duplicate of #6813. Fixed in #6814.

Please verify the problem does not repro in a recent build of VS main.

**Closed** 2021-01-26 18:50 UTC
Labels: Resolution-Duplicate, Triage-No-Action
