### ISSUE TITLE
Some projects don't build by default in a clean solution, but they do build "one by one" (.NET Core projects)

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet/project-system#1710] opened 2017-03-08 23:52 UTC
Issue discussed with **Joe Morris**. Please, if this is a bug, this could impact many people. Other than that, let's isolate it.
Here's the repro. Clone the following repo:
https://github.com/dotnet/eShopOnContainers 
Then open the solution **eShopOnContainers-ServicesAndWebApps.sln**
Try to build all. You'll get those dependency errors.
If building the test project one-by-one, everything will compile afterwards.

Related issue in our repo:
https://github.com/dotnet/eShopOnContainers/issues/102 

EXPLANATION:
We have a solution with 12 projects, all of them .NET Core libs and ASP.NET Core projects.
When the solution is just cloned so you get clean code or if you "clean the solution" from VS and then do a "Rebuild Solution" two of the projects are throwing errors due to references not found pointing to our own projects like class libraries or ASP.NET Core projects.
Those two projects are Testing projects, btw.

However, if building each test project "one-by-one", they do build and you can also do a global "Build Solution" afterwards with no isses.
Need to check the Build Order of the global solution.. or isolate any further issue.
But it looks like a bug in VS 2017? not sure..
Joe Morris said it looks like a bug in VS 2017 when I was shwoing it to him.

**Comment by davkean** [comment] 2017-03-08 23:53
Thanks, we'll take a look.

**Comment by grahamehorner** [comment] 2017-03-09 09:55
@CESARDELATORRE do I get a the bug bounty for spotting this one ;)

**Comment by davkean** [comment] 2017-03-09 10:09
@grahamehorner I'll buy you a beer next time you are in Australia.

**Comment by grahamehorner** [comment] 2017-03-09 10:43
@davkean I'd settle for a xxxl .net t-shirt lolz

**Comment by davkean** [comment] 2017-03-23 02:02
I did the following:

1. Clone the repo
2. Open eShopOnContainers-ServicesAndWebApps.sln
3. Build
4. Unload docker-compose due to a error about docker for Windows not being installed
5. Build

Repeated 5 with Rebuild, and Clean then Build.

I could not repro this. Can you still repro this? Can you attach the build errors and update the build steps with either a video or more specific steps?

**Comment by grahamehorner** [comment] 2017-03-23 10:59
I was still having issues checking Docker it was set for windows containers not Linux, but again still had some build issue

**Comment by davkean** [comment] 2017-03-23 23:00
@grahamehorner Not sure I follow, are you still hitting this? If so, can you attach the build errors and give me more specific steps?

**Comment by CESARDELATORRE** [comment] 2017-03-24 22:46
Hey David! I don't know what changed in Visual Studio or our environment, but we're not having this issue any more... I clean the solution, Rebuild completely, and it builds everything good, I cannot repo it now..
So, I think you can close the issue, as you don't have it neither. :)

**Comment by grahamehorner** [comment] 2017-03-25 15:53
@davkean after a full update of the solution everything now builds fine, so this issue has been resolved, I do get a number of runtime issues but these are caused by something different

**Comment by srivatsn** [comment] 2017-04-03 15:29
Closing this as not repro.

**Closed by srivatsn** 2017-04-03 15:29 UTC
Labels: Bug
