### ISSUE TITLE
Deleting a file doesn't always trigger recompilation on CTRL + F5 in VS for .NETStandard libs

### ISSUE THREAD

**Issue by ahmelsayed** [dotnet/project-system#3245] opened 2018-02-12 23:44 UTC
**Repro steps:**

1. Create a .NETStandard class library
2. right click on the project and change debug to "executable" and put any random exe in there
3. Add Class1 and Class2
4. CTRL + F5 -> builds correctly
5. Delete Class2
6. CTRL + F5 -> "build is up to date"

This affects FunctionApp csproj which are .NETStandard class library projects with a custom executable that is triggered on run that consumes the output dll. See https://github.com/Azure/azure-functions-templates/issues/631 for more details.

**Comment by Pilchie** [comment] 2018-02-12 23:51
@ahmelsayed What version of VS are you seeing this with?

**Comment by ahmelsayed** [comment] 2018-02-12 23:52
VS 15.5.6

This is the full version output of my VS
```
Microsoft Visual Studio Enterprise 2017 
Version 15.5.6
VisualStudio.15.Release/15.5.6+27130.2027
Microsoft .NET Framework
Version 4.7.03036

Installed Version: Enterprise

Visual Basic 2017   00369-60000-00001-AA677
Microsoft Visual Basic 2017

Visual C# 2017   00369-60000-00001-AA677
Microsoft Visual C# 2017

Visual F# 4.1   00369-60000-00001-AA677
Microsoft Visual F# 4.1

Application Insights Tools for Visual Studio Package   8.10.01106.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.0.31127.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   1.0
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2012   4.0.20601.0
For additional information, visit https://www.asp.net/

ASP.NET Web Frameworks and Tools 2017   5.2.51007.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.0.31106.0
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.3.2000.1
Microsoft Azure Data Lake Tools for Visual Studio

Azure Data Lake Tools for Visual Studio   2.3.2000.1
Microsoft Azure Data Lake Tools for Visual Studio

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Cookiecutter   3.0.17320.1
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

JavaScript Language Service   2.0
JavaScript Language Service

Microsoft Azure HDInsight Azure Node   2.3.2000.1
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.3.2000.1
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio   2.0
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service   2.3.2000.1
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.51120.3

Microsoft Continuous Delivery Tools for Visual Studio   0.3
Simplifying the configuration of continuous build integration and continuous build delivery from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

NuGet Package Manager   4.5.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Python   3.0.17320.1
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Python - Django support   3.0.17320.1
Provides templates and integration for the Django web framework.

Python - IronPython support   3.0.17320.1
Provides templates and integration for IronPython-based projects.

Python - Profiling support   3.0.17320.1
Profiling support for Python projects.

Snapshot Debugging Extension   1.0
Snapshot Debugging Visual Studio Extension Detailed Info

SQL Server Data Tools   15.1.61710.120
Microsoft SQL Server Data Tools

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   15.5.11025.1
TypeScript Tools for Microsoft Visual Studio

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

VsVim   2.5.0.0
VsVim is a Vim emulator for Visual Studio

WebJobs Tools v1.0.0   15.0.40108.0
WebJobs Tools v1.0.0
```

**Comment by panopticoncentral** [comment] 2018-03-12 23:05
The issue is with globs. When Class2 is deleted, the project file isn't updated because it was just included because of a glob, so we can't depend on the project file timestamp. The up to date check tries to handle this by remembering that the list of source items changed and returning false for up to date the next time we're called. The problem is that we expect that if we return false, we're going to get a build and everything will be fixed up, so we can reset the flag once we've returned that the project isn't up to date. In the Ctrl + F5 case, though, it seems like we're being called twice. The first time, we return false and reset our flag that the source items have changed. Then the second time (which apparently is the "real" one), we've already reset our flag, so we think we're up to date.

The problem here is that it's not clear _when_ the up to date checker should reset the flag that the source items have changed. I guess if we registered for some kind of notification that a build actually happened, then we could safely reset the flag. @lifeng @davkean is there a good place to get notified that a build was started on a project?

**Comment by panopticoncentral** [comment] 2018-03-13 00:11
Hate to betray my ignorance, but... what compiler cache?

**Comment by davkean** [comment] 2018-03-13 00:48
[project-name].CoreCompileInputs.cache - its an input to CoreCompile that is invalidated when a source file is deleted.

**Comment by panopticoncentral** [comment] 2018-04-17 19:49
OK, so the idea is: Delete a file -> causes a design-time build -> design-time build writes updated CoreCompileInputs -> we check time at next build? I guess there'd still be a window in there where the DT build hasn't run yet where you could slip in a build request and we'd think it was up to date, but I guess it's better than what we have now.

**Closed** 2018-04-24 17:35 UTC
Labels: Area-New-Project-System, Bug, Feature-Up-to-date
