### ISSUE TITLE
Deadlock while reloading solution

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/project-system#2117] opened 2017-05-03 22:09 UTC
I was reloading a solution after switching git branches, and then this hung. Dumps are at `\\mlangfs1\public\jasonmal\Dumps\ProjectSystem\2117`.

```
 	ntdll.dll!_ZwWaitForMultipleObjects@20() Line 821	Unknown
 	KernelBase.dll!WaitForMultipleObjectsEx(unsigned long nCount, void * const * lpHandles, int bWaitAll, unsigned long dwMilliseconds, int bAlertable) Line 1551	C
 	KernelBase.dll!WaitForMultipleObjects(unsigned long nCount, void * const * lpHandles, int bWaitAll, unsigned long dwMilliseconds) Line 1403	C
 	Microsoft.VisualStudio.Threading.ni.dll!609f47c2()	Unknown
 	[Frames below may be incorrect and/or missing, native debugger attempting to walk managed call stack]	
 	Microsoft.VisualStudio.Threading.ni.dll!609f47c2()	Unknown
 	[Managed to Native Transition]	
 	Microsoft.VisualStudio.Threading.dll!Microsoft.VisualStudio.Threading.NoMessagePumpSyncContext.Wait(System.IntPtr[] waitHandles, bool waitAll, int millisecondsTimeout) Line 65	C#
 	mscorlib.dll!System.Threading.SynchronizationContext.InvokeWaitMethodHelper(System.Threading.SynchronizationContext syncContext, System.IntPtr[] waitHandles, bool waitAll, int millisecondsTimeout) Line 349	C#
 	[Native to Managed Transition]	
 	[Managed to Native Transition]	
 	mscorlib.dll!System.Threading.Monitor.Wait(object obj, int millisecondsTimeout, bool exitContext) Line 203	C#
 	mscorlib.dll!System.Threading.Monitor.Wait(object obj, int millisecondsTimeout) Line 213	C#
 	mscorlib.dll!System.Threading.ManualResetEventSlim.Wait(int millisecondsTimeout, System.Threading.CancellationToken cancellationToken) Line 688	C#
 	mscorlib.dll!System.Threading.Tasks.Task.SpinThenBlockingWait(int millisecondsTimeout, System.Threading.CancellationToken cancellationToken) Line 3327	C#
 	mscorlib.dll!System.Threading.Tasks.Task.InternalWait(int millisecondsTimeout, System.Threading.CancellationToken cancellationToken) Line 3259	C#
 	mscorlib.dll!System.Threading.Tasks.Task.Wait(int millisecondsTimeout, System.Threading.CancellationToken cancellationToken) Line 3167	C#
 	mscorlib.dll!System.Threading.Tasks.Task.Wait(System.TimeSpan timeout) Line 3083	C#
 	Microsoft.VisualStudio.Threading.dll!Microsoft.VisualStudio.Threading.JoinableTaskFactory.WaitSynchronouslyCore(System.Threading.Tasks.Task task) Line 313	C#
 	Microsoft.VisualStudio.Threading.dll!Microsoft.VisualStudio.Threading.JoinableTaskFactory.WaitSynchronously(System.Threading.Tasks.Task task) Line 290	C#
 	Microsoft.VisualStudio.Threading.dll!Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread() Line 841	C#
 	Microsoft.VisualStudio.Threading.dll!Microsoft.VisualStudio.Threading.JoinableTask<Microsoft.VisualStudio.ProjectSystem.VS.HResult>.CompleteOnCurrentThread() Line 88	C#
 	Microsoft.VisualStudio.Threading.dll!Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run<Microsoft.VisualStudio.ProjectSystem.VS.HResult>(System.Func<System.Threading.Tasks.Task<Microsoft.VisualStudio.ProjectSystem.VS.HResult>> asyncMethod, Microsoft.VisualStudio.Threading.JoinableTaskCreationOptions creationOptions) Line 459	C#
>	Microsoft.VisualStudio.ProjectSystem.Implementation.dll!Microsoft.VisualStudio.ProjectSystem.ProjectMultiThreadedService.ExecuteSynchronously<Microsoft.VisualStudio.ProjectSystem.VS.HResult>(System.Func<System.Threading.Tasks.Task<Microsoft.VisualStudio.ProjectSystem.VS.HResult>> asyncAction) Line 139	C#
 	Microsoft.VisualStudio.ProjectSystem.VS.Implementation.dll!Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.HrInvoke.AnonymousMethod__0() Line 3738	C#
 	Microsoft.VisualStudio.ProjectSystem.VS.dll!Microsoft.VisualStudio.ProjectSystem.VS.HResult.Invoke(System.Func<Microsoft.VisualStudio.ProjectSystem.VS.HResult> action, System.IServiceProvider vsShellServiceProvider, Microsoft.VisualStudio.ProjectSystem.IProjectFaultHandlerService projectFaultHandlerService, Microsoft.VisualStudio.ProjectSystem.UnconfiguredProject project) Line 313	C#
 	Microsoft.VisualStudio.ProjectSystem.VS.Implementation.dll!Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.HrInvoke(System.Func<System.Threading.Tasks.Task<Microsoft.VisualStudio.ProjectSystem.VS.HResult>> asyncAction, bool registerProjectFaultHandlerService) Line 3735	C#
 	Microsoft.VisualStudio.ProjectSystem.VS.Implementation.dll!Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.Close() Line 1230	C#
 	Microsoft.VisualStudio.ProjectSystem.VS.Implementation.dll!Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNodeWrapper.Close() Line 545	C#
```

**Comment by jasonmalinowski** [comment] 2017-05-03 22:10
And build info:

![image](https://cloud.githubusercontent.com/assets/201340/25683774/a8fbf80a-3012-11e7-8b43-4f876f88eb70.png)

**Comment by davkean** [comment] 2017-05-03 23:06
I suspect this is running the critical tasks that have been registered - see if NuGet or any other critical tasks have been registered.

**Comment by basoundr** [comment] 2017-05-08 23:03
@jasonmalinowski Was this solution roslyn? or a smaller solution? 

Also when you say,
> I was reloading a solution after switching git branches

You mean, you had the solution open, switched the branch for the solution and the reload happened?

**Comment by jasonmalinowski** [comment] 2017-05-09 19:57
This was with Roslyn, yes.

> You mean, you had the solution open, switched the branch for the solution and the reload happened?

Yep.

**Comment by davkean** [comment] 2017-05-09 23:33
Apparently there's a bug in the dependency node that might be the cause of this @lifengl.

**Comment by srivatsn** [comment] 2017-05-12 08:31
What's the bug?

**Comment by lifengl** [comment] 2017-05-12 17:56
Devdiv bug 430005 VS Deadlock

**Comment by srivatsn** [comment] 2017-05-12 17:58
Thanks that's assigned to @natidea - moving this to Nat as well.

**Comment by davkean** [comment] 2017-06-29 08:23
This isn't fixed, in my code changes around this I did not or should not have changed behavior around this.

**Comment by MattGertz** [comment] 2017-06-30 17:08
Mondo escrow triage: meets the bar, assuming customers can run into it.

**Comment by srivatsn** [comment] 2017-07-18 16:55
We haven't seen any other report of this. Moving out to 15.5

**Comment by Pilchie** [comment] 2017-12-20 17:35
Moving to @natidea - keeping in 15.6, because we'd like to change that lock in the dependencies node for perf anyway.

**Comment by Pilchie** [comment] 2018-01-24 00:17
Moving to 15.7 - since the other lock work will be happening then.

**Comment by drewnoakes** [comment] 2018-12-10 16:41
This may have been fixed, based on two points:

- The hang here occurred on an API that didn't join work to the JTC, and that call has since been changed to include the JTF/JTC
- I can't find any other examples of this hang on Developer Community (though my search-fu is weak)

**Comment by drewnoakes** [comment] 2019-01-04 10:37
The dependencies node code that caused this deadlock has been changed to use JTF when waiting on the semaphore. Closing this as fixed.

**Closed by drewnoakes** 2019-01-04 10:37 UTC
Labels: Bug, Feature-Dependency-Node, Project-System-CPS
