### ISSUE TITLE
Can't develop Roslyn if NuGet is allowed to download packages

### ISSUE THREAD

**Issue by rchande** [dotnet/project-system#2865] opened 2017-10-03 16:25 UTC
1. Enlist in Roslyn and restore and build the solution on the command line
2. Open Roslyn.sln 
3. VS continuously hangs/shows a "restoring packages" dialog unless the NuGet option to "Allow NuGet to download missing packages" is unchecked

**Comment by davkean** [comment] 2017-10-06 00:47
@natidea

**Comment by davkean** [comment] 2017-10-06 00:47
Probably want to at least find out what this is - continuous restore?

**Comment by 4creators** [comment] 2017-10-06 01:27
I can repro issue with VS 15.4. Prev 4 intermittent hangs but without "restoring packages" dialogue. VS uses  up to 50% processor time to run continuously restore, git checks and code analysis.

**Comment by sharwell** [comment] 2017-12-24 05:33
@Pilchie For a reason that I have not yet determined, recent builds of Visual Studio appear to be ignoring the following line:

https://github.com/dotnet/roslyn/blob/92eadcd85032e25d3f5006c41a406f0ccec1e43d/NuGet.Config#L8

The underlying problem could be a change in Roslyn, the project system, or NuGet. It was relatively recent though; I always leave Package Restore enabled in Visual Studio and only recently did it start causing a problem for Roslyn.sln.

**Comment by Pilchie** [comment] 2017-12-24 20:36
See also https://github.com/NuGet/Home/issues/1335.

**Comment by Pilchie** [comment] 2018-02-12 16:13
Moving to 15.7, as Roslyn has worked around this in their NuGet.config.  However, the NuGet team is still working on improving things here.

**Comment by davkean** [comment] 2020-02-10 23:44
Triage: Figure if this our bug, and where the problem is, and send back to triage.

**Comment by ocallesp** [comment] 2020-06-11 01:20
I cannot repro this using 
Microsoft Visual Studio Enterprise 2019
Version 16.6.2

Roslyn commit 51b329c22ef220bf20739bab82b2846c18ddc291

Error occurred while restoring NuGet packages: The operation failed as details for project Microsoft.CodeAnalysis.PooledObjects.Package could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project Microsoft.CodeAnalysis.PooledObjects.Package could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project Microsoft.CodeAnalysis.PooledObjects.Package could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project Microsoft.CodeAnalysis.PooledObjects.Package could not be loaded.
Time Elapsed: 00:00:03.8033280

No hang or message "restoring packages" 

@rchande Do you still see the this issue ?

**Comment by ocallesp** [comment] 2020-06-11 01:31
@panopticoncentral 
You have been working on performance, have you seen this issue recently ?

**Comment by panopticoncentral** [comment] 2020-06-11 17:57
No, I haven't, I think we should close it.

**Closed** 2020-06-11 20:33 UTC
Labels: Bug, Feature-NuGet, Performance-Scenario-Solution-Open, Tenet-Performance, Triage-Investigate
