### ISSUE TITLE
Define LaunchSettings.json outside of project

### ISSUE THREAD

**Issue by sanderobdeijn** [dotnet/project-system#2813] opened 2017-09-11 08:13 UTC
I have a couple of that have a bit more complicated launchsettings.json. And I don't want to maintain this file per project. Each project already has a common imported .targets file. And in this target I have include my custom launchsettings.json file. It now loads the file correctly but it is placed in the root project directory and my project won't launch.

I don't know how visual studio recognizes the launchsettings.json file but i expect it has to be places in properties directory for it to work correctly. 

So my question is can you include an external file into a specific directory in the project?

**Comment by sharwell** [comment] 2017-09-11 13:00
Possible duplicate of #2540?

**Comment by davkean** [comment] 2017-09-12 00:17
Yeah it is, duping it against it.

**Closed by davkean** 2017-09-12 00:17 UTC
