### ISSUE TITLE
Fast-up-to-date check skips building Roslyn parsing tests

### ISSUE THREAD

**Issue by jcouv** [dotnet/project-system#3065] opened 2017-12-19 18:28 UTC
I’m seeing strange behavior on Roslyn parser tests (src\Compilers\CSharp\Test\Syntax\Parsing\ValueTupleTests.cs for example).
After I make a change and start build or test, I would expect the project to build.

But, currently, it is not building. 
`========== Build: 0 succeeded, 0 failed, 8 up-to-date, 0 skipped ==========`
Detailed log attached below.

I have to force it to build with a re-build from UI, or building from command-line (which makes me think it’s a fast-up-to-date issue). If I turn off fast-up-to-date check in Options, then things work fine again.

I'm using the latest available preview: `Version 15.6.0 Preview 1.1 [27217.0.d15.6]`

[FUTD.log](https://github.com/dotnet/project-system/files/1572799/FUTD.log)

**Comment by jcouv** [comment] 2017-12-19 18:30
FYI @panopticoncentral

**Comment by davkean** [comment] 2017-12-19 23:28
Dupe of https://github.com/dotnet/project-system/issues/3050. A change in CPS has broken us.

**Closed by davkean** 2017-12-19 23:28 UTC
Labels: Bug, Feature - Up-to-date
