### ISSUE TITLE
Renaming a file doesn't prompt to rename the type

### ISSUE THREAD

**Issue by sharwell** [dotnet/project-system#4537] opened 2019-02-04 03:52 UTC
**Version Used**: Visual Studio 2019 Preview 2

:link: This was originally reported in https://devdiv.visualstudio.com/DevDiv/_workitems/edit/189667 for the old xproj format. I was not able to reproduce the issue in CPS projects in Visual Studio 2017 version 15.9.5, but I *am* able to reproduce it in 2019 Preview 2.

**Steps to Reproduce**:

1. In a CPS project, create a file **Model.cs** which contains a class `Model`
2. Rename **Model.cs**&rarr;**Model2.cs**

**Expected Behavior**:

The IDE prompts to rename `Model`&rarr;`Model2`.

**Actual Behavior**:

The file is renamed, but no prompt to rename the symbol appears.

**Comment by jinujoseph** [comment] 2019-06-11 21:50
also asked in [DC](https://developercommunity.visualstudio.com/content/problem/540377/renaming-cs-file-doesnt-prompt-to-rename-class-in.html)

**Comment by RickRockhold** [comment] 2019-07-01 14:24
This was closed as a duplicate of 3356 & 4959. These are also closed, saying they are duplicates of this issue. The problem isn't fixed, and all tickets are closed, referencing other tickets as duplicates. Can we re-open one of them so this gets fixed?

**Comment by jmarolf** [comment] 2019-07-01 15:29
This is the ticket tracking the issue. I won't close this until the problem is fixed.

**Closed** 2019-07-04 01:11 UTC
Labels: Triaged
