### ISSUE TITLE
ProjectSystem intercepting right click in document.  Adding 5-10 blocked seconds every time i right click.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/project-system#6376] opened 2020-07-15 18:31 UTC
This is 16.7p3.

The time is massively consumed in teh project system with these calls.

Name | Exc % | Exc | Inc %
-- | -- | -- | --
microsoft.visualstudio.platform.vseditor.ni!Microsoft.VisualStudio.Text.Utilities.WpfMouseProcessor+<>c__DisplayClass56_1.<MouseProcessorHandler>b__0() | 0.0 | 0 | 40.9
microsoft.visualstudio.languageservices.ni!AbstractOleCommandTarget.Exec | 0.0 | 0 | 40.9
microsoft.visualstudio.editor.implementation.ni!CommandHandlerServiceFilter.Exec | 0.0 | 0 | 40.9
microsoft.visualstudio.editor.implementation.ni!CommandFilterWrapper.Exec | 0.0 | 0 | 40.9
microsoft.visualstudio.editor.implementation.ni!CommandHandlerServiceAdapter.Exec | 0.0 | 0 | 40.9
mscorlib.ni!TimerQueue.FireQueuedTimerCompletion | 0.0 | 2 | 40.0
system.core.ni!System.IO.Pipes.NamedPipeClientStream.Connect(Int32) | 0.1 | 27 | 39.7
vsdebug!? | 0.0 | 2 | 39.0
ManagedModule!dynamicClass.IL_STUB_COMtoCLR(int,int,int,int) | 0.0 | 8 | 38.5
ManagedModule!ProjectNodeWrapper.IsDocumentInProject2 | 0.0 | 1 | 38.5
ManagedModule!ProjectNode.IsDocumentInProject2 | 0.0 | 1 | 38.5
ManagedModule!ProjectNode.IsDocumentInProjectInternal | 0.0 | 0 | 38.5
microsoft.visualstudio.projectsystem.vs.implementation.ni!ProjectNode.HrInvoke | 0.0 | 2 | 38.5
microsoft.visualstudio.projectsystem.vs.ni!Microsoft.VisualStudio.ProjectSystem.VS.HResult+<>c__DisplayClass37_0.<Invoke>b__0() | 0.0 | 0 | 38.5
microsoft.visualstudio.projectsystem.vs.implementation.ni!Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode+<>c__DisplayClass559_0.<HrInvoke>b__0() | 0.0 | 2 | 38.5
microsoft.visualstudio.projectsystem.implementation.ni!ProjectMultiThreadedService.ExecuteSynchronously | 0.1 | 18 | 38.4
microsoft.visualstudio.threading.ni!JoinableTaskFactory.RunAsync | 0.0 | 15 | 38.4
microsoft.visualstudio.threading.ni!Microsoft.VisualStudio.Threading.JoinableTaskFactory.ExecuteJob[Microsoft.VisualStudio.Threading.EmptyStruct](System.Func`1, Microsoft.VisualStudio.Threading.JoinableTask) | 0.2 | 53 | 38.3
ManagedModule!AsyncTaskMethodBuilder.Start | 0.0 | 7 | 38.2
ManagedModule!Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode+<>c__DisplayClass622_0.<IsDocumentInProjectInternal>b__0() | 0.0 | 2 | 38.2
ManagedModule!Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode+<>c__DisplayClass622_0+<<IsDocumentInProjectInternal>b__0>d.MoveNext() | 0.6 | 197 | 38.1
ManagedModule!Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode+StandardIsDocumentInProjectHandler.IsDocumentInProjectAsync(class System.String) | 0.0 | 2 | 37.5
ManagedModule!System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[Microsoft.VisualStudio.ProjectSystem.VS.IsDocumentInProjectResult].Start(!!0&) | 0.2 | 67 | 37.5
ManagedModule!Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode+StandardIsDocumentInProjectHandler+<IsDocumentInProjectAsync>d__12.MoveNext() | 0.2 | 74 | 37.3
wow64cpu!? | 2.1 | 709 | 37.2
wow64!? | 0.7 | 239 | 36.4
kernelbase!? | 1.3 | 426 | 36.0
ntoskrnl!? | 31.0 | 10,364 | 34.4
system.core.ni!DomainBoundILStubClass.IL_STUB_PInvoke(System.String, Int32) | 0.2 | 52 | 32.0
microsoft.visualstudio.projectsystem.implementation.ni!PhysicalProjectTreeProvider.FindByPath | 0.0 | 4 | 26.2
microsoft.visualstudio.projectsystem.implementation.ni!PhysicalProjectTreeProvider.FindByPath | 0.5 | 178 | 21.4
microsoft.visualstudio.projectsystem.ni!PathHelper.MakeRooted | 0.1 | 33 | 19.9
microsoft.visualstudio.projectsystem.implementation.ni!UnconfiguredProjectInternal.MakeRooted | 1.1 | 358 | 19.8
ManagedModule!DependenciesProjectTreeProvider.FindByPath | 0.0 | 12 | 18.9
ManagedModule!DependenciesTreeViewProvider.FindByPath | 0.1 | 42 | 18.9
ManagedModule!LinqExtensions.FirstOrDefault | 0.1 | 42 | 18.7
ManagedModule!Microsoft.VisualStudio.ProjectSystem.Tree.Dependencies.DependenciesTreeViewProvider+<>c.<FindByPath>b__7_0(class Microsoft.VisualStudio.ProjectSystem.IProjectTree,class System.String) | 0.1 | 41 | 18.0
microsoft.visualstudio.projectsystem.implementation.ni!ProjectTree.get_FilePath | 0.4 | 131 | 17.9
microsoft.visualstudio.projectsystem.implementation.ni!UnattachedProjectItemTreeNode.get_FilePath | 0.0 | 14 | 17.3
fltmgr.sys!? | 2.6 | 871 | 12.9
system.ni!System.Uri..ctor(System.Uri, System.String) | 0.0 | 2 | 10.1
system.ni!System.Uri.CreateUri(System.Uri, System.String, Boolean) | 0.0 | 12 | 10.0
npfs.sys!? | 0.8 | 263 | 9.5
system.core.ni!System.Linq.Enumerable.Any[System.__Canon](System.Collections.Generic.IEnumerable`1, System.Func`2) | 0.3 | 100 | 6.2
system.ni!Uri.CreateThis | 0.2 | 58 | 5.4
system.ni!Uri.InitializeUri | 0.5 | 156 | 5.2
microsoft.visualstudio.projectsystem.implementation.ni![COLD] Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.FindByPath(Microsoft.VisualStudio.ProjectSystem.IProjectTree, System.String, System.StringComparison, Boolean, Boolean) | 0.0 | 12 | 4.8
system.ni!System.Uri.CheckForUnicode(System.String) | 0.6 | 185 | 4.7
system.core.ni!System.Linq.Enumerable.FirstOrDefault[System.__Canon](System.Collections.Generic.IEnumerable`1, System.Func`2) | 0.0 | 13 | 4.7
system.ni!Uri.ResolveHelper | 0.0 | 10 | 4.7
system.ni!Uri.GetCombinedString | 0.0 | 4 | 4.6
system.ni!Uri.CombineUri | 0.5 | 158 | 4.6
system.ni!Uri.GetComponents | 0.0 | 3 | 3.9
system.ni!Uri.GetComponentsHelper | 0.0 | 7 | 3.9
system.ni!Uri.ReCreateParts | 0.1 | 20 | 3.9

I will upload my ETL trace if you want to take a look.

**Comment by CyrusNajmabadi** [comment] 2020-07-15 18:37
ETL trace at: https://drive.google.com/file/d/1gqU-9W4zfQRTe88wQoArjDaVeH8eBGTS/view?usp=sharing

**Comment by CyrusNajmabadi** [comment] 2020-07-15 18:55
This reproes on 16.7p4 as well.

**Comment by davkean** [comment] 2020-07-15 22:48
This will be the debugger looking up break points (work around, delete all your breakpoints). @drewnoakes Didn't we skip the lookup for paths under the dependency node?

**Comment by drewnoakes** [comment] 2020-07-16 03:07
Not completely, as it's still needed for certain types (e.g. analyzers). It's better than it was though, as `IProjectTree.FilePath` is `null` for most tree nodes, meaning the pseudo-path (e.g. `>123`) is used for those nodes, and `PhysicalProjectTreeProvider` takes a fast path when these strings start with `>`.

**Comment by CyrusNajmabadi** [comment] 2020-07-16 22:24
it's unclear to me why breakpoints or the debugger are involved at all on right click.  Who is a good debugger person to pull in to help with thsi?

**Comment by davkean** [comment] 2020-07-17 08:27
This is a dupe of https://developercommunity.visualstudio.com/content/problem/975950/vs-takes-too-long-to-open-a-right-click-menu-insid.html, against the debugger.

**Closed by davkean** 2020-07-17 08:27 UTC
