### ISSUE TITLE
Opening a solution with a previously open class designer file shows an error

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#2998] opened 2017-11-29 05:55 UTC
1. Create a new Console App (.NET Core)
2. Right-click project -> Add -> New Item -> Class Diagram
3. Leave the document open
4. Close Solution
5. Reopen solution

```
---------------------------
Microsoft Visual Studio
---------------------------
Can't load this file:

'C:\Users\davkean\documents\visual studio 2017\Projects\ConsoleApp248\ConsoleApp9\ClassDiagram1.cd'

Object reference not set to an instance of an object.
---------------------------
OK   
---------------------------

```

Stack:
```
 	Microsoft.VisualStudio.Modeling.ArtifactMapper.VSHost.dll!Microsoft.VisualStudio.Modeling.ArtifactMapper.VSHost.CodeHandler.GetRootNamespaceName(out string language) Line 1949	C#	Symbols loaded.
 	Microsoft.VisualStudio.Modeling.ArtifactMapper.VSHost.dll!Microsoft.VisualStudio.Modeling.ArtifactMapper.VSHost.CodeHandler.RootNamespaceProperties.get() Line 2138	C#	Symbols loaded.
 	Microsoft.VisualStudio.Modeling.ArtifactMapper.VSHost.dll!Microsoft.VisualStudio.Modeling.ArtifactMapper.VSHost.CodeHandler.PostRootNamespaceFound() Line 1915	C#	Symbols loaded.
 	Microsoft.VisualStudio.Modeling.ArtifactMapper.VSHost.dll!Microsoft.VisualStudio.Modeling.ArtifactMapper.VSHost.CodeHandler.WalkArtifact(string rootXPath, System.Collections.ICollection queries) Line 1763	C#	Symbols loaded.
 	Microsoft.VisualStudio.Modeling.ArtifactMapper.dll!Microsoft.VisualStudio.Modeling.ArtifactMapper.ArtifactMappingEngine.ExecuteReverseEngineeringQueries(Microsoft.VisualStudio.Modeling.Store store, Microsoft.VisualStudio.Modeling.ArtifactMapper.HashedElementList listOfPendingModelActions)	Unknown	No symbols loaded.
 	Microsoft.VisualStudio.Modeling.ArtifactMapper.dll!Microsoft.VisualStudio.Modeling.ArtifactMapper.ArtifactMappingEngine.SyncFromArtifacts(Microsoft.VisualStudio.Modeling.Store store, Microsoft.VisualStudio.Modeling.ArtifactMapper.SyncFlags syncFlags)	Unknown	No symbols loaded.
 	Microsoft.VisualStudio.Modeling.ArtifactMapper.dll!Microsoft.VisualStudio.Modeling.ArtifactMapper.ArtifactMappingEngine.Synchronize(Microsoft.VisualStudio.Modeling.ArtifactMapper.SyncFlags syncFlags, bool forceSynchronization)	Unknown	No symbols loaded.
 	Microsoft.VisualStudio.Modeling.ArtifactMapper.dll!Microsoft.VisualStudio.Modeling.ArtifactMapper.ArtifactMappingEngine.Synchronize(bool forceSynchronization)	Unknown	No symbols loaded.
 	Microsoft.VisualStudio.Modeling.ArtifactMapper.dll!Microsoft.VisualStudio.Modeling.ArtifactMapper.ArtifactMappingEngineHost.Synchronize(Microsoft.VisualStudio.Modeling.ArtifactMapper.ArtifactMappingEngine artifactMappingEngine, bool forceSynchronization)	Unknown	No symbols loaded.
 	Microsoft.VisualStudio.Modeling.ArtifactMapper.dll!Microsoft.VisualStudio.Modeling.ArtifactMapper.ArtifactMappingManager.Synchronize(Microsoft.VisualStudio.Modeling.ArtifactMapper.ArtifactMappingEngine ame, bool forceSync)	Unknown	No symbols loaded.
 	Microsoft.VisualStudio.Modeling.ArtifactMapper.dll!Microsoft.VisualStudio.Modeling.ArtifactMapper.ArtifactMappingManager.Microsoft.VisualStudio.Modeling.ArtifactMapper.IModelSynchronizer.Synchronize(Microsoft.VisualStudio.Modeling.Store store)	Unknown	No symbols loaded.
 	Microsoft.VisualStudio.EnterpriseTools.Shell.dll!Microsoft.VisualStudio.EnterpriseTools.Shell.ModelingDocData.SynchronizeElements(ref Microsoft.VisualStudio.EnterpriseTools.Shell.ModelingDocStore docStore)	Unknown	No symbols loaded.
 	Microsoft.VisualStudio.EnterpriseTools.Shell.dll!Microsoft.VisualStudio.EnterpriseTools.Shell.ModelingDocData.Synchronize(object storeKey)	Unknown	No symbols loaded.
>	Microsoft.VisualStudio.EnterpriseTools.Shell.dll!Microsoft.VisualStudio.EnterpriseTools.Shell.ModelingDocData.Synchronize()	Unknown	No symbols loaded.
 	Microsoft.VisualStudio.EnterpriseTools.ClassDesigner.dll!Microsoft.VisualStudio.EnterpriseTools.ClassDesigner.ClassDesignerDocData.Load(string fileName, bool isReload)	Unknown	No symbols loaded.
 	Microsoft.VisualStudio.EnterpriseTools.Shell.dll!Microsoft.VisualStudio.EnterpriseTools.Shell.ModelingDocData.LoadDocData(string fileName, bool isReload)	Unknown	No symbols loaded.
 	Microsoft.VisualStudio.EnterpriseTools.ClassDesigner.dll!Microsoft.VisualStudio.EnterpriseTools.ClassDesigner.ClassDesignerDocData.LoadDocData(string fileName, bool isReload)	Unknown	No symbols loaded.
 	Microsoft.VisualStudio.EnterpriseTools.Shell.dll!Microsoft.VisualStudio.EnterpriseTools.Shell.DocData.LoadDocData(string fileName)	Unknown	No symbols loaded.
 	[Native to Managed Transition]		Annotated Frame
 	[Managed to Native Transition]		Annotated Frame
 	Microsoft.VisualStudio.ProjectSystem.VS.Implementation.dll!Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.FileDocumentManager.Open(Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.SimpleHierarchyNode projectItem, bool openWith, uint editorFlags, ref System.Guid editorType, string physicalView, ref System.Guid logicalView, System.IntPtr docDataExisting, out Microsoft.VisualStudio.Shell.Interop.IVsWindowFrame windowFrame, Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.WindowFrameShowAction windowFrameAction) Line 317	C#	Symbols loaded.
 	Microsoft.VisualStudio.ProjectSystem.VS.Implementation.dll!Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.FileDocumentManager.Open(Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.SimpleHierarchyNode projectItem, bool openWith, ref System.Guid logicalView, System.IntPtr docDataExisting, out Microsoft.VisualStudio.Shell.Interop.IVsWindowFrame windowFrame, Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.WindowFrameShowAction windowFrameAction) Line 147	C#	Symbols loaded.
 	Microsoft.VisualStudio.ProjectSystem.VS.Implementation.dll!Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.FileDocumentManager.Open(Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.SimpleHierarchyNode projectItem, bool openWith, System.Guid logicalView, out Microsoft.VisualStudio.Shell.Interop.IVsWindowFrame frame, Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.WindowFrameShowAction windowFrameAction) Line 116	C#	Symbols loaded.
 	Microsoft.VisualStudio.ProjectSystem.VS.Implementation.dll!Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.FileDocumentManager.Open(Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.SimpleHierarchyNode projectItem, bool openWith, Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.WindowFrameShowAction windowFrameAction) Line 84	C#	Symbols loaded.
 	Microsoft.VisualStudio.ProjectSystem.VS.Implementation.dll!Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.Commands.DefaultVsUIHierarchyWindowCmdsHandler.TryHandleCommandAsync.AnonymousMethod__34_1(Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.SimpleHierarchyNode n) Line 111	C#	Symbols loaded.
 	System.Core.dll!System.Linq.Enumerable.CombineSelectors.AnonymousMethod__0(System.__Canon x)	Unknown	No symbols loaded.
 	System.Core.dll!System.Linq.Enumerable.WhereSelectEnumerableIterator<Microsoft.VisualStudio.ProjectSystem.IProjectTree, System.Exception>.MoveNext()	Unknown	No symbols loaded.
 	System.Core.dll!System.Linq.Enumerable.WhereEnumerableIterator<System.Exception>.MoveNext()	Unknown	No symbols loaded.
 	mscorlib.dll!System.Collections.Generic.List<System.Exception>.List(System.Collections.Generic.IEnumerable<System.Exception> collection)	Unknown	No symbols loaded.
 	System.Core.dll!System.Linq.Enumerable.ToList<System.Exception>(System.Collections.Generic.IEnumerable<System.Exception> source)	Unknown	No symbols loaded.
 	Microsoft.VisualStudio.ProjectSystem.VS.Implementation.dll!Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.Commands.DefaultVsUIHierarchyWindowCmdsHandler.TryHandleCommandAsync(System.Collections.Immutable.IImmutableSet<Microsoft.VisualStudio.ProjectSystem.IProjectTree> items, long commandId, bool focused, long commandExecuteOptions, System.IntPtr variantArgIn, System.IntPtr variantArgOut) Line 106	C#	Symbols loaded.
 	Microsoft.VisualStudio.ProjectSystem.VS.Implementation.dll!Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.InternalExecCommandAsync(System.Guid cmdGroup, uint cmdId, uint cmdExecOpt, uint itemId, System.IntPtr vaIn, System.IntPtr vaOut, Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.CommandOrigin commandOrigin) Line 3171	C#	Symbols loaded.
 	Microsoft.VisualStudio.ProjectSystem.VS.Implementation.dll!Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.ExecCommand.AnonymousMethod__0() Line 1897	C#	Symbols loaded.
 	Microsoft.VisualStudio.Threading.dll!Microsoft.VisualStudio.Threading.JoinableTaskFactory.ExecuteJob<Microsoft.VisualStudio.ProjectSystem.VS.HResult>(System.Func<System.Threading.Tasks.Task> asyncMethod, Microsoft.VisualStudio.Threading.JoinableTask job)	Unknown	No symbols loaded.
 	Microsoft.VisualStudio.Threading.dll!Microsoft.VisualStudio.Threading.JoinableTaskFactory.RunAsync<Microsoft.VisualStudio.ProjectSystem.VS.HResult>(System.Func<System.Threading.Tasks.Task<Microsoft.VisualStudio.ProjectSystem.VS.HResult>> asyncMethod, bool synchronouslyBlocking, Microsoft.VisualStudio.Threading.JoinableTaskCreationOptions creationOptions)	Unknown	No symbols loaded.
 	Microsoft.VisualStudio.ProjectSystem.Implementation.dll!Microsoft.VisualStudio.ProjectSystem.ProjectMultiThreadedService.ExecuteSynchronously<Microsoft.VisualStudio.ProjectSystem.VS.HResult>(System.Func<System.Threading.Tasks.Task<Microsoft.VisualStudio.ProjectSystem.VS.HResult>> asyncAction) Line 139	C#	Symbols loaded.
 	Microsoft.VisualStudio.ProjectSystem.VS.Implementation.dll!Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.HrInvoke.AnonymousMethod__0() Line 3828	C#	Symbols loaded.
 	Microsoft.VisualStudio.ProjectSystem.VS.dll!Microsoft.VisualStudio.ProjectSystem.VS.HResult.Invoke(System.Func<Microsoft.VisualStudio.ProjectSystem.VS.HResult> action, System.IServiceProvider vsShellServiceProvider, Microsoft.VisualStudio.ProjectSystem.IProjectFaultHandlerService projectFaultHandlerService, Microsoft.VisualStudio.ProjectSystem.UnconfiguredProject project) Line 314	C#	Symbols loaded.
 	Microsoft.VisualStudio.ProjectSystem.VS.Implementation.dll!Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.HrInvoke(System.Func<System.Threading.Tasks.Task<Microsoft.VisualStudio.ProjectSystem.VS.HResult>> asyncAction, bool registerProjectFaultHandlerService)	C#	Symbols loaded.
 	Microsoft.VisualStudio.ProjectSystem.VS.Implementation.dll!Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.ExecCommand(uint itemId, ref System.Guid guidCmdGroup, uint nCmdId, uint nCmdExecOpt, System.IntPtr pvain, System.IntPtr p) Line 1893	C#	Symbols loaded.
 	Microsoft.VisualStudio.ProjectSystem.VS.Implementation.dll!Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNodeWrapper.ExecCommand(uint itemid, ref System.Guid pguidCmdGroup, uint nCmdID, uint nCmdexecopt, System.IntPtr pvaIn, System.IntPtr pvaOut) Line 625	C#	Symbols loaded.
 	[Native to Managed Transition]		Annotated Frame
 	[Managed to Native Transition]		Annotated Frame
 	Microsoft.VisualStudio.Shell.15.0.dll!Microsoft.Internal.VisualStudio.PlatformUI.HierarchyUtilities.ExecHierParentChain.AnonymousMethod__1()	Unknown	No symbols loaded.
 	Microsoft.VisualStudio.Shell.15.0.dll!Microsoft.VisualStudio.ErrorHandler.CallWithCOMConvention(System.Func<int> method, bool reportError, bool setShellErrorInfo)	Unknown	No symbols loaded.
 	Microsoft.VisualStudio.Shell.15.0.dll!Microsoft.Internal.VisualStudio.PlatformUI.HierarchyUtilities.ExecHierParentChain(Microsoft.VisualStudio.Shell.IVsHierarchyItemManager manager, Microsoft.VisualStudio.Shell.Interop.IVsUIHierarchy lpUIHCmd, Microsoft.VisualStudio.Shell.Interop.IVsUIHierarchy lpUIHCurrent, uint itemidCurrent, ref System.Guid pguidCmdGroupRef, uint nCmdID, uint nCmdexecopt, System.IntPtr pvaIn, System.IntPtr pvaOut)	Unknown	No symbols loaded.
 	Microsoft.VisualStudio.Shell.TreeNavigation.HierarchyProvider.dll!Microsoft.VisualStudio.PlatformUI.HierarchyItem.HierarchyInvocationController.Invoke(System.Collections.Generic.IEnumerable<object> items, Microsoft.Internal.VisualStudio.PlatformUI.InputSource inputSource, bool preview)	Unknown	No symbols loaded.
 	Microsoft.VisualStudio.Shell.15.0.dll!Microsoft.Internal.VisualStudio.PlatformUI.InvocationController.Invoke(System.Collections.Generic.IEnumerable<Microsoft.Internal.VisualStudio.PlatformUI.IInvocationPattern> items, Microsoft.Internal.VisualStudio.PlatformUI.InputSource inputSource, bool preview, System.Func<Microsoft.Internal.VisualStudio.PlatformUI.IInvocationPattern, Microsoft.Internal.VisualStudio.PlatformUI.IInvocationController> getController)	Unknown	No symbols loaded.
 	Microsoft.VisualStudio.Shell.15.0.dll!Microsoft.Internal.VisualStudio.PlatformUI.InvocationController.Invoke(System.Collections.Generic.IEnumerable<Microsoft.Internal.VisualStudio.PlatformUI.IInvocationPattern> items, Microsoft.Internal.VisualStudio.PlatformUI.InputSource inputSource, bool preview)	Unknown	No symbols loaded.
 	Microsoft.VisualStudio.Shell.15.0.dll!Microsoft.Internal.VisualStudio.PlatformUI.PivotTreeViewItem.InvokeItem(System.Windows.Input.InputDevice sourceDevice)	Unknown	No symbols loaded.
 	Microsoft.VisualStudio.Shell.15.0.dll!Microsoft.Internal.VisualStudio.PlatformUI.PivotTreeViewItem.OnMouseLeftButtonDown(System.Windows.Input.MouseButtonEventArgs e)	Unknown	No symbols loaded.
 	PresentationCore.dll!System.Windows.UIElement.OnMouseLeftButtonDownThunk(object sender, System.Windows.Input.MouseButtonEventArgs e)	Unknown	No symbols loaded.
 	PresentationCore.dll!System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(System.Delegate genericHandler, object genericTarget)	Unknown	No symbols loaded.
 	PresentationCore.dll!System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate handler, object target)	Unknown	No symbols loaded.
 	PresentationCore.dll!System.Windows.RoutedEventHandlerInfo.InvokeHandler(object target, System.Windows.RoutedEventArgs routedEventArgs)	Unknown	No symbols loaded.
 	PresentationCore.dll!System.Windows.EventRoute.InvokeHandlersImpl(object source, System.Windows.RoutedEventArgs args, bool reRaised)	Unknown	No symbols loaded.
 	PresentationCore.dll!System.Windows.UIElement.ReRaiseEventAs(System.Windows.DependencyObject sender, System.Windows.RoutedEventArgs args, System.Windows.RoutedEvent newEvent)	Unknown	No symbols loaded.
 	PresentationCore.dll!System.Windows.UIElement.OnMouseDownThunk(object sender, System.Windows.Input.MouseButtonEventArgs e)	Unknown	No symbols loaded.
 	PresentationCore.dll!System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(System.Delegate genericHandler, object genericTarget)	Unknown	No symbols loaded.
 	PresentationCore.dll!System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate handler, object target)	Unknown	No symbols loaded.
 	PresentationCore.dll!System.Windows.RoutedEventHandlerInfo.InvokeHandler(object target, System.Windows.RoutedEventArgs routedEventArgs)	Unknown	No symbols loaded.
 	PresentationCore.dll!System.Windows.EventRoute.InvokeHandlersImpl(object source, System.Windows.RoutedEventArgs args, bool reRaised)	Unknown	No symbols loaded.
 	PresentationCore.dll!System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject sender, System.Windows.RoutedEventArgs args)	Unknown	No symbols loaded.
 	PresentationCore.dll!System.Windows.ContentElement.RaiseTrustedEvent(System.Windows.RoutedEventArgs args)	Unknown	No symbols loaded.
 	PresentationCore.dll!System.Windows.Input.InputManager.ProcessStagingArea()	Unknown	No symbols loaded.
 	PresentationCore.dll!System.Windows.Input.InputManager.ProcessInput(System.Windows.Input.InputEventArgs input)	Unknown	No symbols loaded.
 	PresentationCore.dll!System.Windows.Input.InputProviderSite.ReportInput(System.Windows.Input.InputReport inputReport)	Unknown	No symbols loaded.
 	PresentationCore.dll!System.Windows.Interop.HwndMouseInputProvider.ReportInput(System.IntPtr hwnd, System.Windows.Input.InputMode mode, int timestamp, System.Windows.Input.RawMouseActions actions, int x, int y, int wheel)	Unknown	No symbols loaded.
 	PresentationCore.dll!System.Windows.Interop.HwndMouseInputProvider.FilterMessage(System.IntPtr hwnd, MS.Internal.Interop.WindowMessage msg, System.IntPtr wParam, System.IntPtr lParam, ref bool handled)	Unknown	No symbols loaded.
 	PresentationCore.dll!System.Windows.Interop.HwndSource.InputFilterMessage(System.IntPtr hwnd, int msg, System.IntPtr wParam, System.IntPtr lParam, ref bool handled)	Unknown	No symbols loaded.
 	WindowsBase.dll!MS.Win32.HwndWrapper.WndProc(System.IntPtr hwnd, int msg, System.IntPtr wParam, System.IntPtr lParam, ref bool handled)	Unknown	No symbols loaded.
 	WindowsBase.dll!MS.Win32.HwndSubclass.DispatcherCallbackOperation(object o)	Unknown	No symbols loaded.
 	WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate callback, object args, int numArgs)	Unknown	No symbols loaded.
 	WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.TryCatchWhen(object source, System.Delegate callback, object args, int numArgs, System.Delegate catchHandler)	Unknown	No symbols loaded.
 	WindowsBase.dll!System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority priority, System.TimeSpan timeout, System.Delegate method, object args, int numArgs)	Unknown	No symbols loaded.
 	WindowsBase.dll!MS.Win32.HwndSubclass.SubclassWndProc(System.IntPtr hwnd, int msg, System.IntPtr wParam, System.IntPtr lParam)	Unknown	No symbols loaded.

```

**Comment by davkean** [comment] 2017-11-29 05:58
They are accessing Project.CodeModel (which goes through ProjectContextCodeModelProvider.GetCodeModel) which returns **null** because the language service hasn't initialized. 

Similar to CPS's IVsHierarchy we should block and wait synchronously for the language service to be initialized.
ProjectContextCodeModelProvider.GetFileCodeModel should also wait for the language service to be up-to-date with the current tree, to make sure the language service has seen the file.

**Comment by Pilchie** [comment] 2018-02-26 16:14
Duplicate of #1848

**Closed by Pilchie** 2018-02-26 16:14 UTC
Labels: Area-New-Project-System, Bug, Compatibility
