### ISSUE TITLE
InvalidOperationException: Build target stack was corrupted and contain other unfinished targets

### ISSUE THREAD

**Issue by tmat** [dotnet/project-system#3294] opened 2018-02-21 02:33 UTC
VS Version: 
![image](https://user-images.githubusercontent.com/41759/36460276-8bf82f4e-166c-11e8-8ad9-6ecdb70816b3.png)

```
=====================
2/20/2018 6:31:40 PM
Recoverable
System.InvalidOperationException: Build target stack was corrupted and contain other unfinished targets. Expect: '_GetProjectReferenceTargetFrameworkProperties', Actual: 'ResolveProjectReferences'.
===================
2/20/2018 6:31:44 PM
Recoverable
System.InvalidOperationException: Build target stack was corrupted and contain other unfinished targets. Expect: 'ResolveProjectReferences', Actual: 'GetCopyToOutputDirectoryItems'.
===================
2/20/2018 6:31:48 PM
Recoverable
System.InvalidOperationException: Build target stack was corrupted and contain other unfinished targets. Expect: 'DispatchToInnerBuilds', Actual: 'ResolveProjectReferences'.
===================

```

Repro:
1. Clone http://github.com/symreader-converter
2. Open `SymReaderConverter.sln`
3. Build the solution
4. Rebuild `Microsoft.DiaSymReader.Converter.UnitTests`

If the error doesn't occur try to build and rebuild various projects.

Also notice that building these simple projects takes pretty long time.

**Comment by davkean** [comment] 2018-02-21 02:49
Yeah this is known, I believe there's already a bug on it internally, will find it.

**Comment by davkean** [comment] 2018-02-21 02:52
Dupe of https://devdiv.visualstudio.com/DevDiv/_workitems/edit/531370.

**Closed by davkean** 2018-02-21 02:52 UTC
