### ISSUE TITLE
Content does not show up in solution explorer from content packages

### ISSUE THREAD

**Issue by anangaur** [dotnet/project-system#2083] opened 2017-04-27 22:33 UTC
Repro steps

1. Create a package with some content files in it
2. Consume the package from a NET core project.
3. Do a build that should do the restore.
4. [Current] The content files are **not visible** in the solution explorer post restore.
5. Unload and reload the project
6. [Current] The content files are **not visible** in the solution explorer post restore.
7. Close the solution and open the solution.
8. [Current] The content files are now **visible** in the solution explorer post restore.

Steps 4 and 6 should have been same as step 8

**Comment by srivatsn** [comment] 2017-04-27 23:35
Dupe of https://github.com/dotnet/project-system/issues/1934 and the root cause is https://github.com/dotnet/project-system/issues/268 which is being fixed by CPS

**Closed by srivatsn** 2017-04-27 23:35 UTC
