### ISSUE TITLE
Project fails to build immediately after creating

### ISSUE THREAD

**Issue by SamuelCox** [dotnet/project-system#3202] opened 2018-01-31 10:43 UTC
Hi, I've reproduced this on two individual machines. It's quite the bug and rather annoying.
Visual Studio 15.5.5

Repro Steps:
1) Create a folder in file explorer, in our case its a pre-existing git folder with nothing in it.
2) Open Visual Studio and go file -> new project
3) Browse to the previously mentioned folder and select it.
4) Choose an ASP.net core Web Application (Web API).
Visual studio will create this project, but you will not be able to build it. Moving it from the folder it was created in seems to fix it.

![dotnet error](https://user-images.githubusercontent.com/6514954/35618645-7c9dd0c0-0673-11e8-9086-aa8489cc7880.png)

![weird solution structure](https://user-images.githubusercontent.com/6514954/35618660-82e71130-0673-11e8-93bc-e0662cbce5f3.png)

**Comment by SamuelCox** [comment] 2018-01-31 10:43
Also, the nuget package restore does not change anything

**Comment by SamuelCox** [comment] 2018-01-31 17:21
Turns out this was due to having a %20 in the repository name. We didn't want it like that in the first place, so I've just renamed the repo. Not sure if its worth fixing

**Comment by Pilchie** [comment] 2018-02-01 17:14
@jviau - this is a dupe of a CPS bug that is fixed in 15.6, right?

**Comment by jviau** [comment] 2018-02-05 19:43
Yes it is, https://devdiv.visualstudio.com/DevDiv/VS%20IDE%20CPS/_queries/edit/534404

**Comment by natidea** [comment] 2018-02-05 20:36
This is being tracked on Developer Community as https://developercommunity.visualstudio.com/content/problem/160750/nuget-bug-in-vs155.html 
Fix will be in the next release of Visual Studio

**Closed by natidea** 2018-02-05 20:36 UTC
Labels: Area-External-CPS
