### ISSUE TITLE
Critical capabilities changes were detected without any change made to the project, and forces the project to be reloaded.

### ISSUE THREAD

**Issue by srivatsn** [dotnet/project-system#1874] opened 2017-03-28 16:07 UTC
_From @jmarolf on March 28, 2017 0:13_

Changed branches in git and reloaded the solution.  Then this happened.
```
=====================
3/27/2017 5:06:47 PM
Crippling
System.InvalidOperationException: Internal error: Critical capabilities changes were detected without any change made to the project, and forces the project to be reloaded.
   at Microsoft.VisualStudio.ProjectSystem.ProjectCapabilitiesRequirementsService.RequestReloadForIncompatibleCapabilitiesAsync(IImmutableSet`1 capabilities)
   at Microsoft.VisualStudio.ProjectSystem.UnconfiguredProjectImpl.<Microsoft-VisualStudio-ProjectSystem-IProjectCapabilitiesScopeContext-ReloadIfNecessaryAsync>d__161.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Rethrow(Exception ex)
   at Microsoft.VisualStudio.ProjectSystem.ProjectErrorReporting.<>c__DisplayClass6_0.<SubmitErrorReport>b__0()
   at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>c__DisplayClass2_0.<Guard>b__0()
   at GuardMethodClass.GuardMethod(Func`1 , Func`2 , Func`2 )
===================
3/27/2017 5:06:47 PM
Crippling
System.InvalidOperationException: Internal error: Critical capabilities changes were detected without any change made to the project, and forces the project to be reloaded.
   at Microsoft.VisualStudio.ProjectSystem.ProjectCapabilitiesRequirementsService.RequestReloadForIncompatibleCapabilitiesAsync(IImmutableSet`1 capabilities)
   at Microsoft.VisualStudio.ProjectSystem.UnconfiguredProjectImpl.<Microsoft-VisualStudio-ProjectSystem-IProjectCapabilitiesScopeContext-ReloadIfNecessaryAsync>d__161.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Rethrow(Exception ex)
   at Microsoft.VisualStudio.ProjectSystem.ProjectErrorReporting.<>c__DisplayClass6_0.<SubmitErrorReport>b__0()
   at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>c__DisplayClass2_0.<Guard>b__0()
   at GuardMethodClass.GuardMethod(Func`1 , Func`2 , Func`2 )
===================
3/27/2017 5:06:47 PM
Crippling
System.InvalidOperationException: Internal error: Critical capabilities changes were detected without any change made to the project, and forces the project to be reloaded.
   at Microsoft.VisualStudio.ProjectSystem.ProjectCapabilitiesRequirementsService.RequestReloadForIncompatibleCapabilitiesAsync(IImmutableSet`1 capabilities)
   at Microsoft.VisualStudio.ProjectSystem.UnconfiguredProjectImpl.<Microsoft-VisualStudio-ProjectSystem-IProjectCapabilitiesScopeContext-ReloadIfNecessaryAsync>d__161.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Rethrow(Exception ex)
   at Microsoft.VisualStudio.ProjectSystem.ProjectErrorReporting.<>c__DisplayClass6_0.<SubmitErrorReport>b__0()
   at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>c__DisplayClass2_0.<Guard>b__0()
   at GuardMethodClass.GuardMethod(Func`1 , Func`2 , Func`2 )
===================
```

_Copied from original issue: dotnet/roslyn#18230_

**Comment by srivatsn** [comment] 2017-03-28 16:07
_From @Pilchie on March 28, 2017 15:21_

Tagging @srivatsn  and @davkean but I believe this belongs either internally on CPS, or on `roslyn-project-system`.

**Comment by srivatsn** [comment] 2017-03-28 16:32
I thought this was supposed to be fixed because we added some default capabilities. Also isn't this fault message supposed to show which capability changed? @lifengl?

**Comment by lifengl** [comment] 2017-03-28 22:50
The current message is quite limited to tell what causes the problem.  Adrian plans to improve this area in this sprint

Sent from my phone

On Mar 28, 2017, at 9:32 AM, Srivatsn Narayanan <notifications@github.com<mailto:notifications@github.com>> wrote:


I thought this was supposed to be fixed because we added some default capabilities. Also isn't this fault message supposed to show which capability changed? @lifengl<https://github.com/lifengl>?

**Comment by davkean** [comment] 2017-03-29 00:47
@jmarolf Which project was this?

**Comment by davkean** [comment] 2017-03-29 00:55
It appears that we're not setting default capabilities for Shared Projects - so any startup component that is C#/VB and not dynamic could run into this issue.

**Comment by davkean** [comment] 2017-03-29 02:18
Actually I see that ProjectConfigurationsInferredFromUsage from removed in @RaulPerez1's config changes - but we're still inheriting from targets. That might be the cause depending on the build.

**Comment by jmarolf** [comment] 2017-03-29 17:51
@davkean This was loading the Roslyn.sln

**Comment by abpiskunov** [comment] 2017-03-29 22:35
Just saw that too while closing VS with  roslyn project system solution opened, opened this issue https://github.com/dotnet/roslyn-project-system/issues/1892 , feel free to consolidate them  ..

**Comment by davkean** [comment] 2017-03-30 09:11
With Roslyn.sln it's going to be caused by Shared Projects - they are the only ones that should be opt'd into the new project system.

@abpiskunov If you've not got a new build, can you do the following on one of your projects https://github.com/dotnet/roslyn-project-system/blob/master/docs/repo/debugging-tips.md#capabilities and tell me if you can see ProjectConfigurationsInferredFromUsage?

**Comment by lifengl** [comment] 2017-03-30 19:32
Hmm... that can expose a larger problem of our design to use capabilities to enable/disable features, and uses .props/.targets files to add those capabilities.  When customers uses .props/.targets in a place like a shared project, it could enable feature sets, which may not work inside that project system...

**Comment by chborl** [comment] 2017-04-18 16:14
FYI I just hit this today when opening dotnet/roslyn using the latest internal build of Roslyn.  Let me know if I can provide any additional info or log files.

**Comment by srivatsn** [comment] 2017-05-03 07:04
Same as https://github.com/dotnet/project-system/issues/2103. Keeping that open since that has a repro.

**Comment by davkean** [comment] 2017-05-04 00:22
This is a different bug; the one you dup'd against is web, this is Shared Projects. Different components involved.

**Comment by CyrusNajmabadi** [comment] 2017-05-22 21:03
Note: i just got this again, this time not doing any switching

**Comment by davkean** [comment] 2017-05-22 22:25
@CyrusNajmabadi We added additional information to the error message in recent builds, did you see a different error message?

**Comment by davkean** [comment] 2017-05-25 22:28
@srivatsn Can you give this to someone else to investigate for 15.3?

**Comment by Pilchie** [comment] 2017-12-19 22:17
Closing this for now - the CPS team shows no telemetry on this in 15.5, and we haven't seen reports anymore either.  If we do, hopefully they will be more actionable now.

**Closed by Pilchie** 2017-12-19 22:17 UTC
Labels: Blocking Partner, Bug
