### ISSUE TITLE
VS is not responding when loading project from "https://github.com/balaTest/ProjectKTestProjects"

### ISSUE THREAD

**Issue by MiaomiaoHuangfu** [dotnet/project-system#2477] opened 2017-06-21 08:47 UTC
- Clone this repo [ProjectKTestProjects](https://github.com/balaTest/ProjectKTestProjects)  to your machine and extract it;
- Double click the .sln file and prompt a "One-way upgrade" window, click "OK".
- Then VS is not responding in loading project....
  ![noresponding](https://user-images.githubusercontent.com/22901391/27374322-eb4a7914-569d-11e7-9c33-5f03d78d55c4.PNG)

- Save the dmp file NotResponding_devenv.dmp under "\\bvtsrv2\team\v-mihuan\DevOPsCTI\E2E\NotResponding_devenv.dmp"

- **Expected Result**: the project can be loaded smoothly.

- OS: Windows 10
- build: d15rel.26620.00

**Comment by davkean** [comment] 2017-06-21 09:14
Looked at the dump, this is the relevant stacks:

![image](https://user-images.githubusercontent.com/1103906/27376488-ac5f5306-56b5-11e7-9eea-b0359fab43fb.png)
![image](https://user-images.githubusercontent.com/1103906/27376511-be0ea3b8-56b5-11e7-85be-d75ad9e37277.png)

This is a dupe of https://devdiv.visualstudio.com/DevDiv/_workitems/index?id=451907, which was merged in https://github.com/dotnet/project-system/pull/2461 and should be available in tomorrow's build.

**Closed** 2017-06-21 09:14 UTC
