### ISSUE TITLE
Showing warning in solution file for ItemGroup properties with publishing docker with dotnet

### ISSUE THREAD

**Issue by mehdihadeli** [dotnet/project-system#9059] opened 2023-02-26 12:59 UTC
Hi,
I've created a docker image with `dotnet publish --os linux --arch x64 -p:PublishProfile=DefaultContainer` and this csproj file:

``` xml
  <PropertyGroup>
    <ContainerImageName>test</ContainerImageName>
    <ContainerImageTag>dev</ContainerImageTag>
    <ContainerBaseImage>mcr.microsoft.com/dotnet/aspnet:latest</ContainerBaseImage>
  </PropertyGroup>
  <ItemGroup>
    <ContainerEnvironmentVariable Include="ASPNETCORE_ENVIRONMENT" Value="docker" />
  </ItemGroup>
```
but when I add `ContainerEnvironmentVariable` element or `ContainerPort` to `ItemGroup` according [docs](https://learn.microsoft.com/en-us/dotnet/core/docker/publish-as-container#containerenvironmentvariable) it adds these items to solution with warning, icon I think it should not be visible in the solution
![1](https://user-images.githubusercontent.com/3678399/221411850-96a6a945-5c28-4d35-9386-a2812f31822d.png)

**Comment by drewnoakes** [comment] 2023-06-02 11:33
@mehdihadeli from your screenshot it looks like you are using Rider, not Visual Studio.

This issue should likely be filed for JetBrains to investigate at https://youtrack.jetbrains.com/issues/rider

If the problem also occurs in Visual Studio, let us know, otherwise we will close this. Thanks!

**Comment by melytc** [comment] 2023-06-08 23:08
This seems like it's not a bug in our repo, closing it.

**Closed by melytc** 2023-06-08 23:08 UTC
Labels: untriaged
