### ISSUE TITLE
Create IntelliTest with error

### ISSUE THREAD

**Issue by MiaomiaoHuangfu** [dotnet/project-system#2913] opened 2017-10-20 14:26 UTC
- Create a Class Library project named ClassLibrary1;
- Place some sample test code into your test method;
- Right click in the class and Click on "IntelliTest -> Create IntelliTest";
- Right click in the class again and click on "IntelliTest -> Run IntelliTest";

**Expected Result:** IntelliTests will be created with no error
**Actual Result:** IntelliTests is created, but with an error in output window "[Failure] Could not find file 'c:\users\v-mihuan\source\repos\PEXClassLibrary1\ClassLibrary1.Tests\UnitTest1.cs'."
However, run IntelliTest succeeded with no error.

Test on d15rel.27019.00
OS: Windows 10 x64 ENU

**Comment by Pilchie** [comment] 2017-10-23 22:56
Duplicate of https://github.com/dotnet/roslyn/issues/12202

**Closed by Pilchie** 2017-10-23 22:56 UTC
