### ISSUE TITLE
UpToDateCheckInput always rebuilds with multiple TargetFrameworks

### ISSUE THREAD

**Issue by CarlosOnline** [dotnet/project-system#4458] opened 2019-01-11 19:20 UTC
**UpToDateCheckInput** always rebuilds with multiple TargetFrameworks

See repro in [UpToDateCheckInputBug](https://github.com/CarlosOnline/UpToDateCheckInputBug)

The bug only occurs when using multiple frameworks: `<TargetFrameworks>netstandard2.0;net471</TargetFrameworks>`

Single framework works as expected.
        <Project Sdk="Microsoft.NET.Sdk">

          <PropertyGroup>
            <TargetFrameworks>netstandard2.0;net471</TargetFrameworks>
          </PropertyGroup>

            <ItemGroup>
                <UpToDateCheckInput Include="$(SolutionDir)\ExternalDependency.txt" />
            </ItemGroup>

            <Target Name="PreBuild" BeforeTargets="PreBuildEvent">
              <Exec Command="echo Starting Build" />
            </Target>

        </Project>
`
**Repro:**
- Load solution
- Build solution
- Touch ExternalDependency.txt in solution folder
- Build solution (expects new build)
- Build solution **(project is rebuilt even though nothing changed - this is the bug)**

**Comment by jjmew** [comment] 2019-01-14 20:39
this is a duplicate of #2487

**Closed by jjmew** 2019-01-14 20:39 UTC
Labels: Feature-Up-to-date, Resolution-Duplicate, Triaged

**Comment by davkean** [comment] 2019-02-15 07:40
@CarlosOnline I repro'd this both in single framework and multi framework projects. The behavior is by design if the repro project correctly represents the issue you were encountering. If you turn on logging (Options -> Projects and Solutions -> .NET Core -> Logging Level, you will see the following in the output Window:

```
1>FastUpToDate: Input 'E:\UpToDateCheckInputBug\ExternalDependency.txt' is newer (2/15/2019 6:32:07 PM) than earliest output 'E:\UpToDateCheckInputBug\UpToDateCheckInputBug\bin\Debug\netstandard2.0\UpToDateCheckInputBug.dll' (2/15/2019 6:31:26 PM), not up to date. (UpToDateCheckInputBug)
```

Basically you have an input ExternalDependency.txt that doesn't cause any outputs to change. That's the bug, if inputs don't affect outputs, it shouldn't be an input.
