### ISSUE TITLE
Checking "XML Documentation File" creates DocumentationFile element with fully qualified path rather than relative

### ISSUE THREAD

**Issue by davevans** [dotnet/project-system#4050] opened 2018-09-21 04:19 UTC
In a netstandard class library or dotnet core app, clicking the "XML documentation file" checkbox on the build tab of the project properties now adds the `DocumentationFile` element on the csproj with a _fully qualified path_ to the XML document to be created on build.

Previously this path was previously relative and remains so for non-sdk project files. This causes issues for build servers where the path of drive specified in the fully qualified path does not exist. It can also put developers usernames into DocumentationFile paths depending on where they have checked code out to on their local system.

**Comment by Pilchie** [comment] 2018-09-25 16:16
Dupe of https://github.com/dotnet/project-system/issues/368 :(

**Closed by Pilchie** 2018-09-25 16:16 UTC
Labels: Resolution-Duplicate
