### ISSUE TITLE
High CPU when target framework is empty

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#3670] opened 2018-06-26 08:42 UTC
Opening the following projects causes VS to constantly consume CPU:

``` XML
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework></TargetFramework>
  </PropertyGroup>

</Project>
```

or 

``` XML
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks></TargetFrameworks>
  </PropertyGroup>

</Project>
```

Design time builds are constantly occurring in the background.

Also hit by https://github.com/dotnet/project-system/issues/3489 by AWS SDK.

**Comment by davkean** [comment] 2018-06-26 08:44
Pretty sure this is dependency node.

This was hit by an MVP.

**Comment by Pilchie** [comment] 2018-06-26 15:06
@davkean did you look at all?  Is this an infinite restore loop?

**Comment by jmarolf** [comment] 2018-06-26 17:39
just tried this scenario.  Its infinite restore.

**Comment by davkean** [comment] 2018-06-26 21:53
It didn't look like infinite restore - it was infinite design-time builds but that will likely be dependency node reinitializing over and over.

**Comment by Pilchie** [comment] 2018-06-27 00:21
Oh, right - dupe of #3489 then?

**Comment by davkean** [comment] 2018-06-27 04:50
Yep, dup'd it against this one.

**Comment by eerhardt** [comment] 2018-07-05 23:45
I'm hitting this in `dotnet/corefx` after updating the .csproj's to SDK-style projects.

To repro:

1. pull https://github.com/wtgodbe/corefx/tree/SdkProj  (the branch from PR https://github.com/dotnet/corefx/pull/29831).
2. Build once from the root of the repo on the commandline: `build.cmd`
3. Open `src\System.Collections\System.Collections.sln`.

However, in my scenario I don't see any design-time builds continually happening using the [`Build Logging`](https://github.com/dotnet/project-system/blob/5d9e844bff2cdfc49fc0e893e84f476e05282821/docs/design-time-builds.md#visual-studio-2017-version-154-or-later) window.  However, it is consuming a lot of CPU:

![image](https://user-images.githubusercontent.com/8291187/42353013-826ca0d2-8083-11e8-9be3-5573b043f806.png)

**Comment by Pilchie** [comment] 2018-07-06 00:00
Can you collect an ETL trace during this period?  https://github.com/dotnet/roslyn/wiki/Recording-performance-traces-with-PerfView

**Comment by eerhardt** [comment] 2018-07-06 15:46
I took 2 traces.
1. With the solution already loaded, and eating CPU in the background, I ran the trace for about 10 seconds.
2. A full trace of loading VS, loading the solution, and then letting it run for ~30 seconds.

I uploaded them to the internal scratch file share:  `\\scratch2\scratch\eerhardt`

**Comment by Pilchie** [comment] 2018-07-08 17:50
@sharwell and/or @davkean - care to take a look?

**Comment by davkean** [comment] 2018-07-09 03:47
@eerhardt Can you verify that you have a TargetFramework to verify if its just another symptom of that? This is slated for 16.0, so won't look at until then if its a dupe.

**Comment by eerhardt** [comment] 2018-07-09 19:28
Yes, setting `TargetFramework` makes the CPU usage drop down to nothing when VS is in the background.

The only behavior difference I noticed from the originally described issue is:

> Design time builds are constantly occurring in the background.

I wasn't seeing any design-time builds happening in the `Build Logging` window.

**Comment by davkean** [comment] 2018-07-10 01:21
Thanks. 

It might be good to sync up on CoreFx's requirements and why you can't use TargetFrameworks/TargetFramework. I've had your situation in the back of my mind, and want to address it and make it work for you out of the box.

**Comment by eerhardt** [comment] 2018-07-10 02:30
Agreed.  @weshaggard would have the best background knowledge.

I haven't completely ruled out that we can't use TargetFrameworks/TargetFramework yet. We are [setting TargetFramework](https://github.com/dotnet/corefx/blob/7c28084bb60689f15fc6119c3d11964a5335c4f5/src/Directory.Build.targets#L64) to workaround this issue. It's just that it is kind of a meaningless concept in the corefx repo's projects.  In "normal" projects, it defines which version of netcoreapp/netstandard/netfx you want to reference.  In corefx, we aren't referencing a framework. Instead, we are defining the framework.

**Comment by davkean** [comment] 2018-07-10 02:36
Think of "TargetFramework" as simply another open-ended dimension at which you can specialize a configuration like Platform and Configuration, except it's treated slightly different:

- We build all of them by default
- We provide IntelliSense for all of them

You can call your target frameworks "foo" and "bar" if you'd want (assuming you fill in the details, TargetFrameworkIdentifier, TargetFrameworkVersion, etc that we produce from the friendly name)

**Comment by weshaggard** [comment] 2018-07-10 23:44
Aren't there other assumptions made about those properties as well? For example doesn't Nuget interpret them?

**Comment by davkean** [comment] 2018-07-11 00:18
Barring bugs, TargetFramework is supposed to be treated as a "user value". NuGet gets the full TFM that we generate from TargetFramework, and is supposed to be only using TargetFramework in conditions within the generated props files.

**Comment by onovotny** [comment] 2018-07-11 00:35
> You can call your target frameworks "foo" and "bar" if you'd want (assuming you fill in the details, TargetFrameworkIdentifier, TargetFrameworkVersion, etc that we produce from the friendly name)

This actually won't work because of NuGet validations. When I initially tried to implement multi-RID builds, I attempted it by using/abusing TFM's like `netstandard2.0+win-x86`. I had to monkey-patch a lot of targets to make it work despite setting `NuGetTarketMoniker`, `TargetFrameworkIdentifier` and `TargetFrameworkVersion` correctly. NuGet just blew up with unsupported/unknown TFM's.

**Comment by onovotny** [comment] 2018-07-11 00:36
> My ultimate aim is to be able to able to specialize on other things; such as RID. It would be helpful if we could feed your requirements in so that what we develop around this works for you and you can stop working around MSBuild/VS

I made this work today by making the outer loop get the RID's for the TFM and pass that into the inner loop:
https://github.com/onovotny/MSBuildSdkExtras/blob/db55a020a7d7d0d7119ff01c3104a9dd62a51f11/Source/MSBuild.Sdk.Extras/Build/RIDs.targets#L23

It works and builds, in VS and the command-line, but the project system/IDE knows nothing about it. So no IntelliSense for that combination (to catch the define's for each RID).

**Comment by davkean** [comment] 2018-07-11 00:37
It's not supposed to be interpreting that value, at least that was the original design - but there's going to be bugs here. I'm rewriting our usage of TFM at the moment, and then I'll start pushing on other teams.

**Comment by onovotny** [comment] 2018-07-11 00:45
Here's where NuGet Restore (at least) is validating the tfm itself: 

https://github.com/NuGet/NuGet.Client/blob/b82a7274e5f58c8af2eb052b8ff98d3d29fed66e/src/NuGet.Core/NuGet.Commands/RestoreCommand/Utility/SpecValidationUtility.cs#L131

I would expect that it should be based on a NuGetTargetMoniker value, so I can define my own TFM and say "use netstandard2.0" for it. No dice today.

**Comment by nguerrera** [comment] 2018-07-11 02:21
We did fully intend for TargetFramework do be open ended, but there are definitely issues. Another place where there's a problem is where we negotiate tfms between project references. It passes the TargetFrameworks to nuget to pick the "nearest" one. It would be prohibitively expensive to get all of the full tfms there in the current design. And even if we could there would cases where you have the same full TFM for different custom TF. I think the only out would be to require such P2Ps to skip the negotiation and manually assign the desired TF. There are bugs around doing that though, IIRC.

**Comment by davkean** [comment] 2018-07-11 04:29
> It passes the TargetFrameworks to nuget to pick the "nearest" one.

Ah, yeah, forgot about this case - we'd need the same translation logic in the outer build, or call into the inner build - which would be expensive.

**Comment by onovotny** [comment] 2018-07-11 17:29
@davkean @nguerrera do either of you know off hand where this logic lives in the targets? Would save me some spelunking time.

**Comment by nguerrera** [comment] 2018-07-11 17:38
https://github.com/Microsoft/msbuild/blob/ffa7f408e8d00bda677cfb0ec15d547acf2aea06/src/Tasks/Microsoft.Common.CurrentVersion.targets#L1571-L1582

**Comment by nguerrera** [comment] 2018-07-11 18:14
Related: https://github.com/NuGet/Home/issues/5154

**Comment by davkean** [comment] 2019-12-04 23:56
@ocallesp This is likely the cause: https://github.com/dotnet/project-system/issues/3670#issuecomment-400475289.

**Comment by davkean** [comment] 2019-12-04 23:58
Have a look inside AggregateCrossTargetProjectContext where it persists the targetfamework.

**Comment by drewnoakes** [comment] 2019-12-10 01:00
@ocallesp feel free to reach out if you would like to discuss this.

**Comment by ocallesp** [comment] 2019-12-18 00:49
@davkean this issue is only reproducible in VS 2017. Not able to repro in VS 2019/master.

**Closed** 2019-12-18 01:07 UTC
Labels: Bug, Feature-Dependency-Node, Tenet-Performance, Triaged-Approved
