### ISSUE TITLE
Implicit assemblies for framework assemblies should also be under SDK node

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#1413] opened 2017-02-01 06:34 UTC
We should group the implicit assemblies for framework assemblies under the SDK node as well, similar to what we did with Portable, UWP, etc.

**Comment by davkean** [comment] 2017-02-01 06:36
![image](https://cloud.githubusercontent.com/assets/1103906/22497307/ecb2da38-e8a4-11e6-8797-f1259f747266.png)

However, we should group the assemblies under the node so you can see them.

**Comment by abpiskunov** [comment] 2017-02-01 17:45
hm good point to bring up .. It is not clear actually. You might have implicit assemblies coming from any target - how can you map them to a particular SDK X? It could be not possible .. May be we could keep assemblies under Assemblies node and just mark them with a specific icon "Assembly with some sign" or create a subfolder under Assemblies node "Framework assemblies"?

**Comment by davkean** [comment] 2017-02-01 21:21
@abpiskunov The same way with it in the legacy project system, via the ReferenceGrouping metadata.

**Comment by abpiskunov** [comment] 2017-04-07 21:21
This is pretty easy to do after https://github.com/dotnet/project-system/pull/1880 . 

It would require 
- changes in SDK, that would have to add metadata to implicit assemblies: IsImplicitlyDefined=True and corresponding ReferenceGrouping.
- Implement IDependenciesSnapshotFilter that would update snapshot when new implicit assemblies are added/removed or sdk nodes are added/removed

Not sure if i will have time to do it, so just posting this solution for next owner.

**Comment by srivatsn** [comment] 2017-04-19 20:30
@abpiskunov this is fixed by https://github.com/dotnet/project-system/pull/2010 right?

**Comment by abpiskunov** [comment] 2017-04-19 21:07
No. I am not convinced we should do that at all. Sdk represents actually a complete set of default assemblies available for some target netcoreapp netstandard etc, when if the example here its just some subset of framework assemblies etc .. It just does not look the same to me in this case. Because if we group that subset under Sdk\"NetFxAssemblies" node  when user adds a refrences to another Net46 assembly  in his project  - that one would appear under Assemblies group , which would be completely confusing... 

I propose don't do this at all.

**Comment by srivatsn** [comment] 2017-04-19 21:52
By "fixed" I meant that they'll now show up with the implicit icon. Dave, were you looking just for a different treatment or that they should be grouped into a SDK? What information does the ReferenceGrouping metadata have btw?

**Comment by abpiskunov** [comment] 2017-04-19 22:02
yes they will have implicit icon now, no grouping changed.

**Comment by drewnoakes** [comment] 2019-06-26 12:26
Another approach to achieve the same result would be to visit the targeting pack on disk and discover the assemblies there directly and add them as graph nodes.

This data could be cached across all projects in the solution, allowing graph node reuse.

This might potentially provide less metadata on those referenced assemblies.

**Comment by drewnoakes** [comment] 2019-06-26 12:33
Closing as a duplicate of #4444. Even though this came first, the other has more up-to-date context and a better issue number.

**Closed by drewnoakes** 2019-06-26 12:33 UTC
Labels: Feature Request, Feature-Dependency-Node, Triaged
