### ISSUE TITLE
XML for adding a code gen'd resources file is very verbose

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#1158] opened 2017-01-13 07:47 UTC
Adding a resources file to the project, results in the following code gen:

``` XML
 <ItemGroup>
    <Compile Update="Resource1.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resource1.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Resource1.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Resource1.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

```

This is extremely verbose and we should fix it.

**Comment by dmonroym** [comment] 2020-08-27 23:55
Dupe of https://github.com/dotnet/project-system/issues/3764

**Closed by dmonroym** 2020-08-27 23:55 UTC
Labels: Bug

**Comment by jnm2** [comment] 2020-08-27 23:58
@dmonroym I believe this may be a dupe of https://github.com/dotnet/project-system/issues/5707 rather, based on https://github.com/dotnet/project-system/issues/3764#issuecomment-610204101.

**Comment by dmonroym** [comment] 2020-08-31 22:18
@jnm2 Indeed, thanks for that!
