### ISSUE TITLE
Project references are successfully added however they show as missing.

### ISSUE THREAD

**Issue by rolandh** [dotnet/project-system#3134] opened 2018-01-12 00:27 UTC
I have multiple projects added as references to my project. They sporadically disappear after a successful build

When I go to add the references back they are shown as already added and ticked, but they are missing from the "Projects" drop down and I get intellisense errors.

Only way to fix the issue is to remove the project reference and add it back. This occurs 10+ times a day while working on the project.

I'm using 15.6 preview and C#7.2

I cannot produce a repro other than this private solution, though I have had it occur on other projects. I can organise a teamviewer/skype desktop sharing session if that helps.

All projects are using the new csproj format. I rectified the problem by reverting the old csproj format in other projects. This project is netcore compiled for 4.6.1 so I must use the new csproj format and hence there is no workaround for me.

This screenshot shows the problem.
![image](https://user-images.githubusercontent.com/1109554/34854052-365a2d84-f787-11e7-8005-32f4d0cb8433.png)

I've also raised the problem here, csproj files are privately attached.
https://developercommunity.visualstudio.com/content/problem/181333/references-added-to-project-but-appear-as-missing.html

Windows 10 x64
VS 15.6 Preview
dotnet --info
.NET Command Line Tools (2.1.2)
Product Information:
 Version:            2.1.2
 Commit SHA-1 hash:  5695315371

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.2\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.3
  Build    : a9190d4a75f4a982ae4b4fa8d1a24526566c69df

**Comment by Pilchie** [comment] 2018-01-12 17:20
@jviau / @lifengl - does this look like the issue in https://github.com/dotnet/project-system/issues/3117?

**Comment by rolandh** [comment] 2018-01-15 01:36
Anyone able to assist with this? Im considering not using netcore anymore due to how frustrating it is.

**Comment by jviau** [comment] 2018-01-16 19:45
@Pilchie it is possible it is related. I would need a repro to confirm that.

**Comment by lifengl** [comment] 2018-01-16 20:27
Do you see any error message dialogue popping up in the scenario?

Turning on the design time build log might help?  Either the design time build is no longer running because of previous errors or builds might fail .

Sent from my phone

On Jan 16, 2018, at 11:45 AM, Jacob Viau <notifications@github.com<mailto:notifications@github.com>> wrote:


@Pilchie<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpilchie&data=02%7C01%7C%7C3445301956dd4077321008d55d19c181%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636517287554715227&sdata=ISCoXvqOwCD5xfiFBKA1COcm5wZFLO3p8oM7DCZHK1Y%3D&reserved=0> it is possible it is related. I would need a repro to confirm that.

**Comment by rolandh** [comment] 2018-01-16 22:08
No error is displayed. How do i turn on the design time log?

**Comment by Pilchie** [comment] 2018-01-16 22:15
Take a look at https://github.com/dotnet/project-system/blob/master/docs/design-time-builds.md.

**Comment by lifengl** [comment] 2018-01-17 03:41
Using the batch file to turn on the feature, and you can see design time build log in a new output window tab.  Changing build log configuration, you can get more detailed logging.

Sent from my phone

On Jan 16, 2018, at 2:15 PM, Kevin Pilch <notifications@github.com<mailto:notifications@github.com>> wrote:


Take a look at https://github.com/dotnet/project-system/blob/master/docs/design-time-builds.md<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdotnet%2Fproject-system%2Fblob%2Fmaster%2Fdocs%2Fdesign-time-builds.md&data=02%7C01%7C%7C0d5bc2f8e2014fe3ca3b08d55d2ea76a%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636517377314986296&sdata=GuY%2BmEF8mPBIM6kVcLa%2FVX1pCSmh8WLnuzXC2qJmjqI%3D&reserved=0>.

**Comment by natidea** [comment] 2018-02-13 19:04
I also noticed looking at your project files that you have some custom configurations. See https://github.com/dotnet/project-system/blob/master/docs/configurations.md for changes to the way custom configurations are specified in the new project system. This may not be related to your problem but probably worth looking into.

**Comment by BlueSilverCloud** [comment] 2018-07-27 16:43
Any resolution to this issue? 
I am experiencing the same problem, with 
Microsoft Visual Studio Enterprise 2017 Version 15.7.5
VisualStudio.15.Release/15.7.5+27703.2042
Microsoft .NET Framework Version 4.7.02556

System loses reference to specific project, red squiggly lines appear and intellisense will not function for objects from that project. Exit and restart Visual Studio and system works again -- for a while! No idea what triggers the melt-down.

![image](https://user-images.githubusercontent.com/41800153/43334056-202babca-9181-11e8-95cd-2df6ea20ece4.png)

**Comment by Pilchie** [comment] 2018-07-27 19:11
Can you try running with with an environment variable `PROJECTSYSTEM_PROJECTOUTPUTPANEENABLED=1` and capture the text from the Output Window pane for the project system when this happens?  It should let us know at least whether the project system passed the reference to the language service or not.

**Comment by BlueSilverCloud** [comment] 2018-07-27 22:58
There are 24 projects in the solution.
Does this setting have to be set at the project level for each project?
Is there a location to set this for the solution as a whole?

**Comment by Pilchie** [comment] 2018-07-30 15:43
You want to set it in the Visual Studio process environment, not in projects directly. See https://github.com/Pilchie/project-system/blob/238c3f1a7a9aa1eb3bb973e9fc90ddb660042f30/docs/repo/debugging/logging.md

**Comment by BlueSilverCloud** [comment] 2018-07-31 07:40
I did that. But I dont see pane title project in the dropdown. Here is my
dropdown.



The problem occurred again today, while I had the environment variable
setup, but I dont know where to get your information from.
The exception that you see in the background is fault in my software that I
am debugging.

Here are the squigglies after VS lost track of the references. Sometimes
(as is the case in the snapshot below), I am able to build successfully and
rerun the app fine, even though these squigglies are present, and the only
impact is with Intellisense. Sometimes, however, the system won't build and
I have to restart VS to be able to build successfully.

**Comment by davkean** [comment] 2018-07-31 09:54
@Pilchie Above is the legacy project system. 

@BlueSilverCloud 

1. Please install https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.ProjectSystemTools.
2. Wait until it occurs again
3. Choose View -> Windows -> Build Logging
4. Turn on logging from the toolbar
5. In the project that loses the intellisense, right-click on a any file and exclude it from the project
6. Zip and share the resulting build that shows up in the window

**Comment by BlueSilverCloud** [comment] 2018-07-31 16:42
Will do.

**Comment by BlueSilverCloud** [comment] 2018-08-05 21:24
Occurred today. Followed the script above. [Had previously installed the
tools].

Snapshot of the Build Logging window. Is this what you wanted to see?

**Comment by BlueSilverCloud** [comment] 2018-08-05 21:26
I also tried a build after excluding the file (which is expected to fail,
since required file has been excluded). This is build logging snapshot
right after.

**Comment by BlueSilverCloud** [comment] 2018-08-05 21:32
I exited VS. Reloaded and tried my compile again. I knew that I had a
compile problem, which VS was now able to flag for me. Note the compile
error is in BllCompute, while the Intellisense failure is for project DTO,
which is way early in the dependency chain]. Now that I know where my
compile error is, I am able to fix it and continue.

This is slightly different that before, in that I have also experienced
loss of Intellisense without any compile errors, and the project will run.
I will repeat this process when such situation reoccurs.

Thanks
Rohan

**Comment by BlueSilverCloud** [comment] 2018-08-05 22:11
Here you go.


Just finished a debug session. Switched to release build, to being a
performance profile. Lost my intellisense.

**Comment by BlueSilverCloud** [comment] 2018-08-05 22:13
Added the excluded file back in, and can build just fine. Even though the
squigglies remain.

**Comment by iPazooki** [comment] 2018-09-11 07:20
I have exactly the same issue with **Visual Studio 15.8.3**. interesting point is that it was OK until yesterday and now today, it can't find some references while it compiles without any problem!?!

**Comment by iPazooki** [comment] 2018-09-11 07:36
My temporary solution was **Loading** and **UnLoading** projects that were missing!

**Comment by drewnoakes** [comment] 2019-02-15 12:14
@rolandh looking at the project files you shared, one thing the disappearing projects all had in common is manually importing the SDK properties:

```
<Project>
  <PropertyGroup>
    <BaseIntermediateOutputPath>obj\</BaseIntermediateOutputPath>
  </PropertyGroup>
  <Import Project="Sdk.props" Sdk="Microsoft.NET.Sdk" />
```

Are you still seeing this problem? Can you reproduce it in the latest VS2019 preview?

**Comment by rolandh** [comment] 2019-02-16 01:40
@drewnoakes I don't do much development on the project that was causing the problem, but I can confirm that I have not seen this reoccur in almost a year now. I'm fairly confident it has been resolved, at least the problem I had has been resolved. 

My project still has the import Sdk.props included. I don't remember if I added this my self or if it was automatic, or possibly even when I converted from 461 to netcore it was left over.

Do I need that line? What does it even do? Would you suggest removing it?

**Comment by ppumkin** [comment] 2019-05-29 10:28
The team I work with and myself got this issue recently after upgrading some of our libraries to NetStandard. VS 2017, VS2019 all versions up (as of writing June 2019)

I did an in place upgrade as such

1. Created a new `NetStandard.csproj` from VS and copied it out to a temp location
1. Copy that `NetStandard.csproj` into an existing project library folder
1. Copy name then rename existing Net4.5 based project to `OurUtilities.csproj.bak`
1. Rename `NetStandard.csproj` to `OurUtilities.csproj`
1. Delete obj, bin, packages.config, app.config binding redirects and any other garbage

Back in visual studio it asks to reload everything. OK. The project is restores the NetStandard SDK and complaing about references and packages missing. Fair enough, I add references back and only after that missing NuGets if not resolved automagically if the referenced project was not NetStandard too.

- **Me**: Build. OK! Release. OK!
- **Other developers**:  complaining after pulling that some files lots of red squiggly lines showing but all references are there. I said delete .vs folder. Nope, that didn't help.

The only solution to resolve this is remove and add a reference that is there already. All other references errors goes away. OK. Commit.  NO CHANGES!?

I come back the next day after pulling more changes. The same things starts happenening in projects higher up that used to reference the NET45 but now is NETSTANDARD. BUT, when I build its all OK! IN the IDE its red line hell. Add remove any arbitrary reference, all good no more errors.

The reason I did in place csproj swap out is because we have about 400 projects and I am no way in hell am I going to go through 400 projects re adding reference to a new project (GUID) 400 times so like worst case scenario 160million times. This way is quick, painless and works. 

Apart from this weird IDE problem that happens for all devs after pulling, but only once per file. So everybody has to do this add remove reference work around once on their machine and the issue goes away. Is there any VS cache, work space thing that can be purged?

**Comment by davkean** [comment] 2019-06-04 01:32
@ppumkin I've re-read your comment a few times and it's not clear its relationship with the original isse. @rolandh has mentioned he hasn't seen the issue recently and its sounds very different to yours. Based on that I'll close this issue so that we avoid reusing this issue to represent "all reference-like errors".  

For your issue can you please file a new bug with a repro project or repository and steps indicates the issue? Commits for the steps would be extremely helpful.

**Closed by davkean** 2019-06-04 01:32 UTC
Labels: Bug, Feature-Dependency-Node, Project-System-CPS, Triaged

**Comment by rolandh** [comment] 2019-06-04 02:01
@davkean I have not seen a repeat of this problem come back in many months. I believe my original problem has been resolved in a later update.
