### ISSUE TITLE
Making a change too quickly after saving a project file duplicates content

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#5181] opened 2019-07-25 21:53 UTC
**Visual Studio Version**:
Version 16.3.0 Preview 2.0 [29124.198.master]

**Summary**:
![ProjectFileEditing](https://user-images.githubusercontent.com/1103906/61911272-58ab4100-af7a-11e9-8f7b-d11ce075485f.gif)

**Steps to Reproduce**:
See GIF, I've pasted a few lines -> save and then as I'm adding new lines additional copies of the same thing I've pasted appear. There should only be 5 copies of the Import, there ends up being 7 as its duplicated content from the time I saved to the time its finished updating the buffer.

**Expected Behavior**:

**Actual Behavior**:

**User Impact**:

**Comment by davkean** [comment] 2019-07-25 21:55
cc @davidwengier

**Comment by davidwengier** [comment] 2019-07-25 22:00
Looks like the duplicate line comes in about a second after saving, which coincidentally is how long the project reload is delayed for. It would then be merging the buffer contents you're editing with the contents of the file on disk, and I guess that is deciding you need extra imports for some reason.

That 1 second delay has caused me problems in the past, I'll have to see if I can work out why its so long, or whether its necessary at all. Though the problem could be compounded by the fact that you're creating lots of duplicate content, so the merge algorithm has hard time. Will have to check if it happens with just typing.

**Comment by davkean** [comment] 2019-07-25 22:02
It's adding two duplicate lines. This happens to be me a bunch, regardless of the time it takes, we shouldn't be duplicating content at all based on timing.

**Comment by davidwengier** [comment] 2019-07-25 22:14
This is probably the same root cause as #4940 too. Both repro in VS2017.

**Comment by davidwengier** [comment] 2019-12-17 06:21
A fix for this would be to force the project to reload immediately on Save, rather than queue the reload, and block the editor while its happening

**Comment by davidwengier** [comment] 2019-12-18 21:13
Looked into this a bit and seems the design around this needs fixing. Currently when saving the project file there are two saves, the first for the UnconfiguredProject if it has changes, and the second for the text buffer for the user changes. We then reload the project, as the text changes weren't applied to the project, and the file change watching are suppressed while saving.

The first save is important as if project file editing isn't active (eg, no capability) then thats the only time that changes can be saved. If project file editing is active then the second save will always contain the changes from the first, so the first is arguably unnecessary. It might be a better approach however to simply apply the changes from the buffer (ie, reload the project) before saving, though that needs testing to ensure we're not kicking off unnecessary processing at the wrong time.

**Comment by davidwengier** [comment] 2020-03-30 03:41
Closing as a duplicate of #5430

**Closed by davidwengier** 2020-03-30 03:41 UTC
Labels: Bug, Feature-Project-File-Editing, Needs-CPS-work, Triage-Approved
