### ISSUE TITLE
The process cannot access the file  warning during build

### ISSUE THREAD

**Issue by abpiskunov** [dotnet/project-system#3257] opened 2018-02-14 16:49 UTC
Our automated tests in vsuwpt sometimes fail with unexpected warning in the Error List (see below).

What happens is 
- previous test opens the same solution and builds at the end (verifies there no error or warnings).
- then solution is saved and closed
- next test is running , opens the same solution, waits for restore and builds
- verifies there no errors and warnrings

It is probably some kind of timing in between build/close/open/build which leaves msbuild/dotnet open and holding that file. This can be reproduced manually by user (and appear randomly). I have see similar warnings several times overall, but could not get consistent repro. Test does not fail every time also. 

 
Assert.IsTrue failed. List contained warnings: Could not read state file "obj\Debug\netcoreapp2.0\App1.csprojResolveAssemblyReference.cache". The process cannot access the file 'D:\dd\WTE\Main\TestResults\Deploy_asplab 2018-02-13 22_19_57\Out\MS.VS.PS.Web\TestSolution\DDRITs\Web\App1\obj\Debug\netcoreapp2.0\App1.csprojResolveAssemblyReference.cache' because it is being used by another process.
Assert.Fail failed. Failure encountered during test
 Screen shot and log at D:\dd\WTE\Main\TestResults\Deploy_asplab 2018-02-13 22_19_57\Out\omniLog.html
   at Microsoft.VisualStudio.Web.Common.TestServices.WebVerifier.VerifyNoWarnings() in D:\dd\WTE\Main\test\Common\TestServices\Apex\WebVerifier.cs:line 55
   at Microsoft.VisualStudio.Web.Common.TestServices.WebVerifier.VerifyBuildSucceeded() in D:\dd\WTE\Main\test\Common\TestServices\Apex\WebVerifier.cs:line 19
   at Microsoft.VisualStudio.ProjectSystem.Web.IntegrationTests.DotNetCoreDDRITTests.VerifyBuild() in D:\dd\WTE\Main\test\ProjectSystem\Web.IntegrationTests\Tests\DDRITs\DotNetCoreDDRITTests.cs:line 248
   at Microsoft.VisualStudio.ProjectSystem.Web.IntegrationTests.DotNetCoreDDRITTests.DotNetCoreDDRIT_Web_Test() in D:\dd\WTE\Main\test\ProjectSystem\Web.IntegrationTests\Tests\DDRITs\DotNetCoreDDRITTests.cs:line 142

TestCleanup Stack Trace
   at Microsoft.VisualStudio.Web.Common.TestServices.VisualStudioHostWebTest.TestAttributeValidateAndDeactivate() in D:\dd\WTE\Main\test\Common\TestServices\Apex\VisualStudioHostWebTest.cs:line 398
   at Microsoft.VisualStudio.Web.Common.TestServices.VisualStudioHostWebTest.DoHostTestCleanup() in D:\dd\WTE\Main\test\Common\TestServices\Apex\VisualStudioHostWebTest.cs:line 254
   at Microsoft.Test.Apex.ExternalProcessHostTest`2.TestCleanup() in d:\VS\src\Omni\Apex\MsTestIntegration\ExternalProcessHostTest.cs:line 132
   at Microsoft.Test.Apex.VisualStudio.VisualStudioHostTest.TestCleanup() in d:\VS\src\Omni\Apex\MsTestIntegration\VisualStudioHostTest.cs:line 198

**Comment by Pilchie** [comment] 2018-02-14 17:04
I believe this is the issue where a DTB and a real build can be happening at the same time.  @lifengl - is there a CPS issue tracking this already?

**Comment by davkean** [comment] 2018-02-14 22:38
Dupe of https://github.com/dotnet/project-system/issues/2898.

**Closed by davkean** 2018-02-14 22:38 UTC
Labels: Area-External-CPS
