### ISSUE TITLE
Project system hanging on shutdown.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/project-system#2403] opened 2017-06-08 01:40 UTC
We're hitting this on jenkins.  For example, here: 
https://ci.dot.net/job/dotnet_roslyn/job/dev15.6/job/windows_release_vs-integration_prtest/157/

UI stack is:

```
 	_ZwWaitForMultipleObjects@20()	Unknown
 	WaitForMultipleObjectsEx(nCount, lpHandles, bWaitAll, dwMilliseconds, bAlertable)	C
 	WaitForMultipleObjects(nCount, lpHandles, bWaitAll, dwMilliseconds)	C
 	684a3812()	Unknown
 	[Frames below may be incorrect and/or missing, native debugger attempting to walk managed call stack]	
 	684a3812()	Unknown
 	[Managed to Native Transition]	
>	Microsoft.VisualStudio.Threading.NoMessagePumpSyncContext.Wait(waitHandles, waitAll, millisecondsTimeout)	C#
 	System.Threading.SynchronizationContext.InvokeWaitMethodHelper(syncContext, waitHandles, waitAll, millisecondsTimeout)	C#
 	[Native to Managed Transition]	
 	7232a507()	Unknown
 	[Managed to Native Transition]	
 	System.Threading.Monitor.Wait(obj, millisecondsTimeout, exitContext)	C#
 	System.Threading.Monitor.Wait(obj, millisecondsTimeout)	C#
 	System.Threading.ManualResetEventSlim.Wait(millisecondsTimeout, cancellationToken)	C#
 	System.Threading.Tasks.Task.SpinThenBlockingWait(millisecondsTimeout, cancellationToken)	C#
 	System.Threading.Tasks.Task.InternalWait(millisecondsTimeout, cancellationToken)	C#
 	System.Threading.Tasks.Task.Wait(millisecondsTimeout, cancellationToken)	C#
 	System.Threading.Tasks.Task.Wait(timeout)	C#
 	Microsoft.VisualStudio.Threading.JoinableTaskFactory.WaitSynchronouslyCore(task)	C#
 	Microsoft.VisualStudio.Threading.JoinableTaskFactory.WaitSynchronously(task)	C#
 	Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()	C#
 	Microsoft.VisualStudio.Threading.JoinableTask<Microsoft.VisualStudio.ProjectSystem.VS.HResult>.CompleteOnCurrentThread()	C#
 	Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run<Microsoft.VisualStudio.ProjectSystem.VS.HResult>(asyncMethod, creationOptions)	C#
 	Microsoft.VisualStudio.ProjectSystem.ProjectMultiThreadedService.ExecuteSynchronously<Microsoft.VisualStudio.ProjectSystem.VS.HResult>(asyncAction)	Unknown
 	Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.HrInvoke.AnonymousMethod__0()	Unknown
 	Microsoft.VisualStudio.ProjectSystem.VS.HResult.Invoke(action, vsShellServiceProvider, projectFaultHandlerService, project)	Unknown
 	Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.HrInvoke(asyncAction, registerProjectFaultHandlerService)	Unknown
 	Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.Close()	Unknown
 	Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNodeWrapper.Close()	Unknown
 	[Native to Managed Transition]	
 	CProject::Close(fRemoveProjectDir)	C++
 	CSolution::RemoveProjectByCProject(pProject, fUnloadProject, nUnloadReasonID, dwUnloadStatus)	C++
 	CSolution::RemoveProjectByHierarchy(pHierarchy, fUnloadProject)	C++
 	CSolution::CloseSolutionElement(grfCloseOpts, pHier, docCookie)	C++
 	CSolution::ClearProjectsInternal(fSkipNested, projectsAlreadyClosed)	C++
 	CSolution::Clear(bClearProjects)	C++
 	CSolution::Close(fDoSave, fSaveAll, fUpdateMRU)	C++
 	CVSolution::Close::__l2::<lambda>()	C++
 	VsSupportErrorInfoSafeInvoke<HRESULT <lambda>(void) >(pfnFunctionImpl)	C++
 	CVSolution::Close(SaveFirst)	C++
 	_Invoke@12()	Unknown
 	NdrStubCall2(pThis, pChannel, pRpcMsg, pdwStubPhase)	C++
 	CStdStubBuffer_Invoke(This, prpcmsg, pRpcChannelBuffer)	C++
 	CUnivStubWrapper::Invoke(pMsg, pChnl)	C++
 	[Inline Frame] InvokeStubWithExceptionPolicyAndTracing::__l6::<lambda_1ba7c1521bf8e7d0ebd8f0b3c0295667>::operator()()	C++
 	ObjectMethodExceptionHandlingAction<<lambda_1ba7c1521bf8e7d0ebd8f0b3c0295667> >(action, pExceptionHandlingInfo, pExceptionHandlingResult, )	C++
 	[Inline Frame] InvokeStubWithExceptionPolicyAndTracing(pMsg, )	C++
 	DefaultStubInvoke(bIsAsyncBeginMethod, pServerCall, pChannel, pStub, pdwFault)	C++
 	[Inline Frame] SyncStubCall::Invoke()	C++
 	[Inline Frame] SyncServerCall::StubInvoke()	C++
 	[Inline Frame] StubInvoke(pMsg, pStdID, )	C++
 	ServerCall::ContextInvoke(pMessage, pStub, pChannel, pIPIDEntry, pdwFault)	C++
 	[Inline Frame] CServerChannel::ContextInvoke()	C++
 	[Inline Frame] DefaultInvokeInApartment()	C++
 	[Inline Frame] ClassicSTAInvokeInApartment()	C++
 	AppInvoke(pServerCall, pChannel, pStub, pv, pStubBuffer, pIPIDEntry, pLocalb)	C++
 	ComInvokeWithLockAndIPID(pServerCall, pIPIDEntry, pbCallerResponsibleForRequestMessageCleanup)	C++
 	[Inline Frame] ComInvoke()	C++
 	[Inline Frame] ThreadDispatch()	C++
 	ThreadWndProc(window, message, wparam, params)	C++
 	__InternalCallWinProc@20()	Unknown
 	[Inline Frame] InternalCallWinProc()	C
 	UserCallWinProcCheckWow(pActCtx, pfn, hwnd, msg, wParam, lParam, fEnableLiteHooks, )	C
 	DispatchMessageWorker(pmsg, fAnsi)	C
 	DispatchMessageW(lpMsg)	C
 	[Inline Frame] CCliModalLoop::MyDispatchMessage()	C++
 	CCliModalLoop::PeekRPCAndDDEMessage()	C++
 	CCliModalLoop::FindMessage(dwStatus)	C++
 	CCliModalLoop::HandleWakeForMsg()	C++
 	CCliModalLoop::BlockFn(ahEvent, cEvents, lpdwSignaled)	C++
 	ClassicSTAThreadWaitForHandles(dwFlags, dwTimeout, cHandles, pHandles, pdwIndex)	C++
 	CoWaitForMultipleHandles(dwFlags, dwTimeout, cHandles, pHandles, lpdwindex)	C++
 	VSResponsiveness::Detours::DetourCoWaitForMultipleHandles(dwFlags, dwTimeout, nCount, pHandles, lpdwindex)	C++
 	[Managed to Native Transition]	
 	System.Lazy<uint>.LazyInitValue()	C#
 	System.Lazy<uint>.Value.get()	C#
 	Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioMetadataReference.CurrentSnapshot.get()	Unknown
 	Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.AbstractProject.AddMetadataReferenceCore(reference)	Unknown
 	Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.AbstractProject.AddMetadataReferenceAndTryConvertingToProjectReferenceIfPossible(filePath, properties)	Unknown
 	Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.CPS.CPSProject.AddMetadataReference.AnonymousMethod__0()	Unknown
 	Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.CPS.CPSProject.ExecuteForegroundAction(action)	Unknown
 	Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.CPS.CPSProject.AddMetadataReference(referencePath, properties)	Unknown
 	Microsoft.VisualStudio.ProjectSystem.LanguageServices.Handlers.MetadataReferenceItemHandler.Handle(added, removed, context, isActiveContext)	Unknown
 	Microsoft.VisualStudio.ProjectSystem.LanguageServices.Handlers.CommandLineItemHandler.ProcessItems(projectChange, context, isActiveContext)	Unknown
 	Microsoft.VisualStudio.ProjectSystem.LanguageServices.Handlers.CommandLineItemHandler.Handle(projectChange, context, isActiveContext)	Unknown
 	Microsoft.VisualStudio.ProjectSystem.LanguageServices.LanguageServiceHost.HandleAsync.AnonymousMethod__2()	Unknown
 	System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(stateMachine)	C#
 	System.Threading.ExecutionContext.RunInternal(executionContext, callback, state, preserveSyncCtx)	C#
 	System.Threading.ExecutionContext.Run(executionContext, callback, state, preserveSyncCtx)	C#
 	System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()	C#
 	Microsoft.VisualStudio.Threading.JoinableTaskFactory.SingleExecuteProtector.TryExecute()	C#
 	Microsoft.VisualStudio.Threading.JoinableTaskFactory.SingleExecuteProtector..cctor.AnonymousMethod__20_0(state)	C#
 	System.Windows.Threading.ExceptionWrapper.InternalRealCall(callback, args, numArgs)	Unknown
 	System.Windows.Threading.ExceptionWrapper.TryCatchWhen(source, callback, args, numArgs, catchHandler)	Unknown
 	System.Windows.Threading.DispatcherOperation.InvokeImpl()	Unknown
 	System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(state)	Unknown
 	MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(obj)	Unknown
 	System.Threading.ExecutionContext.RunInternal(executionContext, callback, state, preserveSyncCtx)	C#
 	System.Threading.ExecutionContext.Run(executionContext, callback, state, preserveSyncCtx)	C#
 	System.Threading.ExecutionContext.Run(executionContext, callback, state)	C#
 	MS.Internal.CulturePreservingExecutionContext.Run(executionContext, callback, state)	Unknown
 	System.Windows.Threading.DispatcherOperation.Invoke()	Unknown
 	System.Windows.Threading.Dispatcher.ProcessQueue()	Unknown
 	System.Windows.Threading.Dispatcher.WndProcHook(hwnd, msg, wParam, lParam, handled)	Unknown
 	MS.Win32.HwndWrapper.WndProc(hwnd, msg, wParam, lParam, handled)	Unknown
 	MS.Win32.HwndSubclass.DispatcherCallbackOperation(o)	Unknown
 	System.Windows.Threading.ExceptionWrapper.InternalRealCall(callback, args, numArgs)	Unknown
 	System.Windows.Threading.ExceptionWrapper.TryCatchWhen(source, callback, args, numArgs, catchHandler)	Unknown
 	System.Windows.Threading.Dispatcher.LegacyInvokeImpl(priority, timeout, method, args, numArgs)	Unknown
 	MS.Win32.HwndSubclass.SubclassWndProc(hwnd, msg, wParam, lParam)	Unknown
 	[Native to Managed Transition]	
 	__InternalCallWinProc@20()	Unknown
 	[Inline Frame] InternalCallWinProc()	C
 	UserCallWinProcCheckWow(pActCtx, pfn, hwnd, msg, wParam, lParam, fEnableLiteHooks, )	C
 	DispatchMessageWorker(pmsg, fAnsi)	C
 	DispatchMessageW(lpMsg)	C
 	MainMessageLoop::ProcessMessage(pstdcm, pIVsWindowManager, msg)	C++
 	CMsoCMHandler::EnvironmentMsgLoop()	C++
 	CMsoCMHandler::FPushMessageLoop(uReason)	C++
 	SCM::FPushMessageLoop(pscmi, uReason, pvLoopData)	C++
 	SCM_MsoCompMgr::FPushMessageLoop(dwComponentID, uReason, pvLoopData)	C++
 	CMsoComponent::PushMsgLoop(msgloop)	C++
 	VStudioMainLogged()	C++
 	VStudioMain(pMainParam)	C++
 	util_CallVsMain(pMainParam, piRes)	C++
 	CDevEnvAppId::Run(wszCmdLine, nCmdShow)	C++
 	WinMain(hInstance, __formal, lpCmdLine, nCmdShow)	C++
 	[Inline Frame] invoke_main()	C++
 	__scrt_common_main_seh()	C++
 	BaseThreadInitThunk(RunProcessInit, StartAddress, Argument)	C
 	__RtlUserThreadStart(StartAddress, Argument)	C
 	_RtlUserThreadStart(StartAddress, Argument)	C
```

I'm uploading a dump, but it will take a while as i'm not on corpnet.

**Comment by CyrusNajmabadi** [comment] 2017-06-08 01:48
Dump will be at: \\mlangfs1\public\cyrusn\Dumps\HangOnShutdown.dmp

**Comment by davkean** [comment] 2017-06-08 08:39
Thanks - this is a dupe of https://github.com/dotnet/project-system/issues/2377.

**Closed by davkean** 2017-06-08 08:39 UTC
