### ISSUE TITLE
Race condition in project editing with undo

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#4940] opened 2019-06-20 14:00 UTC
**Visual Studio Version**:

16.2.0-pre.2.0+29006.145. Also occurs in 16.1.3.

**Summary**:

Changes to editor buffer made immediately after save are undone asynchronously after a second or so.

**Steps to Reproduce**:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>netstandard1.3;netcoreapp2.1</TargetFrameworks>
  </PropertyGroup>
</Project>
```

To trigger the behaviour do the following steps quickly:

1. Delete one TFM (leaving say `netcoreapp2.1`)
1. Save
1. Undo (leaving `netstandard1.3;netcoreapp2.1`)

The undone change is reverted back to `netstandard1.3;netcoreapp2.1` after a second or so. It's as though the save operation is replacing the document content some while later.

**Expected Behavior**:

Editor does not make unexpected changes to file.

**Actual Behavior**:

Editor changes the file.

**User Impact**:

Unclear how far reaching this is. Potential for data loss here.

**Comment by drewnoakes** [comment] 2019-06-20 14:02
Further testing yielded, though I'm not sure it's related.

```
=====================
20/06/2019 11:37:05 PM
Recoverable
System.AggregateException: One or more errors occurred. ---> Microsoft.VisualStudio.ProjectSystem.ProjectDataSources+DataSourceRegressionException: Some data sources have regressed in their version number.
   at Microsoft.VisualStudio.ProjectSystem.ProjectDataSources.CheckValidVersionProgression(Func`1 getDataSourceName, IImmutableDictionary`2 oldDataSourceVersions, IImmutableDictionary`2 dataSourceVersions, Boolean unconfiguredProjectLevel)
   at Microsoft.VisualStudio.ProjectSystem.SyncLinkToLink`1.ProcessData(Boolean inline)
   --- End of inner exception stack trace ---
---> (Inner Exception #0) Microsoft.VisualStudio.ProjectSystem.ProjectDataSources+DataSourceRegressionException: Some data sources have regressed in their version number.
   at Microsoft.VisualStudio.ProjectSystem.ProjectDataSources.CheckValidVersionProgression(Func`1 getDataSourceName, IImmutableDictionary`2 oldDataSourceVersions, IImmutableDictionary`2 dataSourceVersions, Boolean unconfiguredProjectLevel)
   at Microsoft.VisualStudio.ProjectSystem.SyncLinkToLink`1.ProcessData(Boolean inline)

Data Source: SyncLink (Microsoft.VisualStudio.ProjectSystem.ProjectDataSources+SourceBlockAndLink`1[Microsoft.VisualStudio.ProjectSystem.IProjectValueVersions][])

Old data source versions: 
Name                                                  Identity     Version
ProjectService                                               2           1
VsIntegration                                                3           1
ActiveProjectConfiguration                                   4          23
ConfiguredProjectVersion                                     5          66
ConfiguredProjectIdentity                                    6           0
ProjectXmlVersion                                            7         145
SolutionGlobalProperties                                    12           2
CapabilitiesInheritedByProject                              14           1
Project                                                     17          24
ProjectCapabilitiesFromImportTargetProvider                 18          25
ProjectExtensionsCapabilitiesProvider                       19          25
DataSourceImportor                                          22           1

New data source versions: 
Name                                                  Identity     Version
ProjectService                                               2           1
VsIntegration                                                3           1
ActiveProjectConfiguration                                   4          24
ConfiguredProjectVersion                                     5          63
ConfiguredProjectIdentity                                    6           1
ProjectXmlVersion                                            7         143
SolutionGlobalProperties                                    12           2
CapabilitiesInheritedByProject                              14           1
Project                                                     17          25
ProjectCapabilitiesFromImportTargetProvider                 18          25
ProjectExtensionsCapabilitiesProvider                       19          25
DataSourceImportor                                          22           1
<---

===================
```

**Comment by davkean** [comment] 2019-06-21 03:33
@davidwengier Can we figure out if this a regression in 16.2? And if so, whether we need to address it in 16.2.

**Comment by drewnoakes** [comment] 2019-06-21 06:39
I checked that. Hidden in the description above:

> Also occurs in 16.1.3.

**Comment by davidwengier** [comment] 2019-06-21 09:18
I'm more curious whether this is fixed by the changes made in 16.2, but I can't seem to work out what build of VS those made it in to. I'll see if I can repro when I get back home and confirm I have a build with the latest bits.

**Comment by davkean** [comment] 2020-01-20 23:40
@davidwengier Can you please dup this against the existing bug on this?

**Comment by davidwengier** [comment] 2020-01-21 05:29
Duplicate of #5430

**Closed by davidwengier** 2020-01-21 05:29 UTC
Labels: Bug, Feature-Project-File-Editing, Needs-CPS-work, Triage-Approved
