### ISSUE TITLE
Support file nesting implemented in for dotnet core web projects

### ISSUE THREAD

**Issue by abpiskunov** [dotnet/project-system#3242] opened 2018-02-12 18:20 UTC
See this request here: https://github.com/aspnet/websdk/issues/248 

Nesting went live in 15.6 Preview 3 and there were requests for other dotnet core projects to support that. 

To support nesting, project needs to have following capabilities:

![image](https://user-images.githubusercontent.com/1592091/36112364-441ecdb6-0fde-11e8-99df-acb079bbc646.png)

To add default nesting behavior for your project type, a provider needs to be implemented.

Contact me for details when ready.

**Comment by SharpNoiZy** [comment] 2019-01-10 11:46
Since nearly one year open...to enable something that another Team of your Company has already developed perfectly...can you please copy&paste the Code over and support also library Projects...

**Comment by SharpNoiZy** [comment] 2019-01-10 14:08
We use in our hole Company (100 Devs, 5 Teams) CQRS with this Config.
````json
{
  "help": "https://go.microsoft.com/fwlink/?linkid=866610",

  "dependentFileProviders": {
    "add": {
      "fileSuffixToExtension": {
        "add": {
          "Request.cs": [ "Command.cs", "Query.cs" ],
          "Response.cs": [ "Command.cs", "Query.cs" ]
        }
      }
    }
  }
}

**Comment by drewnoakes** [comment] 2019-01-11 11:00
Thank you for the example.

It won't be possible to do that automatically for libraries until we add support for custom nesting rules in this project-system. We're aware of the WebToolsExtensions implementation and have looked at porting it, but the amount of work involved is non-trivial and must be considered along with our other priorities.

**Comment by fschmied** [comment] 2019-01-11 15:22
See https://github.com/aspnet/websdk/issues/248#issuecomment-364520896 - just need VS 15.6 or higher, add the capabilities to the csproj file and configure the nesting. We're using this successfully with SDK-style library csprojs (also in a CQRS context, funnily).

**Comment by drewnoakes** [comment] 2019-01-14 12:55
@fschmied thanks for pointing out a workaround.

@SharpNoiZy can you try adding the following to your library's project file?

```xml
<ItemGroup>
    <ProjectCapability Include="DynamicDependentFile" />
    <ProjectCapability Include="DynamicFileNesting" />
</ItemGroup>
```

You'll need to reload the project, but should then see nesting support.

**Comment by SharpNoiZy** [comment] 2019-01-14 13:03
@drewnoakes We have this WORKAROUND in place, but it's exactly that.
It feels hacky and the fear that this Workaround functionality will be removed with some VS Update is Always there.

There should be one official solution for all Project types.

**Comment by diryboy** [comment] 2019-01-23 15:35
How to specify the custom nesting profile file in the project file? Want to include the json file along with the project instead of somewhere in user appdata.

**Comment by NickCraver** [comment] 2019-04-05 10:32
@diryboy You can create as the magical name `.filenesting`. Ours is solution level but it may search for it up the root and work per-project and such like most things...I just haven't tried multiple or anything there.

I *love* this feature and it cleans up our `.csproj` files tremendously. We have a pattern of `Class.cs` and `Class.Area1.cs`/`Class.Area2.cs` (partials so functionality or relationships are grouped). In the old world, it's a 1 line `<Compile>` for `Class.cs` and 3 lines (because of `<DependsUpon>`) for each of the others, so 7 lines total. With this nesting defined once we go from 7 to 0 in the `.csproj`.

We're currently using the workaround of defining the `<ProjectCapability>`, but I'd love to see this *just work* for people and have it move to where that's possible.

**Comment by drewnoakes** [comment] 2020-01-13 00:43
Saint, you're looking at this so I've assigned it to you. Feel free to update/dupe this issue as necessary.

**Comment by jjmew** [comment] 2020-01-13 23:57
We will be tracking this as part of #5722

**Closed by jjmew** 2020-01-13 23:57 UTC
Labels: Feature Request, Feature-File-Nesting, Resolution-Duplicate

**Comment by odalet** [comment] 2020-04-03 13:52
> @diryboy You can create as the magical name `.filenesting`. Ours is solution level but it may search for it up the root and work per-project and such like most things...I just haven't tried multiple or anything there.
> 
> I _love_ this feature and it cleans up our `.csproj` files tremendously. We have a pattern of `Class.cs` and `Class.Area1.cs`/`Class.Area2.cs` (partials so functionality or relationships are grouped). In the old world, it's a 1 line `<Compile>` for `Class.cs` and 3 lines (because of `<DependsUpon>`) for each of the others, so 7 lines total. With this nesting defined once we go from 7 to 0 in the `.csproj`.
> 
> We're currently using the workaround of defining the `<ProjectCapability>`, but I'd love to see this _just work_ for people and have it move to where that's possible.

@Anyone interested in using @NickCraver trick, note that the file at your solution level must be called `.filenesting.json`, not `.filenesting`, at least the former worked for me, and not the latter.

It also seems that, for non-Web projects, `DynamicDependentFile` capability is not necessary. I only have this in my `csproj`:

```xml
<ItemGroup>
  <ProjectCapability Include="DynamicFileNesting"/>
</ItemGroup>
```

**Comment by nathan-alden-sr** [comment] 2021-11-02 01:14
@odalet I'm trying this same workaround in VS Community 2022 RC3 and it's not working.

**Comment by PuzhengCao** [comment] 2021-12-18 16:06
Not working with the latest right now - VS Professional 2022 V17.0.4

**Comment by NickCraver** [comment] 2021-12-18 16:41
I don't have any new information since joining (will ask!), but for those it's not working for: do you have the web payload for VS installed? That's where the actual functionality resides and why it only worked on web projects by default (1:1 with needing the workload anyway), at least previously - I'm not sure if anything changed in VS 2022.

**Comment by gfraiteur** [comment] 2022-02-15 09:20
Same problem here. I got it nicely working for VS 2019 but it broke in VS 2022.

**Comment by fschmied** [comment] 2022-02-23 10:46
New issue for VS 2022: #7939
@gfraiteur @PuzhengCao @NickCraver @nathan-alden-sr

**Comment by gfraiteur** [comment] 2022-02-24 09:33
Thank you. I can confirm it works for us.

Is there a way for a nuget package to suggest/install nesting rules?

We need these:

```json
{
  "help": "https://go.microsoft.com/fwlink/?linkid=866610",
  "dependentFileProviders": {
    "add": {
      "extensionToExtension": {
        "add": {
          ".t.cs": [
            ".cs"
          ],
          ".t.txt": [
            ".cs"
          ],
          ".Aspect.cs": [
            ".cs"
          ],
          ".Helper.cs": [
            ".cs"
          ],
          ".cs.html": [
            ".cs"
          ]
        }
      }
    }
  }
}
```

Our use case is a [custom test framework](https://doc.metalama.net/aspects/testing/compile-time-testing).

**Comment by drewnoakes** [comment] 2022-02-25 00:42
> Is there a way for a nuget package to suggest/install nesting rules?

Not that I know of, though I am not an expert. Could you open a new issue for this please?
