### ISSUE TITLE
Annoying message that file is opened in other project 

### ISSUE THREAD

**Issue by forki** [dotnet/project-system#2959] opened 2017-11-10 17:23 UTC
Since we are all-in on azure functions we do a lot of source file sharing between the different functions project. I think these files where called links in the old days. Anyway base functionality is put into a cs file and shared between projects. We don't compile a project for that single file.

That's working very well for us, but vs2017 is always complaining if we click on the file in solution explorer that it is already opened in different project. 
That message is so annoying. Can we find a way to make it go away forever? 

/cc @cartermp

**Comment by Pilchie** [comment] 2017-11-10 19:11
Can you construct a repro project to share with us?  We're definitely not seeing this in the normal case.

**Comment by forki** [comment] 2017-11-10 20:24
"normal case" ;-)

Yes will try to build repro tomorrow

Am 10.11.2017 20:11 schrieb "Kevin Pilch" <notifications@github.com>:

**Comment by forki** [comment] 2017-11-12 09:04
[ClassLibrary1.zip](https://github.com/dotnet/project-system/files/1464465/ClassLibrary1.zip)

Open sln. 
go to ClassLibrary5 and open Shared.fs
got ClassLibrary4 in solution explore and open Shared.fs

![image](https://user-images.githubusercontent.com/57396/32697436-a5151918-c790-11e7-9320-12cf6e0add3f.png)

this is with VS 15.5 preview 3

@vasily-kirichenko  @KevinRansom  @Pilchie @cartermp I tried to repro the same in C# only sln but didn't work. Maybe it's only a VF# issue.

**Comment by Pilchie** [comment] 2017-11-13 17:20
@KevinRansom can you take a look?

**Comment by Pilchie** [comment] 2017-11-13 17:22
I wonder if this is related to the issue @vasily-kirichenko filed about a file being in 2 projects.  Did that have a linked file?

**Comment by Pilchie** [comment] 2017-11-21 16:10
@KevinRansom or @TIHan - can one of you take a look at this?

**Comment by TIHan** [comment] 2017-11-22 18:01
An update:

We are still trying to figure what is going on. It may be required that a fix for this needs to happen in two places: in our legacy project system and newer sdk.

For what is it worth, in our legacy system, under ```FileDocumentManager.cs```, there is logic for opening files in an editor. The fix most likely might happen in there.

**Comment by TIHan** [comment] 2017-11-27 18:41
I did manage to fix this for the legacy projects, but most likely it was more of a hack instead of a proper fix. The best thing to do here is figure out what C# is doing to determine the best fix. 

Since this is also part of the project system implementation, communication with the project team is required.

**Comment by davkean** [comment] 2017-11-28 00:09
@TIHan We implement this, and it looks like this:

``` C#
        int IVsSupportItemHandoff.HandoffItem(uint itemid, IVsProject3 pProjDest, string pszMkDocumentOld, string pszMkDocumentNew, IVsWindowFrame punkWindowFrame)
        {
            if (pProjDest == null)
            {
                return VSConstants.E_POINTER;
            }

            return pProjDest.TransferItem(pszMkDocumentOld, pszMkDocumentNew, punkWindowFrame);
        }
```

**Comment by TIHan** [comment] 2017-11-28 00:29
@davkean I've implemented this interface on our internal F# legacy project system to see what it would do, but nothing seems to call it. Infact, I don't even know how HandoffItem is called in CPS. I'm assuming somewhere in the IDE, but I don't know why or for what reason.

**Comment by jmarolf** [comment] 2017-11-28 01:41
@davkean this is happening on the new project system.  I thought that CPS would handle this case?

**Comment by davkean** [comment] 2017-11-28 04:58
@jmarolf We debugged this offline and figured it out.  @TIHan will have a PR out that fixes the issue. In summary, this is caused by Textmate editor factory having a higher priority than the F# editor factory.

**Comment by davkean** [comment] 2017-11-28 04:59
Oh and F#'s legacy project system needs to implement IVsSupportItemHandoff.

**Comment by TIHan** [comment] 2017-11-28 22:50
I believe we can mark this as fixed.

**Comment by Pilchie** [comment] 2017-12-19 01:08
Fixed by @TIHan - thanks!

**Closed by Pilchie** 2017-12-19 01:08 UTC
Labels: Area-F#, Bug

**Comment by forki** [comment] 2017-12-19 07:09
Cool. Thanks

Am 19.12.2017 02:08 schrieb "Kevin Pilch" <notifications@github.com>:
