### ISSUE TITLE
Need implement IProjectDefaultConfigurationProvider component to prevent loading an empty configuration

### ISSUE THREAD

**Issue by lifengl** [dotnet/project-system#2711] opened 2017-08-15 01:54 UTC
.Net Core project currently loads an empty configuration to evaluate the project to understand the right set of project configurations.  It is a huge waste, not only adds one more project evaluation, also that CPS loads the dataflow with it, and it will reevaluate that fake configuration after every change in the project.

We added a new contract to the CPS side, which the .Net Core project can try to infer the first configuration it should load by possibly reading the unevaluated model (or just based on SDK and guess).  If it is implemented correctly, and we can guess it correctly in 90% projects, we can load the first configuration correctly.  Otherwise, it will load an useless configuration just like what we do today.  Basically, CPS will load this configuration instead of the empty one, and we will still use the old logic to know the exact configuration to load.  When it matches the originally loaded one, we will reuse it, and will be faster.

**Comment by lifengl** [comment] 2017-08-15 01:54
The CPS side change has been made in 15.5.

**Comment by davkean** [comment] 2017-08-15 03:07
@lifengl Didn't you implement one based on solution config? Is the idea that we do a quick sniff and guess which config it is and use that?

**Comment by lifengl** [comment] 2017-08-15 16:25
The configuration information from the solution has been passed as a parameter to the component, but we need a component from your team to provide the 3rd dimension of your configuration name (if it exists).  We have a default component to just use the one from solution.

**Comment by davkean** [comment] 2017-09-01 06:30
If we guess correctly, this will avoid loading an unneeded configuration for multi-targeted projects. We should basically sniff the TargetFrameworks property and return the first TFM combined with the active from the solution config.

**Comment by lifengl** [comment] 2017-09-01 07:30
Yes

Sent from my phone

On Aug 31, 2017, at 11:30 PM, David Kean <notifications@github.com<mailto:notifications@github.com>> wrote:


If we guess correctly, this will avoid loading an unneeded configuration for multi-targeted projects. We should basically sniff the TargetFrameworks property and return the first TFM combined with the active from the solution config.

**Comment by lifengl** [comment] 2017-10-25 19:35
Also, if the SDK can be updated to exclude globs or some imports when the TFM doesn't match anything set in the project, it can make the evaluation time of a fake configuration shorter, so in the scenario that the provider makes a wrong guess, it can still be faster.

This issue still impacts Roslyn.sln loading, because it has some multiple targeted projects like TestUtilities.csproj, and ETW trace shows the evaluation time is doubled.

**Comment by Pilchie** [comment] 2018-01-10 18:15
@lifengl can you take a look at #3104?  @davkean suggests that it should be in CPS instead of here.  Do you agree

Assigning to myself to track for now.

**Comment by lifengl** [comment] 2018-01-11 00:35
That change looks reasonable.  But it is not yet a complete change, it still requires the dimension provider to implement the new protocol to get this to work.

This logic currently can live in either your assembly or CPS.  @davkean wants to push TPM (related) concept more into CPS, and become some common things to be used in other project system. Here he think instead of implementing the default provider, he wants to push the protocol to the dimension layer, and they return the default value.  That may make sense.  However, we think this can be sorted out in a later update.  (We have other logics like mapping one TPM projects into 2 dimension space, while multiple TPMs are handled differently.  We need review where those logic should belong.)  In the meantime, I think getting this into the ML and makes sure we don't load extra configuration may be easier than introducing a new API change.

**Comment by Pilchie** [comment] 2018-01-23 23:27
Moving to 15.7.

**Comment by steffenloesch** [comment] 2018-03-19 20:05
Is there some documentation on what needs to be in place for the "quick sniff" to be successful?

**Comment by davkean** [comment] 2018-03-20 02:12
@steffenloesch No documented, we haven't come up with a design.

The problem is we have a chicken and egg problem; to identify what configurations a project has, we have to evaluate a project to figure out what `<TargetFrameworks />`, `<Platforms>`  and `<Configurations/>` is ultimately set to. To evaluate these, we need to load a configuration.

At the moment, we load a dummy configuring just to figure out these values then fire up the new "real" configurations. This is causing issues in your solution.

We're adding code to sniff/guess these properties without evaluating by (effectively) parsing the XML - in most cases this will be the correct guess and we'll avoid loading an unneeded config.

In your case, however, `<TargetFrameworks>` result comes from outside of the project, so we need to come up with sniffing logic to find it. It will very likely be searching up the tree looking for Directory.Build.props (existing extension mechanism) - so that will likely be the place for the quick sniff.

**Comment by lifengl** [comment] 2018-03-20 04:35
It was not defined in a directory based porp file directly, but an indirectly referenced file.  Of course, I guess it can be changed.

Sent from my phone

On Mar 19, 2018, at 7:13 PM, David Kean <notifications@github.com<mailto:notifications@github.com>> wrote:


@steffenloesch<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsteffenloesch&data=02%7C01%7C%7C3ab18d367d8d4a8fe5fd08d58e081b7b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636571087825837148&sdata=p5EEj9fv8%2BaTRgcD986rVMvowURBCkXtc13Z6mRaw9Y%3D&reserved=0> No documented, we haven't come up with a design.

The problem is we have a chicken and egg problem; to identify what configurations a project has, we have to evaluate a project to figure out what <TargetFrameworks />, <Platforms> and <Configurations/> is ultimately set to. To evaluate these, we need to load a configuration.

At the moment, we load a dummy configuring just to figure out these values then fire up the new "real" configurations. This is causing issues in your solution.

We're adding code to sniff/guess these properties without evaluating by (effectively) parsing the XML - in most cases this will be the correct guess and we'll avoid loading an unneeded config.

In your case, however, <TargetFrameworks> result comes from outside of the project, so we need to come up with sniffing logic to find it. It will very likely be searching up the tree looking for Directory.Build.props (existing extension mechanism) - so that will likely be the place for the quick sniff.

**Comment by steffenloesch** [comment] 2018-03-20 05:02
We currently define the TFMs in a file that's imported by Directory.Build.Props, but that could be changed. That's why I asked :-) We'd be even OK with defining everything in the project file directly, but having the ability to have the definition in one place like Directory.Build.Props would be much nicer.

Have you thought about conditions on the property definition for TargetFrameworks, Platforms and Configurations. How would those be handled?

**Comment by davkean** [comment] 2018-03-20 05:18
If we guessed "wrong", we were thinking about burning what we found in the suo so next time you open it's faster.

What do your conditions look like?

**Comment by Pilchie** [comment] 2018-03-30 20:09
@davkean are you working on this?  Should I move it back to you?

**Comment by davkean** [comment] 2018-03-30 23:55
Yeah I have an implementation of this.

**Comment by steffenloesch** [comment] 2018-04-02 04:05
@davkean, here's the answer to your conditions question. Currently we set conditions based on BuildingInsideVisualStudio and a custom static property that we set ourselves. The static property is currently not defined in Directory.Build.props, but it could easily be moved there.

**Comment by Pilchie** [comment] 2018-04-25 15:29
This change was inserted into 15.7 Preview 5.

**Closed by Pilchie** 2018-04-25 15:29 UTC
Labels: Area-New-Project-System, Bug, Feature-Configurations, Performance
