### ISSUE TITLE
VS deadlocked during up-to-date check

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#2474] opened 2017-06-21 06:50 UTC
@jcouv attempted to build and VS appears to have deadlocked during up-to-date check.

Threads overview:

![image](https://user-images.githubusercontent.com/1103906/27370827-abf714bc-56a1-11e7-9eb5-4512794c315b.png)
![image](https://user-images.githubusercontent.com/1103906/27370867-b76d35e2-56a1-11e7-82ca-a63e7a9ba907.png)

Dump is on [jcouv's dev box]\shared-dumps\devenv-thread-starvation.dmp

**Comment by davkean** [comment] 2017-06-21 06:51
@srivatsn Put this in 15.3 as this a new path.

**Comment by davkean** [comment] 2017-06-21 06:56
I had a quick look at the code (not the dump - as I can't donwload it) nothing obvious - except maybe the options check, does that call back into the UI thread? Maybe that's not proceeding?

**Comment by panopticoncentral** [comment] 2017-06-21 16:13
Wait... where is the dump file?

**Comment by panopticoncentral** [comment] 2017-06-21 16:17
But, yes, the options check does switch to the main thread to call the settings manager. But I don't think the main thread blocks on up to date checks, so I'm not sure where the block might be.

**Comment by jcouv** [comment] 2017-06-21 18:03
Here is the dump file (when VS was hung, I attached another VS and saved the dump): https://www.dropbox.com/s/gq42udarqzcenij/devenv-thread-starvation.dmp?dl=0
I also have it on my dev box.

**Comment by davkean** [comment] 2017-06-21 22:05
It's wrapped in an ExecuteSynchronously, so it's definitely blocking, it's only going to let transitions to the UI thread that it thinks are part of the same chain.

**Comment by panopticoncentral** [comment] 2017-06-22 18:35
This was on a local built project system instance, is it possible to get the symbols for it so we can see where we were in the up to date check when we hung? Or is there some trick to figure that out?

**Comment by jcouv** [comment] 2017-06-22 18:46
I'm not sure. Assuming that project system is built with determinism, you should be able to get to the same state by building from your PR on FUTD check for ref assemblies (https://github.com/dotnet/project-system/pull/2414). 
Since there were multiple iterations, I'm not sure which iteration it was. Based on my recollection and the timestamps, I think it was 32b9b66 or the one before that.

**Comment by jcouv** [comment] 2017-06-22 23:20
I have a new dump capturing the same issue (I think) and not involving any private binaries. 
//jcouvdev/shared-dumps/devenv-hung2.dmp

Below is the capture of Parallel stacks for confirmation:
![image](https://user-images.githubusercontent.com/12466233/27460094-9264cd08-5766-11e7-939b-c0cda4b63a35.png)

**Comment by panopticoncentral** [comment] 2017-06-23 07:33
This is https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems?id=455018. The problem is that we used to have CPS wait for critical tasks to finish before calling the up to date check, and this would block the UI thread if a critical task didn't finish or took a long time. This was fixed in PR #2453.

**Closed by panopticoncentral** 2017-06-23 07:33 UTC
Labels: Bug

**Comment by jcouv** [comment] 2017-06-23 13:07
Thanks!
