### ISSUE TITLE
Adding COM reference in csproj breaks other references and intellisense

### ISSUE THREAD

**Issue by J4MESD** [dotnet/project-system#3233] opened 2018-02-09 09:45 UTC
Hi,

I have found an issue where by if I add a reference to a COM library in a ASP.NET Core WebAPI project targeting the .NET framework it has the side effect of breaking Intellisense and raising false errors in the Error list window. Mainly that it can't find namespaces and symbols referenced in the non-COM project references. Everything still compiles and works, but it just makes code refactoring and following references incredibly difficult.

I have attached an example project where if you remove the commenting around lines 22 - 31 of ComBreakingExample.csproj you should hopefully see the issue.

Any help is much appreciated.
Many thanks,
James

[ComBreakingExample.zip](https://github.com/dotnet/project-system/files/1710464/ComBreakingExample.zip)

**Comment by Pilchie** [comment] 2018-02-09 18:09
This is https://github.com/Microsoft/msbuild/pull/2592, but the core VS platform pience CPS is also doing a workaround for it.

Tagging @lifengl and @natidea

**Comment by Pilchie** [comment] 2018-02-12 16:25
Oh, we've also got the bug here.  Closing as a duplicate of #3211.

**Closed by Pilchie** 2018-02-12 16:25 UTC
Labels: Area-External-CPS

**Comment by davkean** [comment] 2018-02-14 02:44
A workaround for this is to add the followong to your project file:

``` XML

  <Target Name="COMReferencesWorkaround" BeforeTargets="ResolveAssemblyReferences" DependsOnTargets="ResolveProjectReferences">
  </Target>
```
