### ISSUE TITLE
Get the renamed Platform from Solution Configuration

### ISSUE THREAD

**Issue by kaylumah** [dotnet/project-system#7177] opened 2021-05-04 18:00 UTC
**Visual Studio 2019**:

**Summary**:
After some discussion with MSBuild on the issue https://github.com/dotnet/msbuild/issues/4752 I was pointed to this repo.
In VisualStudio, you have the notion of Platform but also of SolutionPlatform/Configuration.

Unfortunately, it seems that custom platform names always are overwritten with AnyCPU or x64.

Would it be possible to capture the original platform name here so we can use it during the build.

See https://github.com/dotnet/msbuild/issues/4752#issuecomment-832124706 for the entire repo case/scenario

**Comment by jjmew** [comment] 2021-05-04 20:35
@swesonga Can you ask about this on the CPS meeting?

**Comment by swesonga** [comment] 2021-05-06 00:02
Filed CPS issue https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1323548 for this issue. cc @lifengl

**Comment by lifengl** [comment] 2021-05-06 19:18
Just like what the msbuild item pointing out, the original issue was "by design". We can understand the potential usage scenario, but this is a feature request, which doesn't meet the current bar. It requires changes in many loosely coupled areas in the product to drive various different build/evaluation stack in VS & also potential customized target files to drive some project reference builds. As @rainersigwald points out earlier, this may lead others to abuse this feature and create unnecessary dependency between the project build & the solution.

Put it straight, we suggest customer to adopt a special workaround for this scenario, instead of requiring a wide spread product change to add extra entangling between a project & the solution.

**Comment by kaylumah** [comment] 2021-05-06 19:20
@lifengl I can understand your position regarding it.

You mention "special workaround" do you have a proposal that I can then test for our usecase

**Comment by lifengl** [comment] 2021-05-06 19:42
I thought about a special workaround, which might be a little bit messy (not something we like), but you can get it to work with any version of VS.  (Even if we prepare a fix, it would be quite some time for you to get it.)

Now, when solution builds a project, it doesn't only pass a mapped configuration/platform to the project, it also pass in a Xml blob to contain the configuration/platform of all projects, so the project can resolve P2P reference with it. This property is called "CurrentSolutionConfigurationContents", and you can print it out in your build target to read it.

Now, with that, you may create a special (fake) project in your solution, which contains all platform names the same as the solution, and keep a 1:1 mapping between them. Then, you can get the current solution platform in the blob by looking the item referencing that special project.

With this, you will need create a customized build task to retrieve the data from that blob. Although it is not difficult to do, you will have to create a tool package (maybe wrapped it as a NuGet package, and usable in your main project. (make it general enough, so it is just to resolve platform from a referenced project path)

Another possibility is to reuse the standard task (https://docs.microsoft.com/en-us/dotnet/api/microsoft.build.tasks.assignprojectconfiguration?view=msbuild-16-netcore), and feed it with a fake reference to the special project. it will eliminate an extra tools package, but requires some hacky msbuild target work.

**Comment by kaylumah** [comment] 2021-05-08 07:33
Hi @lifengl 

I checked out CurrentSolutionConfigurationContents and perhaps I misunderstood you.

![image](https://user-images.githubusercontent.com/8428126/117530911-08329580-afe0-11eb-8ae0-4a83c10aebe0.png)

The values I get in my XML are still `Debug|AnyCPU`

So lets for a moment imagine I have defined multiple Solution platforms

![image](https://user-images.githubusercontent.com/8428126/117530941-357f4380-afe0-11eb-8581-1fd4daca692e.png)

Theoretically multiple of those could offer Debug|AnyCPU .

Is there also a similar solution that does contain the SolutionPlatform name?

(Note we have logic based on this which nuget package to resolve etc, and we are extending to a third platform, so just using x64 or any cpu does not cut it anymore)

**Comment by kaylumah** [comment] 2021-05-18 07:57
@lifengl Sorry to check again, but do you have any alternative to your proposed solution?

**Comment by lifengl** [comment] 2021-05-20 23:12
My suggestion is that you can create a fake project (maybe a class library project) inside your solution, and inside it, you can put all your solution platforms
	  <Platforms>AnyCPU;Azure.ServiceFabric;DotNet.ServiceFabric</Platforms>

With this, you can do 1:1 mapping between project configuration of this project to your solution configuration with that dialog. During build, the XML item for that fake project will contain the platform of that specific project, which happens to be the same as the solution one.

**Comment by jjmew** [comment] 2021-06-08 17:51
Closing this as it is external and by design. The discussion can continue

**Closed** 2021-06-09 01:14 UTC
Labels: Resolution-External
