### ISSUE TITLE
Publish updated NuGet packages to NuGet.org

### ISSUE THREAD

**Issue by jp2masa** [dotnet/project-system#3162] opened 2018-01-18 21:06 UTC
On NuGet, the latest version of `Microsoft.VisualStudio.ProjectSystem.Managed` and `Microsoft.VisualStudio.ProjectSystem.Managed.VS` were published 7 months ago. I couldn't find any myget feed with those packages either. What's the correct way of extending the managed project systems?

**Comment by Pilchie** [comment] 2018-01-18 21:10
@lifengl?

**Comment by Pilchie** [comment] 2018-01-18 21:10
Oh, wait - those are our packages, not the CPS ones :)

**Comment by Pilchie** [comment] 2018-01-18 21:12
They are published to https://dotnet.myget.org/feed/roslyn/package/nuget/Microsoft.VisualStudio.ProjectSystem.Managed, not sure why we haven't pushed them to NuGet.org, but I'll see.

**Comment by Pilchie** [comment] 2018-01-19 16:05
@jmarolf @natidea @genlu Do you know why these haven't been published more recently?

**Comment by jmarolf** [comment] 2018-01-19 17:58
I believe the problem is we never set up a process to track publishing them regularly after balaji left.

**Comment by natidea** [comment] 2018-01-19 19:55
[This thread](https://github.com/dotnet/project-system/issues/3005) has more information about prerelease dependencies that are preventing us from publishing on nuget.org

**Comment by jp2masa** [comment] 2018-01-19 22:15
The myget packages have some dependencies that shouldn't be there I think, like `RoslynTools.RepoToolset` and `Microsoft.Net.Compilers`, these should have `PrivateAssets="All"`. It would be nice if there were stable packages on NuGet, but I understand that it's not really easy, so I can use the myget packages for now.

**Comment by MiYanni** [comment] 2022-07-27 20:29
This issue will be for discussing/deciding if publishing our packages to NuGet.org on a regular basis actually provides any benefit to anyone. At this point in time, I don't know who would consume those packages from that source. We currently publish to 1 public AzDO feed and 1 internal AzDO feed.
- Public: https://dev.azure.com/azure-public/vside/_artifacts/feed/vs-impl
- Internal: https://dev.azure.com/DevDiv/DevDiv/_artifacts/feed/VS

**Comment by ocallesp** [comment] 2022-08-19 23:59
Maybe we should publish packages to NuGet.org for this [specific versions of VS](https://docs.microsoft.com/en-us/visualstudio/install/visual-studio-build-numbers-and-release-dates?view=vs-2022).

**Comment by adamint** [comment] 2022-09-06 18:26
I would recommend against additionally publishing to nuget. If someone external does want to reference, they can just use the ADO feed.

**Comment by drewnoakes** [comment] 2022-09-07 19:56
Perhaps we should unlist all packages from NuGet.org, and make sure the ADO feed is easily discoverable from our readme, if it isn't already.

**Comment by MiYanni** [comment] 2022-09-07 20:33
@drewnoakes Yeah, that's what I was thinking too. The main problem is having very old packages on NuGet that people are still downloading. 20+ downloads a day of those old packages is pretty crazy.

https://www.nuget.org/packages/Microsoft.VisualStudio.ProjectSystem.Managed
![image](https://user-images.githubusercontent.com/17788297/188971610-61dcd5b9-74cc-4560-990e-3af75dcef23e.png)

https://www.nuget.org/packages/Microsoft.VisualStudio.ProjectSystem.Managed.VS
![image](https://user-images.githubusercontent.com/17788297/188971651-ebcc4f3b-ac59-4406-8640-c1f5074248d1.png)

**Comment by drewnoakes** [comment] 2022-09-07 21:06
Unlisting them won't break those existing users thankfully.

**Comment by tmeschter** [comment] 2022-09-22 23:21
We have these available in a public feed already, so we don't need to have them on NuGet.

- [ ] Update the README.md to specify where these can be found
- [ ] Unlist the old packages on nuget.org

**Comment by MagicAndre1981** [comment] 2023-01-17 20:41
but some [people have issues getting the previews from the Azure feed](https://github.com/dotnet/project-system/issues/7010#issuecomment-1373360991). So the better solution is to release (maybe also preview) versions on nuget which all users get.

**Comment by drewnoakes** [comment] 2023-04-13 23:49
Closing in favour of https://github.com/dotnet/project-system/issues/7010

**Closed by drewnoakes** 2023-04-13 23:49 UTC
Labels: Area-Infrastructure, Triage-Approved, good-first-issue
