### ISSUE TITLE
Removed "Edit n-build" dialog is severely missed

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#7756] opened 2021-11-10 21:50 UTC
_This issue has a corresponding [ticket on Developer Community](https://developercommunity.visualstudio.com/t/Removed-Edit-n-build-dialog-is-severel/1537770). Please vote and comment there to make sure your voice is heard._

---
Unless there's a way to easily list msbuild variables and their current values, I'm left having to go back to VS2019 any time I need a refresher on what's available for use. Not a show stopper and I love the new themed and easily navigatable settings, just miss this removed tool. Hopefully it comes back with more time.

![B5e4ba041e9d04cbdaaec800600db801e637680043396650333_20210923-073218-image](https://user-images.githubusercontent.com/350947/141201032-122a8145-c2af-4f7e-8929-e1ede067e3d7.png)

**Comment by drewnoakes** [comment] 2021-11-10 22:06
Duplicate of https://github.com/dotnet/project-system/issues/7408

**Closed by drewnoakes** 2021-11-10 22:06 UTC
