### ISSUE TITLE
Suggestion: Store indentation and code guidelines in project

### ISSUE THREAD

**Issue by weitzhandler** [dotnet/project-system#2624] opened 2017-07-18 11:54 UTC
Hi,

There should be an option to store the current VS coding-guidelines into the project, so when saving a file in a project that has custom coding-guidelines applied, the indentations, brace-placing, and other coding guidelines are preserved/adapted as to the project settings.
This will make it easier to work with GIT projects with different coding-guidelines (especially indentation, which affects the whole file).
A dev will be able to open a project with coding-guidelines different than his own, work on the file with his own indentation, then when saving, the file will be saved under the project's indentation setting.

**Comment by tannergooding** [comment] 2017-07-18 15:11
This likely belongs under dotnet/roslyn (with the `area-IDE` label).

Additionally, some of this functionality is already provided via `.editorconfig` and the new csharp/dotnet rules that are recognized: https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference

I do not believe we currently expose a way to persist the current VS options into an editorconfig file, but the roslyn-ide team should be able to tell you more if you migrate the issue over to dotnet/roslyn.

**Comment by sharwell** [comment] 2017-07-18 16:04
Duplicate of dotnet/roslyn#20253.

Most of the style features themselves are already supported by using a **.editorconfig** file, but there is no automated way (that I know of) to export the settings. I would recommend using [Mad's extension](https://marketplace.visualstudio.com/items?itemName=MadsKristensen.EditorConfig) along with [samples](https://github.com/dotnet/roslyn/blob/master/.editorconfig) if you'd like to enable the feature.

**Closed by sharwell** 2017-07-18 16:04 UTC
