### ISSUE TITLE
Creating unit test project using .NET Framework template will open older project model with packages.config

### ISSUE THREAD

**Issue by eriawan** [dotnet/project-system#3421] opened 2018-03-26 06:48 UTC
Hi guys,

Now that most of us use VS 2017 15.5.x or later, the project creation (including .NET Core and .NET Framework new project creation) should by default choose `PackageReference` model.

Machine configurations: (I have 2 machines)

- OS: Windows 10 Pro, build 16299.15
- VS used: VS 2017 Enterprise 15.5.5, VS 2017 Enterprise 15.6.4
- No VS 2017 preview installed

# Problem
Every time I create unit test project using .NET Framework template will open older project model with older `packages.config` model, even though I have set up the Package Management settings to always use Package Management as the default.

![image](https://user-images.githubusercontent.com/8773147/37890752-eb0fecfc-30fb-11e8-877b-c56b1b6d1c04.png)

## Current workaround
I have a temporary workaround, by updating the unit test csproj to use ordinary class library (but still use newer PackageReference) and let VS 2017 explore the unit test nicely, then it will be built nicely by MSBUILD. The normal `dotnet restore` afaik won't restore the nuget packages used in .NET Framework class library csproj that uses MSTest unit test. But I can use `MSBUILD /r` to restore nuget packages in projects in my solution as long as I'm sure that I use PackageReference on all of my projects inside the solution.

## Questions and suggestions

1. Is this the default behavior? Because if I use the legacy project model, I have to run `nuget.exe restore` before compile using MSBUILD every time I run CI especially on VSTS/TFS.
2. If this is the default behavior, then the legacy project model of .NET Framework unit test should be updated to use PackageReference as the default package management settings on VS 2017. There might be some problems about the GUID of the project type, and I also suggest to add new GUID as the unit test type project that uses PackageReference model. As far as I know by looking at current master branch, I can't find any references for this. CMIIW, though.

**Comment by davkean** [comment] 2018-03-26 06:51
This issue was moved to NuGet/Home#6736

**Comment by eriawan** [comment] 2018-04-03 04:44
@davkean 

Could you reopen this issue? Because I think this issue is not directly related to Nuget, and based on the latest conversation between @jainaashish and me in the Nuget/Home#6736, it has been confirmed by him that this is not Nuget issue too.

Or is there a repo for .NET Framework unit test project template? If there's any, I would love to move my issue to that repo.

Because I thought this repo of project-system should be the right place. Actually, my emphasize is on the project template when we create a new unit test project that targets .NET Framework, not the usage of the packages.config after I create the unit test project. Although I already set to use PackageReference by default, the unit test project template that targets .NET Framework still use older packages.config and referential GUIDs everywhere.

To demonstrate the issue I have, this is a quick demo of creating unit test using ,NET Framework unit test project template:

![vs2017_netfw_unittest_project](https://user-images.githubusercontent.com/8773147/38229619-d1fad0a4-3733-11e8-865c-791912156fc9.gif)

I hope this will clarify more. Thanks in advance!

**Comment by jmarolf** [comment] 2018-04-03 07:05
This is a feature request.  Currently it is by design that .NET Framework projects do not opt into the new sdk features and do not use package references.  What I am hearing @eriawan say is that he at least wants us to use package references in .NET Framework templates

**Comment by eriawan** [comment] 2018-04-03 09:04
@jmarolf 

Thanks! I'm sorry if this was meant for feature requests. 

I think I have to little bit disagree about your statement about _by design_:
>Currently it is by design that .NET Framework projects do not opt into the new sdk features and do not use package references.

That might not be true, according to my own experiences when I use VS 2017 15.5.x and 15.6.x. Because as far as I know, if we create new .NET Framework based projects such as class library, console, WindowsForms, and WPF (except unit test projects), these projects will use PackageReference as long as the settings of Package Management is set to use PackageReference by default, 

This is my current setting:

![image](https://user-images.githubusercontent.com/8773147/38236502-89efa4ae-374e-11e8-9ed3-7e8e721111f2.png)

and here's a quick demo of creating new .NET FW class library has PackageReference support (as governed by Package Management setting:

![vs2017_netfw_classlibproject_packagereference](https://user-images.githubusercontent.com/8773147/38239693-a714f710-3757-11e8-824e-12542aacfabc.gif)

CMIIW, but imho this proves that the PackageReference is already supported by .NET Framework project templates except .NET Framework unit test project template.

To be honest I don't know about the other .NET Framework projects such as Workflow Foundation and ASP.NET WebForms project template. 😊 

I propose to create a separate issue to track and log the parities of between the implemented/supported PackageReference (PR) project templates and the remaining packages.config (PC) model. If it's accepted, then maybe we can further reduce the parities and start to migrates the PC project templates to PR project templates.

**Comment by jmarolf** [comment] 2018-04-03 13:36
@eriawan ah, I stand corrected.  Looks like this was an oversight by the template owner. @jainaashish what is the public api that template authors should use to determine which setting (packages.config or package reference) has been set by the user?

**Comment by Pilchie** [comment] 2018-04-03 15:15
Isn't this a matter of whether the NuGet template wizard supports <PackageReference> or not?  IIRC - when we did project.json/packagereference for UWP, we did it with a custom template wizard, but to fix this in general, NuGet should fix the template wizard to support the option and do the right thing.

**Comment by Pilchie** [comment] 2018-04-03 15:16
To elaborate, the .NET Framework class library template doesn't install any NuGet packages, and so has no interaction with NuGet at all - it's not a good basis for comparison.

**Comment by eriawan** [comment] 2018-04-03 16:03
@jmarolf and @Pilchie 

Thanks for your reply! 
> ah, I stand corrected. Looks like this was an oversight by the template owner.
So, the scenario in my screenshot animation is not supposed to be the correct behavior? Could you tell me which element of the scenario is the oversight element?

I am now totally confused, as this current behavior is in VS 2017 15.5.x and 15.6.x is like that. Then the next question is:

1. What is the purpose of the dropdown of choice between PackageReference and packages.config then? I am aware that all .NET Core SDK related templates (including .NET Standard) are always using PackageReference, but I was assuming that .NET Framework get <PackageReference> supports too.
2. What I'm still confused is the fact that this option setting dialog is in VS 2017 since 15.4 until now (CMIIW), and I often use this setting since 15.5.1 until now 15.6.4.
3. The documentation of Nuget related to .NET Framework says that the .NET Framework projects support PackageReference. Detail and link below. Comparing to both @Pilchie and your explanation against the current doc, imho it's a little bit contradict and confusing at the same time. So which behavior should be the desired behavior? 
Apologize if I may sound silly, but when I have tried to digest, I always have conclusion that it's resulted in contradiction and at least the doc has different fact.

### Detail on the current nuget doc about packagereference in csproj files 
This is the detail of point 3 about the documentation:
Looking at the docs page of nuget:
https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files

It says that .NET Framework project templates support PackageReference: (emphasize added)

![image](https://user-images.githubusercontent.com/8773147/38259687-db49c49c-378f-11e8-95bb-c26d433ffc32.png)

But it doesn't mention any reference related to the Package Management setting dialog, unfortunately.

@Pilchie 

>To elaborate, the .NET Framework class library template doesn't install any NuGet packages, and so has no interaction with NuGet at all - it's not a good basis for comparison.

Hmmm... What do you mean no interaction with Nuget at all? Could you elaborate and be more specific?
According to my experience. On my machine, any .NET Framework project that are created after I set the setting to PackageReference
Please check the source code of ClassLIbrary3.csproj on my Gist: https://gist.github.com/eriawan/a4c78e73404f118b5b3b13ab7a081b66,

That simple project can always be compiled nicely in Visual Studio, and it will always download the nuget package if it's not yet available in my machine's cache.  


@jainaashish 

So now I'm back to square one. Could you please hop in and tell me your feedback or opinion about this issue? I'm now get the feeling that this is both related: .NET project system toolchain and Visual Studio Nuget tooling.
Still, I'm confused...

@kraigb

CMIIW, but as far as I know there's no documentation page on nuget settings in Visual Studio related to Package Management behavior setting and the consequences on .NET Framework projects.

![image](https://user-images.githubusercontent.com/8773147/38260980-3659af34-3793-11e8-827a-ffa6af793ad2.png)

If there's no docs about this, could I propose new content doc after this issue cleared or clarified?

**Comment by Pilchie** [comment] 2018-04-03 17:26
@jainaashish - I believe this issue does belong at NuGet.  The problem seems to be that the NuGet template wizard doesn't obey the option above.  That should be fixed by the Template wizard, not every individual template owner.

**Comment by jmarolf** [comment] 2018-04-03 17:32
@eriawan allow me to clarify if I can.

All the .NET Framework templates (except for the test template it would seem) do no install nuget packages on creation.  The package reference setting for nuget determines how nuget references should work when you add nuget packages.

So in you [linked example](https://gist.github.com/eriawan/a4c78e73404f118b5b3b13ab7a081b66) you:
1. Create a new class library (no nuget packages yet)
2. You add reference to the `log4net` (package reference is created according to your settings)

In the test template case you:
1. Create a new test project (packages are added for you on project creation)

The bug is that the template engine (specifically the wizard that nuget owns) does not respect your settings and makes a packages.config.

I'll add this context to the bug over in Nuget/Home#6736

**Closed by jmarolf** 2018-04-03 17:32 UTC
Labels: Feature Request, Feature-Templates

**Comment by jainaashish** [comment] 2018-04-03 17:46
Package management format selector was never meant to be supported with template wizard api. If you go through the blog post https://blog.nuget.org/20170316/NuGet-now-fully-integrated-into-MSBuild.html it says it only works when you explicitly install a package.

And the reason, it's not supported from template wizard, is because not all project systems yet supports PackageReference so it will be highly inconsistent behavior. Which is even if you enable this option, this dialog only appears for the projects which actually supports PackageReference.

And that's the reason, this has to come from individual templates owners when they know they supports PackageReference, then they can either set a msbuild property `RestoreProjectStyle` in their template or directly add PackageReference whatever is convenient for them to do.

**Comment by eriawan** [comment] 2018-04-03 18:11
@jmarolf 

Many thanks!
Aha, it makes sense now! Ok, I'm convinced that this issue is more on Nuget tooling side. And now I understand the @Pilchie statement about .NET Frameworks project has no interaction with nuget package: 
 > To elaborate, the .NET Framework class library template doesn't install any NuGet packages, and so has no interaction with NuGet at all - it's not a good basis for comparison.

So this because **_the package will not be restored at project creation_** for .NET Framework project templates. CMIIW.
Again, thanks guys!

to @jainaashish:

About the project template wizard support for PackageReference? I don't know about this template wizard. Is this template wizard open sourced, @jainaashish?
Hmmm.. Still, I couldn't see any further conclusion whose bug is this issue. Is it nuget bug?

I hope this issue reaches a complete agreement/conclusion (especially deciding that this is a bug or not) soon, Because I can't use the current .NET Framework unit test template for my team at all due to the fact of having this package.config model by default.

Pardon, for temporary solution my team and I will create our .NET Framework project template derived from current .NET Framework class library to have temporary solution for this problem. 
Also having a usual class library that has MSTest nuget packages specified means I don't have to maintain the dreaded tags of conditional tags that always check for MSTest DLL availability in the legacy unit test project. 

As I describe in the workaround, template is to provide a usual .NET Framework class library that contains MSTest V2 nuget packages, and then I'll wrap it as VS 2017 extensions with icons that represents unit test project. It's easier for me to do this and encourage my team to use this instead of having creating new .NET Framework unit test but having legacy packages.config model.

I'd love to go back to VS 2017 default .NET Framework unit test template because I hope VS/nuget team has updated the unit test project template to support PackageReference.

Cheers and many thanks, guys! 👍 🙂 

PS: apologize if I may seem like trolling you back and forth, guys. 🙏

**Comment by frizzr** [comment] 2019-01-08 19:11
> @jmarolf
> 
> Pardon, for temporary solution my team and I will create our .NET Framework project template derived from current .NET Framework class library to have temporary solution for this problem.

Would it be possible to share this project template to others who need this workaround? We are moving to PackageReference for everything and it would be really convenient to add this template for our uses.

Thanks!
