### ISSUE TITLE
When adding second target to project restore does not update assets.json file

### ISSUE THREAD

**Issue by abpiskunov** [dotnet/project-system#1960] opened 2017-04-11 01:31 UTC
This started to happen lately:

Create a new app and add 

> <TargetFramework**s**>netcoreapp2.0</TargetFramework**s**>

Then close app and reopen.

Edit csproj and add 

> <TargetFrameworks>netcoreapp2.0;netstandard1.4</TargetFrameworks>

Actual result: No restore happens and when i manually trigger solution level restore it says everything is up to date, however assets.json file has only target netcoreapp2.0 , but no netstandard1.4.

Reopening propject triggers restore and assets.json contains now both targets.

**Comment by davkean** [comment] 2017-04-12 10:02
I reckon the root cause of this is probably: https://github.com/dotnet/project-system/issues/1503

**Comment by srivatsn** [comment] 2017-04-13 07:02
Closing in favor of #1503.

**Closed by srivatsn** 2017-04-13 07:02 UTC
