### ISSUE TITLE
Dependencies node fails when ReferenceOutputAssembly="False" on ProjectReference

### ISSUE THREAD

**Issue by danroth27** [dotnet/project-system#2653] opened 2017-07-24 21:03 UTC
When I open https://github.com/aspnet/Blazor-Hackathon in VS I get a warning in the solution explorer for the project references for samples/ClientServerApp/ClientServerApp.Server. The dotnet-blazor reference has a warning icon, but there is no warning description in the VS error list.

**Comment by danroth27** [comment] 2017-07-24 21:05
![image](https://user-images.githubusercontent.com/1874516/28544733-26826754-7079-11e7-947b-72723de3b342.png)
![image](https://user-images.githubusercontent.com/1874516/28544738-2c85ccea-7079-11e7-9a6f-bcf05f77ffbd.png)

**Comment by danroth27** [comment] 2017-07-24 21:05
@srivatsn

**Comment by srivatsn** [comment] 2017-07-24 21:07
@natidea can you take a look at how widespread is this?

**Comment by abpiskunov** [comment] 2017-07-24 21:07
And what is under dotnet-blazor project? It could be either not compatible with ClientServerApp target framework or has some broken dependencies ...

**Comment by danroth27** [comment] 2017-07-24 21:22
The repo is public - just clone and take a look

**Comment by danroth27** [comment] 2017-07-24 21:22
![image](https://user-images.githubusercontent.com/1874516/28545344-86ca8e14-707b-11e7-963b-1250fa6e8c25.png)

**Comment by danroth27** [comment] 2017-07-24 21:23
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>netstandard1.3</TargetFramework>
    <RootNamespace>corlib</RootNamespace>
    <AssemblyName>corlib</AssemblyName>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <DisableImplicitFrameworkReferences>true</DisableImplicitFrameworkReferences>
    <RuntimeMetadataVersion>0</RuntimeMetadataVersion> <!-- Not sure what this affects, but there's a warning if you don't have some value -->
  </PropertyGroup>

</Project>
```

**Comment by abpiskunov** [comment] 2017-07-24 21:40
ClientServerApp.Server has target netcoreapp2.0 and references netstandard1.3 project which seems to be supported https://docs.microsoft.com/en-us/dotnet/standard/net-standard . So warning icon might appear because we use shipped in VS nuget API to check compatibility and need to see what Nuget returns there to start with...

**Comment by morrisjoe** [comment] 2017-07-27 19:41
@danroth27 @srivatsn @natidea 

This also happens for this simple scenario....

1. File->New->Web .NET Core 2.0 projects
2. Add a unit Test project to the sln
3. Add a P2P Ref from 2 to 1

**Comment by morrisjoe** [comment] 2017-07-27 20:01
@danroth27 @srivatsn @natidea

Note: Even though Dependencies/Projects shows yellow bang, Intellisense is working for the public classes coming in from the project reference

**Comment by natidea** [comment] 2017-07-27 20:07
In the case of @morrisjoe I see a NuGet restore failed and the log file contains package downgrade errors:

```json
    {
      "code": "NU1605",
      "level": "Error",
      "message": "Detected package downgrade: System.Net.Primitives from 4.3.0 to 4.0.11. Reference the package directly from the project to select a different version. \r\n UnitTestProject1 (>= 1.0.0) -> WebApplication1 (>= 1.0.0) -> Microsoft.VisualStudio.Web.BrowserLink (>= 1.1.2) -> Microsoft.AspNetCore.Hosting.Abstractions (>= 1.1.2) -> NETStandard.Library (>= 1.6.1) -> System.Net.Primitives (>= 4.3.0) \r\n UnitTestProject1 (>= 1.0.0) -> WebApplication1 (>= 1.0.0) -> Microsoft.VisualStudio.Web.BrowserLink (>= 1.1.2) -> System.Net.Primitives (>= 4.0.11)",
      "libraryId": "System.Net.Primitives",
      "targetGraphs": [
        ".NETCoreApp,Version=v2.0"
      ]
    },
```

Because of https://github.com/dotnet/project-system/issues/2436 these diagnostics are not showing up.

**Comment by johncollinson2001** [comment] 2017-09-21 09:41
Hi,

I get the same issue:- 

* .netcore2.0 asp.net project
* mstest unit testing project which references it
* warning icon on the referenced project within the the unit testing project
* tests run fine is Visual Studio
* nuget restore fails in the CI build in VSTS

Please help!

John

**Comment by natidea** [comment] 2017-09-21 14:16
@johncollinson2001 what specific errors are you getting in your CI build? If it is failing because of package downgrade errors (NU1605), you could try upgrading to the latest release, or changing the WarnAsError/NoWarn settings in your project.

**Comment by johncollinson2001** [comment] 2017-09-21 21:07
@natidea hi, many thanks for your help.

On my "dotnet restore" task, I'm getting:

`error NU1100: Unable to resolve 'Microsoft.NET.Test.Sdk (>= 15.3.0)' for '.NETCoreApp,Version=v2.0'`
`error NU1100: Unable to resolve 'MSTest.TestAdapter (>= 1.1.18)' for '.NETCoreApp,Version=v2.0'`
`error NU1100: Unable to resolve 'MSTest.TestFramework (>= 1.1.18)' for '.NETCoreApp,Version=v2.0'`

**Comment by natidea** [comment] 2017-09-21 21:55
@johncollinson2001 some things you can check: 
- what version of dotnet are you running (dotnet --info) and what SDK is located under C:\Program Files\dotnet\sdk\
- are the missing packages in any of your NuGet caches (e.g %USERPROFILE%\.nuget\packages)
- you could try clearing these caches
- could you also upload a copy of the project.assets.json file associated with the failing project

**Comment by drewnoakes** [comment] 2019-02-20 17:30
Verified this still occurs in d16.0.

Reproswith aspnet/Blazor-Hackathon@8258a43c8293fcc7eee3ba8c47e3d8acef06b586. You'll probably need to update the SDK version in `global.json`. I used `2.1.600-preview-009497` and the solution built successfully.

- `ClientServerApp.Server.csproj` is `netcoreapp2.0` and references project...
- `Blazor.Host.csproj` (`dotnet-blazor`) which is `netcoreapp2.0` and references project...
- `corlib.csproj` which is `netstandard1.3`

The issue can be isolated between the last two projects. The P2P reference on `corlib` is flagged as unresolved, yet the _Dependencies_ node of `corlib` is empty and does not show any warning.

![image](https://user-images.githubusercontent.com/350947/53110929-fe720400-3533-11e9-8eb3-292213f8db7d.png)

**Comment by drewnoakes** [comment] 2019-02-20 17:33
Adding a reference to `corlib` makes the warning go away on the P2P ref in `Blazor.Host`.

**Comment by drewnoakes** [comment] 2019-02-20 20:03
We are not seeing a `ResolvedProjectReference` for `corlib.csproj`:

![image](https://user-images.githubusercontent.com/350947/53120238-4cddcd80-3549-11e9-8695-e91a050b4d85.png)

The lower red box shows `ProjectReference` changes received via evaluation. These are considered unresolved.

The upper red box shows `ResolvedProjectReference` changes received via design-time builds. These are considered resolved.

`corlib.csproj` does not appear in the list of resolved project references, therefore we never set the 'resolved' state of `corlib.csproj` to `true`.

**Comment by davkean** [comment] 2019-02-20 22:54
@drewnoakes Those are the resolved paths, we match resolved paths -> evaluation equivalent via the `OriginalItemSpec` metadata, what does it say?

**Comment by drewnoakes** [comment] 2019-02-21 17:18
@davkean the `OriginalItemSpec` values all match the DLL names. There's no mention of `corlib.csproj` anywhere in the `ResolvedProjectReference` data.

**Comment by davkean** [comment] 2019-02-21 21:58
We'd need to fall back to design-time build logs to figure out why its not being resolved. Very likely the project is missing core targets, or targets that are returning the wrong answers.

**Comment by davkean** [comment] 2019-02-21 22:02
Or maybe not the project [looks normal](https://github.com/aspnet/Blazor-Hackathon/blob/master/src/DNA/corlib/corlib.csproj), but I'd still look design-time builds logs.

**Comment by drewnoakes** [comment] 2020-04-30 00:35
Minimal repro for this:

1. Create two projects
2. Add a `ProjectReference` from one to the other
3. Add `ReferenceOutputAssembly="False"` to that `ProjectReference` item

This causes the item to appear in evaluation but not in the DTB, which is currently treated as indicating the project is unresolved.

**Comment by drewnoakes** [comment] 2020-04-30 05:10
Duplicate of #2928.

**Closed by drewnoakes** 2020-04-30 05:10 UTC
Labels: Bug, Feature-Dependency-Node
