### ISSUE TITLE
Unexpected problem when using multiple target frameworks like net5.0;net5.0-windows

### ISSUE THREAD

**Issue by michaelmairegger** [dotnet/project-system#6843] opened 2021-01-19 16:09 UTC
**Visual Studio Version**: 16.8.4

**Summary**:

If I open a solution that contains at least one project with multiple target frameworks of the same base type e.g. `net5.0` then VS shows me an error with the attached log file.

**Steps to Reproduce**:

Create a solution with a project with the following content:

    <Project Sdk="Microsoft.NET.Sdk">
        <PropertyGroup>
            <TargetFrameworks>net5.0;net5.0-windows</TargetFrameworks>
        </PropertyGroup>
    </Project>

If you remove either `net5.0` or `net5.0-windows` than no error appears. It seems that having duplicate `net5.0` raises the issue. Note that package restore and building works.

Another scenario happens if you change the target frameworks to `net451;net5.0;net5.0-windows` . Then after opening the solution no warning appears but witin the "Error List" window three errors occur:

> Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4018	The "ResolvePackageDependencies" task failed unexpectedly.
System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Microsoft.NET.Build.Tasks.ResolvePackageDependencies.ExecuteCore()
   at Microsoft.NET.Build.Tasks.TaskBase.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	ClassLibrary1	C:\Program Files\dotnet\sdk\5.0.102\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets	186	

**Expected Behavior**:

No warning

**Actual Behavior**:

Warning with the log file that is attached to this issue
[VsProjectFault_715cee26-a656-4da1-b1f9-65aa19d4e467.failure.txt](https://github.com/dotnet/project-system/files/5837026/VsProjectFault_715cee26-a656-4da1-b1f9-65aa19d4e467.failure.txt)

**User Impact**:

Annoying warning popup

**Comment by drewnoakes** [comment] 2021-01-19 22:51
Thanks for the detailed error report.

This is a duplicate of https://github.com/dotnet/sdk/issues/15291 which has a fix in PR and is currently slated for 5.0.2xx.

**Comment by michaelmairegger** [comment] 2021-01-20 13:33
@drewnoakes Thanks for the quick response.

**Closed** 2021-01-26 18:51 UTC
Labels: Resolution-Duplicate, Triage-No-Action
