### ISSUE TITLE
Dependency Build node does not account for Package References modified by build tasks

### ISSUE THREAD

**Issue by KevinRansom** [dotnet/project-system#3235] opened 2018-02-09 21:04 UTC
This project:

Incorrectly identifies ValueTuple as a reference that is not resolved.  It is not resolved because it was removed by a build task.

Effectively, the dependency node needs to identify depends following the design time build.

````
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="System.ValueTuple" Version="4.3.1" />
    </ItemGroup>

     <Target Name="ValueTuplePackageReferences" BeforeTargets="CollectPackageReferences;">
        <ItemGroup>
            <PackageReference Remove="System.ValueTuple" />
        </ItemGroup>
    </Target>

</Project>
````

![image](https://user-images.githubusercontent.com/5175830/36049907-53eb4a9a-0d99-11e8-98e9-1c6280404bf6.png)

**Comment by davkean** [comment] 2018-02-14 03:52
I'm not sure what the design for this would like. The design is as follows:

- Populate the references from evaluation results (fast)
- Fill in the details from design-time builds (slow)

If we were to remove it in this case, we'd basically have to ignore evaluation results - causing the node to take longer to populate, or add it but then remove it when we noticed the design-time build removed it (which we can't tell if it just wasn't resolved or removed).

The former would be slow, the latter would be confusing as it would appear and then disappear when the design-time build finished (the user is unaware of this build)

Make note, legacy project system hasn't resolved this and gives the same experience. Open to ideas for a better design.

**Comment by drewnoakes** [comment] 2019-08-06 05:20
@KevinRansom the dependency node is designed to ensure that items are added during evaluation and not changed by targets in the build. Although that is supported by MSBuild, it's not supported in the UI.

The goal is to have the UI populate quickly based on the evaluation results. This is what happens today, and it's a good experience.

When the build arrives, items are updated with extra data, but we're explicitly designing it so that the build cannot add or remove items.

Adding or removing items after evaluation is potentially confusing. And what if a target only adds the item based on some uncontrollable and unknowable external condition (e.g. the current timestamp has an odd number of ticks)?

As @davkean says above, legacy behaves the same way.

This issue is fairly old now. Is this something you've missed in the last year and a half? Would you object to this being closed as by design?

**Comment by drewnoakes** [comment] 2019-08-09 02:13
Closing for now.

**Closed by drewnoakes** 2019-08-09 02:13 UTC
Labels: Feature-Dependency-Node
