### ISSUE TITLE
Close VS and reopen the project, prompt error for F# .net core projects

### ISSUE THREAD

**Issue by MiaomiaoHuangfu** [dotnet/project-system#2893] opened 2017-10-16 10:03 UTC
Create an F# .net core console app, restore, build and run succeeded.
Close VS and reopen the project, the Error List Window show 1 error about namespace "open System".
![f1](https://user-images.githubusercontent.com/22901391/31606143-e3b2b280-b29a-11e7-9b9f-5875ec3ea2f7.png)

**Expected result**
Close VS and reopen the project, restore succeeded with no error in error list window.

Test on d15rel.27013.02
dotnet --version:
```
.NET Command Line Tools (15.5.0-preview-007044)

Product Information:
 Version:            15.5.0-preview-007044
 Commit SHA-1 hash:  278cbf6c44

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\15.5.0-preview-007044\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

**Comment by Pilchie** [comment] 2017-10-16 14:53
Tagging @KevinRansom @brettfo @cartermp.

**Comment by cartermp** [comment] 2017-10-16 15:50
I'm noticing that `EntryPoint` is not colorized as a type.  Could that mean this is related to https://github.com/Microsoft/visualfsharp/issues/3222 ?

**Comment by cartermp** [comment] 2017-10-25 16:55
I cannot reproduce this on 15.5 Preview 2 with @KevinRansom's P2P branch VSIX installed.

**Comment by Pilchie** [comment] 2017-11-01 20:34
Closing based on current F# insertions.

**Closed by Pilchie** 2017-11-01 20:34 UTC
Labels: Area-F#, Bug
