### ISSUE TITLE
"Warning level" UI shows values for each target, when it can't vary by target

### ISSUE THREAD

**Issue by BretJohnson** [dotnet/project-system#8042] opened 2022-04-06 05:35 UTC
## Visual Studio Version
Recent Int Preview build (32403.30.main)

## Summary
"Warning level" UI shows values for each target, but it can't vary by target

## Steps to Reproduce

1. Do File / New Project / MAUI, to create a new project that uses multi targeting.
2. Bring up the project settings, and view the "Warning level" setting and "Analysis level" setting

Note that for Warning level it shows all the targets (and is disabled). Is this setting allowed to vary by target type? Probably not, as there's no gear icon for it nor for "Analysis level". 

![image](https://user-images.githubusercontent.com/245892/161901218-5c94e008-784a-4b08-8228-d1afc6d3d3ab.png)
![image](https://user-images.githubusercontent.com/245892/161902380-74ae9c2c-c53d-44d8-bf30-939e54337037.png)

## Expected Behavior

Warning level shouldn't list all the targets (I assume this is a bug).

## User Impact

Users can be confused

**Comment by drewnoakes** [comment] 2022-04-06 09:35
At first glance this appears to be a duplicate of #8043.

**Comment by adamint** [comment] 2022-05-18 03:45
This is a duplicate of #7886

**Closed by adamint** 2022-05-18 03:45 UTC
Labels: Triage-Investigate, Feature-Project-Properties-Designer
