### ISSUE TITLE
Opening Roslyn.sln edits a bunch of designer files

### ISSUE THREAD

**Issue by rchande** [dotnet/project-system#2614] opened 2017-07-14 15:31 UTC
I have roslyn master checked out at b63394e0c0ce7ae748cd8df4d68a6045713cece9 and am using VS 26706.0.d15rel. Every time I open Roslyn.sln, I get edits to a bunch of Resources.Designer files.

The diffs look like below. Seems like something is replacing 4 with 15.
```C#
-    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
+    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
```

**Comment by rchande** [comment] 2017-07-14 15:31
cc @davkean

**Comment by srivatsn** [comment] 2017-07-24 18:54
@davkean @tmeschter any idea what causes this?

**Comment by davkean** [comment] 2017-07-24 22:16
I suspect we're running single file generators - why, I don't know.

**Comment by tmeschter** [comment] 2017-09-12 18:24
@rchande I'm not able to reproduce this with 26831.0.d15rel. Unless you have an objection, I'm going to close this.

**Closed** 2017-09-12 18:24 UTC
Labels: Bug, Resolution-No Repro

**Comment by DanJ210** [comment] 2019-06-27 18:22
This is happening to me as well but with no one else on the time. Knowing why would be a cool thing to know.

**Comment by DanJ210** [comment] 2019-06-27 18:32
Actually it could be related to .Net Versions. https://apisof.net/catalog/System.Resources.Tools.StronglyTypedResourceBuilder

I saw 4.7 on a coworkers machine and I had 4.8, unfortunately the link doesn't show 4.8 but this theory does make sense. The main question is if a coworker will have any issue when using the `15` version opposed to the `4`.
