### ISSUE TITLE
Dependencies tree is lost when creating a .NET Core project

### ISSUE THREAD

**Issue by MiaomiaoHuangfu** [dotnet/project-system#1986] opened 2017-04-13 08:43 UTC
1. Create a .NET Core project with no errors, auto restore succeeded, but failed to display the dependency tree.
![createnetcoreprojectfailedtoshowdependenciestree](https://cloud.githubusercontent.com/assets/22901391/24997154/3c26f432-2068-11e7-87e3-7a14aad47cbc.png)

2. Closed the solution and reopen it, the  Dependencies tree shows correctly.
![closeandreopenslnshowdependenciestree](https://cloud.githubusercontent.com/assets/22901391/24997137/29b3d806-2068-11e7-9e9b-6957c8ae2ee7.png)

**Comment by MiaomiaoHuangfu** [comment] 2017-04-13 08:46
Test on  vsuwpt.26412.00;
OS: Window 10 X64

**Comment by davkean** [comment] 2017-04-13 08:47
Is there any errors in the error list?

**Comment by MiaomiaoHuangfu** [comment] 2017-04-13 08:50
No, there is no errors or warnings in error list window.

**Comment by abpiskunov** [comment] 2017-04-13 13:11
This is known and should be fixed by pending PR.

Thanks,
Anton

On Apr 13, 2017, at 1:47 AM, David Kean <notifications@github.com<mailto:notifications@github.com>> wrote:


Is there any errors in the error list?

**Comment by srivatsn** [comment] 2017-04-13 16:40
By pending PR you mean #1981?

**Comment by abpiskunov** [comment] 2017-04-13 16:52
The one i am preparing for memory leak issue, i am testing it now

**Comment by abpiskunov** [comment] 2017-04-13 16:52
(the root cause is similar and it would fix it)

**Comment by srivatsn** [comment] 2017-04-20 18:53
This should be fixed with https://github.com/dotnet/project-system/pull/1991. Please reopen if you see it still.

**Closed by srivatsn** 2017-04-20 18:53 UTC
