### ISSUE TITLE
Make sure class diagrams work

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#256] opened 2016-06-22 18:16 UTC
Class diagrams didn't work in xproj, we need to figure out if that was based on CPS, or just based on the xproj model. We should test them.

**Comment by 333fred** [comment] 2016-12-06 22:58
The command for the right-click menu is `VSConstants.VSStd2KCmdID.ViewInClassDiagram`. Old csproj handled this by using an IViewInClassDiagram instance, which is defined in MS.VS.EnterpriseTools.Shell. This binary isn't always installed, so rather than having the project system handle this command and check so see whether the designer is installed, we should make the designer handle the command itself. Dave and I are thinking this is probably beyond the scope of RC3 though. @srivatsn, opinions?

**Comment by davkean** [comment] 2016-12-06 23:00
It's already handling View In Class diagram for Class View, so I think it makes more sense to live in the class diagram code.

**Comment by srivatsn** [comment] 2016-12-06 23:01
That seems fine - why do you think it's beyond the scope of RC3?

**Comment by 333fred** [comment] 2016-12-06 23:04
With the edit csproj changes and migration changes, I'm not sure I'll have time for this as well.

**Comment by srivatsn** [comment] 2016-12-06 23:11
Ah ok. @RaulPerez1 would you be able to look into this?

**Comment by RaulPerez1** [comment] 2016-12-16 23:29
@davkean where is the class diagram code? I couldn't find any reference in the project system repo so I'm presuming this is in VS?

**Comment by davkean** [comment] 2016-12-16 23:30
Yeah, look at the usages of IViewInClassDiagram on index.

**Comment by RaulPerez1** [comment] 2016-12-16 23:58
Even though the core class diagram code handles the command (for class view) it does nothing so I think we're going to need changes on our side one way or another.

@srivatsn I think this is going to be larger than a regular bug fix and will definitely not fit in for RC3.

**Comment by davkean** [comment] 2017-03-21 06:29
@RaulPerez1 What's going on with this? Is this something you plan on completing before joining your old team?

**Comment by RaulPerez1** [comment] 2017-03-21 16:32
As long as I can get it done this week yes. I'm investigating and I've found 2 additional bugs in the area so far. One's a CPS issue and the other one I'm sending out a PR today as soon as I finish testing it.

**Comment by tannergooding** [comment] 2017-04-21 16:19
@srivatsn. Class diagrams do not currently work at all. Attempting to open one results in the following dialog:

![image](https://cloud.githubusercontent.com/assets/10487869/25286714/9249d742-2673-11e7-8ac0-d91f89018909.png)

**Comment by srivatsn** [comment] 2017-04-21 16:26
I assume this is because class designer is still looking for C# projects based on projectypeguid instead of capabilities. @RaulPerez1 did your VSO PR get merged?

**Comment by srivatsn** [comment] 2017-04-21 16:27
I see that https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/61185 is still active. @tannergooding can you shepherd that in?

**Comment by tannergooding** [comment] 2017-04-21 16:32
Can do. I've pinged the original author ( @RaulPerez1 ) and the current reviewer ( @davkean ). It looks like all feedback has been addressed and it is just waiting final sign-off.

**Comment by RaulPerez1** [comment] 2017-04-21 16:49
Look at my email on the topic for details, there's also a CPS bug and you'll need to add the capability to the design time targets in the project system.

**Comment by patnolan** [comment] 2017-04-21 21:30
Is it possible to get as ETA for when the fix for this issue will be available?

**Comment by wolf99** [comment] 2017-07-25 09:29
What is the current state of this? Did that PR ever get merged? I'm not seeing it in the listings here for either 15.3 or 15.6 milestones.

**Comment by srivatsn** [comment] 2017-07-25 16:50
The PR mentioned above was for the class diagram designer which is not open source. That was merged. However there's a bug in CPS (also not open source) that still needs to be fixed before this scenario can work fully. I've just pinged that bug today.

**Comment by srivatsn** [comment] 2017-07-25 16:51
[CPS bug for reference](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/395144)

**Comment by xiexin36** [comment] 2017-08-29 12:04
Any update about this?

**Comment by Andrey-iTech** [comment] 2017-09-11 17:25
Hi guys,

Is the issue going to be resolved in the nearest future? For our team it is very important feature and the issue is preventing us from migrationg to .net standard/core. [Modeling project](https://msdn.microsoft.com/en-us/library/dd409445.aspx) is not an option for us because it doesn't provide "two-way binding" between a digram and actual source code.

**Comment by tannergooding** [comment] 2017-09-11 17:36
FYI. @Pilchie. I pinged the CPS bug as well, which is still open.

**Comment by tannergooding** [comment] 2017-09-11 22:21
FYI. @davkean

**Comment by tannergooding** [comment] 2017-09-11 22:22
FYI. @davkean

**Comment by davkean** [comment] 2017-09-11 22:24
@tannergooding What's the CPS ask here?

**Comment by tannergooding** [comment] 2017-09-11 22:30
To fix this bug https://devdiv.visualstudio.com/DevDiv/_workitems/edit/395144

**Comment by davkean** [comment] 2017-09-12 01:38
@tannergooding Looks like a one line change - can we just submit the change?

**Comment by tannergooding** [comment] 2017-09-12 02:28
If they will take it, we should be able to

**Comment by tannergooding** [comment] 2017-09-12 17:25
The fix on our side is here: https://github.com/dotnet/project-system/pull/2817

If you build and deploy locally, you should be able to add and open class diagrams.

However, without the CPS change it may result in multiple warning dialogs popping up the first time you attempt to add the diagram to the project.

Then, manually opening the document subsequently appears to function correctly.

**Comment by Andrey-iTech** [comment] 2017-09-13 08:13
Thank you guys and thank you @tannergooding! I've replaced "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\VisualStudio\Managed\Microsoft.CSharp.DesignTime.targets" with the file from #2817 (https://raw.githubusercontent.com/tannergooding/project-system/1ab632313f0715fced04e2f383416f3ec6695268/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.CSharp.DesignTime.targets) and it works for .net core projects!

There is a minor issue occurring every time I load the solution (https://www.screencast.com/t/q6yuSZMd8u0A) but the diagram works.

Additionally, there is another minor issue with .net standard projects (I'm not sure if it right place to report it). "Class Diagram" item is missing from "Add new item" menu for .net standard projects (e.g. <TargetFramework>netstandard1.3</TargetFramework>) https://www.screencast.com/t/xY3KM5sZ. It works if I copy existing class diagram from .net core project to .net standard project.

VS version 15.3.4.

**Comment by davkean** [comment] 2017-09-13 08:19
@tannergooding We should fix/investigate that bug in the screen cast as part of this.

@Andrey-iTech Can you file a separate bug about that Add New Item? That won't block checking this in.

**Comment by Andrey-iTech** [comment] 2017-09-13 09:08
@davkean added #2820.

**Comment by Univac1107** [comment] 2017-09-14 17:24
Hello, I need to add a class diagram to a .net core class library project. 
I've replaced the Microsoft.CSharp.DesignTime.targets file as stated, and restarted VS. 
There are no changes, it does not open a manually added class diagram.

Am I missing some other steps? 

I'm using Visual Studio Community 2017.
Thank you very much.

**Comment by tannergooding** [comment] 2017-09-14 17:28
@Univac1107, when you attempt to open the class diagram, do you get an error dialog or does attempting to open it cause nothing to occur?

**Comment by Univac1107** [comment] 2017-09-14 17:39
The class diagram option does not appear on the new item menu.
I manually added a class diagram with this content:

`<?xml version="1.0" encoding="utf-8"?>
<ClassDiagram /> `

When double clicking it, I get the dialog:

> Class diagrams are not supported for this project type.

I've used the file given on: (https://raw.githubusercontent.com/tannergooding/project-system/1ab632313f0715fced04e2f383416f3ec6695268/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.CSharp.DesignTime.targets).

Should I reinstall VS?

**Comment by tannergooding** [comment] 2017-09-14 17:51
@Univac1107, is it a NetStandard project (#2820)?

Could you share the solution (or a simplified solution) so that I can check this out?

**Comment by Univac1107** [comment] 2017-09-14 18:58
Here is the link to the sample app i'm using:

https://drive.google.com/file/d/0B5Cy0l7YShV2UC1aam9nT0dWNEE/view?usp=sharing

**Comment by Univac1107** [comment] 2017-10-03 15:25
Any update on this?

**Comment by tannergooding** [comment] 2017-10-03 16:43
@Univac1107, I am able to open the class diagram successfully with the solution you supplied (sorry for the delayed response, this slipped my radar).

**Comment by Univac1107** [comment] 2017-10-03 17:43
So I guess I'm missing something.
Beside of replacing that file, is there something else to do? May the version of VS Community Edition matter? Should I reinstall it?

**Comment by tannergooding** [comment] 2017-10-03 17:46
AFAIK, it shouldn't. You should just have to replace/modify your local copy of `Microsoft.CSharp.DesignTime.targets` with the fixes in the PR (your local copy, by default, would be under C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Microsoft\VisualStudio\Managed\Microsoft.CSharp.DesignTime.targets).

**Comment by Univac1107** [comment] 2017-10-03 18:21
So it leaves it only one option, that this file:
https://raw.githubusercontent.com/tannergooding/project-system/1ab632313f0715fced04e2f383416f3ec6695268/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.CSharp.DesignTime.targets 
has something wrong!

**Comment by justdmitry** [comment] 2017-10-13 13:06
@Univac1107, double-check changes to file.

I have VS2017 Community Edition (v15.3.0), changed `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Microsoft\VisualStudio\Managed\Microsoft.CSharp.DesignTime.targets` with this diff:
![targets-diff](https://user-images.githubusercontent.com/3540597/31547405-e88c8672-b02f-11e7-9aaf-113505d8f559.png)

Then I restarted VS, manually create *.cd file with content:
```
<?xml version="1.0" encoding="utf-8"?>
<ClassDiagram MajorVersion="1" MinorVersion="1">
  <Font Name="Segoe UI" Size="9" />
</ClassDiagram>
```

And this diagram successfully opened in VS and I can add classes to it, save, reopen VS and open diagram again. With error message (once after VS launch), but works. Woo-hoo!

**Comment by mortb** [comment] 2017-10-24 11:43
So, this is scheduled to work after the release of https://github.com/dotnet/project-system/milestone/19 ?

**Comment by tgitchel** [comment] 2017-11-02 13:54
This works for me, except I cannot create Collection Association links.  I get "This is not a valid type name." message when I try.

**Comment by sandord** [comment] 2017-11-10 09:47
> This works for me, except I cannot create Collection Association links. I get "This is not a valid type name." message when I try.

Same here, actually in a .NET Framework 4.7 project that references a netstandard 2.0 class library that has the classes in it which I have on my diagram.

**Closed** 2017-11-29 06:02 UTC
Labels: 0 - Backlog, Feature Request, Parity-VSLangProj

**Comment by davkean** [comment] 2017-11-29 06:09
@tgitchel @sandord It's been about 12 years since I've used Class Diagrams, can you tell me how/what are Collection Association links are? My google foo is failing me and can't figure out how to attempt to add them.

**Comment by tgitchel** [comment] 2017-11-29 12:38
@davkean, a collection association link will show the relationship from once class property that is a collection (array, list, etc.) of another.  If you right-click on the collection property you will see an option for "Show as Collection Association".

**Comment by davkean** [comment] 2017-11-29 22:43
@tgitchel Thanks - I can repro this. It looks like the diagram thinks we're a VB project, filed: https://github.com/dotnet/project-system/issues/3003.

On top of that, there's two other bugs that we have around this:

https://github.com/dotnet/project-system/issues/2999
https://github.com/dotnet/project-system/issues/2998

**Comment by odalet** [comment] 2018-01-10 08:55
@justdmitry 

Based on your trick, I managed to have my netstandard 2.0 project work with class diagrams (VS 15.4.4):

I simply added this to the end of my .csproj:

```xml
  <ItemGroup>
    <ProjectCapability Include="CSharp;Managed;ClassDesigner" />
  </ItemGroup>
```

and I can add/edit class diagrams in this project (nio need to restart VS as it is local to the project).

Btw, it works whatever framework I target (tried netstandard2.0 and net45).

**Comment by weitzhandler** [comment] 2020-04-16 15:52
Are we ever gonna see official Class Designer support in .NET Core or Standard again?
