### ISSUE TITLE
Remove "Prefer32Bit" checkBox in . NetCore project settings.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#5746] opened 2019-12-18 16:39 UTC
_This issue has a corresponding [ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/791429/remove-prefer32bit-checkbox-in-netcore-project-set.html). Please vote and comment there to make sure your voice is heard._

---
<p>According to the question in [Prefer32Bit is ignored in .netcore3.0 app](https://developercommunity.visualstudio.com/content/problem/789878/prefer32bit-is-ignored-in-netcore30-app.html), AnyCPU + Prefer32bit is only used on .NET Framework and Windows due to how processes are loaded/launched.
So, I suggest that remove &quot;Prefer32Bit&quot; checkBox in . NetCore project setting page as It may misslead developer.</p>

---
#### Visual Studio Feedback System on 10/24/2019, 11:17 PM: 

Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by melytc** [comment] 2020-02-18 19:15
This is a duplicate of issue #5074. Will be tracking progress there (giving priority to it since it was opened first), closing this one out 😄

**Closed by melytc** 2020-02-18 19:15 UTC
Labels: Bug, Feature-AppDesigner, Triage-Approved
