### ISSUE TITLE
Info bar to warn users about slow design time builds due to custom tasks

### ISSUE THREAD

**Issue by srivatsn** [dotnet/project-system#2676] opened 2017-07-31 17:49 UTC
If a design time build is taking longer than some threshold and if we see that there are custom tasks in the DT build, pop up an info bar with a link to a doc that explains how to profile and fix the DT build perf.

**Comment by davkean** [comment] 2017-08-04 07:16
I've thought about this a bit more, and I think we need to take this further. In the [past two slow design-time builds](https://github.com/Microsoft/msbuild/issues/2392) that I've investigated - none of them are due to slow targets. The are caused by evaluation time. Perhaps we need a hook from MSBuild to grab evaluation times (or we capture that from CPS) - and we warn if things are slow.

**Comment by rainersigwald** [comment] 2017-08-04 15:14
@davkean MSBuild does have `ProjectEvaluationStartedEventArgs`; in https://github.com/Microsoft/msbuild/pull/2157 we started emitting evaluation time information into our own performance summary.

**Comment by srivatsn** [comment] 2017-08-04 15:28
We should only pop up the info bar if there is something that the user can do fix the problem. If it's evaluation being slow, I doubt there's anything they can do - that's for us to fix the perf issues.

**Comment by davkean** [comment] 2017-08-04 18:50
User written globs can affect evaluation.

**Comment by Pilchie** [comment] 2017-09-20 15:46
Moving to 15.5, since that's where we're targeting the infobar now.

**Closed** 2017-11-16 22:12 UTC
Labels: Feature Request
