### ISSUE TITLE
conditional compilation symbol not read

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#4295] opened 2018-11-20 22:27 UTC
I added a conditional compilation symbol PROD to my Release.
After I changed my configuration to Debug and came back to Release, the PROD compilation symbol is not read. 

I had to check Debug and then uncheck it for the editor to be able to pick up the compilation symbol.

This used to work correctly before this last update to VS 2017.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/45205/conditional-compilation-symbol-not-read.html
VSTS ticketId: 412101_
_These are the original issue comments:_

Nick Bauer on 8/16/2017, 01:07 PM (461 days ago): I believe I have a similar problem, having just upgraded from 15.2 to 15.3. I have a "LOCAL" constant to cause the client project to call a local service vs. web service, but this symbol doesn't seem to be read--the code shows #if LOCAL code in gray, and compilation uses the code under #elif instead.
Nick Bauer on 8/16/2017, 01:17 PM (461 days ago): Possibly related: it seems that one of my build configurations was being ignored, so when I recreated it there were two entires in the csproj file. Deleting that, unloading and reloading the project fixed it.
志文 左 on 3/21/2018, 11:23 PM (243 days ago): it is not fix yet!
_These are the original issue solutions:_
(no solutions)

**Comment by jjmew** [comment] 2018-11-20 22:29
duplicate of https://github.com/dotnet/project-system/issues/2733

**Closed by jjmew** 2018-11-20 22:29 UTC
