### ISSUE TITLE
VS and msbuild spinning constantly in recent drop

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/project-system#2576] opened 2017-07-07 04:18 UTC
I've upgraded to: 

![image](https://user-images.githubusercontent.com/4564579/27942983-3718cf32-6290-11e7-9fa4-39ebd14300df.png)

I'm finding huge swaths of time when both VS and msbuild are just spinning at least two full cores of my machine.  This is especially bad since this is a laptop and it drains the battery significantly while this is happening.

ETL can be found here: https://drive.google.com/file/d/0ByISdSEZ09PBbVp0enRzSVNhZVk/view?usp=sharing

**Comment by CyrusNajmabadi** [comment] 2017-07-07 04:18
Tagging @davkean

**Comment by davkean** [comment] 2017-07-10 23:35
@CyrusNajmabadi I'll look at this today.

**Comment by davkean** [comment] 2017-07-11 00:05
Can you give me the exact commit that you are sync'd against?

**Comment by davkean** [comment] 2017-07-11 00:11
Haven't figured out what's going on yet (I suspect we're constantly reevaluation due to a restore loop), but 16% of all the time here is spent on a GetFileAttributesEx check in the DiagnosticIncrementalAnalyzer that seems a lot:

![image](https://user-images.githubusercontent.com/1103906/28045572-382bfcd4-6621-11e7-8e57-d4ed25220297.png)

**Comment by davkean** [comment] 2017-07-11 01:27
I'm not seeing this on 46709.0.d15rel. I do see lots of MSBuild instances and us chewing CPU for a few minutes, but this looks like us doing design-time builds but we eventually stop.

@CyrusNajmabadi If you leave it VS open for 10 minutes, does the CPU stop?

**Comment by CyrusNajmabadi** [comment] 2017-07-11 01:31
Probably yes.  But then i use the product and these things spin up again.  Effectively, as long as i'm using VS i'm seeing these issues unendingly.

**Comment by davkean** [comment] 2017-07-11 01:34
@CyrusNajmabadi What kinds of changes? If you add a source file, remove, rename a source file then this is going to cause us to reevaluate and spawn MSBuild.

**Comment by CyrusNajmabadi** [comment] 2017-07-11 01:40
Just editing.  Perhaps a file change a few times an hour.  VS is behaving exceptionally poorly from startup till shutdown.  When it gets particularly bad (i.e. i can't even function and deal with the constant few-second ui hangs), i take these traces and report the issues.

**Comment by davkean** [comment] 2017-07-11 01:44
@CyrusNajmabadi Okay, but I'm trying to figure out if those issues are different to this issue or not. This issue says you have constant CPU and MSBuild constantly - I'm trying to figure out if you are actually experiencing a constant CPU when you aren't making changes or whether the perf issues are result of something else, such as this one: https://github.com/dotnet/project-system/issues/2579.

**Comment by CyrusNajmabadi** [comment] 2017-07-11 01:47
Ok.  so as an example, i was just editing right now and i lost all intellisense.  I looked and my file had moved into the misc workspace.  So i tried to close VS.  It just hung there.  The hang was so long that i went and collected a trace.  I will upload that now.

**Comment by CyrusNajmabadi** [comment] 2017-07-11 02:15
Closing VS trace: https://drive.google.com/file/d/0ByISdSEZ09PBUF9pSy1wQXNHZTQ/view?usp=sharing
MSBuild spinning trace: https://drive.google.com/file/d/0ByISdSEZ09PBVmVCQ3AzdUdjOEU/view?usp=sharing

**Comment by Pilchie** [comment] 2017-11-01 20:42
Duplicate of #2593

**Closed by Pilchie** 2017-11-01 20:42 UTC
Labels: Bug, Performance
