### ISSUE TITLE
Up-to-date checks are too agressive in VS15.6

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#3359] opened 2018-03-07 19:09 UTC
No clear repro in this case.

My guess is that legacy projects that depend on &quot;sdk style&quot; which have modifications projects don't get picked up properly.

This is new to 15.6.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/209819/up-to-date-checks-are-too-agressive-in-vs156.html
VSTS ticketId: 578080_
_These are the original issue comments:_

Kevin Pilch [MSFT] on 3/7/2018, 10:57 AM (11 min ago): <p>Thank you for your feedback! For us to investigate this further, could you please provide describe what you're seeing in more detail?  We look forward to hearing from you!</p>

Jérôme Laban on 3/7/2018, 11:06 AM (3 min ago): <p>Hi Kevin,</p><p>From a clean (-fdx) repo, first build compiles all projects, runs a Xamarin.iOS app for instance.</p><p>I modify a .cs file in an "sdk style" project, press F5, the result is "all projects are up to date", and the app starts right away.</p><p>To be able to have the app project take the modifications, I have to build the project which contains the modified file explicitly (right click build), then build the app again.</p><p>It's also no consistently doing this, as sometimes modifications are taken into account by the up-to-date checks.</p><p>Thanks,</p>

_These are the original issue solutions:_
(no solutions)

**Comment by panopticoncentral** [comment] 2018-03-12 22:11
When you got this, that was the entire output in the output window? Did it say anything about the C# project you'd modified? It should have spit out a bunch of information about the up to date check for the project.

**Comment by jeromelaban** [comment] 2018-03-12 22:16
Yes, this was the entire content of the output window, nothing else. I was in diagnostics for msbuild output verbosity, verbose for .NET Core options.

If this can help, my solution is very similar to this one: https://github.com/jeromelaban/XTargetSolution, where I'm debugging the iOS head project, an modifying one of the ProjectXX dependent projects.

**Comment by jeromelaban** [comment] 2018-03-14 12:29
I've found a repro:
- Build [this solution](https://github.com/dotnet/project-system/files/1810998/20180314.-.MultiConfigRebuild.zip)
- Modify the `Class1.cs` file
- Build
- Repeat modify/build, you'll end up with the same issue.

Looks like the conditional inclusion of `Compile` files is causing the up-to-date check to fail.

**Comment by davkean** [comment] 2018-03-14 12:51
Nice. 

Unsure if related @panopticoncentral but Class1.cs is actually included twice; once in None inherited from SDK and once in the project itself.

**Comment by panopticoncentral** [comment] 2018-04-02 19:10
@davkean Yes, that appears to be it -- the dataflow appears to be *very* confused by this, I get a project update saying that there is a Compile item Class1.cs, then I get an update saying, no, there are no Compile items, then maybe I get another update saying, yes, there is a Compile item Class1.cs, then another update...

This isn't technically a bug in the fast up-to-date check, we're just following what we're told by the dataflow. Should we be giving an error in this case somewhere? Does this go to CPS to look at?

**Comment by panopticoncentral** [comment] 2018-04-17 19:43
Ah, OK, this is a problem with multiple target frameworks. This is duplicate of #2487.

**Closed by panopticoncentral** 2018-04-17 19:43 UTC
Labels: Area-New-Project-System, Bug, Feature-Up-to-date
