### ISSUE TITLE
ProjectSystem VSIX contains unnecessary files (source and localised rule files)

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#6612] opened 2020-09-16 04:13 UTC
Our VSIX is shipping a bunch of source files:

![image](https://user-images.githubusercontent.com/1103906/93291552-b5c12080-f826-11ea-82c4-733ae68f2bbb.png)

Probably a regression from the work to embed the rules.

**Comment by davkean** [comment] 2020-09-18 05:24
This is worse, this also includes all the localized rule files as well. All in all, this is 3 MB of data that shouldn't be shipped.

**Comment by davkean** [comment] 2020-09-18 05:48
The GetCopyToOutputDirectoryItems target is producing them in the following (ie they are being treated as CopyToOutputDirectory items) but I'm not sure why:

```
    <ProjectReference Include="..\..\src\Microsoft.VisualStudio.ProjectSystem.Managed\Microsoft.VisualStudio.ProjectSystem.Managed.csproj">
      <Name>Microsoft.VisualStudio.ProjectSystem.Managed</Name>
      <IncludeOutputGroupsInVSIX>BuiltProjectOutputGroup;GetCopyToOutputDirectoryItems;SatelliteDllsProjectOutputGroup</IncludeOutputGroupsInVSIX>
      <IncludeOutputGroupsInVSIXLocalOnly>DebugSymbolsProjectOutputGroup</IncludeOutputGroupsInVSIXLocalOnly>
    </ProjectReference>
```

**Comment by drewnoakes** [comment] 2020-09-18 12:38
We should add some automation to prevent files accidentally being added or removed from the package, which runs in CI.

**Comment by ocallesp** [comment] 2020-09-25 22:31
@davkean 
The `CopyToOutputDirectory `for `XamlPropertyRule `should be **false** ?
https://github.com/dotnet/project-system/blob/master/build/import/VisualStudio.XamlRules.targets#L8

**Comment by ocallesp** [comment] 2020-09-25 22:59
I created a new work item for TSA so they can automate this
https://dev.azure.com/devdiv/DevDiv/_queries/edit/1220080

**Comment by davkean** [comment] 2020-09-25 23:07
TSA?

**Comment by dmonroym** [comment] 2020-11-12 06:46
@ocallesp have you been able to take a further look at this? With the work related to #6652 we'll be creating new packages so would like to avoid this happening

**Comment by davkean** [comment] 2021-07-30 05:38
This has increased to 454 additional files above our dlls and required files, I think this should be prioritized, just to reduce extract and copy time of these files.

**Comment by drewnoakes** [comment] 2021-11-29 03:40
Running a `git bisect` shows this regressed in commit e30c529bc40da262c9ff5c5ccaefce2684b713aa:

> Embed translated rules into satellite assemblies
>
> This embeds translated rules into satellite assemblies, ready for CPS to automatically load them from our assembly.

<details>
<summary>git bisect log</summary>

```
# bad: [05694efe8e5e25e920be570969adc53fcac71895] Ignore warning about xUnit package versions
git bisect bad 05694efe8e5e25e920be570969adc53fcac71895
# bad: [8b7a9c55697b7e201fccdbee938d1dacc37fe6b8] Revert "Merge pull request #6859 from dotnet/revert-6712-RemoveTFMParsing"
git bisect bad 8b7a9c55697b7e201fccdbee938d1dacc37fe6b8
# bad: [2fc987d7c2170ef93e60649f732f7876455b5496] Merge pull request #6593 from drewnoakes/unresolved-dependency-telemetry
git bisect bad 2fc987d7c2170ef93e60649f732f7876455b5496
# good: [08057f7062591da46567367ad0b18b96c642558d] Merge pull request #6260 from drewnoakes/remove-adtbi-full-path
git bisect good 08057f7062591da46567367ad0b18b96c642558d
# good: [08057f7062591da46567367ad0b18b96c642558d] Merge pull request #6260 from drewnoakes/remove-adtbi-full-path
git bisect good 08057f7062591da46567367ad0b18b96c642558d
# good: [1b7b8754377350deecb8fc7e90c31c91a64aeb58] Merge pull request #6407 from tmeschter/200716-AddPackagePropertyPage
git bisect good 1b7b8754377350deecb8fc7e90c31c91a64aeb58
# bad: [282e66a0a4097148a0cba53a510dadc0af1a6970] Add new tests for rules
git bisect bad 282e66a0a4097148a0cba53a510dadc0af1a6970
# good: [6e7823a6e4f6cb26af4bb068700ffad48aeb91fd] Merge pull request #6458 from davkean/Workaround
git bisect good 6e7823a6e4f6cb26af4bb068700ffad48aeb91fd
# good: [781a6e772107d754995c048dd60eed7c5536054e] Merge pull request #6429 from ocallesp/enable/resource_editor_codespaces_client
git bisect good 781a6e772107d754995c048dd60eed7c5536054e
# good: [80c01985e6ea340ea75dc722a60d532fa31905c0] Merge pull request #6488 from davkean/TaskCompletionSource
git bisect good 80c01985e6ea340ea75dc722a60d532fa31905c0
# good: [257091291fcd1aa111dd6b2f16a6cb32a28adb72] Merge pull request #6489 from davkean/SolutionLoadedInHost
git bisect good 257091291fcd1aa111dd6b2f16a6cb32a28adb72
# good: [4a2e3aa90847ec5f2e78e6d4eebaaa7e84ca4446] Merge pull request #6493 from tmeschter/200812-SigningPropertyPage
git bisect good 4a2e3aa90847ec5f2e78e6d4eebaaa7e84ca4446
# bad: [5f7ca174b5d6ca72e4e094c5b4b8867418ebb66d] Merge pull request #6496 from davkean/Localization
git bisect bad 5f7ca174b5d6ca72e4e094c5b4b8867418ebb66d
# bad: [e30c529bc40da262c9ff5c5ccaefce2684b713aa] Embed translated rules into satellite assemblies
git bisect bad e30c529bc40da262c9ff5c5ccaefce2684b713aa
# first bad commit: [e30c529bc40da262c9ff5c5ccaefce2684b713aa] Embed translated rules into satellite assemblies
```

NOTE: this required removing all `myget.org` references from `build/import/Packages.targets` as that package source no longer exists.

</details>

**Comment by drewnoakes** [comment] 2021-11-29 10:31
The issue is having both of these on XAML rule items:

```xml
<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
<XlfOutputItem>EmbeddedResource</XlfOutputItem>
```

The fix here is in two parts:

1. A change in this repo to never copy to output directory for embedded rules.
2. A change in CPS to reset `CopyToOutputDirectory` for rule files' `Compile` items

The CPS part is fixed in https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/366694.

**Comment by drewnoakes** [comment] 2021-12-01 02:14
The CPS fix just merged. I suspect we need to update our package references for the fix to apply to our builds.

**Comment by MiYanni** [comment] 2022-06-28 00:55
I've confirmed (both locally and in CI), there are no extraneous source files in the VSIX packages.
![image](https://user-images.githubusercontent.com/17788297/176063539-500b4818-4adb-4344-bfa3-a90a065267ed.png)
![image](https://user-images.githubusercontent.com/17788297/176063586-2127aea6-b78c-447b-855e-428ff7439604.png)
![image](https://user-images.githubusercontent.com/17788297/176063647-2ebe533a-c471-441c-b4af-0035824d31b4.png)

- The folders with language codes only contain the localized versions of the resource DLLs
- The `package` folder only contains the digital signature related to MicroBuild signing
- The `ProjectSystem` folder only contains .xaml rule files

Closing this issue as the problem has been resolved.

**Comment by drewnoakes** [comment] 2022-06-28 02:37
Nice one @MiYanni!

Is there a PR or commit we can link here for future reference?

**Comment by drewnoakes** [comment] 2022-06-28 02:39
Are you sure this has been fixed? Our unit tests still suggest these files would be present:

https://github.com/dotnet/project-system/blob/main/tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Setup/PackageContentTests.ProjectSystem.verified.txt

In particular the comment from @davkean above:

> This is worse, this also includes all the localized rule files as well. All in all, this is 3 MB of data that shouldn't be shipped.

While the .cs files are not present, it seems that all the localised rules are still present.

**Comment by drewnoakes** [comment] 2022-06-28 02:40
I'm going to re-open this so it doesn't get lost, until we get to the bottom of it.

**Comment by MiYanni** [comment] 2022-06-28 20:38
Sorry, the scope of the issue was not clear. I thought it was only source files that was the problem. Are we certain we don't need the translated XAML rule files in the VSIX? Basically, that would mean removing the `ProjectSystem` folder out of the VSIX as it **only contains** translated XAML rule files. The contents of the VSIX are exactly what go into the VS installation as seen here:

![image](https://user-images.githubusercontent.com/17788297/176281945-c2dfd09f-9333-40af-894c-9e277cb68c0e.png)

**Comment by MiYanni** [comment] 2022-06-28 23:06
Fixed it in my infra changes. No more translated XAMLs (aka, no more `ProjectSystem` folder):
![image](https://user-images.githubusercontent.com/17788297/176318676-1a040638-0d35-499a-8e90-3f9fc1bfb903.png)

**Closed** 2022-07-15 19:37 UTC
Labels: Tenet-Performance, Area-Infrastructure, Triage-Investigate, Performance-Scenario-General
